const cheerio=require('cheerio');
const crypto=require('crypto');

const MAX_ARTICLE_BYTES=12*1024*1024;
const CTA_RE=/\b(?:consulta|revisa|conoce|mira|ingresa|entra|descubre|encuentra)\s+(?:todos?\s+los?\s+detalles?\s+)?(?:aquí|aca)|\b(?:más|mayor)\s+información\s+(?:aquí|aca)|\bhaz\s+clic\s+aquí/i;
const ARTICLE_SELECTORS=['article','[itemprop="articleBody"]','[data-testid="article-body"]','.story-contents','.story-content','.article-body','.article__body','.article-content','.nota-body','.content-body','main'];
const PREMIUM_RE=/(?:solo|exclusiv[oa])\s+(?:para\s+)?suscriptores?|contenido\s+(?:exclusivo|premium)|suscr[ií]bete\s+(?:para|y)\s+(?:continuar|leer)|inicia\s+sesi[oó]n\s+para\s+leer|subscriber\s+only|premium\s+content|members?\s+only/i;
const METERED_RE=/(?:te\s+quedan|has\s+usado)\s+\d+\s+(?:art[ií]culos?|lecturas?)|l[ií]mite\s+(?:mensual|de\s+lecturas)|free\s+articles?\s+remaining/i;
const LIVE_RE=/lbposting|liveblog|live-blog|live_blog/i;

async function readHtmlLimited(res,maxBytes=MAX_ARTICLE_BYTES){const declared=Number(res.headers.get('content-length')||0);if(declared>maxBytes)throw new Error(`contenido demasiado grande (${Math.ceil(declared/1048576)} MB)`);if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder('utf-8');let total=0,out='';try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>maxBytes){try{await reader.cancel();}catch{}throw new Error(`contenido excede ${Math.round(maxBytes/1048576)} MB`);}out+=decoder.decode(value,{stream:true});}out+=decoder.decode();return out;}finally{try{reader.releaseLock();}catch{}}}
function cleanText(value){return String(value||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim();}
function fingerprint(value){return crypto.createHash('sha1').update(String(value||'')).digest('hex');}
function chooseContainer($){let best=$('body'),bestScore=0;for(const sel of ARTICLE_SELECTORS){$(sel).each((_,el)=>{const node=$(el),paragraphs=node.find('p').filter((__,p)=>cleanText($(p).text()).length>30).length,chars=cleanText(node.text()).length,score=paragraphs*220+Math.min(chars,16000);if(score>bestScore){bestScore=score;best=node;}});}return best;}
function structuredBlocks($,container){const out=[],seen=new Set();const push=(kind,text)=>{const value=cleanText(text);if(value.length<12)return;const key=value.toLowerCase();if(seen.has(key))return;seen.add(key);out.push(kind?`${kind}: ${value}`:value);};container.find('p,h2,h3,blockquote,ul li,ol li,table tr').each((_,el)=>{const tag=String(el.tagName||el.name||'').toLowerCase(),node=$(el);if(tag==='tr'){const cells=node.find('th,td').map((__,cell)=>cleanText($(cell).text())).get().filter(Boolean).slice(0,8);if(cells.length>=2)push('TABLA',cells.join(' | '));return;}const value=cleanText(node.text());if(tag==='h2'||tag==='h3')push('SUBTÍTULO',value);else if(tag==='li')push('LISTA',value);else if(tag==='blockquote')push('CITA',value);else push('',value);});return out;}
function globalParagraphBody($){const reject=/^(lee también|también puedes leer|te puede interesar|suscríbete|regístrate|publicidad|newsletter|síguenos|contenido patrocinado|recomendamos|últimas noticias)/i,seen=new Set(),out=[];$('p').each((_,el)=>{const t=cleanText($(el).text());if(t.length<40||reject.test(t))return;const k=t.toLowerCase();if(seen.has(k))return;seen.add(k);out.push(t);});return out.join('\n\n');}
function jsonLdObjects($){const found=[];$('script[type="application/ld+json"]').each((_,el)=>{const raw=$(el).contents().text();if(!raw)return;try{const x=JSON.parse(raw);Array.isArray(x)?found.push(...x):found.push(x);}catch{}});return found;}
function walkJson(value,fn,depth=0){if(value==null||depth>12)return;if(Array.isArray(value)){value.forEach(x=>walkJson(x,fn,depth+1));return;}if(typeof value!=='object')return;fn(value);for(const v of Object.values(value))if(v&&typeof v==='object')walkJson(v,fn,depth+1);}
function jsonLdBodies($){const found=[];for(const obj of jsonLdObjects($))walkJson(obj,node=>{for(const k of ['articleBody','text'])if(typeof node[k]==='string'){const t=cleanText(node[k]);if(t.length>=120)found.push(t);}});return found.sort((a,b)=>b.length-a.length);}
function absoluteUrl(href,base){try{return new URL(String(href||''),base).href;}catch{return'';}}
function publisherInfo($,objects,pageUrl){let name=$('meta[property="og:site_name"]').attr('content')||'';for(const obj of objects)walkJson(obj,node=>{if(name)return;const p=node.publisher;if(typeof p==='string')name=p;else if(p&&typeof p==='object'&&typeof p.name==='string')name=p.name;});let web='';try{web=new URL(pageUrl).hostname.replace(/^www\./,'');}catch{}return{name:cleanText(name)||web.split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),web};}
function detectAccess($,objects,pageUrl){
  let schemaLocked=false,schemaFree=false;for(const obj of objects)walkJson(obj,node=>{if(node.isAccessibleForFree===false||String(node.isAccessibleForFree).toLowerCase()==='false')schemaLocked=true;if(node.isAccessibleForFree===true||String(node.isAccessibleForFree).toLowerCase()==='true')schemaFree=true;});
  const paywallNodes=$('[class*="paywall"],[class*="premium"],[class*="subscriber"],[class*="locked"],[data-paywall],[data-premium]'),paywallText=cleanText(paywallNodes.text()).slice(0,10000),articleText=cleanText($('article,[itemprop="articleBody"],[data-testid="article-body"],main').first().text()).slice(0,24000),bodyText=cleanText($('body').text()).slice(0,30000),urlHint=/(?:\/premium\/|\/suscriptores?\/|\/exclusive\/|\/exclusivo\/|\/plusg\/)/i.test(pageUrl),articlePhrase=PREMIUM_RE.test(articleText),paywallPhrase=PREMIUM_RE.test(paywallText),hintedPhrase=urlHint&&PREMIUM_RE.test(bodyText),domStrong=paywallNodes.length>0&&(paywallPhrase||urlHint);
  if(schemaLocked||articlePhrase||paywallPhrase||hintedPhrase||domStrong)return{status:'SUBSCRIBER_ONLY',confidence:schemaLocked||articlePhrase||paywallPhrase?'high':'medium',signals:{schemaLocked,phrase:articlePhrase||paywallPhrase||hintedPhrase,dom:domStrong,urlHint}};
  if(schemaFree)return{status:'PUBLIC',confidence:'high',signals:{schemaFree}};
  if(METERED_RE.test(articleText)||METERED_RE.test(paywallText)||METERED_RE.test(bodyText))return{status:'METERED',confidence:'medium',signals:{metered:true,urlHint}};
  return{status:'UNKNOWN',confidence:urlHint?'low':'none',signals:{urlHint}};
}
function parseNumber(value){const n=Number(String(value||'').replace(',','.'));return Number.isFinite(n)?n:null;}
function parseEarthquake(text){
  const t=cleanText(text);
  const mag=t.match(/\bmagnitud(?:\s+de)?\s*:?\s*(\d+(?:[.,]\d+)?)/i);
  const depth=t.match(/\bprofundidad(?:\s+de)?\s*:?\s*(\d+(?:[.,]\d+)?)\s*(?:km|kil[oó]metros?)/i);
  const lat=t.match(/\blatitud\s*:?\s*(-?\d+(?:[.,]\d+)?)[°º]?/i),lon=t.match(/\blongitud\s*:?\s*(-?\d+(?:[.,]\d+)?)[°º]?/i);
  const local=t.match(/\bhora\s+local\s*:?\s*((?:20\d{2}[-/]\d{1,2}[-/]\d{1,2}\s+)?\d{1,2}:\d{2}(?::\d{2})?)/i),utc=t.match(/\bhora\s+utc\s*:?\s*((?:20\d{2}[-/]\d{1,2}[-/]\d{1,2}\s+)?\d{1,2}:\d{2}(?::\d{2})?)/i);
  const report=t.match(/\b(?:IGP\s*\/\s*)?(?:CENSIS\s*\/\s*)?RS\s*[:#-]?\s*(20\d{2}-\d{3,6})\b/i)||t.match(/\bIGP\s*\/\s*CENSIS\s*\/\s*RS\s+(20\d{2}-\d{3,6})\b/i);
  let location='';const loc=t.match(/\bsismo\s+en\s+([^|•.;\n]{3,100})/i)||t.match(/(?:epicentro|ubicaci[oó]n)\s*:?\s*([^|•.;\n]{3,100})/i);if(loc)location=cleanText(loc[1]);
  const magnitude=mag?parseNumber(mag[1]):null,depthKm=depth?parseNumber(depth[1]):null,latitude=lat?parseNumber(lat[1]):null,longitude=lon?parseNumber(lon[1]):null,reportId=report?`IGP/CENSIS/RS ${report[1]}`:'';
  const signals=[magnitude!=null,depthKm!=null,!!location,!!local,latitude!=null&&longitude!=null,!!reportId].filter(Boolean).length;if(magnitude==null||signals<2)return null;
  return{magnitude,depthKm,location,localTime:local?cleanText(local[1]):'',utcTime:utc?cleanText(utc[1]):'',latitude,longitude,reportId,signals,text:t};
}
function liveBlogUpdates($,objects){
  const out=[],seen=new Set();const add=(text,date='',title='',source='')=>{const value=cleanText([title,text].filter(Boolean).join('. '));if(value.length<25)return;const key=value.toLowerCase();if(seen.has(key))return;seen.add(key);out.push({text:value,date:cleanText(date),source});};let liveSchema=false;
  for(const obj of objects)walkJson(obj,node=>{const type=Array.isArray(node['@type'])?node['@type'].join(' '):String(node['@type']||'');if(/LiveBlogPosting/i.test(type))liveSchema=true;if(/BlogPosting/i.test(type)&&!/LiveBlogPosting/i.test(type)){const body=node.articleBody||node.text||node.description||'';if(body)add(body,node.datePublished||node.dateModified||'',node.headline||'','jsonld-update');}if(node.liveBlogUpdate){for(const update of Array.isArray(node.liveBlogUpdate)?node.liveBlogUpdate:[node.liveBlogUpdate]){if(!update||typeof update!=='object')continue;const body=update.articleBody||update.text||update.description||'';if(body)add(body,update.datePublished||update.dateModified||'',update.headline||'','jsonld-liveBlogUpdate');}}});
  const selectors=['[class*="liveblog"] [class*="update"]','[class*="live-blog"] [class*="update"]','[data-liveblog] [data-update]','[class*="live"] article','[class*="timeline"] article','[class*="lb-"] article'].join(',');$(selectors).each((_,el)=>{const node=$(el),date=node.find('time').first().attr('datetime')||node.find('time').first().text(),title=node.find('h2,h3,h4').first().text();add(node.text(),date,title,'dom-update');});return{updates:out,liveSchema};
}
function selectLatestEarthquake(updates){const valid=[];for(const u of updates){const event=parseEarthquake(u.text);if(!event)continue;const ts=Date.parse(u.date||event.localTime||'')||0;valid.push({...event,date:u.date||'',ts,source:u.source||''});}if(!valid.length)return null;valid.sort((a,b)=>b.ts-a.ts||b.signals-a.signals);const e=valid[0],id=e.reportId?`report:${e.reportId}`:fingerprint(['sismo',e.date,e.localTime,e.magnitude,e.location,e.latitude,e.longitude].join('|'));return{...e,id};}
function eventBody(e){const parts=[];if(e.location)parts.push(`Sismo en ${e.location}`);else parts.push('Sismo reportado');parts.push(`Magnitud ${e.magnitude}`);if(e.depthKm!=null)parts.push(`Profundidad ${e.depthKm} km`);if(e.localTime)parts.push(`Hora local ${e.localTime}`);if(e.latitude!=null)parts.push(`Latitud ${e.latitude}`);if(e.longitude!=null)parts.push(`Longitud ${e.longitude}`);if(e.reportId)parts.push(`Reporte ${e.reportId}`);return parts.join('. ')+'.';}
function parseArticleHtml(html,pageUrl){const $=cheerio.load(html),objects=jsonLdObjects($),ampHref=$('link[rel="amphtml"]').first().attr('href')||'',jsonBodies=jsonLdBodies($),meta=(key,attr='property')=>$(`meta[${attr}="${key}"]`).attr('content')||'',title=meta('og:title')||cleanText($('h1').first().text())||cleanText($('title').text()),image=meta('og:image'),description=meta('og:description')||meta('description','name')||'',category=meta('article:section')||'',author=meta('author','name')||cleanText($('[rel="author"]').first().text())||'',publisher=publisherInfo($,objects,pageUrl),access=detectAccess($,objects,pageUrl),live=liveBlogUpdates($,objects),isLive=live.liveSchema||LIVE_RE.test(pageUrl)||LIVE_RE.test($('body').attr('class')||'');$('script,style,noscript,svg,nav,footer,header,aside,form,iframe').remove();const container=chooseContainer($),rawContainerText=cleanText(container.text()),sourceHadCTA=CTA_RE.test(rawContainerText)||container.find('a').toArray().some(a=>CTA_RE.test(cleanText($(a).text()))),blocks=structuredBlocks($,container);let body=blocks.join('\n\n'),mode='article';const globalBody=globalParagraphBody($),jsonBody=jsonBodies[0]||'';if(globalBody.length>body.length*1.35&&globalBody.length>500){body=globalBody;mode='global-paragraphs';}if(jsonBody.length>body.length*1.15&&jsonBody.length>500){body=jsonBody;mode='jsonld';}if(body.length<180&&globalBody.length>body.length){body=globalBody;mode='global-paragraphs';}if(body.length<120&&jsonBody.length>body.length){body=jsonBody;mode='jsonld';}let liveEvent=null,liveblogNoEvent=false;if(isLive){liveEvent=selectLatestEarthquake(live.updates);if(liveEvent){body=eventBody(liveEvent);mode='liveblog-event';}else liveblogNoEvent=true;}body=cleanText(body).slice(0,30000);return{title,image,description:cleanText(description),category:cleanText(category),author:cleanText(author),publisher,access,body,sourceHadCTA,ampUrl:absoluteUrl(ampHref,pageUrl),extractionMode:mode,isLiveBlog:isLive,liveblogNoEvent,liveEvent,liveUpdateCount:live.updates.length};}
async function fetchHtmlPage(url,timeoutMs=25000){let res;try{res=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) EC-Automatic-News/0.3.24','Accept':'text/html,*/*','Accept-Language':'es-PE,es;q=0.9,en;q=0.6'},redirect:'follow',signal:AbortSignal.timeout(timeoutMs)});}catch(e){throw new Error(`Artículo: ${e.name==='TimeoutError'?'tiempo de espera agotado':(e.message||e)}`);}if(!res.ok)throw new Error(`Artículo: HTTP ${res.status}`);const type=String(res.headers.get('content-type')||'');if(type&&!/html|text\//i.test(type))throw new Error(`Artículo: contenido no HTML (${type})`);let html;try{html=await readHtmlLimited(res);}catch(e){throw new Error(`Artículo: ${e.message||e}`);}return{html,finalUrl:res.url||url};}
function contentState(body,description,isLiveBlog,liveblogNoEvent){const chars=String(body||'').length;if(isLiveBlog&&liveblogNoEvent)return'LIVEBLOG_SIN_EVENTO';if(/<\/?[a-z][^>]*>/i.test(body||''))return'DEFECTIVE';if(chars>=700)return'COMPLETE';if(chars>=250)return'PARTIAL';if(chars>=120||String(description||'').length>=80)return'SUMMARY';return'INSUFFICIENT';}
function extractionLabel(mode,chars,ampUsed=false,state=''){if(state==='LIVEBLOG_SIN_EVENTO')return'Liveblog sin evento factual nuevo';if(mode==='liveblog-event')return`Liveblog · evento factual · ${chars} caracteres`;if(state==='DEFECTIVE')return`Extracción defectuosa · ${chars} caracteres`;if(chars<300)return ampUsed?`AMP breve · ${chars} caracteres`:`Extracción breve · ${chars} caracteres`;if(mode==='jsonld')return`JSON-LD · ${chars} caracteres`;if(ampUsed)return`Artículo AMP · ${chars} caracteres`;return`Artículo completo · ${chars} caracteres`;}
async function fetchArticle(url){const value=String(url||'').trim();if(!/^https?:\/\//i.test(value))throw new Error('Artículo: URL inválida');const first=await fetchHtmlPage(value),primary=parseArticleHtml(first.html,first.finalUrl);let selected=primary,finalUrl=first.finalUrl,ampUsed=false;if(!primary.isLiveBlog&&primary.body.length<700&&primary.ampUrl&&primary.ampUrl!==first.finalUrl){try{const amp=await fetchHtmlPage(primary.ampUrl,18000),parsed=parseArticleHtml(amp.html,amp.finalUrl);if(parsed.body.length>primary.body.length+180||parsed.body.length>=700){selected={...parsed,image:parsed.image||primary.image,title:parsed.title||primary.title,description:parsed.description||primary.description,category:parsed.category||primary.category,author:parsed.author||primary.author,publisher:parsed.publisher?.name?parsed.publisher:primary.publisher,access:parsed.access?.status!=='UNKNOWN'?parsed.access:primary.access,sourceHadCTA:parsed.sourceHadCTA||primary.sourceHadCTA};finalUrl=amp.finalUrl;ampUsed=true;}}catch{}}const sourceChars=String(selected.body||'').length,state=contentState(selected.body,selected.description,selected.isLiveBlog,selected.liveblogNoEvent),extractionWarning=['INSUFFICIENT','DEFECTIVE','LIVEBLOG_SIN_EVENTO'].includes(state),contentFingerprint=fingerprint(`${selected.title}\n${selected.description}\n${selected.body}`),extractionLabelText=extractionLabel(selected.extractionMode,sourceChars,ampUsed,state);return{title:selected.title,image:selected.image,description:selected.description,category:selected.category,author:selected.author,body:selected.body,sourceHadCTA:selected.sourceHadCTA,contentFingerprint,finalUrl,sourceChars,extractionMode:ampUsed?'amp':selected.extractionMode,extractionWarning,extractionLabel:extractionLabelText,contentState:state,ampUsed,publisher:selected.publisher,access:selected.access,isExclusive:selected.access?.status==='SUBSCRIBER_ONLY',isLiveBlog:!!selected.isLiveBlog,liveblogNoEvent:!!selected.liveblogNoEvent,liveEvent:selected.liveEvent||null,eventId:selected.liveEvent?.id||'',liveUpdateCount:selected.liveUpdateCount||0};}
module.exports={fetchArticle,readHtmlLimited,MAX_ARTICLE_BYTES,CTA_RE,structuredBlocks,fingerprint,parseArticleHtml,jsonLdBodies,globalParagraphBody,detectAccess,liveBlogUpdates,parseEarthquake,contentState};
