const {AutomationEngine:BaseAutomationEngine}=require('./automation');
const {STATUS_INSUFFICIENT,QUALITY_PARTIAL}=require('./editorial');

function locutionSource(title,script){const t=String(title||'').trim(),s=String(script||'').trim();if(!t)return s;if(!s)return t;const clean=x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(),ct=clean(t),cs=clean(s.slice(0,Math.max(t.length*2,220)));if(ct&&cs.startsWith(ct))return s;return`${t}. ${s}`;}
function join(a,b){return`${String(a||'').trim()}${/[.!?]$/.test(String(a||'').trim())?'':' .'} ${String(b||'').trim()}`.replace(/\s+\./g,'.').replace(/\s+/g,' ').trim();}
function spokenWeb(feed={}){const web=String(feed.publisherWeb||'').replace(/^https?:\/\//i,'').replace(/^www\./i,'').replace(/\/$/,'').trim(),name=String(feed.publisherName||'').trim();if(!web)return'';const parts=web.split('.'),suffix=parts.length>1?parts.slice(1).join(' punto '):'',base=name||parts[0].replace(/[-_]+/g,' ');return`${base}${suffix?` punto ${suffix}`:''}`;}
function articleAccess(story,article,settings){const feed=(settings.rssFeeds||[]).find(f=>f.id===story.feedId)||{},override=String(feed.accessMode||'auto');let status=String(article?.access?.status||'UNKNOWN');if(override==='exclusive')status='SUBSCRIBER_ONLY';else if(override==='public')status='PUBLIC';const exclusive=status==='SUBSCRIBER_ONLY',publisherName=String(feed.publisherName||article?.publisher?.name||story.feedName||'').trim(),publisherWeb=String(feed.publisherWeb||article?.publisher?.web||'').replace(/^https?:\/\//i,'').replace(/^www\./i,'').replace(/\/$/,'').trim();return{feed,status,exclusive,publisherName,publisherWeb,override};}
function applyClosings(story,article,result,settings){const access=articleAccess(story,article,settings),feed=access.feed;if(result?.status===STATUS_INSUFFICIENT)return{result,spokenScript:result?.script||'',access};if(access.exclusive&&settings.exclusiveClose?.enabled!==false&&feed.exclusiveCtaEnabled!==false){const template=String(feed.exclusiveCtaTemplate||settings.exclusiveClose?.template||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.').trim(),display=template.replace(/\{medio\}/gi,access.publisherName||story.feedName||'el medio').replace(/\{web\}/gi,access.publisherWeb),spoken=template.replace(/\{medio\}/gi,access.publisherName||story.feedName||'el medio').replace(/\{web\}/gi,spokenWeb(feed)||access.publisherWeb);return{result:{...result,script:join(result.script,display),isExclusive:true,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:access.publisherWeb},spokenScript:join(result.script,spoken),access};}
  if(result?.sourceQuality===QUALITY_PARTIAL&&article?.sourceHadCTA&&feed.partialCtaEnabled===true){const web=access.publisherWeb;if(web){const template=String(feed.partialCtaTemplate||'Para más información, visita {web}.').trim(),display=template.replace(/\{web\}/gi,web),spoken=template.replace(/\{web\}/gi,spokenWeb(feed)||web);return{result:{...result,script:join(result.script,display),isExclusive:false,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:web},spokenScript:join(result.script,spoken),access};}}
  return{result:{...result,isExclusive:false,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:access.publisherWeb},spokenScript:result?.script||'',access};}
function isLiveUrl(url=''){return /lbposting|liveblog|live-blog|live_blog/i.test(String(url));}

class AutomationEngine extends BaseAutomationEngine{
  constructor(args){super(args);const raw=this.sendAutomaticOutput;this.sendAutomaticOutput=(payload)=>{if((payload?.kind||'news')==='news'&&this.currentItem){const r=this.currentItem.result||{},a=this.currentItem.article||{};payload={...payload,isExclusive:!!r.isExclusive,accessStatus:r.accessStatus||a.access?.status||'UNKNOWN',publisherName:r.publisherName||a.publisher?.name||'',publisherWeb:r.publisherWeb||a.publisher?.web||'',eventId:a.eventId||''};}return raw(payload);};}
  removeItem(item){const original=item?.originalLink;super.removeItem(item);if(original)this.queuedUrls.delete(original);}
  candidateFrom(items,s){const maxAge=(s.automation.maxAgeHours||6)*3600000,now=Date.now();return items.find(x=>{if(!x?.link||this.queuedUrls.has(x.link)||!this.isFeedActive(x,s)||this.omittedSources.has(this.omittedKey(x)))return false;if(s.automation.avoidRepeats&&this.history.has(x.link)&&!isLiveUrl(x.link))return false;const t=Date.parse(x.pubDate||'');if(t&&t>now+10*60000)return false;if(t&&now-t>maxAge&&!isLiveUrl(x.link))return false;return true;});}
  displayQueue(settings){const rows=super.displayQueue(settings);for(const row of rows){if(!row?.id)continue;const item=this.queue.find(x=>x.id===row.id);if(item){row.isExclusive=!!item.result?.isExclusive;row.accessStatus=item.result?.accessStatus||item.article?.access?.status||'';row.publisherName=item.result?.publisherName||item.article?.publisher?.name||'';row.eventId=item.article?.eventId||'';}}return rows;}
  async process(story,s,holder,epoch){
    let article;holder.stage='article';this.state();try{article=await this.fetchArticle(story.link);}catch(e){e.message=`Artículo: ${e.message}`;throw e;}this.assertProcessingActive(epoch);if(!this.isFeedActive(story,this.getSettings()||s))return{omitted:true,reason:'fuente pausada o eliminada'};
    if(['DEFECTIVE','INSUFFICIENT'].includes(article.contentState))return{omitted:true,reason:'extracción de artículo insuficiente'};if(article.isLiveBlog&&article.liveblogNoEvent)return{omitted:true,reason:'liveblog sin evento factual nuevo'};
    if(article.eventId){const original=story.link,eventLink=`${original}#ec-event=${encodeURIComponent(article.eventId)}`;if(s.automation.avoidRepeats&&this.history.has(eventLink))return{omitted:true,reason:'evento del liveblog ya emitido'};holder.originalLink=original;holder.story={...holder.story,link:eventLink};story=holder.story;}
    const image=story.image||article.image||this.getFallbackUrl();holder.stage='ai';this.state();let ai;try{ai=await this.providers.generate(story,article,s);}catch(e){e.message=`IA: ${e.message}`;throw e;}this.assertProcessingActive(epoch);holder.provider=ai.provider;holder.model=ai.model;holder.attempts=ai.attempts||[];holder.metrics=ai.metrics||null;if(ai.result.status===STATUS_INSUFFICIENT)return{omitted:true,reason:'fuente insuficiente'};
    const closing=applyClosings(story,article,ai.result,s),result=closing.result;
    const local=await this.runLocalHeavy(async()=>{this.assertProcessingActive(epoch);holder.stage='pronunciation';this.state();const spoken=locutionSource(result.title||story.title,closing.spokenScript||result.script);let locution={text:spoken,elapsedMs:0,smartUsed:false,smartFailed:false};if(this.pronunciation)locution=await this.pronunciation.normalize(spoken,{smart:s.tts?.pronunciationSmart!==false});this.assertProcessingActive(epoch);holder.metrics={...(holder.metrics||{}),pronunciationElapsedMs:locution.elapsedMs||0,pronunciationSmart:!!locution.smartUsed,pronunciationSmartFailed:!!locution.smartFailed,pronunciationSmartError:locution.smartFailed?String(locution.smartError||'').slice(0,180):'',pronunciationClaude:!!locution.claudeUsed,pronunciationLearned:locution.learnedCount||0};holder.stage='tts';this.state();let audio;try{audio=await this.kokoro.generate(locution.text,{voice:s.tts.voice,speed:s.tts.speed});}catch(e){e.message=`Voz: ${e.message}`;e.details=ai.attempts||[];throw e;}try{this.assertProcessingActive(epoch);}catch(e){this.kokoro?.cleanupAudio?.(audio.path);throw e;}holder.metrics={...(holder.metrics||{}),ttsElapsedMs:audio.elapsedMs||0,ttsThreads:audio.threads||2,audioDurationSec:audio.durationSec||0,ttsRealtimeFactor:audio.realtimeFactor||0,ttsProfile:audio.performanceLabel||audio.performanceProfile||'',ttsPersistent:!!audio.persistent,ttsWorkerStartupMs:audio.workerStartupMs||0};return{locution,audio};});
    return{article,provider:ai.provider,model:ai.model,result:{...result,ttsScript:local.locution.text},attempts:ai.attempts||[],metrics:holder.metrics,audio:local.audio,image,fallback:this.getFallbackUrl()};
  }
}
module.exports={AutomationEngine,applyClosings,articleAccess};
