const {AutomationEngine:BaseAutomationEngine}=require('./automation');
const {STATUS_INSUFFICIENT,QUALITY_PARTIAL}=require('./editorial');
const {fetchArticleMetadata}=require('./articleMetadata0324');
const {storyKey,baseStoryKey}=require('./storyKey0324');

const wait=ms=>new Promise(r=>setTimeout(r,ms));
function locutionSource(title,script){const t=String(title||'').trim(),s=String(script||'').trim();if(!t)return s;if(!s)return t;const clean=x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(),ct=clean(t),cs=clean(s.slice(0,Math.max(t.length*2,220)));if(ct&&cs.startsWith(ct))return s;return`${t}. ${s}`;}
function join(a,b){return`${String(a||'').trim()}${/[.!?]$/.test(String(a||'').trim())?'':' .'} ${String(b||'').trim()}`.replace(/\s+\./g,'.').replace(/\s+/g,' ').trim();}
function spokenWeb(feed={}){const web=String(feed.publisherWeb||'').replace(/^https?:\/\//i,'').replace(/^www\./i,'').replace(/\/$/,'').trim(),name=String(feed.publisherName||'').trim();if(!web)return'';const parts=web.split('.'),suffix=parts.length>1?parts.slice(1).join(' punto '):'',base=name||parts[0].replace(/[-_]+/g,' ');return`${base}${suffix?` punto ${suffix}`:''}`;}
function articleAccess(story,article,settings){const feed=(settings.rssFeeds||[]).find(f=>f.id===story.feedId)||{},override=String(feed.accessMode||'auto'),strongLock=article?.access?.signals?.strongLock===true;let status=String(article?.access?.status||'UNKNOWN');if(override==='exclusive')status='SUBSCRIBER_ONLY';else if(override==='public'&&!strongLock)status='PUBLIC';const exclusive=status==='SUBSCRIBER_ONLY',publisherName=String(feed.publisherName||article?.publisher?.name||story.feedName||'').trim(),publisherWeb=String(feed.publisherWeb||article?.publisher?.web||'').replace(/^https?:\/\//i,'').replace(/^www\./i,'').replace(/\/$/,'').trim();return{feed,status,exclusive,publisherName,publisherWeb,override,strongLock};}
function applyClosings(story,article,result,settings){const access=articleAccess(story,article,settings),feed=access.feed;if(result?.status===STATUS_INSUFFICIENT)return{result,spokenScript:result?.script||'',access};if(access.exclusive&&settings.exclusiveClose?.enabled!==false&&feed.exclusiveCtaEnabled!==false){const template=String(feed.exclusiveCtaTemplate||settings.exclusiveClose?.template||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.').trim(),display=template.replace(/\{medio\}/gi,access.publisherName||story.feedName||'el medio').replace(/\{web\}/gi,access.publisherWeb),spoken=template.replace(/\{medio\}/gi,access.publisherName||story.feedName||'el medio').replace(/\{web\}/gi,spokenWeb(feed)||access.publisherWeb);return{result:{...result,script:join(result.script,display),isExclusive:true,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:access.publisherWeb},spokenScript:join(result.script,spoken),access};}
  if(result?.sourceQuality===QUALITY_PARTIAL&&article?.sourceHadCTA&&feed.partialCtaEnabled===true){const web=access.publisherWeb;if(web){const template=String(feed.partialCtaTemplate||'Para más información, visita {web}.').trim(),display=template.replace(/\{web\}/gi,web),spoken=template.replace(/\{web\}/gi,spokenWeb(feed)||web);return{result:{...result,script:join(result.script,display),isExclusive:false,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:web},spokenScript:join(result.script,spoken),access};}}
  return{result:{...result,isExclusive:false,accessStatus:access.status,publisherName:access.publisherName,publisherWeb:access.publisherWeb},spokenScript:result?.script||'',access};}
function isLiveUrl(url=''){return /lbposting|liveblog|live-blog|live_blog/i.test(String(url));}
function compactUnique(parts){const seen=new Set(),out=[];for(const x of parts){const text=String(x||'').replace(/\s+/g,' ').trim();if(!text)continue;const k=text.toLocaleLowerCase('es');if(seen.has(k))continue;seen.add(k);out.push(text);}return out;}
function buildExclusivePublicArticle(story,article){const publicParts=compactUnique([story?.description,article?.description,article?.publicPreview]),body=publicParts.join('\n\n').slice(0,2800),chars=body.length;return{...article,title:article?.title||story?.title||'',description:article?.description||story?.description||'',body,sourceChars:chars,contentState:chars>=250?'PARTIAL':chars>=80?'SUMMARY':'INSUFFICIENT',extractionMode:'public-preview',extractionLabel:`Vista pública · ${chars} caracteres`,sourceHadCTA:false,protectedBodyOmitted:true};}
function exclusiveContextSufficient(story,article){const safe=buildExclusivePublicArticle(story,article),words=safe.body.split(/\s+/).filter(Boolean);return safe.body.length>=80&&words.length>=12;}
function chooseNewsItem(queue,everyNews,hasEmittedExclusive,newsSinceExclusive){const ready=(queue||[]).filter(x=>x.status==='LISTA');if(!ready.length)return null;const every=Math.max(0,Math.round(Number(everyNews)||0));if(every<=1||!hasEmittedExclusive||newsSinceExclusive>=every-1)return ready[0];return ready.find(x=>!x.result?.isExclusive)||ready[0];}

class AutomationEngine extends BaseAutomationEngine{
  constructor(args){
    super(args);this.newsStatuses=new Map();
    const persisted=this.history?.getAutomationState?.()||{};this.exclusiveHasEmitted=!!persisted.exclusiveHasEmitted;this.newsSinceExclusive=Math.max(0,Number(persisted.newsSinceExclusive)||0);
    const raw=this.sendAutomaticOutput;this.sendAutomaticOutput=(payload)=>{if((payload?.kind||'news')==='news'&&this.currentItem){const r=this.currentItem.result||{},a=this.currentItem.article||{};payload={...payload,isExclusive:!!r.isExclusive,accessStatus:r.accessStatus||a.access?.status||'UNKNOWN',publisherName:r.publisherName||a.publisher?.name||'',publisherWeb:r.publisherWeb||a.publisher?.web||'',eventId:a.eventId||''};}return raw(payload);};
  }
  trimNewsStatuses(){while(this.newsStatuses.size>500){let oldestKey='',oldest=Infinity;for(const[k,v]of this.newsStatuses){const t=Number(v.updatedAt)||0;if(t<oldest){oldest=t;oldestKey=k;}}if(!oldestKey)break;this.newsStatuses.delete(oldestKey);}}
  setNewsStatus(story,status,extra={}){if(!/^https?:/i.test(String(story?.link||'')))return;const key=storyKey(story),baseKey=baseStoryKey(story);if(!key)return;const now=Date.now(),entry={storyKey:key,baseKey,url:String(story.link||''),title:String(story.title||''),feedId:String(story.feedId||''),status:String(status||''),isExclusive:!!extra.isExclusive,accessStatus:String(extra.accessStatus||''),reason:String(extra.reason||''),eventId:String(extra.eventId||''),updatedAt:now};if(key!==baseKey){const base=this.newsStatuses.get(baseKey);if(base&&['PROCESANDO','LISTA','AL AIRE','ERROR'].includes(base.status))this.newsStatuses.delete(baseKey);}this.newsStatuses.set(key,{...(this.newsStatuses.get(key)||{}),...entry});this.trimNewsStatuses();}
  newsStatusRows(){return[...this.newsStatuses.values()].sort((a,b)=>Number(b.updatedAt)-Number(a.updatedAt)).slice(0,500);}
  schedulerState(settings=this.getSettings()||{}){const every=Math.max(0,Math.min(20,Math.round(Number(settings.automation?.exclusiveEveryNews)||0))),needed=this.exclusiveHasEmitted&&every>1?Math.max(0,(every-1)-this.newsSinceExclusive):0;return{everyNews:every,hasEmittedExclusive:this.exclusiveHasEmitted,newsSinceExclusive:this.newsSinceExclusive,nonExclusiveNeeded:needed};}
  recordExclusiveEmission(item){if(item?.result?.isExclusive){this.exclusiveHasEmitted=true;this.newsSinceExclusive=0;}else if(this.exclusiveHasEmitted)this.newsSinceExclusive++;try{this.history?.setAutomationState?.({exclusiveHasEmitted:this.exclusiveHasEmitted,newsSinceExclusive:this.newsSinceExclusive});}catch{}}
  snapshot(extra={}){const s=super.snapshot(extra);return{...s,newsStatuses:this.newsStatusRows(),exclusiveScheduler:this.schedulerState()};}
  removeItem(item){const original=item?.originalLink;super.removeItem(item);if(original)this.queuedUrls.delete(original);}
  candidateFrom(items,s){const maxAge=(s.automation.maxAgeHours||6)*3600000,now=Date.now();return items.find(x=>{if(!x?.link||this.queuedUrls.has(x.link)||!this.isFeedActive(x,s)||this.omittedSources.has(this.omittedKey(x)))return false;if(s.automation.avoidRepeats&&this.history.has(x.link)&&!isLiveUrl(x.link))return false;const t=Date.parse(x.pubDate||'');if(t&&t>now+10*60000)return false;if(t&&now-t>maxAge&&!isLiveUrl(x.link))return false;return true;});}
  displayQueue(settings){const rows=super.displayQueue(settings);for(const row of rows){if(!row?.id)continue;const item=this.queue.find(x=>x.id===row.id);if(item){row.isExclusive=!!item.result?.isExclusive||!!item.isExclusive;row.accessStatus=item.result?.accessStatus||item.accessStatus||item.article?.access?.status||'';row.publisherName=item.result?.publisherName||item.article?.publisher?.name||'';row.eventId=item.article?.eventId||'';row.storyKey=storyKey(item.story);row.baseKey=baseStoryKey(item.story);row.storyUrl=String(item.story?.link||'');}}return rows;}
  launchCandidate(candidate,s,epoch){
    if(!this.isFeedActive(candidate,this.getSettings()||s))return;this.queuedUrls.add(candidate.link);const feed=(s.rssFeeds||[]).find(f=>f.id===candidate.feedId)||{},forcedExclusive=String(feed.accessMode||'auto')==='exclusive',holder={id:`rss-${Date.now()}-${Math.random().toString(16).slice(2)}`,sourceType:'rss',story:candidate,status:'PROCESANDO',attempts:[],metrics:null,stage:'article',outputRetries:0,isExclusive:forcedExclusive,accessStatus:forcedExclusive?'SUBSCRIBER_ONLY':''};this.queue.push(holder);this.setNewsStatus(candidate,'PROCESANDO',{isExclusive:forcedExclusive,accessStatus:holder.accessStatus});this.state();
    const task=(async()=>{try{const outcome=await this.process(candidate,s,holder,epoch);if(outcome?.omitted){super.markOmitted(holder.story||candidate,outcome.reason||'fuente insuficiente');this.setNewsStatus(holder.story||candidate,'OMITIDA',{reason:outcome.reason||'fuente insuficiente',isExclusive:!!holder.isExclusive,accessStatus:holder.accessStatus,eventId:holder.article?.eventId||''});this.removeItem(holder);return;}Object.assign(holder,outcome);this.assertProcessingActive(epoch);holder.status='LISTA';holder.stage='ready';holder.error='';this.omissionStreak=0;this.setNewsStatus(holder.story,'LISTA',{isExclusive:!!holder.result?.isExclusive,accessStatus:holder.result?.accessStatus||holder.accessStatus,eventId:holder.article?.eventId||''});}
      catch(e){if(e?.code==='PROCESSING_CANCELLED')this.removeItem(holder);else if(this.isEditorialFailure(e)){super.markOmitted(holder.story||candidate,'generación inválida tras 2 intentos');this.setNewsStatus(holder.story||candidate,'OMITIDA',{reason:'generación inválida tras 2 intentos',isExclusive:!!holder.isExclusive,accessStatus:holder.accessStatus,eventId:holder.article?.eventId||''});this.removeItem(holder);}else{if(this.isVoiceInfrastructureFailure(e,holder))this.haltProcessingForVoiceError(e);holder.status='ERROR';holder.error=e.message;holder.attempts=e.details||holder.attempts||[];this.setNewsStatus(holder.story||candidate,'ERROR',{reason:e.message||'error',isExclusive:!!holder.isExclusive,accessStatus:holder.accessStatus,eventId:holder.article?.eventId||''});this.emit('error-item',{title:candidate.title,error:e.message,details:e.details,stage:holder.stage});}}
      finally{this.inFlight.delete(task);if(!this.processingRunning&&!this.inFlight.size&&!this.voiceFailureLatched)this.processingNotice='Preparación de noticias detenida.';this.state();this.kickDocumentWorker();}})();this.inFlight.add(task);
  }
  async process(story,s,holder,epoch){
    let article;holder.stage='article';this.state();try{article=await this.fetchArticle(story.link);}catch(e){e.message=`Artículo: ${e.message}`;throw e;}holder.article=article;this.assertProcessingActive(epoch);if(!this.isFeedActive(story,this.getSettings()||s))return{omitted:true,reason:'fuente pausada o eliminada'};
    let access=articleAccess(story,article,s);if(!story.pubDate||access.exclusive||String(article?.access?.status||'')==='UNKNOWN'){const meta=await fetchArticleMetadata(article.finalUrl||story.link);if(meta.pubDate&&!article.pubDate)article.pubDate=meta.pubDate;if(meta.publicPreview&&!article.publicPreview)article.publicPreview=meta.publicPreview;if(meta.strongLock){article.isExclusive=true;article.access={...(article.access||{}),status:'SUBSCRIBER_ONLY',confidence:'high',signals:{...(article.access?.signals||{}),strongLock:true}};}access=articleAccess(story,article,s);}
    holder.isExclusive=access.exclusive;holder.accessStatus=access.status;if(!story.pubDate&&article.pubDate){holder.story={...holder.story,pubDate:article.pubDate};story=holder.story;}
    if(article.isLiveBlog&&article.liveblogNoEvent)return{omitted:true,reason:'liveblog sin evento factual nuevo'};if(['DEFECTIVE','INSUFFICIENT'].includes(article.contentState)&&!(article.isLiveBlog&&article.liveEvent)&&!access.exclusive)return{omitted:true,reason:'extracción de artículo insuficiente'};
    if(article.eventId){const original=story.link,eventLink=`${original}#ec-event=${encodeURIComponent(article.eventId)}`;if(s.automation.avoidRepeats&&this.history.has(eventLink))return{omitted:true,reason:'evento del liveblog ya emitido'};holder.originalLink=original;holder.story={...holder.story,link:eventLink};story=holder.story;}
    let sourceArticle=article;if(access.exclusive){if(!exclusiveContextSufficient(story,article))return{omitted:true,reason:'información pública insuficiente'};sourceArticle=buildExclusivePublicArticle(story,article);}
    const image=story.image||article.image||this.getFallbackUrl();holder.stage='ai';this.state();let ai;try{ai=await this.providers.generate(story,sourceArticle,s);}catch(e){e.message=`IA: ${e.message}`;throw e;}this.assertProcessingActive(epoch);holder.provider=ai.provider;holder.model=ai.model;holder.attempts=ai.attempts||[];holder.metrics=ai.metrics||null;if(ai.result.status===STATUS_INSUFFICIENT)return{omitted:true,reason:access.exclusive?'información pública insuficiente':'fuente insuficiente'};
    const closing=applyClosings(story,article,ai.result,s),result=closing.result;holder.isExclusive=!!result.isExclusive;holder.accessStatus=result.accessStatus||access.status;
    const local=await this.runLocalHeavy(async()=>{this.assertProcessingActive(epoch);holder.stage='pronunciation';this.state();const spoken=locutionSource(result.title||story.title,closing.spokenScript||result.script);let locution={text:spoken,elapsedMs:0,smartUsed:false,smartFailed:false};if(this.pronunciation)locution=await this.pronunciation.normalize(spoken,{smart:s.tts?.pronunciationSmart!==false});this.assertProcessingActive(epoch);holder.metrics={...(holder.metrics||{}),pronunciationElapsedMs:locution.elapsedMs||0,pronunciationSmart:!!locution.smartUsed,pronunciationSmartFailed:!!locution.smartFailed,pronunciationSmartError:locution.smartFailed?String(locution.smartError||'').slice(0,180):'',pronunciationClaude:!!locution.claudeUsed,pronunciationLearned:locution.learnedCount||0};holder.stage='tts';this.state();let audio;try{audio=await this.kokoro.generate(locution.text,{voice:s.tts.voice,speed:s.tts.speed});}catch(e){e.message=`Voz: ${e.message}`;e.details=ai.attempts||[];throw e;}try{this.assertProcessingActive(epoch);}catch(e){this.kokoro?.cleanupAudio?.(audio.path);throw e;}holder.metrics={...(holder.metrics||{}),ttsElapsedMs:audio.elapsedMs||0,ttsThreads:audio.threads||2,audioDurationSec:audio.durationSec||0,ttsRealtimeFactor:audio.realtimeFactor||0,ttsProfile:audio.performanceLabel||audio.performanceProfile||'',ttsPersistent:!!audio.persistent,ttsWorkerStartupMs:audio.workerStartupMs||0};return{locution,audio};});
    return{article,provider:ai.provider,model:ai.model,result:{...result,ttsScript:local.locution.text},attempts:ai.attempts||[],metrics:holder.metrics,audio:local.audio,image,fallback:this.getFallbackUrl(),isExclusive:!!result.isExclusive,accessStatus:result.accessStatus||access.status};
  }
  async consumer(epoch){
    while(this.emissionRunning&&epoch===this.emissionEpoch){
      if(this.emissionPaused){await wait(300);continue;}if(!this.isOutputReady()){this.emissionPaused=true;this.state({notice:'Abre Output para continuar la emisión'});continue;}
      const s=this.getSettings(),anyReady=this.queue.some(x=>x.status==='LISTA'),reason=this.cannedReason(s,anyReady);if(reason){const played=await this.playCanned(s,reason);if(played)continue;}
      const item=chooseNewsItem(this.queue,s.automation?.exclusiveEveryNews,this.exclusiveHasEmitted,this.newsSinceExclusive);if(!item){await wait(300);continue;}
      this.currentItem=item;this.currentKind='news';this.currentCanned=null;item.status='AL AIRE';item.error='';if(item.sourceType==='rss')this.setNewsStatus(item.story,'AL AIRE',{isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus,eventId:item.article?.eventId||''});this.state();
      const next=chooseNewsItem(this.queue.filter(x=>x!==item),s.automation?.exclusiveEveryNews,this.exclusiveHasEmitted,this.newsSinceExclusive),p={source:'automatic',kind:'news',title:item.result.title||item.story.title,category:item.result.category||item.story.category||'ACTUALIDAD',pubDate:item.story.pubDate||item.article?.pubDate||'',summary:item.result.summary||'',script:item.result.script,image:item.image,preloadImage:next?.image||'',fallbackImage:item.fallback,audioUrl:item.audio.url,audioDurationSec:item.audio.durationSec||item.result.durationSec||60};
      const sent=this.sendAutomaticOutput(p);if(!sent){item.status='LISTA';if(item.sourceType==='rss')this.setNewsStatus(item.story,'LISTA',{isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus,eventId:item.article?.eventId||''});this.currentItem=null;this.currentKind='none';this.emissionPaused=true;this.state({notice:'Output no disponible'});continue;}
      const expected=Math.max(10,Number(p.audioDurationSec)||60)*1000+15000,result=await this.waitPlayback(expected);
      if(result==='ended'){
        if(item.sourceType==='rss'&&/^https?:/i.test(item.story.link||''))this.history.add(item.story,{isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus||''});item.status='EMITIDA';this.newsEmitted++;this.scheduledNewsTotal++;this.recordExclusiveEmission(item);const extra={durationSec:p.audioDurationSec,isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus||'',storyKey:storyKey(item.story),baseKey:baseStoryKey(item.story),storyUrl:String(item.story?.link||'')};this.addEmissionHistory(item.sourceType||'rss',p.title,'EMITIDA',extra);if(item.sourceType==='rss')this.setNewsStatus(item.story,'EMITIDA',{isExclusive:!!item.result?.isExclusive,accessStatus:extra.accessStatus,eventId:item.article?.eventId||''});this.state();await wait((this.getSettings().visual.pauseSeconds||2.5)*1000);this.removeItem(item);this.kickDocumentWorker();
      }else if(result==='error'||result==='timeout'){
        try{this.controlOutput('stop');}catch{}item.outputRetries=(item.outputRetries||0)+1;item.error=result==='timeout'?'El audio excedió el tiempo esperado':'No se pudo reproducir el audio';if(item.outputRetries<=1){item.status='LISTA';if(item.sourceType==='rss')this.setNewsStatus(item.story,'LISTA',{isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus,eventId:item.article?.eventId||''});this.state({notice:`Reintentando una vez: ${item.story.title}`});await wait(750);}else{item.status='ERROR';this.cleanupItemAudio(item);if(item.sourceType==='rss')this.setNewsStatus(item.story,'ERROR',{reason:item.error,isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus,eventId:item.article?.eventId||''});this.emit('error-item',{title:item.story.title,error:`${item.error}. Se omitió tras 1 reintento.`,stage:'output'});this.state({notice:'Una noticia con audio defectuoso fue omitida; continúa la siguiente.'});}
      }else{item.status='LISTA';if(item.sourceType==='rss')this.setNewsStatus(item.story,'LISTA',{isExclusive:!!item.result?.isExclusive,accessStatus:item.result?.accessStatus||item.accessStatus,eventId:item.article?.eventId||''});if(result==='closed'||result==='interrupted')this.emissionPaused=true;}
      this.currentItem=null;this.currentKind='none';this.state();
    }
  }
}
module.exports={AutomationEngine,applyClosings,articleAccess,buildExclusivePublicArticle,exclusiveContextSufficient,chooseNewsItem};
