'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {pathToFileURL}=require('url');

const BASE_FONTS=['Arial','Segoe UI','Verdana','Georgia','Impact'];
const WEIGHTS=[100,200,300,400,500,600,700,800,900];
function safeText(v){return String(v||'').replace(/\0/g,'').replace(/\s+/g,' ').trim();}
function decodeUtf16BE(buf){let out='';for(let i=0;i+1<buf.length;i+=2)out+=String.fromCharCode(buf.readUInt16BE(i));return safeText(out);}
function decodeName(buf,platform){if(platform===0||platform===3)return decodeUtf16BE(buf);return safeText(buf.toString('latin1'));}
function fileHash(file){const h=crypto.createHash('sha1'),fd=fs.openSync(file,'r');try{const b=Buffer.alloc(1024*1024);let n;while((n=fs.readSync(fd,b,0,b.length,null))>0)h.update(b.subarray(0,n));}finally{fs.closeSync(fd);}return h.digest('hex');}
function fixed1616(n){return n/65536;}
function tableMap(buf){if(buf.length<12)throw new Error('Fuente incompleta');const sig=buf.toString('ascii',0,4);if(sig==='wOFF'||sig==='wOF2')throw new Error('Use TTF u OTF; WOFF/WOFF2 no se importan en esta versión');const num=buf.readUInt16BE(4),out={};if(num<1||num>256)throw new Error('Tabla SFNT inválida');for(let i=0;i<num;i++){const p=12+i*16;if(p+16>buf.length)break;const tag=buf.toString('ascii',p,p+4),offset=buf.readUInt32BE(p+8),length=buf.readUInt32BE(p+12);if(offset+length<=buf.length)out[tag]={offset,length};}return out;}
function readNames(buf,tables){const t=tables.name;if(!t||t.length<6)throw new Error('La fuente no contiene nombres');const base=t.offset,count=buf.readUInt16BE(base+2),strOff=buf.readUInt16BE(base+4),records=[];for(let i=0;i<count;i++){const p=base+6+i*12;if(p+12>base+t.length)break;const platform=buf.readUInt16BE(p),encoding=buf.readUInt16BE(p+2),language=buf.readUInt16BE(p+4),nameId=buf.readUInt16BE(p+6),len=buf.readUInt16BE(p+8),off=buf.readUInt16BE(p+10),s=base+strOff+off;if(s+len>buf.length)continue;const value=decodeName(buf.subarray(s,s+len),platform);if(value)records.push({platform,encoding,language,nameId,value});}
  const pick=(ids)=>{for(const id of ids){const candidates=records.filter(x=>x.nameId===id);const preferred=candidates.find(x=>x.language===0x0409)||candidates.find(x=>x.platform===3)||candidates[0];if(preferred)return preferred.value;}return'';};
  return{family:pick([16,1]),subfamily:pick([17,2]),postscript:pick([6])};}
function canonicalVariant(weight,style,subfamily=''){const italic=style==='italic';if(italic)return /bold|black|heavy/i.test(String(subfamily||''))||weight>=650?'bolditalic':'italic';if(weight>=850)return'black';if(weight>=750)return'extrabold';if(weight>=650)return'bold';if(weight>=550)return'semibold';if(weight>=450)return'medium';return'regular';}
function labelForVariant(v,weight){return({regular:'Regular',medium:'Medium',semibold:'Semibold',bold:'Bold',extrabold:'Extra Bold',black:'Black',italic:'Italic',bolditalic:'Bold Italic'}[v]||`${weight}`);}
function parseFont(file){const buf=fs.readFileSync(file);const tables=tableMap(buf),names=readNames(buf,tables);let weight=400,style=/italic|oblique/i.test(names.subfamily)?'italic':'normal';const os2=tables['OS/2'];if(os2&&os2.length>=6){const w=buf.readUInt16BE(os2.offset+4);if(w>=1&&w<=1000)weight=w;}const head=tables.head;if(head&&head.length>=46){const macStyle=buf.readUInt16BE(head.offset+44);if(macStyle&2)style='italic';}
  const axes={};const fvar=tables.fvar;if(fvar&&fvar.length>=16){const base=fvar.offset,axesOffset=buf.readUInt16BE(base+4),axisCount=buf.readUInt16BE(base+8),axisSize=buf.readUInt16BE(base+10);for(let i=0;i<axisCount;i++){const p=base+axesOffset+i*axisSize;if(axisSize<20||p+20>base+fvar.length)break;const tag=buf.toString('ascii',p,p+4);axes[tag]={min:fixed1616(buf.readInt32BE(p+4)),def:fixed1616(buf.readInt32BE(p+8)),max:fixed1616(buf.readInt32BE(p+12))};}}
  const family=safeText(names.family)||safeText(path.basename(file,path.extname(file)).replace(/[-_]+/g,' ').replace(/\b(Regular|Bold|Black|Medium|SemiBold|ExtraBold|Italic|VariableFont)\b/gi,''));if(!family)throw new Error('No se pudo identificar la familia tipográfica');return{family,subfamily:names.subfamily||'Regular',postscript:names.postscript,weight,style,axes,variable:!!axes.wght};}
function descriptorUrl(file,weight,style,variant){const u=pathToFileURL(file).href;return`${u}#ecw=${Math.round(weight)}&ecs=${encodeURIComponent(style)}&ecv=${encodeURIComponent(variant)}`;}
function facesForFile(file){const meta=parseFont(file),hash=fileHash(file),weights=meta.variable?WEIGHTS.filter(w=>w>=Math.max(100,meta.axes.wght.min)&&w<=Math.min(900,meta.axes.wght.max)):[Math.max(100,Math.min(900,Math.round(meta.weight/100)*100))];const selected=weights.length?weights:[400];return selected.map(w=>{const variant=canonicalVariant(w,meta.style,meta.subfamily);return{family:meta.family,variant,variantLabel:labelForVariant(variant,w),weight:w,style:meta.style,file,url:descriptorUrl(file,w,meta.style,variant),custom:true,variable:meta.variable,hash,postscript:meta.postscript||'',subfamily:meta.subfamily||''};});}

class FontManager{
  constructor(dataDir){this.dataDir=dataDir;this.dir=path.join(dataDir,'fonts');this.cacheFile=path.join(this.dir,'fonts-cache.json');fs.mkdirSync(this.dir,{recursive:true});}
  async windowsFonts(){return[...BASE_FONTS];}
  custom(){const out=[];for(const name of fs.readdirSync(this.dir)){const ext=path.extname(name).toLowerCase();if(!['.ttf','.otf'].includes(ext))continue;const file=path.join(this.dir,name);try{out.push(...facesForFile(file));}catch{const family=safeText(path.basename(file,ext).replace(/[_-]+/g,' '));out.push({family,variant:'regular',variantLabel:'Regular',weight:400,style:'normal',file,url:descriptorUrl(file,400,'normal','regular'),custom:true,variable:false,invalid:true,hash:''});}}return out.sort((a,b)=>a.family.localeCompare(b.family,'es',{sensitivity:'base'})||a.weight-b.weight||a.style.localeCompare(b.style));}
  async list(){return{installed:[...BASE_FONTS],custom:this.custom()};}
  importFont(src){const file=String(src||'').trim(),ext=path.extname(file).toLowerCase();if(!['.ttf','.otf'].includes(ext))throw new Error('Formato no compatible. Importa una fuente TTF u OTF');if(!fs.existsSync(file))throw new Error('No se encontró la fuente');const probe=facesForFile(file);if(!probe.length||probe.some(x=>x.invalid))throw new Error('La fuente no se pudo validar');const hash=probe[0].hash,existing=this.custom().find(x=>x.hash&&x.hash===hash);if(existing)return{...existing,duplicate:true};let dest=path.join(this.dir,path.basename(file)),n=2;while(fs.existsSync(dest))dest=path.join(this.dir,`${path.basename(file,ext)}-${n++}${ext}`);fs.copyFileSync(file,dest);const imported=facesForFile(dest);return{...imported[0],variants:imported.map(x=>({variant:x.variant,label:x.variantLabel,weight:x.weight,style:x.style,url:x.url})),duplicate:false};}
  removeFont(family){const target=String(family||'').trim(),faces=this.custom().filter(x=>x.family===target||x.postscript===target);if(!faces.length)throw new Error('Fuente personalizada no encontrada');const files=[...new Set(faces.map(x=>x.file))];for(const file of files)try{fs.rmSync(file,{force:true});}catch{}return{family:faces[0].family,removed:files.length,files};}
}
module.exports={FontManager,BASE_FONTS,parseFont,facesForFile,canonicalVariant};
