const fs=require('fs');
const path=require('path');
const os=require('os');
const {spawn}=require('child_process');
const {pathToFileURL}=require('url');
const {candidateThreads,safeThreadCap,median,selectEfficientCandidate}=require('./ttsOptimizer');

const TTS_PROFILES={safe_streaming:{label:'Seguro para transmisión',intra:2,inter:1,priority:'below'},balanced:{label:'Equilibrado',intra:3,inter:1,priority:'below'},performance:{label:'Rápido',intra:6,inter:1,priority:'below'}};
const BENCHMARK_WARMUP='EC Automatic News prepara el motor de voz antes de medir su velocidad real en español.';
const BENCHMARK_TEXT='EC Automatic News realiza esta prueba para encontrar una configuración rápida y estable para esta computadora. El objetivo es medir la generación de una locución similar a una noticia real, con frases de distinta longitud, cifras y pausas naturales. La prueba utiliza un solo motor de voz, mantiene recursos disponibles para otras aplicaciones y compara varias cantidades de hilos antes de elegir la opción más eficiente para la transmisión automática.';
const delay=ms=>new Promise(r=>setTimeout(r,ms));

class KokoroTTS{
  constructor({resourcesDir,dataDir}){this.resourcesDir=resourcesDir;this.dataDir=dataDir;this.python=path.join(resourcesDir,'runtime','python','python.exe');this.script=path.join(resourcesDir,'runtime','kokoro','tts.py');this.model=path.join(resourcesDir,'runtime','kokoro','kokoro-v1.0.int8.onnx');this.voices=path.join(resourcesDir,'runtime','kokoro','voices-v1.0.bin');this.espeakRoot=path.join(resourcesDir,'runtime','python','Lib','site-packages','espeakng_loader');this.espeakData=path.join(this.espeakRoot,'espeak-ng-data');this.espeakLibrary=path.join(this.espeakRoot,'espeak-ng.dll');this.espeakPhontab=path.join(this.espeakData,'phontab');this.settingsFile=path.join(dataDir,'settings.json');this.audioDir=path.join(dataDir,'audio');fs.mkdirSync(this.audioDir,{recursive:true});this.generationTail=Promise.resolve();this.worker=null;this.workerProfile='';this.workerProfileKey='';this.workerReady=false;this.workerStarting=null;this.workerStartedAt=0;this.workerPending=new Map();this.workerSeq=0;this.workerBuffer='';this.workerIdleTimer=null;this.workerLastUsedAt=0;this.workerHealth=null;this.healthPromise=null;this.voiceCache=null;this.voiceCachePromise=null;this.recentRealtimeFactors=[];this.cleanupOldAudio();}
  ready(){return[this.python,this.script,this.model,this.voices,this.espeakLibrary,this.espeakPhontab].every(fs.existsSync);}settings(){try{return JSON.parse(fs.readFileSync(this.settingsFile,'utf8'));}catch{return{};}}persistentEnabled(){return this.settings()?.tts?.persistent!==false;}idleMinutes(){return Math.max(1,Math.min(30,Number(this.settings()?.tts?.persistentIdleMinutes)||5));}logicalCpuCount(){return Math.max(1,Number(os.cpus()?.length)||1);}performanceThreadCap(){return safeThreadCap(this.logicalCpuCount());}
  profileName(s=null){const settings=s||this.settings(),mode=String(settings?.tts?.resourceMode||'safe_streaming');return TTS_PROFILES[mode]?mode:'safe_streaming';}
  profile(){const s=this.settings(),name=this.profileName(s),base={name,...TTS_PROFILES[name]};if(name!=='performance')return base;const cap=this.performanceThreadCap(),saved=Number(s?.tts?.performanceThreads),fallback=Math.min(6,cap),intra=Math.max(1,Math.min(cap,Number.isFinite(saved)&&saved>0?Math.round(saved):fallback));return{...base,intra};}
  profileKey(profile){return`${profile.name}:${Math.max(1,Number(profile.intra)||1)}:${Math.max(1,Number(profile.inter)||1)}:${profile.priority||'below'}`;}
  envFor(profile){const threads=String(Math.max(1,profile.intra||2)),env={...process.env,PYTHONNOUSERSITE:'1',PYTHONUTF8:'1',OMP_NUM_THREADS:threads,OMP_THREAD_LIMIT:threads,OMP_DYNAMIC:'FALSE',OMP_WAIT_POLICY:'PASSIVE',OPENBLAS_NUM_THREADS:threads,MKL_NUM_THREADS:threads,NUMEXPR_NUM_THREADS:threads};delete env.PHONEMIZER_ESPEAK_LIBRARY;delete env.PHONEMIZER_ESPEAK_DATA_PATH;delete env.ESPEAK_DATA_PATH;return env;}
  spawnOptions(profile){return{windowsHide:true,env:this.envFor(profile),cwd:this.resourcesDir};}
  setProcessPriority(p,profile){try{const priority=profile.priority==='normal'?os.constants.priority.PRIORITY_NORMAL:os.constants.priority.PRIORITY_BELOW_NORMAL;os.setPriority(p.pid,priority);}catch{}}
  run(args,profile=this.profile(),timeoutMs=120000){return new Promise((resolve,reject)=>{if(!this.ready())return reject(new Error('El motor de voz no está disponible en esta instalación'));const p=spawn(this.python,[this.script,...args],this.spawnOptions(profile));let out='',err='',settled=false;const finish=(fn,value)=>{if(settled)return;settled=true;clearTimeout(timer);fn(value);};const timer=setTimeout(()=>{try{p.kill();}catch{}finish(reject,new Error(`La generación de voz excedió ${Math.round(timeoutMs/1000)} s`));},Math.max(5000,timeoutMs));this.setProcessPriority(p,profile);p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>finish(reject,e));p.on('exit',code=>code===0?finish(resolve,out.trim()):finish(reject,new Error(`El motor de voz se cerró inesperadamente (${code}): ${err.slice(-800)}`)));});}
  async listVoices(){if(Array.isArray(this.voiceCache))return[...this.voiceCache];if(this.voiceCachePromise)return this.voiceCachePromise;const task=(async()=>{const out=await this.run(['--list-voices','--voices',this.voices],{name:'safe_streaming',...TTS_PROFILES.safe_streaming},20000);let voices=[];try{voices=(JSON.parse(out).voices||[]).filter(Boolean);}catch{}this.voiceCache=voices;return[...voices];})();this.voiceCachePromise=task;try{return await task;}finally{if(this.voiceCachePromise===task)this.voiceCachePromise=null;}}
  handleWorkerLine(line){const s=String(line||'').trim();if(!s.startsWith('ECJSON '))return;let data;try{data=JSON.parse(s.slice(7));}catch{return;}if(data.type==='ready'){if(data.ok){this.workerReady=true;this.workerStartedAt=Date.now();this.workerHealth={ok:true,esSupported:data.es_supported===true,espeakData:data.espeak_data||'',languages:Array.isArray(data.languages)?data.languages:[]};this.workerStarting?.resolve?.(true);}else{this.workerHealth={ok:false,esSupported:false,error:data.error||'No se pudo iniciar el motor de voz'};this.workerStarting?.reject?.(new Error(data.error||'No se pudo iniciar el motor de voz'));}return;}const id=String(data.id||''),pending=this.workerPending.get(id);if(!pending)return;this.workerPending.delete(id);clearTimeout(pending.timer);if(data.ok===false)pending.reject(new Error(data.error||'No se pudo generar la voz'));else pending.resolve(data);}
  attachWorker(p){p.stdout.on('data',chunk=>{this.workerBuffer+=chunk.toString();let idx;while((idx=this.workerBuffer.indexOf('\n'))>=0){const line=this.workerBuffer.slice(0,idx);this.workerBuffer=this.workerBuffer.slice(idx+1);this.handleWorkerLine(line);}});let stderr='';p.stderr.on('data',d=>{stderr=(stderr+d.toString()).slice(-1600);});const gone=(err)=>{if(this.worker!==p)return;const message=err?.message||`El motor de voz se cerró${stderr?`: ${stderr}`:''}`;if(this.workerStarting&&!this.workerReady)this.workerStarting.reject?.(new Error(message));this.workerStarting=null;this.workerReady=false;this.worker=null;this.workerProfile='';this.workerProfileKey='';this.workerHealth={ok:false,esSupported:false,error:message};for(const pending of this.workerPending.values()){clearTimeout(pending.timer);pending.reject(new Error(message));}this.workerPending.clear();};p.on('error',gone);p.on('exit',()=>gone());}
  async ensureWorker(profile=this.profile(),force=false){const key=this.profileKey(profile);if(!force&&!this.persistentEnabled())return null;if(this.worker&&this.workerReady&&this.workerProfileKey===key)return this.worker;if(this.workerStarting&&this.workerProfileKey===key)return this.workerStarting.promise;if(this.worker)await this.stopAndWait('profile-change');if(!this.ready())throw new Error('El motor de voz no está disponible en esta instalación');const p=spawn(this.python,[this.script,'--worker','--model',this.model,'--voices',this.voices,'--onnx-intra',String(profile.intra),'--onnx-inter',String(profile.inter)],this.spawnOptions(profile));this.worker=p;this.workerProfile=profile.name;this.workerProfileKey=key;this.workerReady=false;this.workerBuffer='';this.workerHealth=null;this.setProcessPriority(p,profile);this.attachWorker(p);let resolveStart,rejectStart;const promise=new Promise((resolve,reject)=>{resolveStart=resolve;rejectStart=reject;}),timer=setTimeout(()=>rejectStart(new Error('El motor de voz tardó demasiado en iniciar')),90000);this.workerStarting={promise,resolve:v=>{clearTimeout(timer);resolveStart(v);},reject:e=>{clearTimeout(timer);rejectStart(e);}};try{await promise;return this.worker;}finally{this.workerStarting=null;}}
  workerCommand(command,timeoutMs=180000){if(!this.worker||!this.workerReady)throw new Error('El motor de voz todavía no está listo');const id=`k${++this.workerSeq}`,payload={id,...command};return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.workerPending.delete(id);reject(new Error(`La generación de voz excedió ${Math.round(timeoutMs/1000)} s`));this.stop('timeout');},timeoutMs);this.workerPending.set(id,{resolve,reject,timer});try{this.worker.stdin.write(JSON.stringify(payload)+'\n');}catch(e){clearTimeout(timer);this.workerPending.delete(id);reject(e);}});}
  async healthCheck(force=false){if(!force&&this.worker&&this.workerReady&&this.workerHealth?.ok&&this.workerHealth.esSupported)return{...this.workerHealth};if(this.healthPromise)return this.healthPromise;const task=(async()=>{if(!this.ready())throw new Error('Kokoro/eSpeak no están completos en esta instalación');await this.ensureWorker(this.profile());const ping=await this.workerCommand({cmd:'ping'},30000);const health={...(this.workerHealth||{}),ok:!!ping?.ok,esSupported:ping?.es_supported===true,espeakData:ping?.espeak_data||this.workerHealth?.espeakData||''};if(!health.ok||!health.esSupported)throw new Error('eSpeak inició, pero el idioma español no está disponible');this.workerHealth=health;this.workerLastUsedAt=Date.now();this.scheduleIdleStop();return{...health};})();this.healthPromise=task;try{return await task;}finally{if(this.healthPromise===task)this.healthPromise=null;}}
  scheduleIdleStop(){clearTimeout(this.workerIdleTimer);this.workerIdleTimer=null;if(!this.worker)return;this.workerIdleTimer=setTimeout(()=>this.stop('idle'),this.idleMinutes()*60000);}
  stop(reason='manual'){clearTimeout(this.workerIdleTimer);this.workerIdleTimer=null;const p=this.worker;this.worker=null;this.workerReady=false;this.workerProfile='';this.workerProfileKey='';this.workerHealth=null;if(!p)return false;try{p.stdin.write(JSON.stringify({id:`stop-${Date.now()}`,cmd:'stop'})+'\n');}catch{}setTimeout(()=>{try{if(p.exitCode==null&&!p.killed)p.kill();}catch{}},700);return true;}
  async stopAndWait(reason='manual',timeoutMs=2500){const p=this.worker;if(!p)return false;const exited=new Promise(resolve=>{if(p.exitCode!=null)return resolve();p.once('exit',resolve);});this.stop(reason);await Promise.race([exited,delay(Math.max(200,timeoutMs))]);if(p.exitCode==null){try{p.kill();}catch{}await Promise.race([exited,delay(500)]);}return true;}
  cleanupAudio(file){try{const resolved=path.resolve(String(file||'')),root=path.resolve(this.audioDir)+path.sep;if(resolved.startsWith(root)&&fs.existsSync(resolved))fs.rmSync(resolved,{force:true});}catch{}}
  cleanupOldAudio(maxAgeMs=24*60*60*1000){try{const now=Date.now();for(const name of fs.readdirSync(this.audioDir)){if(!/^news-.*\.(wav|txt)$/i.test(name))continue;const full=path.join(this.audioDir,name),st=fs.statSync(full);if(now-st.mtimeMs>maxAgeMs)fs.rmSync(full,{force:true});}}catch{}}
  recordRealtime(rtf){const value=Number(rtf);if(!Number.isFinite(value)||value<=0)return;this.recentRealtimeFactors.push(value);if(this.recentRealtimeFactors.length>10)this.recentRealtimeFactors.splice(0,this.recentRealtimeFactors.length-10);}
  generate(text,{voice='ef_dora',speed=1.0}={}){const task=async()=>{const profile=this.profile(),started=Date.now(),id=`news-${Date.now()}-${Math.random().toString(16).slice(2)}`,txt=path.join(this.audioDir,`${id}.txt`),wav=path.join(this.audioDir,`${id}.wav`);fs.writeFileSync(txt,text,'utf8');try{let meta={},persistent=false,workerStartupMs=0,synthesisElapsedMs=0;if(this.persistentEnabled()){const before=Date.now();await this.healthCheck();workerStartupMs=Date.now()-before;persistent=true;const synthStarted=Date.now();meta=await this.workerCommand({cmd:'generate',text_file:txt,output:wav,voice,speed:Number(speed)},180000);synthesisElapsedMs=Date.now()-synthStarted;this.workerLastUsedAt=Date.now();this.scheduleIdleStop();}else{const synthStarted=Date.now(),out=await this.run(['--text-file',txt,'--output',wav,'--voice',voice,'--speed',String(speed),'--model',this.model,'--voices',this.voices,'--onnx-intra',String(profile.intra),'--onnx-inter',String(profile.inter)],profile,180000);synthesisElapsedMs=Date.now()-synthStarted;try{meta=JSON.parse(out);}catch{}}if(!fs.existsSync(wav)||fs.statSync(wav).size<1000)throw new Error('El motor de voz no produjo un audio válido');const elapsedMs=Date.now()-started,durationSec=Number(meta.duration_sec||0),intra=Number(meta.onnx_intra_threads||profile.intra),inter=Number(meta.onnx_inter_threads||profile.inter),realtimeFactor=durationSec>0?Number(((elapsedMs/1000)/durationSec).toFixed(3)):0,steadyRealtimeFactor=durationSec>0?Number(((synthesisElapsedMs/1000)/durationSec).toFixed(3)):0;this.recordRealtime(steadyRealtimeFactor||realtimeFactor);return{path:wav,url:pathToFileURL(wav).href,durationSec,voice:meta.voice||voice,elapsedMs,synthesisElapsedMs,workerStartupMs,persistent,phonemeMs:Number(meta.phoneme_ms||0),inferenceMs:Number(meta.inference_ms||0),threads:intra,onnxIntraThreads:intra,onnxInterThreads:inter,executionMode:meta.execution_mode||'sequential',performanceProfile:profile.name,performanceLabel:profile.label,realtimeFactor,steadyRealtimeFactor};}catch(e){this.cleanupAudio(wav);throw e;}finally{try{fs.rmSync(txt,{force:true});}catch{}}};const queued=this.generationTail.then(task,task);this.generationTail=queued.catch(()=>{});return queued;}
  cpuSnapshot(){let idle=0,total=0;for(const cpu of os.cpus()||[]){const t=cpu.times||{};idle+=Number(t.idle)||0;total+=(Number(t.user)||0)+(Number(t.nice)||0)+(Number(t.sys)||0)+(Number(t.irq)||0)+(Number(t.idle)||0);}return{idle,total};}
  cpuPercentBetween(a,b){const total=Math.max(1,Number(b.total)-Number(a.total)),idle=Math.max(0,Number(b.idle)-Number(a.idle));return Math.max(0,Math.min(100,(1-idle/total)*100));}
  async measureCpuBaseline(ms=1200){const a=this.cpuSnapshot();await delay(Math.max(500,ms));return Number(this.cpuPercentBetween(a,this.cpuSnapshot()).toFixed(1));}
  startCpuMonitor({intervalMs=500,overloadPct=85,overloadSamples=4}={}){let prev=this.cpuSnapshot(),samples=[],streak=0,overloaded=false,peak=0,stopped=false;const sample=()=>{if(stopped)return;const next=this.cpuSnapshot(),pct=this.cpuPercentBetween(prev,next);prev=next;samples.push(pct);peak=Math.max(peak,pct);if(pct>=overloadPct)streak+=1;else streak=0;if(streak>=overloadSamples)overloaded=true;};const timer=setInterval(sample,Math.max(250,intervalMs));return()=>{if(!stopped){sample();stopped=true;clearInterval(timer);}const average=samples.length?samples.reduce((a,b)=>a+b,0)/samples.length:0;return{average:Number(average.toFixed(1)),peak:Number(peak.toFixed(1)),overloaded,samples:samples.length};};}
  async benchmarkPass(profile,textFile,wav,{voice='ef_dora',speed=1}={}){let stopCpu=this.startCpuMonitor(),cpu=null;const started=Date.now();try{const meta=await this.workerCommand({cmd:'generate',text_file:textFile,output:wav,voice,speed:Number(speed)},180000),elapsedMs=Date.now()-started;cpu=stopCpu();stopCpu=null;const durationSec=Number(meta.duration_sec||0);if(!fs.existsSync(wav)||fs.statSync(wav).size<1000||durationSec<=0)throw new Error('La prueba de Kokoro no produjo audio válido');return{elapsedMs,durationSec,realtimeFactor:Number(((elapsedMs/1000)/durationSec).toFixed(3)),cpuAverage:cpu.average,cpuPeak:cpu.peak,cpuOverloaded:cpu.overloaded,phonemeMs:Number(meta.phoneme_ms||0),inferenceMs:Number(meta.inference_ms||0)};}finally{if(stopCpu)stopCpu();this.cleanupAudio(wav);}}
  async benchmarkCandidate(threads,{voice='ef_dora',speed=1}={}){const profile={name:`benchmark-${threads}`,label:`Prueba ${threads} hilos`,intra:Math.max(1,Number(threads)||1),inter:1,priority:'below'},id=`bench-${threads}-${Date.now()}`,warmTxt=path.join(this.audioDir,`${id}-warm.txt`),warmWav=path.join(this.audioDir,`${id}-warm.wav`),txt=path.join(this.audioDir,`${id}.txt`),runs=[];fs.writeFileSync(warmTxt,BENCHMARK_WARMUP,'utf8');fs.writeFileSync(txt,BENCHMARK_TEXT,'utf8');try{await this.stopAndWait('benchmark-switch');await this.ensureWorker(profile,true);await this.workerCommand({cmd:'generate',text_file:warmTxt,output:warmWav,voice,speed:Number(speed)},180000);if(!fs.existsSync(warmWav)||fs.statSync(warmWav).size<1000)throw new Error('El warm-up de Kokoro no produjo audio válido');for(let n=0;n<2;n++){const run=await this.benchmarkPass(profile,txt,path.join(this.audioDir,`${id}-${n}.wav`),{voice,speed});runs.push(run);if(run.cpuOverloaded)break;}const realtimeFactor=Number(median(runs.map(x=>x.realtimeFactor)).toFixed(3)),cpuAverage=Number(median(runs.map(x=>x.cpuAverage)).toFixed(1)),cpuPeak=Number(Math.max(...runs.map(x=>x.cpuPeak),0).toFixed(1)),safe=runs.length===2&&!runs.some(x=>x.cpuOverloaded),error=safe?'':runs.some(x=>x.cpuOverloaded)?`La carga total de CPU superó 85% de forma sostenida con ${profile.intra} hilos`:'La configuración no completó las dos mediciones de seguridad';return{threads:profile.intra,realtimeFactor,cpuAverage,cpuPeak,safe,audioDurationSec:Number(median(runs.map(x=>x.durationSec)).toFixed(2)),runs,error};}catch(e){return{threads:profile.intra,realtimeFactor:999,cpuAverage:0,cpuPeak:0,safe:false,runs,error:e.message||String(e)};}finally{this.cleanupAudio(warmWav);try{fs.rmSync(warmTxt,{force:true});fs.rmSync(txt,{force:true});}catch{}await this.stopAndWait('benchmark-candidate-finished');}}
  benchmark({voice='ef_dora',speed=1}={}){const task=async()=>{if(!this.ready())return{ok:false,error:'El motor de voz no está disponible en esta instalación',results:[]};const logicalCpus=this.logicalCpuCount(),maxSafeThreads=this.performanceThreadCap(),candidates=candidateThreads(logicalCpus),baselineCpu=await this.measureCpuBaseline(1200);if(baselineCpu>=75)return{ok:false,error:`La computadora ya tiene ${baselineCpu.toFixed(0)}% de uso de CPU. Cierra o pausa tareas pesadas y vuelve a ejecutar la optimización.`,logicalCpus,maxSafeThreads,candidates,baselineCpu,results:[]};const results=[];for(const threads of candidates){const result=await this.benchmarkCandidate(threads,{voice,speed});results.push(result);if(result.safe===false&&result.cpuPeak>=85)break;}const recommended=selectEfficientCandidate(results,{tolerance:.03});if(!recommended)return{ok:false,error:'No se encontró una configuración de Kokoro que completara la prueba dentro del margen de seguridad.',logicalCpus,maxSafeThreads,candidates,baselineCpu,results};const valid=results.filter(x=>x.safe!==false&&!x.error&&Number.isFinite(Number(x.realtimeFactor))),fastest=valid.length?Math.min(...valid.map(x=>Number(x.realtimeFactor))):Number(recommended.realtimeFactor);return{ok:true,recommended:'performance',recommendedThreads:Number(recommended.threads),bestRealtimeFactor:Number(recommended.realtimeFactor),fastestRealtimeFactor:Number(fastest.toFixed(3)),logicalCpus,maxSafeThreads,candidates,baselineCpu,efficiencyTolerancePct:3,results};};const queued=this.generationTail.then(task,task);this.generationTail=queued.catch(()=>{});return queued;}
  status(){const p=this.profile(),recent=median(this.recentRealtimeFactors);return{ready:this.ready(),persistent:this.persistentEnabled(),workerRunning:!!this.worker&&this.workerReady,workerProfile:this.workerProfile||'',healthy:!!this.workerHealth?.ok&&this.workerHealth?.esSupported===true,healthError:this.workerHealth?.error||'',idleMinutes:this.idleMinutes(),workerIdleForSec:this.workerLastUsedAt?Math.max(0,Math.round((Date.now()-this.workerLastUsedAt)/1000)):0,logicalCpus:this.logicalCpuCount(),maxSafeThreads:this.performanceThreadCap(),threads:p.intra,profile:p.name,profileLabel:p.label,recentRealtimeFactor:recent?Number(recent.toFixed(3)):0,recentSamples:this.recentRealtimeFactors.length};}
}
module.exports={KokoroTTS,TTS_PROFILES};
