'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {app,ipcMain,dialog,BrowserWindow}=require('electron');
const {SettingsStore}=require('./settings');
const {HistoryStore}=require('./history');
const {CannedManager,bestDurationIndex}=require('./canned');
const {AutomationEngine}=require('./automation0325');
const {FontManager}=require('./fonts');
const {CustomVoiceManager}=require('./customVoices');
const {getProfileManager,DEFAULT_QUEUE_COLORS,readJson,atomicJson}=require('./profileManager0329');
const {ProfilePackage0329}=require('./profilePackage0329');

const wait=ms=>new Promise(r=>setTimeout(r,ms));
const keyPath=v=>{try{return path.resolve(String(v||'')).normalize('NFKC').toLocaleLowerCase('es');}catch{return String(v||'').normalize('NFKC').toLocaleLowerCase('es');}};
function dataRoot(){const portable=process.env.PORTABLE_EXECUTABLE_DIR;if(portable)return path.join(portable,'EC Automatic News Data');if(app.isPackaged)return path.join(path.dirname(process.execPath),'EC Automatic News Data');return path.join(app.getPath('userData'),'EC Automatic News Data');}
function manager(){const m=getProfileManager(dataRoot());global.__ec0329ProfileManager=m;return m;}
function defaults(){try{return SettingsStore.prototype.defaults.call({baseDir:dataRoot()});}catch{return{};}}
function controlWindow(){return BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!/OUTPUT/i.test(w.getTitle?.()||''))||null;}
function outputWindows(){return BrowserWindow.getAllWindows().filter(w=>!w.isDestroyed()&&(/OUTPUT/i.test(w.getTitle?.()||'')||/output\.html/i.test(w.webContents?.getURL?.()||'')));}
function sendControl(channel,payload){const w=controlWindow();if(w)w.webContents.send(channel,payload);}

function installSettingsRouting(){const p=SettingsStore.prototype;if(p.__ec0329ProfileRouting)return;Object.defineProperty(p,'__ec0329ProfileRouting',{value:true});const d=p.defaults;p.load=function(){const m=getProfileManager(this.baseDir),base=d.call(this);global.__ec0329ProfileManager=m;return m.effectiveSettings(base);};p.save=function(settings){const m=getProfileManager(this.baseDir),base=d.call(this);global.__ec0329ProfileManager=m;m.saveEffective(base,settings);return settings;};}

function installHistoryRouting(){const p=HistoryStore.prototype;if(p.__ec0329ProfileRouting)return;Object.defineProperty(p,'__ec0329ProfileRouting',{value:true});function bind(self){if(!self.__ec0329BaseDir)self.__ec0329BaseDir=path.dirname(self.file||path.join(dataRoot(),'history.json'));const m=getProfileManager(self.__ec0329BaseDir),id=m.activeId();if(self.__ec0329ProfileId===id&&self.data)return id;self.__ec0329ProfileId=id;self.file=id?m.historyFile(id):path.join(self.__ec0329BaseDir,'.no-profile-history.json');let x=id?readJson(self.file,{emitted:[],automation:{}}):{emitted:[],automation:{}};self.data={emitted:Array.isArray(x?.emitted)?x.emitted:[],automation:x?.automation&&typeof x.automation==='object'?x.automation:{}};self.urls=new Set(self.data.emitted.map(x=>x?.url).filter(Boolean));return id;}
  p.read=function(){bind(this);return{emitted:[...(this.data?.emitted||[])],automation:{...(this.data?.automation||{})}};};p.load=function(){bind(this);return{emitted:[...(this.data.emitted||[])],automation:{...(this.data.automation||{})}};};p.save=function(){if(!bind(this))return;atomicJson(this.file,this.data);};p.has=function(url){bind(this);return!!url&&this.urls.has(url);};p.add=function(story,extra={}){if(!bind(this))return;const url=String(story?.link||'').trim();if(!url||this.urls.has(url))return;this.data.emitted.unshift({url,title:String(story?.title||''),at:new Date().toISOString(),...extra});if(this.data.emitted.length>5000)this.data.emitted.length=5000;this.urls=new Set(this.data.emitted.map(x=>x.url).filter(Boolean));this.save();};p.getAutomationState=function(){bind(this);return{...(this.data.automation||{})};};p.setAutomationState=function(patch={}){if(!bind(this))return{};this.data.automation={...(this.data.automation||{}),...patch,updatedAt:new Date().toISOString()};this.save();return{...this.data.automation};};p.reset=function(){if(!bind(this))return;this.data={emitted:[],automation:{}};this.urls.clear();this.save();};}

function installCannedRouting(){const p=CannedManager.prototype;if(p.__ec0329ProfileCycle)return;Object.defineProperty(p,'__ec0329ProfileCycle',{value:true});const baseList=p.list,baseReset=p.reset;const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=crypto.randomInt(i+1);[x[i],x[j]]=[x[j],x[i]];}return x;};const rel=(folder,file)=>path.relative(path.resolve(folder),path.resolve(file)).replace(/\\/g,'/');const abs=(folder,r)=>path.join(folder,...String(r||'').split('/'));
  function source(self,folder){const m=manager(),id=m.activeId();if(!id)return null;const s=m.readProfileSettings(id),c=s.canned||{},f=keyPath(folder),cf=keyPath(c.folder),af=keyPath(c.adsFolder);let role=self.__ec0329Role;if(!role){role=f&&af&&f===af&&f!==cf?'ad':'content';self.__ec0329Role=role;}const sourceId=role==='ad'?(c.adSourceId||'ads'):(c.contentSourceId||'content');return{m,id,role,sourceId,file:m.cycleFile(id)};}
  function state(src){const all=readJson(src.file,{version:2,sources:{}})||{version:2,sources:{}};all.version=2;all.sources=all.sources||{};return all;}
  function rec(self,folder,scan,{advance=false,write=true}={}){const src=source(self,folder);if(!src)return null;const all=state(src),k=`${src.role}:${src.sourceId}`,available=(scan.files||[]).map(x=>rel(folder,x.path)),set=new Set(available);let r=all.sources[k];if(!r)r={cycleNumber:1,cycleStartedAt:new Date().toISOString(),remaining:[],played:[],recent:[],last:''};r.remaining=(r.remaining||[]).filter(x=>set.has(x));r.played=(r.played||[]).filter(x=>set.has(x)&&!r.remaining.includes(x));r.recent=(r.recent||[]).filter(x=>set.has(x)).slice(-8);const known=new Set([...r.remaining,...r.played]),added=available.filter(x=>!known.has(x));if(added.length)r.remaining.push(...shuffle(added));if(advance&&!r.remaining.length&&available.length&&r.played.length>=available.length){r.cycleNumber=Math.max(1,Number(r.cycleNumber)||1)+1;r.cycleStartedAt=new Date().toISOString();r.played=[];r.remaining=shuffle(available);if(r.remaining.length>1&&r.last&&r.remaining[0]===r.last){const j=1+crypto.randomInt(r.remaining.length-1);[r.remaining[0],r.remaining[j]]=[r.remaining[j],r.remaining[0]];}}if(!r.remaining.length&&available.length&&!r.played.length)r.remaining=shuffle(available);all.sources[k]=r;if(write)atomicJson(src.file,all);return{src,all,k,r,available};}
  p.reset=function(){baseReset.call(this);this.__ec0328ReservedPath='';};p.ensureBag=function(folder){const scan=baseList.call(this,folder);if(!scan.ok||!scan.files.length){const e=new Error(scan.message||'No hay contenidos disponibles');e.code='CANNED_EMPTY';throw e;}const x=rec(this,folder,scan,{advance:true}),by=new Map(scan.files.map(i=>[rel(folder,i.path),i]));this.bag=(x?.r.remaining||[]).map(r=>by.get(r)).filter(Boolean);this.lastPath=x?.r.last?abs(folder,x.r.last):'';return scan;};p.reservePath=function(v){this.__ec0328ReservedPath=String(v||'');};p.peekForDuration=function(folder,targetSec){const scan=this.ensureBag(folder),i=bestDurationIndex(this.bag,targetSec),item=this.bag[i<0?0:i];return item?{...item,remainingInCycle:this.bag.length,total:scan.files.length}:null;};p.pickPath=function(folder,wanted){const scan=this.ensureBag(folder),idx=this.bag.findIndex(x=>keyPath(x.path)===keyPath(wanted));if(idx<0)return null;const item=this.bag.splice(idx,1)[0],x=rec(this,folder,scan,{advance:false,write:false}),r=x.r,rr=rel(folder,item.path);r.remaining=r.remaining.filter(v=>v!==rr);if(!r.played.includes(rr))r.played.push(rr);r.last=rr;r.recent=[...r.recent.filter(v=>v!==rr),rr].slice(-8);x.all.sources[x.k]=r;atomicJson(x.src.file,x.all);this.lastPath=item.path;return{...item,remainingInCycle:r.remaining.length,total:scan.files.length,cycleNumber:r.cycleNumber};};p.pickForDuration=function(folder,targetSec){const scan=this.ensureBag(folder),i=bestDurationIndex(this.bag,targetSec),item=this.bag[i<0?0:i];return item?this.pickPath(folder,item.path):null;};p.peek=function(folder){return this.peekForDuration(folder,this.requestedDurationSec||0);};p.pick=function(folder){const reserved=this.__ec0328ReservedPath;this.__ec0328ReservedPath='';const target=this.requestedDurationSec||0;this.requestedDurationSec=0;if(reserved){const item=this.pickPath(folder,reserved);if(item)return item;}return this.pickForDuration(folder,target);};p.cycleStatus=function(folder){const scan=baseList.call(this,folder);if(!scan.ok||!scan.files.length)return{ok:false,total:0,emitted:0,remaining:0,recent:[],cycleNumber:0,complete:false};const x=rec(this,folder,scan,{advance:false}),r=x.r,by=new Map(scan.files.map(i=>[rel(folder,i.path),i.name]));return{ok:true,total:scan.files.length,emitted:r.played.length,remaining:r.remaining.length,recent:r.recent.slice().reverse().map(v=>by.get(v)||path.basename(v)),last:by.get(r.last)||'',cycleNumber:Number(r.cycleNumber)||1,cycleStartedAt:r.cycleStartedAt||'',complete:r.remaining.length===0&&r.played.length>=scan.files.length};};}

function resetEngineSession(engine){if(!engine)return;for(const item of engine.queue||[])try{engine.cleanupItemAudio?.(item);}catch{}engine.queue=[];engine.queuedUrls?.clear?.();engine.newsStatuses?.clear?.();engine.emissionHistory=[];engine.cachedItems=[];engine.currentItem=null;engine.currentCanned=null;engine.currentKind='none';engine.cannedRequested=false;engine.__ec0328Reservation=null;engine.__ec0328AdReservation=null;engine.newsEmitted=0;engine.cannedPlayed=0;engine.adsPlayed=0;engine.scheduledNewsTotal=0;engine.lastScheduledCannedAt=-1;engine.feedCacheGeneration=(Number(engine.feedCacheGeneration)||0)+1;engine.processingRunning=false;engine.processingPaused=false;engine.emissionRunning=false;engine.emissionPaused=false;engine.processingEpoch=(Number(engine.processingEpoch)||0)+1;engine.emissionEpoch=(Number(engine.emissionEpoch)||0)+1;const persisted=engine.history?.getAutomationState?.()||{};engine.exclusiveHasEmitted=!!persisted.exclusiveHasEmitted;engine.newsSinceExclusive=Math.max(0,Number(persisted.newsSinceExclusive)||0);engine.state?.({notice:'Perfil cargado · sesión limpia'});}
function installAutomationCapture(){const p=AutomationEngine.prototype;if(p.__ec0329Capture)return;Object.defineProperty(p,'__ec0329Capture',{value:true});const base=p.snapshot;p.snapshot=function(extra={}){global.__ec0329AutomationRef=this;const m=manager();return{...base.call(this,extra),profileContext:{id:m.activeId(),generation:Number(m.registry.updatedAt?Date.parse(m.registry.updatedAt):0)||0}};};}
function pendingWork(engine){const out=[];if(engine?.inFlight?.size)out.push(`${engine.inFlight.size} noticia(s) IA/TTS`);if(engine?.documentWorkerRunning)out.push('Generador de Notas');if(engine?.localHeavyRunning)out.push('proceso local pesado');if(engine?.currentKind&&engine.currentKind!=='none')out.push('reproducción actual');return out;}
async function stopForSwitch(force=false){const e=global.__ec0329AutomationRef;try{e?.stopEmission?.();}catch{}try{e?.stopProcessing?.();}catch{}for(const w of outputWindows())try{w.close();}catch{}if(!e)return{ok:true,pending:[]};const deadline=Date.now()+(force?1200:10000);while(Date.now()<deadline){const p=pendingWork(e);if(!p.length)return{ok:true,pending:[]};await wait(120);}const pending=pendingWork(e);if(!force)return{ok:false,needsForce:true,pending};try{e.processingRunning=false;e.emissionRunning=false;e.processingEpoch++;e.emissionEpoch++;e.finishPlayback?.('profile-switch-force');await Promise.race([Promise.resolve(e.kokoro?.stopAndWait?.('profile-switch-force')),wait(900)]);e.pronunciation?.stop?.('profile-switch-force');e.providers?.localRuntime?.stop?.('profile-switch-force');}catch{}return{ok:true,forced:true,pending};}
async function switchProfile(id,force=false){const m=manager();if(id===m.activeId())return{ok:true,unchanged:true,profile:m.active()};const stopped=await stopForSwitch(force);if(!stopped.ok)return stopped;resetEngineSession(global.__ec0329AutomationRef);m.activate(id);resetEngineSession(global.__ec0329AutomationRef);sendControl('profile:changed',m.status());return{ok:true,profile:m.active(),forced:!!stopped.forced};}

async function healthFor(meta){const m=manager(),s=m.readProfileSettings(meta.id),checks=[];const test=async(type,p,exts=[])=>{const value=String(p||'').trim();if(!value)return checks.push({type,status:'unset',path:''});try{const st=await Promise.race([fs.promises.stat(value),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),1800))]);if(!st.isDirectory())return checks.push({type,status:'missing',path:value});let count=0;try{count=(await fs.promises.readdir(value)).filter(n=>!exts.length||exts.includes(path.extname(n).toLowerCase())).length;}catch{}checks.push({type,status:'ok',path:value,count});}catch{checks.push({type,status:'missing',path:value});}};await test('content',s.canned?.folder,['.mp4','.m4v','.webm','.mov']);await test('ads',s.canned?.adsFolder,['.mp4','.m4v','.webm','.mov']);await test('documents',s.documents?.folder,['.txt','.docx']);return{profileId:meta.id,ok:checks.every(x=>x.status!=='missing'),checks};}

function installDependencyGuards(){const fp=FontManager.prototype;if(!fp.__ec0329ProfileGuard){Object.defineProperty(fp,'__ec0329ProfileGuard',{value:true});const base=fp.removeFont;fp.removeFont=function(family){const users=manager().list().filter(p=>Object.entries(manager().readProfileSettings(p.id).visual?.output||{}).some(([k,v])=>(/FontFamily$/.test(k)||k==='fontFamily')&&String(v)===String(family))).map(x=>x.name);if(users.length)throw new Error(`La tipografía está en uso por: ${users.join(', ')}. Cambia esas tipografías antes de eliminarla.`);return base.call(this,family);};}const vp=CustomVoiceManager.prototype;if(!vp.__ec0329ProfileGuard){Object.defineProperty(vp,'__ec0329ProfileGuard',{value:true});const base=vp.remove;vp.remove=function(id){const users=manager().list().filter(p=>String(manager().readProfileSettings(p.id).tts?.voice||'')===String(id)).map(x=>x.name);if(users.length)throw new Error(`La voz está en uso por: ${users.join(', ')}. Cambia la voz de esos perfiles antes de eliminarla.`);return base.call(this,id);};}}

function installIpc(){if(global.__ec0329ProfileIpc)return;global.__ec0329ProfileIpc=true;const bind=(ch,fn)=>{try{ipcMain.removeHandler(ch);}catch{}ipcMain.handle(ch,fn);};bind('profiles:status',()=>manager().status());bind('profiles:create',(_,p={})=>manager().create({...p,defaults:defaults()}));bind('profiles:update',(_,p={})=>manager().update(p.id,p));bind('profiles:duplicate',(_,p={})=>manager().duplicate(p.id,p));bind('profiles:delete',(_,id)=>manager().delete(String(id||'')));bind('profiles:switch',(_,p={})=>switchProfile(String(p.id||''),!!p.force));bind('profiles:restartInto',(_,id)=>{const m=manager();m.setPending(String(id||''));app.relaunch();setTimeout(()=>app.exit(0),80);return{ok:true};});bind('profiles:health',async(_,id)=>{const p=manager().list().find(x=>x.id===id);if(!p)throw new Error('Perfil no encontrado');return healthFor(p);});
  bind('profiles:exportOne',async(_,id)=>{const m=manager(),pkg=new ProfilePackage0329({manager:m,dataDir:dataRoot(),fontManager:global.__ec0329FontManager,voiceManager:global.__ec0329VoiceManager}),p=m.list().find(x=>x.id===id);if(!p)throw new Error('Perfil no encontrado');const r=await dialog.showSaveDialog(controlWindow(),{title:'Exportar perfil',defaultPath:`${p.name.replace(/[\\/:*?"<>|]/g,'-')}.gecprofile`,filters:[{name:'Perfil GEC',extensions:['gecprofile']}]});if(r.canceled||!r.filePath)return{cancelled:true};return{ok:true,...pkg.exportProfile(id,r.filePath)};});
  bind('profiles:exportAll',async()=>{const m=manager(),pkg=new ProfilePackage0329({manager:m,dataDir:dataRoot(),fontManager:global.__ec0329FontManager,voiceManager:global.__ec0329VoiceManager}),r=await dialog.showSaveDialog(controlWindow(),{title:'Exportar todos los perfiles',defaultPath:`GEC-Perfiles-${new Date().toISOString().slice(0,10)}.gecpack`,filters:[{name:'Copia completa GEC',extensions:['gecpack']}]});if(r.canceled||!r.filePath)return{cancelled:true};return{ok:true,...pkg.exportAll(r.filePath)};});
  bind('profiles:import',async()=>{const m=manager(),pkg=new ProfilePackage0329({manager:m,dataDir:dataRoot(),fontManager:global.__ec0329FontManager,voiceManager:global.__ec0329VoiceManager}),r=await dialog.showOpenDialog(controlWindow(),{title:'Cargar perfiles',properties:['openFile'],filters:[{name:'Perfiles GEC',extensions:['gecprofile','gecpack']}]});if(r.canceled||!r.filePaths[0])return{cancelled:true};const file=r.filePaths[0],info=pkg.readInfo(file);let mode='keep';if(info.conflicts.length){const c=await dialog.showMessageBox(controlWindow(),{type:'question',title:'Perfiles ya existentes',message:`Ya existe${info.conflicts.length===1?'':'n'}: ${info.conflicts.join(', ')}`,detail:'¿Qué quieres hacer con los perfiles que tienen el mismo nombre?',buttons:['Reemplazar','Mantener ambos','Omitir'],defaultId:1,cancelId:2});mode=['replace','keep','skip'][c.response]||'skip';}if(info.kind==='all'&&m.list().length){const c=await dialog.showMessageBox(controlWindow(),{type:'warning',title:'Restaurar configuración completa',message:'Este paquete también contiene configuración global.',detail:'Se conservarán las API Keys de esta computadora. La cola actual nunca se importa.',buttons:['Continuar','Cancelar'],defaultId:0,cancelId:1});if(c.response!==0)return{cancelled:true};}await stopForSwitch(true);resetEngineSession(global.__ec0329AutomationRef);const result=pkg.importFile(file,mode);if(result.requiresRestart){manager().setPending(result.activeProfileId);app.relaunch();setTimeout(()=>app.exit(0),100);}return result;});}

function installVersion0329Profiles(){installSettingsRouting();installHistoryRouting();installCannedRouting();installAutomationCapture();installDependencyGuards();installIpc();app.on('browser-window-created',(_,w)=>{setTimeout(()=>{try{const title=w.getTitle?.()||'';if(!/OUTPUT/i.test(title)){const m=manager();sendControl('profile:changed',m.status());}}catch{}},700);});}
function registerManagers(fontManager,voiceManager){if(fontManager)global.__ec0329FontManager=fontManager;if(voiceManager)global.__ec0329VoiceManager=voiceManager;}
module.exports={installVersion0329Profiles,registerManagers,switchProfile,stopForSwitch,resetEngineSession,manager,healthFor};
