'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const zlib=require('zlib');
const {atomicJson,readJson,merge,safeName,safeColor}=require('./profileManager0329');

const PACKAGE_SCHEMA=1;
const MAX_PACKAGE_BYTES=768*1024*1024;
const MAX_RESOURCE_BYTES=1024*1024*1024;
function sha(buf){return crypto.createHash('sha256').update(buf).digest('hex');}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function relSafe(v){const s=String(v||'').replace(/\\/g,'/').replace(/^\/+/,''),parts=s.split('/');if(!s||parts.some(x=>!x||x==='.'||x==='..'))throw new Error('Ruta insegura dentro del paquete');return parts.join('/');}
function resource(file,relative){const b=fs.readFileSync(file);return{path:relSafe(relative),size:b.length,sha256:sha(b),data:b.toString('base64')};}
function addDirResources(base,dir,prefix,out,filter=()=>true){if(!fs.existsSync(dir))return;const walk=current=>{for(const e of fs.readdirSync(current,{withFileTypes:true})){const full=path.join(current,e.name);if(e.isDirectory()){walk(full);continue;}if(!e.isFile()||!filter(full))continue;const rel=path.relative(dir,full).replace(/\\/g,'/');out.push(resource(full,`${prefix}/${rel}`));}};walk(dir);}
function writePackage(file,payload){const raw=Buffer.from(JSON.stringify(payload),'utf8'),gz=zlib.gzipSync(raw,{level:9});if(gz.length>MAX_PACKAGE_BYTES)throw new Error('El paquete excede el tamaño permitido');const tmp=`${file}.tmp`;fs.writeFileSync(tmp,gz);try{fs.renameSync(tmp,file);}catch{fs.copyFileSync(tmp,file);try{fs.rmSync(tmp,{force:true});}catch{}}return{path:file,size:gz.length,sha256:sha(gz)};}
function readPackage(file){const st=fs.statSync(file);if(st.size>MAX_PACKAGE_BYTES)throw new Error('El paquete es demasiado grande');let json;try{json=JSON.parse(zlib.gunzipSync(fs.readFileSync(file)).toString('utf8'));}catch{throw new Error('El archivo no es un paquete GEC válido');}if(json?.manifest?.format!=='GEC_PROFILE_PACKAGE'||Number(json.manifest.packageSchemaVersion)!==PACKAGE_SCHEMA)throw new Error('Versión de paquete no compatible');let total=0;for(const r of json.resources||[]){const p=relSafe(r.path),buf=Buffer.from(String(r.data||''),'base64');total+=buf.length;if(total>MAX_RESOURCE_BYTES)throw new Error('Los recursos del paquete exceden el límite permitido');if(Number(r.size)!==buf.length||String(r.sha256)!==sha(buf))throw new Error(`Recurso dañado: ${p}`);r.path=p;}return json;}
function sanitizeGlobalForExport(globalSettings={}){const out=clone(globalSettings)||{};if(out.ai){delete out.ai.claudeKeyEnc;delete out.ai.geminiKeyEnc;delete out.ai.localResourceMode;}if(out.tts){for(const k of ['performanceThreads','resourceMode','autoTune','autoTuned','benchmark','lastBenchmark','gpuProvider'])delete out.tts[k];}return out;}
function portableProfileSettings(manager,id,settings){const out=clone(settings)||{},root=path.resolve(manager.assetsDir(id))+path.sep;const encode=v=>{const s=String(v||'');if(!s)return s;try{const r=path.resolve(s);return r.startsWith(root)?`@profile/assets/${path.basename(r)}`:s;}catch{return s;}};if(out.visual){out.visual.fallbackImage=encode(out.visual.fallbackImage);if(out.visual.output){out.visual.output.musicFile=encode(out.visual.output.musicFile);out.visual.output.verticalVideoBackground=encode(out.visual.output.verticalVideoBackground);}}return out;}
function resolveProfileSettings(settings,newDir){const out=clone(settings)||{},decode=v=>{const s=String(v||'');return s.startsWith('@profile/assets/')?path.join(newDir,path.basename(s.slice('@profile/assets/'.length))):s;};if(out.visual){out.visual.fallbackImage=decode(out.visual.fallbackImage);if(out.visual.output){out.visual.output.musicFile=decode(out.visual.output.musicFile);out.visual.output.verticalVideoBackground=decode(out.visual.output.verticalVideoBackground);}}return out;}

class ProfilePackage0329{
  constructor({manager,dataDir,fontManager=null,voiceManager=null}){this.manager=manager;this.dataDir=dataDir;this.fontManager=fontManager;this.voiceManager=voiceManager;}
  manifest(kind){return{format:'GEC_PROFILE_PACKAGE',packageSchemaVersion:PACKAGE_SCHEMA,profileSchemaVersion:1,globalSchemaVersion:1,kind,createdBy:'0.3.29',createdAt:new Date().toISOString()};}
  profilePayload(id){const meta=this.manager.list().find(x=>x.id===id);if(!meta)throw new Error('Perfil no encontrado');const raw=this.manager.readProfileSettings(id),settings=portableProfileSettings(this.manager,id,raw),resources=[];addDirResources(this.dataDir,this.manager.assetsDir(id),`profiles/${id}/assets`,resources);const families=new Set(Object.entries(raw.visual?.output||{}).filter(([k])=>/FontFamily$/.test(k)||k==='fontFamily').map(([,v])=>String(v||'')));for(const f of this.fontManager?.custom?.()||[]){if(families.has(f.family)&&f.file&&fs.existsSync(f.file)&&!resources.some(x=>x.path===`dependencies/fonts/${path.basename(f.file)}`))resources.push(resource(f.file,`dependencies/fonts/${path.basename(f.file)}`));}const voiceId=String(raw.tts?.voice||''),voice=(this.voiceManager?.list?.()||[]).find(x=>x.id===voiceId),voiceManifest=[];if(voice){voiceManifest.push({id:voice.id,name:voice.name,source:voice.source,createdAt:voice.createdAt,hasPt:!!voice.sourceFile});for(const [label,file] of [['npz',voice.file],['pt',voice.sourceFile]])if(file&&fs.existsSync(file))resources.push(resource(file,`dependencies/voices/${voice.id}.${label}`));}return{manifest:this.manifest('profile'),profiles:[{meta:{...meta,active:false},settings}],voiceManifest,resources};}
  exportProfile(id,file){return writePackage(file,this.profilePayload(id));}
  allPayload(){const resources=[],profiles=this.manager.list().map(meta=>{addDirResources(this.dataDir,this.manager.assetsDir(meta.id),`profiles/${meta.id}/assets`,resources);return{meta:{...meta,active:false},settings:portableProfileSettings(this.manager,meta.id,this.manager.readProfileSettings(meta.id)),history:readJson(this.manager.historyFile(meta.id),{emitted:[],automation:{}}),cycle:readJson(this.manager.cycleFile(meta.id),{version:2,sources:{}})};});addDirResources(this.dataDir,path.join(this.dataDir,'fonts'),'global/fonts',resources,f=>['.ttf','.otf'].includes(path.extname(f).toLowerCase()));const voicesDir=path.join(this.dataDir,'voices'),voiceManifest=readJson(path.join(voicesDir,'manifest.json'),[]);for(const v of Array.isArray(voiceManifest)?voiceManifest:[]){for(const [label,file] of [['npz',v.file],['pt',v.sourceFile]])if(file&&fs.existsSync(file))resources.push(resource(file,`global/voices/${v.id}.${label}`));}for(const name of ['pronunciation-learning.json','pronunciation-cache.json']){const f=path.join(this.dataDir,name);if(fs.existsSync(f))resources.push(resource(f,`global/${name}`));}addDirResources(this.dataDir,path.join(this.dataDir,'normalizer'),'global/normalizer',resources);const globalSettings=sanitizeGlobalForExport(this.manager.globalSettings({}));return{manifest:{...this.manifest('all'),activeProfileId:this.manager.activeId()},globalSettings,voiceManifest:(Array.isArray(voiceManifest)?voiceManifest:[]).map(v=>({id:v.id,name:v.name,source:v.source,createdAt:v.createdAt,hasPt:!!v.sourceFile})),profiles,resources};}
  exportAll(file){return writePackage(file,this.allPayload());}
  conflicts(pkg){const existing=this.manager.list(),incoming=(pkg.profiles||[]).map(x=>x.meta).filter(Boolean);return incoming.filter(p=>existing.some(e=>safeName(e.name).toLocaleLowerCase('es')===safeName(p.name).toLocaleLowerCase('es'))).map(p=>p.name);}
  backupBeforeImport(){const root=path.join(this.dataDir,'backups','pre-import',new Date().toISOString().replace(/[:.]/g,'-'));fs.mkdirSync(root,{recursive:true});for(const name of ['profiles','global','profiles.json','pronunciation-learning.json','pronunciation-cache.json','fonts','voices','normalizer']){const src=path.join(this.dataDir,name),dst=path.join(root,name);if(!fs.existsSync(src))continue;const st=fs.statSync(src);if(st.isDirectory())fs.cpSync(src,dst,{recursive:true,force:true});else fs.copyFileSync(src,dst);}return root;}
  installResources(pkg,profileIdMap=new Map(),kind='profile'){for(const r of pkg.resources||[]){const buf=Buffer.from(r.data,'base64'),rel=r.path,m=rel.match(/^profiles\/([^/]+)\/assets\/(.+)$/);if(m){const newId=profileIdMap.get(m[1])||m[1],dest=path.join(this.manager.assetsDir(newId),path.basename(m[2]));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,buf);continue;}if(rel.startsWith('dependencies/fonts/')||rel.startsWith('global/fonts/')){let dest=path.join(this.dataDir,'fonts',path.basename(rel));fs.mkdirSync(path.dirname(dest),{recursive:true});if(fs.existsSync(dest)&&sha(fs.readFileSync(dest))!==r.sha256){const ext=path.extname(dest),base=path.basename(dest,ext);dest=path.join(path.dirname(dest),`${base}-${r.sha256.slice(0,8)}${ext}`);}if(!fs.existsSync(dest))fs.writeFileSync(dest,buf);continue;}if(rel.startsWith('dependencies/voices/')||rel.startsWith('global/voices/')){const dest=path.join(this.dataDir,'voices','custom',path.basename(rel));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,buf);continue;}if(kind==='all'&&rel==='global/pronunciation-learning.json'){fs.writeFileSync(path.join(this.dataDir,'pronunciation-learning.json'),buf);continue;}if(kind==='all'&&rel==='global/pronunciation-cache.json'){fs.writeFileSync(path.join(this.dataDir,'pronunciation-cache.json'),buf);continue;}if(kind==='all'&&rel.startsWith('global/normalizer/')){const dest=path.join(this.dataDir,'normalizer',rel.slice('global/normalizer/'.length));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,buf);}}}
  rebuildVoiceManifest(pkg){const entries=[],meta=Array.isArray(pkg.voiceManifest)?pkg.voiceManifest:[],depIds=new Set((pkg.resources||[]).filter(r=>/^(?:dependencies|global)\/voices\//.test(r.path)).map(r=>path.basename(r.path).replace(/\.(?:npz|pt)$/i,'')));for(const id of depIds){const old=meta.find(x=>x.id===id),npz=path.join(this.dataDir,'voices','custom',`${id}.npz`),pt=path.join(this.dataDir,'voices','custom',`${id}.pt`);if(fs.existsSync(npz))entries.push({id,name:safeName(old?.name)||id,file:npz,sourceFile:fs.existsSync(pt)?pt:'',source:old?.source||'Perfil GEC importado',createdAt:old?.createdAt||new Date().toISOString()});}if(!entries.length)return;const file=path.join(this.dataDir,'voices','manifest.json'),current=readJson(file,[]),merged=[...(Array.isArray(current)?current:[]).filter(x=>!entries.some(n=>n.id===x.id)),...entries];atomicJson(file,merged);}
  importFile(file,mode='keep'){const pkg=readPackage(file),conflicts=this.conflicts(pkg);if(!['replace','keep','skip'].includes(mode))mode='keep';this.backupBeforeImport();const idMap=new Map(),existing=this.manager.list();for(const row of pkg.profiles||[]){if(!row?.meta)continue;const incoming=row.meta,match=existing.find(e=>safeName(e.name).toLocaleLowerCase('es')===safeName(incoming.name).toLocaleLowerCase('es'));if(match&&mode==='skip')continue;let id=incoming.id;if(match&&mode==='replace')id=match.id;else if(match||existing.some(e=>e.id===id)||this.manager.list().some(e=>e.id===id))id=crypto.randomUUID();idMap.set(incoming.id,id);const meta={...incoming,id,name:match&&mode==='keep'?`${safeName(incoming.name)} (importado)`:safeName(incoming.name),color:safeColor(incoming.color)||'#F7C600',active:false,updatedAt:new Date().toISOString()},settings=resolveProfileSettings(row.settings||{},this.manager.assetsDir(id));fs.mkdirSync(this.manager.profileDir(id),{recursive:true});atomicJson(path.join(this.manager.profileDir(id),'profile.json'),meta);this.manager.writeProfileSettings(id,settings);if(pkg.manifest.kind==='all'){atomicJson(this.manager.historyFile(id),row.history||{emitted:[],automation:{}});atomicJson(this.manager.cycleFile(id),row.cycle||{version:2,sources:{}});}else{atomicJson(this.manager.historyFile(id),{emitted:[],automation:{}});atomicJson(this.manager.cycleFile(id),{version:2,sources:{}});}const i=this.manager.registry.profiles.findIndex(x=>x.id===id);if(i>=0)this.manager.registry.profiles[i]=meta;else this.manager.registry.profiles.push(meta);}if(pkg.manifest.kind==='all'&&pkg.globalSettings){const current=this.manager.globalSettings({}),incoming=clone(pkg.globalSettings);incoming.ai={...(incoming.ai||{}),claudeKeyEnc:current.ai?.claudeKeyEnc||'',geminiKeyEnc:current.ai?.geminiKeyEnc||'',claudeModel:current.ai?.claudeModel||incoming.ai?.claudeModel};atomicJson(this.manager.globalSettingsFile,merge(current,incoming));}this.installResources(pkg,idMap,pkg.manifest.kind);this.rebuildVoiceManifest(pkg);let activate='';if(pkg.manifest.kind==='all'&&pkg.manifest.activeProfileId)activate=idMap.get(pkg.manifest.activeProfileId)||'';if(!activate){const first=(pkg.profiles||[]).find(x=>idMap.has(x.meta?.id));activate=first?idMap.get(first.meta.id):'';}if(activate)this.manager.registry.activeProfileId=activate;this.manager.saveRegistry();return{ok:true,kind:pkg.manifest.kind,imported:[...idMap.values()],conflicts,activeProfileId:this.manager.activeId(),requiresRestart:pkg.manifest.kind==='all'};}
  readInfo(file){const pkg=readPackage(file);return{kind:pkg.manifest.kind,createdBy:pkg.manifest.createdBy,createdAt:pkg.manifest.createdAt,profiles:(pkg.profiles||[]).map(x=>x.meta?.name).filter(Boolean),conflicts:this.conflicts(pkg)};}
}
module.exports={ProfilePackage0329,readPackage,writePackage,PACKAGE_SCHEMA,portableProfileSettings,resolveProfileSettings};
