'use strict';
const fs=require('fs');
const path=require('path');
const {app}=require('electron');
const {ProfileManager0329,safeName}=require('./profileManager0329');
const {ProfilePackage0329}=require('./profilePackage0329');
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function dataRoot(){const portable=process.env.PORTABLE_EXECUTABLE_DIR;if(portable)return path.join(portable,'EC Automatic News Data');if(app.isPackaged)return path.join(path.dirname(process.execPath),'EC Automatic News Data');return path.join(app.getPath('userData'),'EC Automatic News Data');}
function installRegistrySanitizer(){const p=ProfileManager0329.prototype;if(p.__ec0329RegistrySanitizer)return;Object.defineProperty(p,'__ec0329RegistrySanitizer',{value:true});const load=p.loadRegistry;p.loadRegistry=function(){const r=load.call(this),ids=new Set(),names=new Set(),profiles=[];for(const x of Array.isArray(r.profiles)?r.profiles:[]){const id=String(x?.id||''),name=safeName(x?.name),nk=name.toLocaleLowerCase('es');if(!UUID_RE.test(id)||!name||ids.has(id)||names.has(nk))continue;ids.add(id);names.add(nk);profiles.push(x);}const active=profiles.some(x=>x.id===r.activeProfileId)?r.activeProfileId:'';const changed=profiles.length!==(r.profiles||[]).length||active!==r.activeProfileId;const out={...r,profiles,activeProfileId:active};if(changed){try{const quarantine=path.join(this.baseDir,'backups','registry-recovery');fs.mkdirSync(quarantine,{recursive:true});const src=this.registryFile;if(fs.existsSync(src))fs.copyFileSync(src,path.join(quarantine,`profiles-${Date.now()}.json`));}catch{}}return out;};}
function freeBytes(target){try{if(typeof fs.statfsSync!=='function')return Number.MAX_SAFE_INTEGER;const s=fs.statfsSync(target);return Number(s.bavail)*Number(s.bsize);}catch{return Number.MAX_SAFE_INTEGER;}}
function cleanupBackups(dataDir,keep=5){try{const dir=path.join(dataDir,'backups','pre-import');if(!fs.existsSync(dir))return;const entries=fs.readdirSync(dir,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>({name:x.name,path:path.join(dir,x.name),mtime:fs.statSync(path.join(dir,x.name)).mtimeMs})).sort((a,b)=>b.mtime-a.mtime);for(const x of entries.slice(keep))fs.rmSync(x.path,{recursive:true,force:true});}catch{}}
function installImportDiskSafety(){const p=ProfilePackage0329.prototype;if(p.__ec0329DiskSafety)return;Object.defineProperty(p,'__ec0329DiskSafety',{value:true});const base=p.importFile;p.importFile=function(file,mode){const compressed=fs.statSync(file).size,minimum=Math.max(512*1024*1024,compressed*4);if(freeBytes(this.dataDir)<minimum)throw new Error(`No hay espacio libre suficiente para importar de forma segura. Libera al menos ${Math.ceil(minimum/1048576)} MB y vuelve a intentarlo.`);const result=base.call(this,file,mode);cleanupBackups(this.dataDir,5);return result;};}
function installProfileFinalSafety0329(){installRegistrySanitizer();installImportDiskSafety();}
module.exports={installProfileFinalSafety0329};
