'use strict';
const fs=require('fs');
const path=require('path');
const {app,ipcMain,dialog,BrowserWindow}=require('electron');
const {pathToFileURL}=require('url');

const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const PROFILE_BG='#0F0F0F';
const nativeSetInterval=global.setInterval.bind(global);
let documentGeneration=1;
let documentTickBusy=false;
let documentCoordinatorTimer=null;
const documentReadContext=new Map();

function dataRoot(){const portable=process.env.PORTABLE_EXECUTABLE_DIR;if(portable)return path.join(portable,'EC Automatic News Data');if(app.isPackaged)return path.join(path.dirname(process.execPath),'EC Automatic News Data');return path.join(app.getPath('userData'),'EC Automatic News Data');}
function manager(){return require('./profileManager0329').getProfileManager(dataRoot());}
function controlWindow(){return BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!/OUTPUT/i.test(w.getTitle?.()||''))||null;}
function sendControl(channel,payload){try{controlWindow()?.webContents.send(channel,payload);}catch{}}
function bumpDocumentGeneration(){documentGeneration++;return documentGeneration;}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}

function installLegacyWatcherSuppression(){
  if(global.__ec0329LegacyDocumentWatcherSuppressed)return;
  global.__ec0329LegacyDocumentWatcherSuppressed=true;
  const original=global.setInterval;
  global.__ec0329OriginalSetInterval=original;
  global.setInterval=function(fn,delay,...args){
    if(typeof fn==='function'&&fn.name==='queueNewDocumentsFromWatch'&&Number(delay)===5000){
      const dummy=nativeSetInterval(()=>{},2147483000);try{dummy.unref?.();}catch{}return dummy;
    }
    return original(fn,delay,...args);
  };
}

function luminance(hex){const m=/^#([0-9a-f]{6})$/i.exec(String(hex||''));if(!m)return 0;const vals=[0,2,4].map(i=>parseInt(m[1].slice(i,i+2),16)/255).map(v=>v<=0.03928?v/12.92:((v+0.055)/1.055)**2.4);return 0.2126*vals[0]+0.7152*vals[1]+0.0722*vals[2];}
function contrast(a,b=PROFILE_BG){const l1=luminance(a),l2=luminance(b),hi=Math.max(l1,l2),lo=Math.min(l1,l2);return(hi+0.05)/(lo+0.05);}
function assertReadableColor(value){const color=String(value||'').trim().toUpperCase();if(!/^#[0-9A-F]{6}$/.test(color))throw new Error('Selecciona un color válido');if(contrast(color)<3){const e=new Error('El color del perfil es demasiado oscuro para la interfaz. Elige uno con mayor contraste.');e.code='PROFILE_COLOR_CONTRAST';throw e;}return color;}
function sanitizeRegistryColors(){const m=manager();let changed=false;for(const p of m.registry.profiles||[]){try{assertReadableColor(p.color);}catch{p.color='#F7C600';changed=true;try{const pm=require('./profileManager0329'),metaFile=path.join(m.profileDir(p.id),'profile.json'),meta=pm.readJson(metaFile,p)||p;meta.color=p.color;pm.atomicJson(metaFile,meta);}catch{}}}if(changed)m.saveRegistry();}
function installProfileColorGuards(){const {ProfileManager0329}=require('./profileManager0329'),p=ProfileManager0329.prototype;if(p.__ec0329ReadableColorGuard)return;Object.defineProperty(p,'__ec0329ReadableColorGuard',{value:true});const create=p.create,update=p.update;p.create=function(payload={}){return create.call(this,{...payload,color:assertReadableColor(payload.color)});};p.update=function(id,payload={}){const next=payload.color==null?payload:{...payload,color:assertReadableColor(payload.color)};return update.call(this,id,next);};sanitizeRegistryColors();}

function normalizeProcessedMap(settings){const s=clone(settings)||{};s.documents=s.documents||{};const out={};for(const [fp,raw] of Object.entries(s.documents.processed||{})){if(!fp)continue;const entry=raw&&typeof raw==='object'?{...raw}:{};if(!entry.status)entry.status=entry.emittedAt?'emitted':entry.queuedAt?'queued':'emitted';entry.status=String(entry.status||'emitted').toLowerCase();out[fp]=entry;}s.documents.processed=out;return s;}
function installProcessedStateNormalization(){const {SettingsStore}=require('./settings'),p=SettingsStore.prototype;if(p.__ec0329DocumentStateNormalize)return;Object.defineProperty(p,'__ec0329DocumentStateNormalize',{value:true});const load=p.load,save=p.save;p.load=function(...args){return normalizeProcessedMap(load.apply(this,args));};p.save=function(settings,...args){return save.call(this,normalizeProcessedMap(settings),...args);};}
function setProcessedState(doc,state){const fp=String(doc?.fingerprint||'').trim();if(!fp)return;const {SettingsStore}=require('./settings'),store=new SettingsStore(dataRoot()),s=store.load();s.documents=s.documents||{};s.documents.processed=s.documents.processed||{};if(state===false||state==='clear'||state==null){delete s.documents.processed[fp];store.save(s);return;}const old=s.documents.processed[fp]||{},status=String(state||'queued');s.documents.processed[fp]={...old,path:String(doc.path||old.path||''),title:String(doc.title||old.title||''),status,[`${status}At`]:new Date().toISOString()};if(status==='emitted'){delete s.documents.processed[fp].queuedAt;delete s.documents.processed[fp].generatingAt;delete s.documents.processed[fp].readyAt;}store.save(s);}
function clearTransientDocumentStates(profileId=manager().activeId()){if(!profileId)return;const m=manager(),s=m.readProfileSettings(profileId),processed=s.documents?.processed||{};let changed=false;for(const [fp,entry] of Object.entries(processed)){const status=String(entry?.status||'').toLowerCase();if(status&&status!=='emitted'){delete processed[fp];changed=true;}else if(!status){processed[fp]={...(entry||{}),status:'emitted',legacy:true};changed=true;}}if(changed){s.documents=s.documents||{};s.documents.processed=processed;m.writeProfileSettings(profileId,s);}}
function migrateLegacyDocumentStates(){const m=manager();for(const meta of m.list()){const s=m.readProfileSettings(meta.id),processed=s.documents?.processed||{};let changed=false;for(const [fp,entry] of Object.entries(processed)){if(entry&&typeof entry==='object'&&!entry.status){processed[fp]={...entry,status:'emitted',legacy:true};changed=true;}}if(changed){s.documents=s.documents||{};s.documents.processed=processed;m.writeProfileSettings(meta.id,s);}}clearTransientDocumentStates(m.activeId());}

function installDocumentReadContext(){const {DocumentLibrary}=require('./documents'),p=DocumentLibrary.prototype;if(p.__ec0329ProfileReadContext)return;Object.defineProperty(p,'__ec0329ProfileReadContext',{value:true});const read=p.read;p.read=async function(file,...args){const profileId=manager().activeId(),generation=documentGeneration,r=await read.call(this,file,...args),fp=String(r?.fingerprint||'');if(fp){documentReadContext.set(fp,{profileId,generation,at:Date.now()});while(documentReadContext.size>2000)documentReadContext.delete(documentReadContext.keys().next().value);}return r;};}
function installDocumentLifecycle(){const {AutomationEngine}=require('./automation0325'),p=AutomationEngine.prototype;if(p.__ec0329DocumentLifecycle)return;Object.defineProperty(p,'__ec0329DocumentLifecycle',{value:true});const enqueue=p.enqueueDocument,remove=p.removeItem,clearQueue=p.clearQueue,record=p.recordExclusiveEmission;
  p.__ecSetDocumentProcessed=function(doc,state){return setProcessedState(doc,state);};
  p.enqueueDocument=function(doc,options={}){if(this.__ec0329Switching){const e=new Error('Cambio de perfil en curso');e.code='DOCUMENT_PROFILE_SWITCH';throw e;}const fp=String(doc?.fingerprint||'').trim(),ctx=fp?documentReadContext.get(fp):null,current=manager().activeId();if(ctx&&(ctx.profileId!==current||ctx.generation!==documentGeneration)){const e=new Error('El documento pertenece al perfil anterior');e.code='DOCUMENT_PROFILE_SWITCH';throw e;}if(fp&&(this.queue||[]).some(x=>x?.sourceType==='generated'&&String(x.document?.fingerprint||'')===fp&&x.status!=='EMITIDA')){const e=new Error('El documento ya está en la cola');e.code='DOCUMENT_ALREADY_QUEUED';throw e;}const r=enqueue.call(this,doc,options);if(fp)setProcessedState(doc,'queued');return r;};
  p.recordExclusiveEmission=function(item){const r=record.call(this,item);if(item?.sourceType==='generated'&&item.document?.fingerprint)setProcessedState(item.document,'emitted');return r;};
  p.removeItem=function(item){if(item?.sourceType==='generated'&&item.document?.fingerprint&&item.status!=='EMITIDA')setProcessedState(item.document,false);return remove.call(this,item);};
  p.clearQueue=function(...args){for(const item of this.queue||[])if(item?.sourceType==='generated'&&item.document?.fingerprint)setProcessedState(item.document,false);return clearQueue.apply(this,args);};
  p.__ec0329DiscardSessionDocuments=function(){for(const item of this.queue||[])if(item?.sourceType==='generated'&&item.document?.fingerprint)try{setProcessedState(item.document,false);}catch{}try{this.__ecDocumentFailedFingerprints?.clear?.();}catch{};};
}

async function documentCoordinatorTick(){if(documentTickBusy)return;const e=global.__ec0329AutomationRef;if(!e||e.__ec0329Switching)return;const startGeneration=documentGeneration,startProfile=manager().activeId();if(!startProfile)return;const {SettingsStore}=require('./settings'),{DocumentLibrary,canonicalCategory}=require('./documents'),s=new SettingsStore(dataRoot()).load(),folder=String(s.documents?.folder||'').trim();if(!s.documents?.watch||!folder)return;documentTickBusy=true;try{const lib=new DocumentLibrary(),scan=lib.scan(folder);if(!scan.ok)return;const processed=s.documents?.processed||{},queued=new Set((e.queue||[]).filter(x=>x?.sourceType==='generated').map(x=>String(x.document?.fingerprint||'')));for(const item of (scan.files||[]).slice(0,500)){if(startGeneration!==documentGeneration||startProfile!==manager().activeId()||e.__ec0329Switching)return;const st=processed[item.fingerprint],status=String(st?.status||'').toLowerCase();if(status==='emitted'||queued.has(item.fingerprint))continue;let r;try{r=await lib.read(item.path);}catch{continue;}if(startGeneration!==documentGeneration||startProfile!==manager().activeId()||e.__ec0329Switching)return;const fp=String(r.fingerprint||item.fingerprint||'');if((e.queue||[]).some(x=>x?.sourceType==='generated'&&String(x.document?.fingerprint||'')===fp))continue;const cat=canonicalCategory(path.basename(path.dirname(item.path)))||'',img=r.image?.path||'',doc={path:item.path,fingerprint:fp,text:r.text,title:r.explicitTitle||path.basename(item.path,path.extname(item.path)).replace(/[_-]+/g,' ').trim(),category:cat,pubDate:r.explicitDate||new Date().toISOString(),imagePath:img,imageUrl:img?pathToFileURL(img).href:'',imageSource:r.image?.source||'fallback',targetSeconds:Math.max(30,Math.min(180,Number(s.documents?.targetSeconds)||60))};try{e.enqueueDocument(doc,{category:cat,priority:s.documents?.priority||'normal'});}catch(err){if(!['DOCUMENT_ALREADY_QUEUED','DOCUMENT_PROFILE_SWITCH','DOCUMENT_NO_CAPACITY','DOCUMENT_PREPARATION_STOPPED','DOCUMENT_FAILED_SESSION'].includes(String(err?.code||'')))throw err;}break;}}catch(err){sendControl('automation:engineError',{message:`Generador de Notas: ${err.message||err}`});}finally{documentTickBusy=false;}}
function installDocumentCoordinator(){if(documentCoordinatorTimer)return;documentCoordinatorTimer=nativeSetInterval(documentCoordinatorTick,5000);try{documentCoordinatorTimer.unref?.();}catch{}setTimeout(documentCoordinatorTick,1500);}

async function countRecursiveAsync(root,exts,{limit=2000,maxDepth=5,budgetMs=1200}={}){let count=0,timedOut=false;const deadline=Date.now()+budgetMs;async function walk(dir,depth){if(depth>maxDepth||count>=limit||Date.now()>deadline){if(Date.now()>deadline)timedOut=true;return;}let entries;try{entries=await fs.promises.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(count>=limit||Date.now()>deadline){if(Date.now()>deadline)timedOut=true;break;}const full=path.join(dir,e.name);if(e.isDirectory())await walk(full,depth+1);else if(e.isFile()&&(!exts.length||exts.includes(path.extname(e.name).toLowerCase())))count++;}}await walk(root,0);return{count,truncated:count>=limit||timedOut,timedOut};}
async function profileHealth(id){if(!UUID_RE.test(String(id||'')))throw new Error('Perfil no encontrado');const m=manager(),meta=m.list().find(x=>x.id===id);if(!meta)throw new Error('Perfil no encontrado');const {SettingsStore}=require('./settings'),{composeSettings}=require('./profileManager0329'),{CustomVoiceManager}=require('./customVoices'),{FontManager}=require('./fonts'),defaults=new SettingsStore(dataRoot()).defaults(),s=composeSettings(defaults,m.globalSettings(defaults),m.readProfileSettings(id)),checks=[];
  async function folder(type,value,exts){const v=String(value||'').trim();if(!v){checks.push({type,status:'unset',severity:'info',path:''});return;}try{const st=await Promise.race([fs.promises.stat(v),wait(1800).then(()=>{throw new Error('timeout');})]);if(!st.isDirectory())throw new Error('not-dir');const c=await countRecursiveAsync(v,exts);checks.push({type,status:'ok',severity:'ok',path:v,count:c.count,truncated:c.truncated});}catch{checks.push({type,status:'missing',severity:'error',path:v});}}
  await folder('content',s.canned?.folder,['.mp4','.m4v','.webm','.mov']);await folder('ads',s.canned?.adsFolder,['.mp4','.m4v','.webm','.mov']);await folder('documents',s.documents?.folder,['.txt','.docx']);
  for(const [type,v] of [['fallback',s.visual?.fallbackImage],['music',s.visual?.output?.musicFile],['verticalBackground',s.visual?.output?.verticalVideoBackground]])if(v){let ok=false;try{await fs.promises.access(v,fs.constants.R_OK);ok=true;}catch{}checks.push({type,status:ok?'ok':'missing',severity:ok?'ok':'error',path:v});}
  const voice=String(s.tts?.voice||'');if(voice.startsWith('ecv_')){let ok=false;try{ok=new CustomVoiceManager({resourcesDir:app.isPackaged?process.resourcesPath:path.join(__dirname,'..','..'),dataDir:dataRoot()}).has(voice);}catch{}checks.push({type:'voice',status:ok?'ok':'missing',severity:ok?'ok':'error',id:voice});}
  const families=new Set(Object.entries(s.visual?.output||{}).filter(([k])=>/FontFamily$/.test(k)||k==='fontFamily').map(([,v])=>String(v||'')).filter(Boolean));if(families.size){try{const listed=await new FontManager(dataRoot()).list(),available=new Set([...(listed.installed||[]),...(listed.custom||[]).map(x=>x.family)]);for(const family of families)if(!available.has(family))checks.push({type:'font',status:'missing',severity:'error',name:family});}catch{checks.push({type:'font',status:'unknown',severity:'warning'});}}
  const chain=[String(s.ai?.primary||'local'),String(s.ai?.backup1||''),String(s.ai?.backup2||'')].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);let localStatus=null;for(let i=0;i<chain.length;i++){const provider=chain[i],primary=i===0,severity=primary?'error':'warning';if(provider==='claude'&&!s.ai?.claudeKeyEnc)checks.push({type:'provider',provider,status:'missing',severity});else if(provider==='gemini'&&!s.ai?.geminiKeyEnc)checks.push({type:'provider',provider,status:'missing',severity});else if(provider==='local'){if(localStatus==null){try{localStatus=await global.__ec0329AutomationRef?.providers?.localRuntime?.status?.();}catch{localStatus={};}}if(!localStatus?.model)checks.push({type:'provider',provider:'local',status:'missing',severity});}}
  const hardErrors=checks.filter(x=>x.severity==='error'&&x.status==='missing');return{profileId:id,ok:hardErrors.length===0,checks};}
function installHealthHandler(){try{ipcMain.removeHandler('profiles:health');}catch{}ipcMain.handle('profiles:health',(_,id)=>profileHealth(String(id||'')));}

function installSwitchCoordinator(){try{ipcMain.removeHandler('profiles:switch');}catch{}ipcMain.handle('profiles:switch',async(_,payload={})=>{const id=String(payload.id||''),force=!!payload.force,m=manager(),oldId=m.activeId(),e=global.__ec0329AutomationRef;if(id===oldId)return{ok:true,unchanged:true,profile:m.active()};if(!m.list().some(x=>x.id===id))throw new Error('Perfil no encontrado');const safety=require('./profileSwitchSafety0329'),policy=require('./profilePolicy0329');let activated=false;try{bumpDocumentGeneration();const stopped=await safety.stopStrict(force);if(!stopped.ok)return stopped;try{e?.providers?.localRuntime?.stop?.('profile-switch');}catch{}try{e?.__ec0329DiscardSessionDocuments?.();}catch{}policy.resetEngineSession(e);m.readProfileSettings(id);clearTransientDocumentStates(id);m.activate(id);activated=true;policy.resetEngineSession(e);try{if(e?.canned)e.canned.__ec0329Role='content';if(e?.ads)e.ads.__ec0329Role='ad';}catch{}sendControl('profile:changed',m.status());return{ok:true,profile:m.active(),forced:!!stopped.forced};}catch(err){if(activated&&oldId&&m.list().some(x=>x.id===oldId)){try{m.activate(oldId);clearTransientDocumentStates(oldId);policy.resetEngineSession(e);sendControl('profile:changed',m.status());}catch(rollback){err.message=`${err.message}. Además falló la recuperación del perfil anterior: ${rollback.message}`;err.code='PROFILE_SWITCH_RESTART_REQUIRED';}}throw err;}finally{if(e)e.__ec0329Switching=false;bumpDocumentGeneration();}});}

function installImportCoordinator(){try{ipcMain.removeHandler('profiles:import');}catch{}ipcMain.handle('profiles:import',async()=>{const m=manager(),oldId=m.activeId(),e=global.__ec0329AutomationRef,{ProfilePackage0329}=require('./profilePackage0329'),pkg=new ProfilePackage0329({manager:m,dataDir:dataRoot(),fontManager:global.__ec0329FontManager,voiceManager:global.__ec0329VoiceManager}),r=await dialog.showOpenDialog(controlWindow(),{title:'Cargar perfiles',properties:['openFile'],filters:[{name:'Perfiles GEC',extensions:['gecprofile','gecpack']}]});if(r.canceled||!r.filePaths[0])return{cancelled:true};const file=r.filePaths[0],info=pkg.readInfo(file);let mode='keep';if(info.conflicts.length){const c=await dialog.showMessageBox(controlWindow(),{type:'question',title:'Perfiles ya existentes',message:`Ya existe${info.conflicts.length===1?'':'n'}: ${info.conflicts.join(', ')}`,detail:'¿Qué quieres hacer con los perfiles que tienen el mismo nombre?',buttons:['Reemplazar','Mantener ambos','Omitir'],defaultId:1,cancelId:2});mode=['replace','keep','skip'][c.response]||'skip';}if(info.kind==='all'&&m.list().length){const c=await dialog.showMessageBox(controlWindow(),{type:'warning',title:'Restaurar configuración completa',message:'Este paquete también contiene configuración global.',detail:'Se conservarán las API Keys de esta computadora. La cola actual nunca se importa.',buttons:['Continuar','Cancelar'],defaultId:0,cancelId:1});if(c.response!==0)return{cancelled:true};}
    const safety=require('./profileSwitchSafety0329'),policy=require('./profilePolicy0329');let relaunching=false;try{bumpDocumentGeneration();const stopped=await safety.stopStrict(true);if(!stopped.ok)throw new Error('No se pudieron detener todos los procesos para importar.');try{e?.providers?.localRuntime?.stop?.('profile-import');}catch{}try{e?.__ec0329DiscardSessionDocuments?.();}catch{}policy.resetEngineSession(e);const result=pkg.importFile(file,mode);sanitizeRegistryColors();if(info.kind==='profile'&&oldId&&m.list().some(x=>x.id===oldId)){m.activate(oldId);result.activeProfileId=oldId;}clearTransientDocumentStates(m.activeId());policy.resetEngineSession(e);sendControl('profile:changed',m.status());if(result.requiresRestart){const target=info.kind==='all'?(result.activeProfileId||m.activeId()):(oldId||result.activeProfileId||m.activeId());if(target)m.setPending(target);relaunching=true;app.relaunch();setTimeout(()=>app.exit(0),120);}return result;}catch(err){if(oldId&&m.list().some(x=>x.id===oldId)){try{m.activate(oldId);policy.resetEngineSession(e);sendControl('profile:changed',m.status());}catch{}}throw err;}finally{if(e)e.__ec0329Switching=false;bumpDocumentGeneration();if(!relaunching)sendControl('profile:changed',m.status());}});}

function installDocumentListHandler(){try{ipcMain.removeHandler('documents:list');}catch{}ipcMain.handle('documents:list',()=>{const {SettingsStore}=require('./settings'),{DocumentLibrary}=require('./documents'),s=new SettingsStore(dataRoot()).load(),r=new DocumentLibrary().scan(s.documents?.folder||'');return{...r,files:(r.files||[]).map(x=>{const state=s.documents?.processed?.[x.fingerprint]||null,status=String(state?.status||'');return{...x,processed:status==='emitted',processState:status||''};})};});}

function installProfileStability0329(){installProcessedStateNormalization();installProfileColorGuards();migrateLegacyDocumentStates();installDocumentReadContext();installDocumentLifecycle();installDocumentCoordinator();installHealthHandler();installSwitchCoordinator();installImportCoordinator();installDocumentListHandler();}
module.exports={installLegacyWatcherSuppression,installProfileStability0329,profileHealth,assertReadableColor,contrast,bumpDocumentGeneration,clearTransientDocumentStates,documentCoordinatorTick,normalizeProcessedMap};
