'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {app,ipcMain,BrowserWindow,dialog}=require('electron');
const {SettingsStore}=require('./settings');
const {HistoryStore}=require('./history');
const {KokoroTTS}=require('./kokoro');
const {Providers}=require('./providers');
const {AutomationEngine}=require('./automation0325');
const {CannedManager,bestDurationIndex}=require('./canned');
const {DocumentLibrary,canonicalCategory}=require('./documents');
const {pathToFileURL}=require('url');
const rss=require('./rss');
const {getProfileManager,readJson,atomicJson}=require('./profileManager0329');
const {CustomVoiceManager}=require('./customVoices');
const {FontManager}=require('./fonts');

const wait=ms=>new Promise(r=>setTimeout(r,ms));
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function dataRoot(){const portable=process.env.PORTABLE_EXECUTABLE_DIR;if(portable)return path.join(portable,'EC Automatic News Data');if(app.isPackaged)return path.join(path.dirname(process.execPath),'EC Automatic News Data');return path.join(app.getPath('userData'),'EC Automatic News Data');}
function settingsRoot(base){let r=path.resolve(String(base||dataRoot()));if(path.basename(path.dirname(r)).toLowerCase()==='profiles'&&UUID_RE.test(path.basename(r)))r=path.dirname(path.dirname(r));return r;}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function normalizeSettings(s={}){const x=clone(s)||{};x.ai=x.ai||{};x.tts=x.tts||{};x.visual=x.visual||{};x.visual.output=x.visual.output||{};x.visual.queueColors=x.visual.queueColors||{};x.documents=x.documents||{};x.documents.processed=x.documents.processed&&typeof x.documents.processed==='object'?x.documents.processed:{};x.automation=x.automation||{};x.canned=x.canned||{};
  x.tts.pronunciationMaxSeconds=Math.max(5,Math.min(30,Number(x.tts.pronunciationMaxSeconds)||15));x.tts.persistentIdleMinutes=Math.max(1,Math.min(30,Number(x.tts.persistentIdleMinutes)||5));x.tts.performanceThreads=Math.max(1,Math.min(12,Number(x.tts.performanceThreads)||6));
  const o=x.visual.output;o.titleFontSize=Math.max(20,Math.min(120,Number(o.titleFontSize)||64));o.summaryFontSize=Math.max(12,Math.min(72,Number(o.summaryFontSize)||30));o.categoryFontSize=Math.max(10,Math.min(48,Number(o.categoryFontSize)||22));o.dateFontSize=Math.max(10,Math.min(48,Number(o.dateFontSize)||18));o.exclusiveFontSize=Math.max(10,Math.min(48,Number(o.exclusiveFontSize)||18));
  x.documents.targetSeconds=Math.max(30,Math.min(180,Number(x.documents.targetSeconds)||60));x.automation.recoveryAutonomyMin=Math.max(2,Math.min(30,Number(x.automation.recoveryAutonomyMin)||8));x.automation.criticalAutonomyMin=Math.max(1,Math.min(x.automation.recoveryAutonomyMin,Number(x.automation.criticalAutonomyMin)||3));x.automation.targetAutonomyMin=Math.max(3,Math.min(60,Number(x.automation.targetAutonomyMin)||15));x.automation.bufferReady=Math.max(1,Math.min(30,Number(x.automation.bufferReady)||15));x.automation.queueMax=Math.max(x.automation.bufferReady,Math.min(60,Number(x.automation.queueMax)||30));return x;
}

function installSettingsHardening(){const p=SettingsStore.prototype;if(p.__ec0329AuditSettings)return;Object.defineProperty(p,'__ec0329AuditSettings',{value:true});const defaults=p.defaults;
  p.load=function(){const root=settingsRoot(this.baseDir),m=getProfileManager(root),base=defaults.call({baseDir:root});global.__ec0329ProfileManager=m;return normalizeSettings(m.effectiveSettings(base));};
  p.save=function(settings){const root=settingsRoot(this.baseDir),m=getProfileManager(root),base=defaults.call({baseDir:root}),safe=normalizeSettings(settings);global.__ec0329ProfileManager=m;m.saveEffective(base,safe);return safe;};
}

function installManagerHardening(){const {ProfileManager0329}=require('./profileManager0329'),p=ProfileManager0329.prototype;if(p.__ec0329AuditManager)return;Object.defineProperty(p,'__ec0329AuditManager',{value:true});
  const safeId=id=>{const s=String(id||'');if(!UUID_RE.test(s))throw new Error('Identificador de perfil inválido');return s;};
  for(const name of ['profileDir','profileSettingsFile','historyFile','cycleFile','assetsDir']){const base=p[name];p[name]=function(id){return base.call(this,safeId(id));};}
  const baseRead=p.readProfileSettings;p.readProfileSettings=function(id){safeId(id);const file=this.profileSettingsFile(id),raw=readJson(file)||readJson(`${file}.bak`);return raw?baseRead.call(this,id):baseRead.call(this,id);};
  const baseActivate=p.activate;p.activate=function(id){safeId(id);const r=baseActivate.call(this,id);this.__ec0329EffectiveCache=null;return r;};
  const baseWrite=p.writeProfileSettings;p.writeProfileSettings=function(id,s){safeId(id);const r=baseWrite.call(this,id,s);this.__ec0329EffectiveCache=null;return r;};
  const baseSave=p.saveEffective;p.saveEffective=function(defaults,effective){const r=baseSave.call(this,defaults,effective);this.__ec0329EffectiveCache=null;return r;};
  const baseEffective=p.effectiveSettings;p.effectiveSettings=function(defaults){const key=`${this.activeId()}|${this.registry.updatedAt}|${fs.existsSync(this.globalSettingsFile)?fs.statSync(this.globalSettingsFile).mtimeMs:0}`;if(this.__ec0329EffectiveCache?.key===key)return clone(this.__ec0329EffectiveCache.value);const value=baseEffective.call(this,defaults);this.__ec0329EffectiveCache={key,value:clone(value)};return value;};
  p.delete=function(id){safeId(id);if(id===this.activeId()){const e=new Error('No puedes eliminar el perfil activo. Cambia primero a otro perfil y vuelve a intentarlo.');e.code='PROFILE_ACTIVE_DELETE';throw e;}const i=this.registry.profiles.findIndex(x=>x.id===id);if(i<0)throw new Error('Perfil no encontrado');const src=this.profileDir(id),backup=path.join(this.baseDir,'backups','deleted-profiles',`${new Date().toISOString().replace(/[:.]/g,'-')}-${id}`);if(fs.existsSync(src)){fs.mkdirSync(path.dirname(backup),{recursive:true});fs.cpSync(src,backup,{recursive:true,force:true});if(!fs.existsSync(backup))throw new Error('No se pudo crear la copia de seguridad del perfil; no se eliminó nada.');}fs.rmSync(src,{recursive:true,force:true});const[pMeta]=this.registry.profiles.splice(i,1);this.saveRegistry();this.__ec0329EffectiveCache=null;return pMeta;};
  const baseCopy=p.copyManagedAsset;p.copyManagedAsset=function(src,id,slot){safeId(id);const result=baseCopy.call(this,src,id,slot);try{const dir=this.assetsDir(id),keep=path.basename(result);for(const n of fs.readdirSync(dir))if(n!==keep&&n.startsWith(`${slot}.`))fs.rmSync(path.join(dir,n),{force:true});}catch{}return result;};
}

function saveEffectiveSettings(patch={}){const store=new SettingsStore(dataRoot()),s=store.load();s.tts={...(s.tts||{}),...patch};store.save(s);return s;}
function installKokoroHardening(){const p=KokoroTTS.prototype;if(p.__ec0329AuditKokoro)return;Object.defineProperty(p,'__ec0329AuditKokoro',{value:true});p.settings=function(){try{return new SettingsStore(dataRoot()).load();}catch{return{};}};
  const bench=p.benchmark;if(typeof bench==='function')p.benchmark=async function(...args){const legacy=this.settingsFile;this.settingsFile=path.join(dataRoot(),'.kokoro-benchmark-legacy-0329.json');try{const r=await bench.apply(this,args);if(r?.ok&&r.recommendedThreads)saveEffectiveSettings({resourceMode:'performance',performanceThreads:Number(r.recommendedThreads),autoTuned:true});return r;}finally{this.settingsFile=legacy;try{fs.rmSync(path.join(dataRoot(),'.kokoro-benchmark-legacy-0329.json'),{force:true});}catch{}}};
  const gpu=p.benchmarkGpu;if(typeof gpu==='function')p.benchmarkGpu=async function(...args){const legacy=this.settingsFile;this.settingsFile=path.join(dataRoot(),'.kokoro-gpu-benchmark-legacy-0329.json');try{const r=await gpu.apply(this,args);if(r?.ok){const summary={at:new Date().toISOString(),gpu:r.nvidia?.name||'',driver:r.nvidia?.driver||'',cpuRtf:Number(r.cpu?.realtimeFactor)||0,gpuRtf:Number(r.gpu?.realtimeFactor)||0,gainPct:Number(r.gainPct)||0,recommended:r.recommended||'cpu'};saveEffectiveSettings({resourceMode:'performance',acceleration:r.recommended==='cuda'?'cuda':'cpu',lastHardwareBenchmark:summary,autoTuned:true});}return r;}finally{this.settingsFile=legacy;try{fs.rmSync(path.join(dataRoot(),'.kokoro-gpu-benchmark-legacy-0329.json'),{force:true});}catch{}}};
  if(typeof p.nvidiaSmiExecutable==='function'){const base=p.nvidiaSmiExecutable;p.nvidiaSmiExecutable=function(){if(this.__ec0329NvidiaExe!==undefined)return this.__ec0329NvidiaExe;return(this.__ec0329NvidiaExe=base.call(this));};}
  if(typeof p.queryNvidia==='function'){const base=p.queryNvidia;p.queryNvidia=function(){const now=Date.now();if(this.__ec0329NvidiaCache&&now-this.__ec0329NvidiaCache.at<3000)return this.__ec0329NvidiaCache.value;const value=base.call(this);this.__ec0329NvidiaCache={at:now,value};return value;};}
}

function installProviderAbort(){if(global.__ec0329FetchAbortInstalled)return;global.__ec0329FetchAbortInstalled=true;const nativeFetch=global.fetch;if(typeof nativeFetch!=='function')return;global.__ec0329ProviderAbort=new AbortController();global.fetch=function(input,init={}){let host='';try{host=new URL(typeof input==='string'?input:input?.url).hostname;}catch{}if(!/^(?:api\.anthropic\.com|generativelanguage\.googleapis\.com)$/i.test(host))return nativeFetch(input,init);const a=global.__ec0329ProviderAbort.signal,signals=[a,init.signal].filter(Boolean);let signal=signals[0];if(signals.length>1&&typeof AbortSignal.any==='function')signal=AbortSignal.any(signals);return nativeFetch(input,{...init,signal});};
  Providers.prototype.cancelActiveRequests=function(){try{global.__ec0329ProviderAbort.abort(new Error('Cambio de perfil'));}catch{}global.__ec0329ProviderAbort=new AbortController();};
}

function mediaKey(folder,item){const rel=path.relative(path.resolve(folder),path.resolve(item.path)).replace(/\\/g,'/');return`${rel}|${Number(item.sizeBytes)||0}|${Math.round(Number(item.mtimeMs)||0)}`;}
function installCannedHardening(){const p=CannedManager.prototype;if(p.__ec0329AuditCanned)return;Object.defineProperty(p,'__ec0329AuditCanned',{value:true});const baseList=p.list;
  function manager(){return getProfileManager(dataRoot());}
  function source(self,folder){const m=manager(),id=m.activeId();if(!id)return null;const s=m.readProfileSettings(id),role=self.__ec0329Role==='ad'?'ad':'content',sourceId=role==='ad'?s.canned?.adSourceId:s.canned?.contentSourceId;return{m,id,role,sourceId:sourceId||role,file:m.cycleFile(id),folder};}
  function load(src){const all=readJson(src.file)||readJson(`${src.file}.bak`)||{version:3,sources:{}};all.version=3;all.sources=all.sources||{};return all;}
  function reconcile(src,scan,{advance=false,commit=false}={}){const all=load(src),k=`${src.role}:${src.sourceId}`,items=scan.files||[],byKey=new Map(items.map(i=>[mediaKey(src.folder,i),i])),available=[...byKey.keys()];let r=all.sources[k]||{cycleNumber:1,cycleStartedAt:new Date().toISOString(),remaining:[],played:[],recent:[],last:''};r.remaining=(r.remaining||[]).filter(x=>byKey.has(x));r.played=(r.played||[]).filter(x=>byKey.has(x)&&!r.remaining.includes(x));r.recent=(r.recent||[]).filter(x=>byKey.has(x)).slice(-8);const known=new Set([...r.remaining,...r.played]),added=available.filter(x=>!known.has(x));if(added.length)r.remaining.push(...added.sort(()=>crypto.randomInt(3)-1));if(advance&&!r.remaining.length&&available.length&&r.played.length>=available.length){r.cycleNumber=Math.max(1,Number(r.cycleNumber)||1)+1;r.cycleStartedAt=new Date().toISOString();r.played=[];r.remaining=[...available].sort(()=>crypto.randomInt(3)-1);if(r.remaining.length>1&&r.last&&r.remaining[0]===r.last)[r.remaining[0],r.remaining[1]]=[r.remaining[1],r.remaining[0]];}if(!r.remaining.length&&available.length&&!r.played.length)r.remaining=[...available].sort(()=>crypto.randomInt(3)-1);all.sources[k]=r;if(commit)atomicJson(src.file,all);return{all,k,r,byKey};}
  p.ensureBag=function(folder,{advance=false}={}){const scan=baseList.call(this,folder);if(!scan.ok||!scan.files.length){const e=new Error(scan.message||'No hay contenidos disponibles');e.code='CANNED_EMPTY';throw e;}const src=source(this,folder),x=reconcile(src,scan,{advance,commit:advance}),items=x.r.remaining.map(k=>x.byKey.get(k)).filter(Boolean);this.bag=items;this.lastPath=x.r.last&&x.byKey.get(x.r.last)?.path||'';return{scan,src,x};};
  p.peekForDuration=function(folder,targetSec){const {scan}=this.ensureBag(folder,{advance:false});const i=bestDurationIndex(this.bag,targetSec),item=this.bag[i<0?0:i];return item?{...item,remainingInCycle:this.bag.length,total:scan.files.length}:null;};p.peek=function(folder){return this.peekForDuration(folder,this.requestedDurationSec||0);};
  p.pickPath=function(folder,wanted){const {scan,src}=this.ensureBag(folder,{advance:true}),item=this.bag.find(x=>path.resolve(x.path)===path.resolve(wanted));if(!item)return null;const x=reconcile(src,scan,{advance:false,commit:false}),key=mediaKey(folder,item);x.r.remaining=x.r.remaining.filter(v=>v!==key);if(!x.r.played.includes(key))x.r.played.push(key);x.r.last=key;x.r.recent=[...x.r.recent.filter(v=>v!==key),key].slice(-8);x.all.sources[x.k]=x.r;atomicJson(src.file,x.all);this.lastPath=item.path;return{...item,remainingInCycle:x.r.remaining.length,total:scan.files.length,cycleNumber:x.r.cycleNumber};};
  p.pickForDuration=function(folder,targetSec){this.ensureBag(folder,{advance:true});const i=bestDurationIndex(this.bag,targetSec),item=this.bag[i<0?0:i];return item?this.pickPath(folder,item.path):null;};p.pick=function(folder){const target=this.requestedDurationSec||0,res=this.__ec0328ReservedPath;this.requestedDurationSec=0;this.__ec0328ReservedPath='';if(res){const item=this.pickPath(folder,res);if(item)return item;}return this.pickForDuration(folder,target);};
  p.cycleStatus=function(folder){const scan=baseList.call(this,folder);if(!scan.ok||!scan.files.length)return{ok:false,total:0,emitted:0,remaining:0,recent:[],cycleNumber:0,complete:false};const src=source(this,folder),x=reconcile(src,scan,{advance:false,commit:false});return{ok:true,total:scan.files.length,emitted:x.r.played.length,remaining:x.r.remaining.length,recent:x.r.recent.slice().reverse().map(k=>x.byKey.get(k)?.name||String(k).split('|')[0]),last:x.byKey.get(x.r.last)?.name||'',cycleNumber:Number(x.r.cycleNumber)||1,cycleStartedAt:x.r.cycleStartedAt||'',complete:x.r.remaining.length===0&&x.r.played.length>=scan.files.length};};
  const baseSnap=AutomationEngine.prototype.snapshot;AutomationEngine.prototype.snapshot=function(...args){if(this.canned)this.canned.__ec0329Role='content';if(this.ads)this.ads.__ec0329Role='ad';return baseSnap.apply(this,args);};
}

function installSwitchGate(){const p=AutomationEngine.prototype;if(p.__ec0329AuditSwitchGate)return;Object.defineProperty(p,'__ec0329AuditSwitchGate',{value:true});const enqueue=p.enqueueDocument;p.enqueueDocument=function(...args){if(this.__ec0329Switching){const e=new Error('Cambio de perfil en curso');e.code='DOCUMENT_PROFILE_SWITCH';throw e;}return enqueue.apply(this,args);};p.__ec0329DiscardSessionDocuments=function(){for(const item of this.queue||[])if(item?.sourceType==='generated'&&item.document?.fingerprint)try{this.__ecSetDocumentProcessed?.(item.document,false);}catch{}try{this.__ecDocumentFailedFingerprints?.clear?.();}catch{};};}

function installRssConcurrency(){if(rss.__ec0329Concurrency)return;rss.__ec0329Concurrency=true;const fetchOne=rss.fetchFeedDetailed;rss.loadAll=async function(feeds){const list=(Array.isArray(feeds)?feeds:[]).filter(f=>f&&f.enabled&&f.url),results=new Array(list.length),limit=Math.min(6,Math.max(1,list.length)),next={i:0};const worker=async()=>{while(true){const i=next.i++;if(i>=list.length)return;try{results[i]={status:'fulfilled',value:await fetchOne(list[i])};}catch(e){results[i]={status:'rejected',reason:e};}}};await Promise.all(Array.from({length:limit},worker));const items=[],errors=[],feedStatus=[];for(let i=0;i<results.length;i++){const r=results[i],feed=list[i];if(r?.status==='fulfilled'){items.push(...r.value.items);feedStatus.push({id:feed.id,name:feed.name,ok:r.value.items.length>0,count:r.value.items.length,rawCount:r.value.rawCount,parsedCount:r.value.parsedCount,sourceType:r.value.sourceType,partial:r.value.partial,mode:r.value.mode,detail:r.value.detail});}else{const error=r?.reason?.message||String(r?.reason||'Error');errors.push({feed:feed.name,error});feedStatus.push({id:feed.id,name:feed.name,ok:false,count:0,rawCount:0,parsedCount:0,sourceType:'',partial:false,mode:'ERROR',detail:error});}}return{items:rss.mergeUniqueItems(items),errors,feedStatus,stale:false};};}

function recursiveCount(root,exts,limit=2000){let count=0;const walk=(dir,depth=0)=>{if(depth>5||count>=limit)return;let entries=[];try{entries=fs.readdirSync(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(count>=limit)break;const full=path.join(dir,e.name);if(e.isDirectory())walk(full,depth+1);else if(e.isFile()&&(!exts.length||exts.includes(path.extname(e.name).toLowerCase())))count++;}};walk(root);return count;}
async function health(id){const m=getProfileManager(dataRoot());if(!UUID_RE.test(String(id||'')))throw new Error('Perfil no encontrado');const meta=m.list().find(x=>x.id===id);if(!meta)throw new Error('Perfil no encontrado');const s=m.readProfileSettings(id),checks=[];const folder=async(type,value,exts)=>{const v=String(value||'').trim();if(!v)return checks.push({type,status:'unset',path:''});try{const st=await fs.promises.stat(v);if(!st.isDirectory())throw new Error();checks.push({type,status:'ok',path:v,count:recursiveCount(v,exts)});}catch{checks.push({type,status:'missing',path:v});}};await folder('content',s.canned?.folder,['.mp4','.m4v','.webm','.mov']);await folder('ads',s.canned?.adsFolder,['.mp4','.m4v','.webm','.mov']);await folder('documents',s.documents?.folder,['.txt','.docx']);
  for(const [type,v] of [['fallback',s.visual?.fallbackImage],['music',s.visual?.output?.musicFile],['verticalBackground',s.visual?.output?.verticalVideoBackground]])if(v)checks.push({type,status:fs.existsSync(v)?'ok':'missing',path:v});
  const voice=String(s.tts?.voice||'');if(voice.startsWith('ecv_')){let ok=false;try{ok=new CustomVoiceManager({resourcesDir:app.isPackaged?process.resourcesPath:path.join(__dirname,'..','..'),dataDir:dataRoot()}).has(voice);}catch{}checks.push({type:'voice',status:ok?'ok':'missing',id:voice});}
  const fonts=new Set(Object.entries(s.visual?.output||{}).filter(([k])=>/FontFamily$/.test(k)||k==='fontFamily').map(([,v])=>String(v||'')));if(fonts.size){let available=new Set();try{available=new Set(new FontManager(dataRoot()).list(false).map(x=>x.family));}catch{}for(const f of fonts)if(f&&!available.has(f)&&f!=='Arial')checks.push({type:'font',status:'missing',name:f});}
  return{profileId:id,ok:checks.every(x=>x.status!=='missing'),checks};}
function installHealth(){try{ipcMain.removeHandler('profiles:health');}catch{}ipcMain.handle('profiles:health',(_,id)=>health(String(id||'')));}

function controlWindow(){return BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!/OUTPUT/i.test(w.getTitle?.()||''))||null;}
function installProfileDocumentWatchFallback(){if(global.__ec0329WatchFallbackTimer)return;const lib=new DocumentLibrary();let busy=false;global.__ec0329WatchFallbackTimer=setInterval(async()=>{if(busy)return;const e=global.__ec0329AutomationRef;if(!e||e.__ec0329Switching)return;let s;try{s=new SettingsStore(dataRoot()).load();}catch{return;}const folder=String(s.documents?.folder||'').trim();if(!s.documents?.watch||!folder)return;busy=true;try{const scan=lib.scan(folder);if(!scan.ok)return;const processed=s.documents?.processed||{},queued=new Set((e.queue||[]).filter(x=>x?.sourceType==='generated').map(x=>String(x.document?.fingerprint||'')));for(const item of (scan.files||[]).slice(0,500)){if(processed[item.fingerprint]||queued.has(item.fingerprint)||e.__ec0329Switching)continue;try{const r=await lib.read(item.path),cat=canonicalCategory(path.basename(path.dirname(item.path)))||'',img=r.image?.path||'',doc={path:item.path,fingerprint:r.fingerprint,text:r.text,title:r.explicitTitle||path.basename(item.path,path.extname(item.path)).replace(/[_-]+/g,' ').trim(),category:cat,pubDate:r.explicitDate||new Date().toISOString(),imagePath:img,imageUrl:img?pathToFileURL(img).href:'',imageSource:r.image?.source||'fallback',targetSeconds:Math.max(30,Math.min(180,Number(s.documents?.targetSeconds)||60))};e.enqueueDocument(doc,{category:cat,priority:s.documents?.priority||'normal'});queued.add(item.fingerprint);}catch(err){if(!['DOCUMENT_NO_CAPACITY','DOCUMENT_PREPARATION_STOPPED','DOCUMENT_ALREADY_QUEUED','DOCUMENT_FAILED_SESSION','DOCUMENT_PROFILE_SWITCH'].includes(String(err?.code||'')))throw err;}break;}}catch(err){try{const w=controlWindow();w?.webContents.send('automation:engineError',{message:`Generador de Notas: ${err.message||err}`});}catch{}}finally{busy=false;}},5000);}

function installImportCoordinator(){try{ipcMain.removeHandler('profiles:import');}catch{}ipcMain.handle('profiles:import',async()=>{const m=getProfileManager(dataRoot()),{ProfilePackage0329}=require('./profilePackage0329'),pkg=new ProfilePackage0329({manager:m,dataDir:dataRoot(),fontManager:global.__ec0329FontManager,voiceManager:global.__ec0329VoiceManager}),r=await dialog.showOpenDialog(controlWindow(),{title:'Cargar perfiles',properties:['openFile'],filters:[{name:'Perfiles GEC',extensions:['gecprofile','gecpack']}]});if(r.canceled||!r.filePaths[0])return{cancelled:true};const file=r.filePaths[0],info=pkg.readInfo(file);let mode='keep';if(info.conflicts.length){const c=await dialog.showMessageBox(controlWindow(),{type:'question',title:'Perfiles ya existentes',message:`Ya existe${info.conflicts.length===1?'':'n'}: ${info.conflicts.join(', ')}`,detail:'¿Qué quieres hacer con los perfiles que tienen el mismo nombre?',buttons:['Reemplazar','Mantener ambos','Omitir'],defaultId:1,cancelId:2});mode=['replace','keep','skip'][c.response]||'skip';}if(info.kind==='all'&&m.list().length){const c=await dialog.showMessageBox(controlWindow(),{type:'warning',title:'Restaurar configuración completa',message:'Este paquete también contiene configuración global.',detail:'Se conservarán las API Keys de esta computadora. La cola actual nunca se importa.',buttons:['Continuar','Cancelar'],defaultId:0,cancelId:1});if(c.response!==0)return{cancelled:true};}const safety=require('./profileSwitchSafety0329'),stopped=await safety.stopStrict(true);if(!stopped.ok)throw new Error('No se pudieron detener todos los procesos para importar.');const e=global.__ec0329AutomationRef;try{e?.__ec0329DiscardSessionDocuments?.();}catch{}require('./profilePolicy0329').resetEngineSession(e);const result=pkg.importFile(file,mode);if(result.requiresRestart&&result.activeProfileId){m.setPending(result.activeProfileId);app.relaunch();setTimeout(()=>app.exit(0),100);}return result;});}

function installProfileAuditHardening0329(){try{require('./profilePackage0329').recoverPendingImport(dataRoot());}catch{}installManagerHardening();installSettingsHardening();installKokoroHardening();installProviderAbort();installCannedHardening();installSwitchGate();installRssConcurrency();installHealth();installImportCoordinator();installProfileDocumentWatchFallback();}
module.exports={installProfileAuditHardening0329,dataRoot,settingsRoot,normalizeSettings,UUID_RE,health};
