'use strict';
const {ipcMain,BrowserWindow}=require('electron');
const policy=require('./profilePolicy0329');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function outputs(){return BrowserWindow.getAllWindows().filter(w=>!w.isDestroyed()&&(/OUTPUT/i.test(w.getTitle?.()||'')||/output\.html/i.test(w.webContents?.getURL?.()||'')));}
function pending(e){const out=[];if(e?.inFlight?.size)out.push(`${e.inFlight.size} noticia(s) IA/TTS`);if(e?.documentWorkerRunning||e?.documentWorkerPromise)out.push('Generador de Notas');if(e?.localHeavyRunning)out.push('proceso local pesado');if(e?.currentKind&&e.currentKind!=='none')out.push('reproducción actual');return [...new Set(out)];}
function installDocumentGate(){let proto=null;try{proto=require('./automation0325').AutomationEngine.prototype;}catch{return;}if(proto.__ec0329SwitchGate)return;Object.defineProperty(proto,'__ec0329SwitchGate',{value:true});const baseCan=proto.documentCanRun,baseStart=proto.startProcessing;proto.documentCanRun=function(item){if(this.__ec0329Switching)return false;return baseCan.call(this,item);};proto.startProcessing=async function(...args){this.__ec0329Switching=false;return baseStart.apply(this,args);};}
async function stopStrict(force=false){const e=global.__ec0329AutomationRef;if(!e)return{ok:true,pending:[]};e.__ec0329Switching=true;try{e.stopEmission?.();}catch{}try{e.stopProcessing?.();}catch{}for(const w of outputs())try{w.close();}catch{}const firstDeadline=Date.now()+(force?900:10000);while(Date.now()<firstDeadline){const p=pending(e);if(!p.length)return{ok:true,pending:[]};await wait(120);}let p=pending(e);if(!force)return{ok:false,needsForce:true,pending:p};try{e.processingRunning=false;e.emissionRunning=false;e.processingEpoch=(Number(e.processingEpoch)||0)+1;e.emissionEpoch=(Number(e.emissionEpoch)||0)+1;e.finishPlayback?.('profile-switch-force');}catch{}try{await Promise.race([Promise.resolve(e.kokoro?.stopAndWait?.('profile-switch-force')),wait(1200)]);}catch{}try{e.pronunciation?.stop?.('profile-switch-force');}catch{}try{e.providers?.localRuntime?.stop?.('profile-switch-force');}catch{}const forceDeadline=Date.now()+3500;while(Date.now()<forceDeadline){p=pending(e);if(!p.length)return{ok:true,forced:true,pending:[]};await wait(120);}p=pending(e);const err=new Error(`Todavía no se pudo detener: ${p.join(', ')||'un proceso activo'}. Reinicia GEC para cambiar de perfil de forma segura.`);err.code='PROFILE_SWITCH_RESTART_REQUIRED';throw err;}
async function switchStrict(id,force=false){const m=policy.manager(),e=global.__ec0329AutomationRef;if(id===m.activeId())return{ok:true,unchanged:true,profile:m.active()};if(!m.list().some(x=>x.id===id))throw new Error('Perfil no encontrado');const stopped=await stopStrict(force);if(!stopped.ok)return stopped;policy.resetEngineSession(e);m.activate(id);policy.resetEngineSession(e);if(e)e.__ec0329Switching=false;const control=BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!/OUTPUT/i.test(w.getTitle?.()||''));try{control?.webContents.send('profile:changed',m.status());}catch{}return{ok:true,profile:m.active(),forced:!!stopped.forced};}
function installProfileSwitchSafety0329(){installDocumentGate();try{ipcMain.removeHandler('profiles:switch');}catch{}ipcMain.handle('profiles:switch',(_,p={})=>switchStrict(String(p.id||''),!!p.force));}
module.exports={installProfileSwitchSafety0329,stopStrict,switchStrict,pending};
