'use strict';
const {SettingsStore,DEFAULT_CLAUDE_MODEL,sourceWebFromUrl,publisherNameFromWeb}=require('./settings');
function fullNormalize(input={}){const data={...input,ai:{...(input.ai||{})},tts:{...(input.tts||{})},visual:{...(input.visual||{})},canned:{...(input.canned||{})},documents:{...(input.documents||{})},automation:{...(input.automation||{})}};data.visual.output={...(input.visual?.output||{})};data.visual.queueColors={...(input.visual?.queueColors||{})};data.documents.processed=data.documents.processed&&typeof data.documents.processed==='object'?data.documents.processed:{};
  data.rssPartialClose={enabled:data.rssPartialClose?.enabled!==false,template:String(data.rssPartialClose?.template||'Para más información, visita {web}.').trim()||'Para más información, visita {web}.'};data.exclusiveClose={enabled:data.exclusiveClose?.enabled!==false,template:String(data.exclusiveClose?.template||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.').trim()||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.'};
  data.rssFeeds=(Array.isArray(data.rssFeeds)?data.rssFeeds:[]).map((f,i)=>{const id=String(f?.id||`rss-${i}`),url=String(f?.url||'').trim(),name=f?.name==null?'Fuente':String(f.name),publisherWeb=sourceWebFromUrl(url),publisherName=String(f?.publisherName||publisherNameFromWeb(publisherWeb)||name||'').trim(),sourceMode=['auto','rss','web'].includes(String(f?.sourceMode||'').toLowerCase())?String(f.sourceMode).toLowerCase():'auto',accessMode=['auto','public','exclusive'].includes(String(f?.accessMode||'').toLowerCase())?String(f.accessMode).toLowerCase():'auto';return{...f,id,name,url,enabled:f?.enabled!==false,priority:Number(f?.priority)||50,publisherName,publisherWeb,sourceMode,accessMode,partialCtaEnabled:data.rssPartialClose.enabled,partialCtaTemplate:data.rssPartialClose.template,exclusiveCtaEnabled:data.exclusiveClose.enabled,exclusiveCtaTemplate:data.exclusiveClose.template};});
  if(!String(data.ai.claudeModel||'').trim())data.ai.claudeModel=DEFAULT_CLAUDE_MODEL;data.ai.editorialPrompt=String(data.ai.editorialPrompt||'');data.ai.lastValidEditorialPrompt=String(data.ai.lastValidEditorialPrompt||'');data.ai.editorialInstructions=String(data.ai.editorialInstructions||'');
  data.tts.pronunciationMaxSeconds=Math.max(5,Math.min(30,Number(data.tts.pronunciationMaxSeconds)||15));data.tts.persistentIdleMinutes=Math.max(1,Math.min(30,Number(data.tts.persistentIdleMinutes)||5));data.tts.performanceThreads=Math.max(1,Math.min(12,Number(data.tts.performanceThreads)||6));data.tts.fallbackVoice=String(data.tts.fallbackVoice||'ef_dora');
  const o=data.visual.output,legacyFont=String(o.fontFamily||'Arial');for(const key of ['titleFontFamily','summaryFontFamily','categoryFontFamily','dateFontFamily','exclusiveFontFamily'])if(!o[key])o[key]=legacyFont;if(!o.dateColor)o.dateColor=o.summaryColor||'#F3F3F3';if(o.transitionEnabled===false||o.transitionType==='none')o.transitionType='none';else o.transitionType='fade';o.transitionEnabled=o.transitionType!=='none';
  o.titleFontSize=Math.max(20,Math.min(120,Number(o.titleFontSize)||64));o.summaryFontSize=Math.max(12,Math.min(72,Number(o.summaryFontSize)||30));o.categoryFontSize=Math.max(10,Math.min(48,Number(o.categoryFontSize)||22));o.dateFontSize=Math.max(10,Math.min(48,Number(o.dateFontSize)||18));o.exclusiveFontSize=Math.max(10,Math.min(48,Number(o.exclusiveFontSize)||18));
  o.titleFontWeight=Math.max(100,Math.min(900,Number(o.titleFontWeight)||800));o.summaryFontWeight=Math.max(100,Math.min(900,Number(o.summaryFontWeight)||400));o.categoryFontWeight=Math.max(100,Math.min(900,Number(o.categoryFontWeight)||900));o.dateFontWeight=Math.max(100,Math.min(900,Number(o.dateFontWeight)||500));o.exclusiveFontWeight=Math.max(100,Math.min(900,Number(o.exclusiveFontWeight)||800));
  data.documents.targetSeconds=Math.max(30,Math.min(180,Number(data.documents.targetSeconds)||60));data.automation.recoveryAutonomyMin=Math.max(2,Math.min(30,Number(data.automation.recoveryAutonomyMin)||8));data.automation.criticalAutonomyMin=Math.max(1,Math.min(data.automation.recoveryAutonomyMin,Number(data.automation.criticalAutonomyMin)||3));data.automation.targetAutonomyMin=Math.max(3,Math.min(60,Number(data.automation.targetAutonomyMin)||15));const generatedRaw=Number(data.automation.generatedEveryRss);data.automation.generatedEveryRss=Number.isFinite(generatedRaw)?Math.max(0,Math.min(50,generatedRaw)):5;data.automation.bufferReady=Math.max(1,Math.min(30,Number(data.automation.bufferReady)||15));data.automation.queueMax=Math.max(data.automation.bufferReady,Math.min(60,Number(data.automation.queueMax)||30));data.canned.adaptiveDuration=data.canned.adaptiveDuration!==false;
  if(data.ai.localResourceMode===undefined)data.ai.localResourceMode='safe_streaming';return data;}
function installProfileSettingsValidation0329(){const p=SettingsStore.prototype;if(p.__ec0329FullValidation)return;Object.defineProperty(p,'__ec0329FullValidation',{value:true});const load=p.load,save=p.save;p.load=function(...args){return fullNormalize(load.apply(this,args));};p.save=function(settings,...args){return save.call(this,fullNormalize(settings),...args);};}
module.exports={installProfileSettingsValidation0329,fullNormalize};
