const DEFAULT_CLAUDE_MODEL='claude-haiku-4-5-20251001';
const {buildPrompt,buildDocumentPrompt,parseEditorialJson,validateEditorialResult,correctivePrompt,compactBody,normalizeCategory}=require('./editorial');
const extractJson=parseEditorialJson;
class ProviderError extends Error{constructor(provider,message,code='',retryAfter=0){super(message);this.provider=provider;this.code=code;this.retryAfter=retryAfter;}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const CONTENT_RETRY_CODES=new Set(['BAD_JSON','EMPTY_RESPONSE','BAD_STATUS','BAD_QUALITY','EMPTY_FIELDS','FORMAT_GARBAGE','SOURCE_CTA','TOO_SHORT','UNSUPPORTED_NUMBER','TOO_LONG']);
function retryableError(e){const code=String(e?.code||'');return !['NO_KEY','401','403','NO_MODEL','404','UNKNOWN_PROVIDER'].includes(code);}
function claudeBody(model,maxTokens,messages){const body={model,max_tokens:maxTokens,messages};if(/claude-(?:sonnet-5|opus-5)/i.test(String(model||'')))body.thinking={type:'disabled'};return body;}
async function claudeRequest(apiKey,body,timeout=90000){const started=Date.now(),r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify(body),signal:AbortSignal.timeout(Math.max(1000,timeout))});if(!r.ok){const retry=Number(r.headers.get('retry-after')||0),text=await r.text();throw new ProviderError('claude',`Claude HTTP ${r.status}: ${text.slice(0,500)}`,String(r.status),retry);}const json=await r.json();return{json,elapsedMs:Date.now()-started};}
async function listClaudeModels(apiKey){if(!apiKey)throw new ProviderError('claude','Falta Claude API Key','NO_KEY');const r=await fetch('https://api.anthropic.com/v1/models?limit=100',{headers:{'x-api-key':apiKey,'anthropic-version':'2023-06-01'},signal:AbortSignal.timeout(20000)});if(!r.ok){const body=await r.text();throw new ProviderError('claude',`Claude HTTP ${r.status}: ${body.slice(0,300)}`,String(r.status),Number(r.headers.get('retry-after')||0));}const j=await r.json();return(j.data||[]).map(x=>x.id);}
async function claudeGenerate(apiKey,model,prompt){if(!apiKey)throw new ProviderError('claude','Falta Claude API Key','NO_KEY');const m=DEFAULT_CLAUDE_MODEL,{json:j,elapsedMs}=await claudeRequest(apiKey,claudeBody(m,650,[{role:'user',content:prompt}])),out=(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n'),usage=j.usage||{};return{model:m,result:extractJson(out),metrics:{elapsedMs,inputTokens:Number(usage.input_tokens||0),outputTokens:Number(usage.output_tokens||0)}};}
async function claudeProbe(apiKey,model=DEFAULT_CLAUDE_MODEL){if(!apiKey)throw new ProviderError('claude','Falta Claude API Key','NO_KEY');const {json:j,elapsedMs}=await claudeRequest(apiKey,claudeBody(model,32,[{role:'user',content:'Responde únicamente con la palabra OK.'}]),30000),out=(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join(' ').trim();if(!/^OK\b/i.test(out))throw new ProviderError('claude',`La API respondió, pero la prueba de generación devolvió: ${out.slice(0,120)||'vacío'}`,'PROBE_FAILED');return{elapsedMs};}
function pronunciationClaudePrompt(items,proposals={}){const rows=(items||[]).slice(0,18).map(x=>({term:String(x.term||''),context:String(x.context||'').slice(0,320),local_proposal:proposals?.[x.term]?.to||proposals?.[x.term]?.pronunciation||''}));return `Actúa como verificador de pronunciación para un TTS de noticias en español latinoamericano. Revisa cada término usando su contexto. No traduzcas nombres propios ni cambies palabras españolas que Kokoro pueda leer normalmente. Solo adapta términos extranjeros, siglas o marcas cuando ayude claramente al TTS. Usa ortografía española simple y legible; no uses IPA, explicaciones, paréntesis, barras, emojis ni instrucciones. Si no hace falta cambiar un término, marca needs_replacement=false y deja pronunciation vacío. Devuelve SOLO JSON válido con este esquema exacto: {"items":[{"term":"texto exacto","needs_replacement":true,"pronunciation":"aproximación simple","confidence":0.95}]}. Confidence debe estar entre 0 y 1.\n\nENTRADAS:\n${JSON.stringify(rows)}`;}
function parsePronunciationClaude(raw,allowedTerms){let text=String(raw||'').replace(/<think>[\s\S]*?<\/think>/gi,'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();const a=text.indexOf('{'),b=text.lastIndexOf('}');if(a>=0&&b>a)text=text.slice(a,b+1);let data;try{data=JSON.parse(text);}catch(e){throw new ProviderError('claude',`Pronunciación Claude: JSON inválido (${e.message})`,'BAD_JSON');}const allowed=new Set((allowedTerms||[]).map(String)),out=[];for(const x of Array.isArray(data?.items)?data.items:[]){const term=String(x?.term||'').trim();if(!allowed.has(term))continue;out.push({term,needsReplacement:x?.needs_replacement===true,pronunciation:String(x?.pronunciation||'').trim(),confidence:Math.max(0,Math.min(1,Number(x?.confidence)||0))});}return out;}
async function listGeminiModels(apiKey){if(!apiKey)throw new ProviderError('gemini','Falta Gemini API Key','NO_KEY');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(apiKey)}`,{signal:AbortSignal.timeout(20000)});if(!r.ok){const body=await r.text();throw new ProviderError('gemini',`Gemini HTTP ${r.status}: ${body.slice(0,300)}`,String(r.status),Number(r.headers.get('retry-after')||0));}const j=await r.json();return(j.models||[]).filter(x=>(x.supportedGenerationMethods||[]).includes('generateContent')).map(x=>x.name.replace(/^models\//,''));}
async function geminiGenerate(apiKey,model,prompt){if(!apiKey)throw new ProviderError('gemini','Falta Gemini API Key','NO_KEY');let m=model;if(!m){const models=await listGeminiModels(apiKey);m=models.find(x=>/flash/i.test(x)&&!/image|tts|live/i.test(x))||models[0];}if(!m)throw new ProviderError('gemini','No se encontró un modelo Gemini disponible','NO_MODEL');const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key=${encodeURIComponent(apiKey)}`,started=Date.now(),r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.1,responseMimeType:'application/json',maxOutputTokens:650}}),signal:AbortSignal.timeout(90000)});if(!r.ok){const body=await r.text();throw new ProviderError('gemini',`Gemini HTTP ${r.status}: ${body.slice(0,500)}`,String(r.status),Number(r.headers.get('retry-after')||0));}const j=await r.json(),out=j?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n')||'';return{model:m,result:extractJson(out),metrics:{elapsedMs:Date.now()-started,inputTokens:Number(j?.usageMetadata?.promptTokenCount||0),outputTokens:Number(j?.usageMetadata?.candidatesTokenCount||0)}};}
class Providers{
  constructor({settingsStore,localRuntime}){this.settingsStore=settingsStore;this.localRuntime=localRuntime;this.cooldownUntil={claude:0,gemini:0,local:0};this.claudeModelsCache={items:[],at:0};}
  async getClaudeModels(key,force=false){if(!force&&this.claudeModelsCache.items.length&&Date.now()-this.claudeModelsCache.at<30*60000)return this.claudeModelsCache.items;const items=await listClaudeModels(key);this.claudeModelsCache={items,at:Date.now()};return items;}
  async test(provider,settings){if(provider==='local')return this.localRuntime.status();if(provider==='claude'){const key=this.settingsStore.decryptSecret(settings.ai.claudeKeyEnc),models=await this.getClaudeModels(key,true);if(!models.includes(DEFAULT_CLAUDE_MODEL))throw new ProviderError('claude',`La API Key funciona, pero ${DEFAULT_CLAUDE_MODEL} no aparece disponible en esta cuenta.`,'NO_MODEL');const probe=await claudeProbe(key,DEFAULT_CLAUDE_MODEL);return{ok:true,keyStored:!!settings.ai.claudeKeyEnc,models,model:DEFAULT_CLAUDE_MODEL,generationOk:true,elapsedMs:probe.elapsedMs};}if(provider==='gemini'){const key=this.settingsStore.decryptSecret(settings.ai.geminiKeyEnc),models=await listGeminiModels(key);return{ok:true,keyStored:!!settings.ai.geminiKeyEnc,models,model:settings.ai.geminiModel||models.find(x=>/flash/i.test(x)&&!/image|tts|live/i.test(x))||models[0]||''};}return{ok:false};}
  async verifyPronunciations(items,proposals,settings,timeoutMs=6000){if(settings?.tts?.pronunciationClaudeVerify===false)return{used:false,reason:'disabled',items:[]};const key=this.settingsStore.decryptSecret(settings?.ai?.claudeKeyEnc||'');if(!key)return{used:false,reason:'no-key',items:[]};const terms=(items||[]).map(x=>String(x.term||'')).filter(Boolean);if(!terms.length)return{used:false,reason:'empty',items:[]};const prompt=pronunciationClaudePrompt(items,proposals),{json,elapsedMs}=await claudeRequest(key,claudeBody(DEFAULT_CLAUDE_MODEL,700,[{role:'user',content:prompt}]),Math.max(1500,timeoutMs)),raw=(json.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n');return{used:true,model:DEFAULT_CLAUDE_MODEL,elapsedMs,items:parsePronunciationClaude(raw,terms)};}
  localIsBackup(settings){return settings.ai.primary!=='local'&&[settings.ai.backup1,settings.ai.backup2].includes('local');}
  async callProvider(provider,prompt,settings){if(provider==='local'){this.localRuntime.configure(settings.ai.localResourceMode||'safe_streaming');const onDemand=this.localIsBackup(settings)&&(settings.ai.localBackupMode||'on_demand')==='on_demand',started=Date.now();try{const text=await this.localRuntime.generate(prompt);return{model:'Qwen3-8B-Q4_K_M',result:extractJson(text),metrics:{elapsedMs:Date.now()-started,inputTokens:0,outputTokens:0}};}finally{if(onDemand){const minutes=Math.max(1,Math.min(60,Number(settings.ai.localIdleMinutes)||5));this.localRuntime.scheduleIdleStop(minutes*60000);}}}if(provider==='claude'){const key=this.settingsStore.decryptSecret(settings.ai.claudeKeyEnc);return claudeGenerate(key,DEFAULT_CLAUDE_MODEL,prompt);}if(provider==='gemini'){const key=this.settingsStore.decryptSecret(settings.ai.geminiKeyEnc);return geminiGenerate(key,settings.ai.geminiModel,prompt);}throw new ProviderError(provider,'Proveedor desconocido','UNKNOWN_PROVIDER');}
  setCooldown(provider,e){if(String(e?.code)!=='429')return;const seconds=Math.max(15,Math.min(300,Number(e.retryAfter)||30));this.cooldownUntil[provider]=Date.now()+seconds*1000;}
  async generateBuilt(built,settings,order){const providers=[...new Set((order||[]).filter(x=>x&&x!=='none'))],attempts=[];if(!providers.length)throw new Error('No hay un proveedor de IA configurado');let generations=0,providerIndex=0,correction=null,retryProvider='';while(generations<2&&providerIndex<providers.length){const provider=correction&&retryProvider?retryProvider:providers[providerIndex],cooldown=Math.max(0,(this.cooldownUntil[provider]||0)-Date.now());if(cooldown>0){attempts.push({provider,attempt:generations,ok:false,code:'COOLDOWN',message:`En espera por límite de uso (${Math.ceil(cooldown/1000)} s)`});correction=null;retryProvider='';providerIndex++;continue;}const attemptNo=generations+1,effectivePrompt=correction?correctivePrompt(built.prompt,correction):built.prompt;generations++;try{const out=await this.callProvider(provider,effectivePrompt,settings),result=validateEditorialResult(out.result,built.sourceText,built),metrics={...(out.metrics||{}),inputChars:built.inputChars,promptTokens:built.promptTokens||0,sourceBudgetChars:built.sourceBudgetChars||0,generationCount:generations};attempts.push({provider,attempt:attemptNo,ok:true,model:out.model||'',elapsedMs:metrics.elapsedMs||0});return{provider,model:out.model||'',result,attempts,metrics};}catch(e){this.setCooldown(provider,e);const code=String(e?.code||'');attempts.push({provider,attempt:attemptNo,ok:false,message:e.message,code});if(generations<2&&CONTENT_RETRY_CODES.has(code)){correction=e;retryProvider=provider;await wait(250);continue;}correction=null;retryProvider='';providerIndex++;if(generations<2&&retryableError(e))await wait(e.retryAfter?Math.min(e.retryAfter*1000,5000):450);}}const err=new Error('Todos los intentos de IA fallaron');err.details=attempts;throw err;}
  async generate(story,article,settings){if(story?.__editorialTest)return this.testEditorialPrompt(article?.body||story.description||'',settings);const built=buildPrompt(story,article,settings),order=[settings.ai.primary,settings.ai.backup1,settings.ai.backup2];return this.generateBuilt(built,settings,order);}
  async generateDocument(doc,settings,options={}){const targetSeconds=Math.max(30,Math.min(180,Number(options.targetSeconds)||Number(settings?.documents?.targetSeconds)||60)),forcedCategory=String(options.category||'').trim(),built=buildDocumentPrompt(doc,settings,{targetSeconds,category:forcedCategory}),order=[settings.ai.primary,settings.ai.backup1,settings.ai.backup2],out=await this.generateBuilt(built,settings,order);if(forcedCategory&&forcedCategory.toLowerCase()!=='auto')out.result.category=normalizeCategory(forcedCategory);return out;}
  async testEditorialPrompt(source,settings){const text=String(source||'').trim();if(!text)throw new Error('Pega un texto de prueba');const built=buildDocumentPrompt({title:'Prueba de prompt',text},settings,{targetSeconds:Number(settings?.ai?.targetSeconds)||60,category:''}),started=Date.now(),out=await this.callProvider('local',built.prompt,settings),result=validateEditorialResult(out.result,built.sourceText,built);return{provider:'local',model:out.model||'Qwen3-8B-Q4_K_M',result,elapsedMs:Date.now()-started,promptTokens:built.promptTokens,sourceBudgetChars:built.sourceBudgetChars};}
}
module.exports={Providers,ProviderError,listClaudeModels,listGeminiModels,extractJson,compactBody,buildDocumentPrompt,DEFAULT_CLAUDE_MODEL,parsePronunciationClaude};