const {XMLParser}=require('fast-xml-parser');
const cheerio=require('cheerio');
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',trimValues:true,cdataPropName:'#cdata'});
const EC_LATEST_WEB='https://elcomercio.pe/ultimas-noticias/',EC_LATEST_MIN_ITEMS=10,MAX_FEED_BYTES=8*1024*1024,PARTIAL_ITEM_THRESHOLD=2;
let loadGeneration=0;const sharedItems=[];
function arrayify(v){return v==null?[]:(Array.isArray(v)?v:[v]);}
function text(v){if(v==null)return'';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);if(Array.isArray(v))return v.map(text).find(Boolean)||'';if(typeof v==='object'){for(const k of ['#text','#cdata','__cdata','value','@_href','@_url'])if(v[k]!=null){const t=text(v[k]);if(t)return t;}}return'';}
function cleanHtml(s){if(!s)return'';return cheerio.load(`<div>${s}</div>`)('div').text().replace(/\s+/g,' ').trim();}
function firstImageFromHtml(s){if(!s)return'';const $=cheerio.load(String(s));return $('img').first().attr('src')||$('img').first().attr('data-src')||$('img').first().attr('data-lazy-src')||'';}
function extractLink(item){for(const v of arrayify(item?.link)){if(typeof v==='string')return v.trim();if(v&&typeof v==='object'){const href=v['@_href']||v['@_url']||v.href||v.url||v['#text']||v['#cdata'];if(href)return String(href).trim();}}return text(item?.guid||item?.url||item?.loc).trim();}
function mediaUrl(item){const enclosure=Array.isArray(item?.enclosure)?item.enclosure[0]:item?.enclosure;if(enclosure&&(enclosure['@_url']||enclosure.url))return enclosure['@_url']||enclosure.url;for(const k of ['media:content','media:thumbnail','media_content','media_thumbnail','image']){const first=Array.isArray(item?.[k])?item[k][0]:item?.[k];if(typeof first==='string'&&/^https?:/i.test(first))return first;if(first&&typeof first==='object'){const u=first['@_url']||first['@_href']||first.url||first.href;if(u)return String(u);}}const encoded=text(item?.['content:encoded']||item?.encoded||item?.content||'');return firstImageFromHtml(encoded)||firstImageFromHtml(text(item?.description));}
function discoverEntries(doc){const direct=[doc?.rss?.channel?.item,doc?.rss?.channel?.items?.item,doc?.channel?.item,doc?.feed?.entry,doc?.rdf?.item,doc?.['rdf:RDF']?.item].flatMap(arrayify).filter(Boolean);if(direct.length)return direct;const found=[],seen=new Set();function walk(node,depth=0){if(!node||depth>9||found.length>=300)return;if(Array.isArray(node)){node.forEach(x=>walk(x,depth+1));return;}if(typeof node!=='object'||seen.has(node))return;seen.add(node);const title=text(node.title),link=extractLink(node);if(title&&link&&(node.description!=null||node.summary!=null||node.pubDate!=null||node.published!=null||node.guid!=null)){found.push(node);return;}Object.values(node).forEach(v=>walk(v,depth+1));}walk(doc);return found;}
function feedBase(feed={}){return{feedId:String(feed.id||'rss'),feedName:String(feed.name||'Fuente'),feedUrl:String(feed.url||'').trim(),feedAccessMode:String(feed.accessMode||'auto'),sourceMode:String(feed.sourceMode||'auto')};}
function parseFeedDetailed(xml,feed={}){const raw=String(xml||'');if(Buffer.byteLength(raw,'utf8')>MAX_FEED_BYTES)throw new Error('La fuente excede el tamaño máximo permitido');const doc=parser.parse(raw),entries=discoverEntries(doc).slice(0,300),base=feedBase(feed),items=entries.map((item,index)=>{const link=extractLink(item);return{id:`${base.feedId}:${index}:${text(item.guid||link)}`,...base,sourceType:'RSS',title:cleanHtml(text(item.title)),link,description:cleanHtml(text(item.description||item.summary||item.subtitle||item['media:description'])),category:cleanHtml(text(item.category?.['@_term']||item.category||item['dc:subject']||'')),pubDate:text(item.pubDate||item.published||item.updated||item['dc:date']),author:cleanHtml(text(item['dc:creator']||item.author?.name||item.author||'')),image:mediaUrl(item)};}).filter(x=>x.title&&/^https?:\/\//i.test(x.link));return{items,rawCount:entries.length,parsedCount:items.length};}
function parseFeed(xml,feed={}){return parseFeedDetailed(xml,feed).items;}
function categoryFromUrl(link){try{const parts=new URL(link).pathname.split('/').filter(Boolean),seg=parts.find(x=>!/^20\d\d$|^\d{2}$/.test(x))||'';return seg.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}catch{return'';}}
function samePublisherHost(a,b){try{const clean=h=>h.toLowerCase().replace(/^(?:www|m|amp)\./,'');const x=clean(new URL(a).hostname),y=clean(new URL(b).hostname);return x===y||x.endsWith('.'+y)||y.endsWith('.'+x);}catch{return false;}}
function utilityPath(pathname=''){return /^\/(?:feed|rss|archivo|autor|authors?|tag|buscar|search|login|registro|suscripcion|newsletter|contacto|politicas?|terminos?)(\/|$)/i.test(pathname);}
function parseHtmlGeneric(html,feed={},baseUrl=''){const raw=String(html||'');if(Buffer.byteLength(raw,'utf8')>MAX_FEED_BYTES)throw new Error('La fuente web excede el tamaño máximo permitido');const $=cheerio.load(raw),out=[],seen=new Set(),base=feedBase(feed),root=baseUrl||base.feedUrl;const selectors=['main article a[href]','main h1 a[href]','main h2 a[href]','main h3 a[href]','main h4 a[href]','main [class*="story"] a[href]','main [class*="card"] a[href]','main [class*="article"] a[href]','section article a[href]','article a[href]','[class*="story"] h2 a[href]','[class*="card"] h2 a[href]','[class*="article"] h2 a[href]'].join(',');$(selectors).each((_,a)=>{if(out.length>=200)return false;const href=$(a).attr('href')||'';let link='';try{link=new URL(href,root).href;}catch{return;}if(!/^https?:\/\//i.test(link)||!samePublisherHost(link,root))return;let u;try{u=new URL(link);}catch{return;}u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid|ref|outputType)$/i.test(k))u.searchParams.delete(k);link=u.href;if(seen.has(link)||utilityPath(u.pathname)||u.pathname==='/'||u.pathname.length<5)return;const container=$(a).closest('article,li,[class*="story"],[class*="card"],[class*="article"],section,div');let headline=$(a).attr('aria-label')||$(a).attr('title')||$(a).text();headline=String(headline||'').replace(/\s+/g,' ').trim();if(headline.length<18)headline=container.find('h1,h2,h3,h4').first().text().replace(/\s+/g,' ').trim();if(headline.length<18||headline.length>260)return;const description=container.find('p').first().text().replace(/\s+/g,' ').trim(),image=container.find('img').first().attr('src')||container.find('img').first().attr('data-src')||container.find('img').first().attr('data-lazy-src')||container.find('img').first().attr('srcset')?.split(/[ ,]/)[0]||'',pubDate=container.find('time').first().attr('datetime')||container.find('time').first().text().trim()||'',author=container.find('[rel="author"], [class*="author"]').first().text().replace(/\s+/g,' ').trim();seen.add(link);out.push({id:`${base.feedId}:web:${out.length}:${link}`,...base,sourceType:'WEB',title:headline,link,description,category:categoryFromUrl(link),pubDate,author,image});});return out;}
function parseHtmlLatest(html,feed={},baseUrl=EC_LATEST_WEB){return parseHtmlGeneric(html,feed,baseUrl);}
function canonicalLink(value){try{const u=new URL(String(value||''));u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid|mc_cid|mc_eid|ref)$/i.test(k))u.searchParams.delete(k);return u.href;}catch{return String(value||'').trim();}}
function mergeUniqueItems(...groups){const out=[],seen=new Set();for(const group of groups)for(const item of Array.isArray(group)?group:[]){const key=canonicalLink(item?.link);if(!key||seen.has(key))continue;seen.add(key);out.push({...item,link:key});}out.sort((a,b)=>(Date.parse(b.pubDate||'')||0)-(Date.parse(a.pubDate||'')||0));return out;}
function looksXmlSource(source,mode='auto'){if(mode==='web')return false;return mode==='rss'||/xml|rss|atom/i.test(source.contentType||'')||/^\s*<\?xml|^\s*<(rss|feed|rdf:RDF)/i.test(source.body||'');}
function looksHtmlSource(source,mode='auto'){if(mode==='rss')return false;return mode==='web'||/html/i.test(source.contentType||'')||/<html[\s>]/i.test(source.body||'');}
function isEcLatestArc(url=''){return /elcomercio\.pe\/arc\/outboundfeeds\/rss\/category\/ultimas-noticias/i.test(url);}
async function readBodyLimited(res,maxBytes=MAX_FEED_BYTES){const declared=Number(res.headers.get('content-length')||0);if(declared>maxBytes)throw new Error(`Respuesta demasiado grande (${Math.ceil(declared/1048576)} MB)`);if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder('utf-8');let total=0,out='';try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>maxBytes){try{await reader.cancel();}catch{}throw new Error(`La respuesta excede ${Math.round(maxBytes/1048576)} MB`);}out+=decoder.decode(value,{stream:true});}out+=decoder.decode();return out;}finally{try{reader.releaseLock();}catch{}}}
async function requestText(url){const value=String(url||'').trim();if(!/^https?:\/\//i.test(value))throw new Error('La dirección debe usar HTTP o HTTPS');const res=await fetch(value,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 EC-Automatic-News/0.3.24','Accept':'application/rss+xml, application/atom+xml, application/xml, text/xml, text/html, */*','Accept-Language':'es-PE,es;q=0.9,en;q=0.6'},redirect:'follow',signal:AbortSignal.timeout(22000)});if(!res.ok)throw new Error(`HTTP ${res.status}`);return{body:await readBodyLimited(res),contentType:res.headers.get('content-type')||'',finalUrl:res.url||value};}
function statusResult(items,sourceType,rawCount,mode,detail){const parsedCount=items.length,partial=parsedCount>0&&parsedCount<=PARTIAL_ITEM_THRESHOLD;return{items,sourceType,rawCount:Number(rawCount)||parsedCount,parsedCount,partial,mode,detail};}
async function complementEcLatest(feed,primary){try{const alt=await requestText(EC_LATEST_WEB),web=parseHtmlGeneric(alt.body,feed,alt.finalUrl||EC_LATEST_WEB),merged=mergeUniqueItems(primary.items,web);if(web.length&&merged.length>primary.items.length)return statusResult(merged,'RSS+WEB',primary.rawCount,'COMBINED_FALLBACK',`RSS complementado con web (${merged.length} noticias)`);}catch(e){return{...primary,partial:true,mode:`${primary.mode}_PARTIAL`,detail:`RSS con pocos resultados; no se pudo complementar: ${e.message}`};}return{...primary,partial:true,mode:`${primary.mode}_PARTIAL`,detail:primary.detail||'RSS con pocos resultados'};}
async function fetchFeedDetailed(feed={}){if(!feed.url)throw new Error(`${feed.name||'Fuente'}: falta URL`);const requestedMode=['rss','web'].includes(String(feed.sourceMode||'').toLowerCase())?String(feed.sourceMode).toLowerCase():'auto';let source;try{source=await requestText(feed.url);}catch(e){if(!isEcLatestArc(feed.url))throw new Error(`${feed.name||'Fuente'}: ${e.message}`);source=await requestText(EC_LATEST_WEB);}let parseError='';if(looksXmlSource(source,requestedMode)){try{const parsed=parseFeedDetailed(source.body,feed);if(parsed.items.length){let result=statusResult(parsed.items,'RSS',parsed.rawCount,'XML',`RSS: ${parsed.rawCount} elemento${parsed.rawCount===1?'':'s'} recibido${parsed.rawCount===1?'':'s'} · ${parsed.parsedCount} válido${parsed.parsedCount===1?'':'s'}`);if(isEcLatestArc(feed.url)&&parsed.items.length<EC_LATEST_MIN_ITEMS)result=await complementEcLatest(feed,result);return result;}}catch(e){parseError=e.message;}if(requestedMode==='rss')return statusResult([], 'RSS',0,'UNRECOGNIZED',parseError?`No se pudo interpretar el RSS: ${parseError}`:'El RSS no contiene noticias reconocibles');}
  if(looksHtmlSource(source,requestedMode)){const items=parseHtmlGeneric(source.body,feed,source.finalUrl||feed.url);if(items.length)return statusResult(items,'WEB',items.length,'HTML',`WEB: ${items.length} noticia${items.length===1?'':'s'} detectada${items.length===1?'':'s'}`);}
  return statusResult([],requestedMode==='web'?'WEB':requestedMode==='rss'?'RSS':'AUTO',0,'UNRECOGNIZED',parseError?`No se pudo interpretar la fuente: ${parseError}`:'La URL responde, pero no contiene noticias reconocibles');}
async function fetchFeed(feed){return(await fetchFeedDetailed(feed)).items;}
async function testFeed(feed){const r=await fetchFeedDetailed(feed);return{ok:r.items.length>0,count:r.items.length,rawCount:r.rawCount,parsedCount:r.parsedCount,sourceType:r.sourceType,partial:r.partial,mode:r.mode,detail:r.detail};}
async function loadAll(feeds){const generation=++loadGeneration,list=Array.isArray(feeds)?feeds:[],active=list.filter(f=>f&&f.enabled&&f.url),settled=await Promise.allSettled(active.map(fetchFeedDetailed)),items=[],errors=[],feedStatus=[];settled.forEach((r,i)=>{const feed=active[i];if(r.status==='fulfilled'){items.push(...r.value.items);feedStatus.push({id:feed.id,name:feed.name,ok:r.value.items.length>0,count:r.value.items.length,rawCount:r.value.rawCount,parsedCount:r.value.parsedCount,sourceType:r.value.sourceType,partial:r.value.partial,mode:r.value.mode,detail:r.value.detail});}else{const error=r.reason?.message||String(r.reason);errors.push({feed:feed.name,error});feedStatus.push({id:feed.id,name:feed.name,ok:false,count:0,rawCount:0,parsedCount:0,sourceType:'',partial:false,mode:'ERROR',detail:error});}});const dedup=mergeUniqueItems(items);if(generation===loadGeneration){sharedItems.splice(0,sharedItems.length,...dedup);}return{items:sharedItems,errors,feedStatus,stale:generation!==loadGeneration};}
module.exports={parseFeed,parseFeedDetailed,parseHtmlLatest,parseHtmlGeneric,fetchFeed,fetchFeedDetailed,testFeed,loadAll,canonicalLink,mergeUniqueItems,readBodyLimited,MAX_FEED_BYTES,EC_LATEST_MIN_ITEMS,PARTIAL_ITEM_THRESHOLD};
