'use strict';

const VERSION='2.1.0-es-PE';
const SCHEMA=1;
const MONTHS=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
const SMALL=['cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','once','doce','trece','catorce','quince','dieciséis','diecisiete','dieciocho','diecinueve','veinte','veintiuno','veintidós','veintitrés','veinticuatro','veinticinco','veintiséis','veintisiete','veintiocho','veintinueve'];
const TENS=['','','veinte','treinta','cuarenta','cincuenta','sesenta','setenta','ochenta','noventa'];
const HUNDREDS=['','ciento','doscientos','trescientos','cuatrocientos','quinientos','seiscientos','setecientos','ochocientos','novecientos'];
const ORD=['','primero','segundo','tercero','cuarto','quinto','sexto','séptimo','octavo','noveno'];
const ORD_TENS=['','décimo','vigésimo','trigésimo','cuadragésimo','quincuagésimo','sexagésimo','septuagésimo','octogésimo','nonagésimo'];
const FEMALE_NAMES=new Set(['isabel','margarita','maría','maria','victoria','juana','ana','catalina']);
const ROMAN_EXCLUSIONS=new Set(['canal','vitamina','grupo','clase','plan','modelo','ruta','fase','zona']);
const SPORTS_HINT=/(partido|gol(?:es)?|marcador|resultado|gan[oó]|perdi[oó]|empat[oó]|venci[oó]|derrot[oó]|penales|global|copa|liga|torneo|selecci[oó]n|f[uú]tbol|tenis|v[oó]ley|b[aá]squet|versus|vs\.?|contra)/i;

function apocope(s){return String(s).replace(/veintiuno$/,'veintiún').replace(/ y uno$/,' y un').replace(/uno$/,'un');}
function feminineOne(s){return String(s).replace(/veintiuno$/,'veintiuna').replace(/ y uno$/,' y una').replace(/uno$/,'una');}
function under100(n){n=Math.trunc(n);if(n<30)return SMALL[n]||'';const t=Math.trunc(n/10),u=n%10;return u?`${TENS[t]} y ${SMALL[u]}`:TENS[t];}
function under1000(n){n=Math.trunc(n);if(n<100)return under100(n);if(n===100)return'cien';const h=Math.trunc(n/100),r=n%100;return`${HUNDREDS[h]}${r?' '+under100(r):''}`;}
function integerWords(value){let n=typeof value==='bigint'?value:BigInt(Math.trunc(Number(value)));if(n===0n)return'cero';if(n<0n)return`menos ${integerWords(-n)}`;if(n>999999999999999n)return String(n).split('').map(d=>SMALL[Number(d)]).join(' ');const p=[];const b=n/1000000000000n;n%=1000000000000n;if(b)p.push(b===1n?'un billón':`${apocope(integerWords(b))} billones`);const m=n/1000000n;n%=1000000n;if(m)p.push(m===1n?'un millón':`${apocope(integerWords(m))} millones`);const k=n/1000n;n%=1000n;if(k)p.push(k===1n?'mil':`${apocope(under1000(Number(k)))} mil`);if(n)p.push(under1000(Number(n)));return p.join(' ');}
function parseNumber(raw,{dotDecimal=false}={}){
  let s=String(raw||'').trim().replace(/\s/g,''),sign='';if(/^[+-]/.test(s)){sign=s[0];s=s.slice(1);}if(!/^\d[\d.,]*$/.test(s))return null;
  let i=s,d='';const dots=(s.match(/\./g)||[]).length,commas=(s.match(/,/g)||[]).length;
  if(dots&&commas){const dec=s.lastIndexOf(',')>s.lastIndexOf('.')?',':'.',th=dec===','?'.':',';const at=s.lastIndexOf(dec);i=s.slice(0,at).split(th).join('');d=s.slice(at+1).replace(/[.,]/g,'');}
  else if(commas){const at=s.lastIndexOf(',');i=s.slice(0,at).replace(/,/g,'');d=s.slice(at+1);}
  else if(dots){const groups=s.split('.'),thousands=groups.length>1&&groups.slice(1).every(x=>x.length===3)&&groups[0]!=='0';if(thousands)i=groups.join('');else if(dotDecimal&&dots===1)[i,d]=groups;else if(groups.slice(1).every(x=>x.length===3))i=groups.join('');else{const at=s.lastIndexOf('.');i=s.slice(0,at).replace(/\./g,'');d=s.slice(at+1);}}
  i=i.replace(/^0+(?=\d)/,'')||'0';try{return{integer:BigInt(i),decimal:d,negative:sign==='-',positive:sign==='+'};}catch{return null;}
}
function decimalWords(d){if(!d)return'';if(d.length<=2&&!/^0/.test(d))return integerWords(BigInt(d));return d.split('').map(x=>SMALL[Number(x)]).join(' ');}
function numberWords(raw,opts={}){const p=parseNumber(raw,opts);if(!p)return String(raw);let s=integerWords(p.integer);if(p.decimal)s+=` coma ${decimalWords(p.decimal)}`;if(p.negative)s=`menos ${s}`;else if(p.positive)s=`más ${s}`;return s;}
function hourWords(n){n=Number(n);const base=integerWords(BigInt(n));return n===1||n===21?feminineOne(base):base;}
function minuteWords(n){n=Number(n);return apocope(integerWords(BigInt(n)));}
function seasonEndYear(start,suffix){const y=Number(start),s=Number(suffix);if(!Number.isInteger(y)||!Number.isInteger(s))return null;let candidate=Math.floor(y/100)*100+s;if(candidate<y)candidate+=100;return candidate;}
function romanToInt(raw){const s=String(raw||'').toUpperCase();if(!/^[IVXLCDM]+$/.test(s))return null;const v={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};let total=0,prev=0;for(let i=s.length-1;i>=0;i--){const n=v[s[i]];if(n<prev)total-=n;else{total+=n;prev=n;}}const enc=n=>{const pairs=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let o='';for(const [x,r] of pairs)while(n>=x){o+=r;n-=x;}return o;};return total>0&&total<=3999&&enc(total)===s?total:null;}
function ordinalWords(n,female=false){n=Number(n);if(!Number.isInteger(n)||n<1||n>100)return integerWords(BigInt(Math.max(0,Math.trunc(n))));if(n===100)return female?'centésima':'centésimo';const t=Math.trunc(n/10),u=n%10;let out=[t?ORD_TENS[t]:'',u?ORD[u]:''].filter(Boolean).join(' ');if(female)out=out.replace(/o\b/g,'a');return out;}
function romanNameWords(raw,female=false){const n=romanToInt(raw);if(!n)return raw;if(n<=10)return ordinalWords(n,female);return integerWords(BigInt(n));}
function validDate(y,m,d){const x=new Date(Date.UTC(+y,+m-1,+d));return x.getUTCFullYear()===+y&&x.getUTCMonth()===+m-1&&x.getUTCDate()===+d;}
function protect(text){const stash=[];const put=m=>`ECZPROT${stash.push(m)-1}Z`;let s=String(text||'');s=s.replace(/https?:\/\/[^\s)\]}>,]+/gi,put).replace(/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b/g,put).replace(/\bv\d+\.\d+(?:\.\d+)+\b/gi,put).replace(/\b(?:F|G|COP|COVID|iPhone|iOS|Windows|Android|PS|Xbox|RTX|GTX|USB|HDMI)\s*[-.]?\s*\d[\w.-]*\b/gi,put);return{text:s,restore:x=>String(x).replace(/ECZPROT(\d+)Z/g,(_,i)=>stash[Number(i)]??_)};}
function safeExternalPattern(pattern){const p=String(pattern||'');if(!p||p.length>160)return false;if(/\(\?/.test(p)||/\\[1-9]/.test(p)||/\.\*|\.\+/.test(p))return false;if((p.match(/\|/g)||[]).length>6)return false;if(/\([^)]*[+*{][^)]*\)[+*{]/.test(p))return false;if(/(?:\+|\*|\{\d+(?:,\d*)?\})(?:\s*)(?:\+|\*|\{)/.test(p))return false;return true;}
function applyExternalRules(text,rules=[],phase='pre'){let out=String(text||'');for(const r of Array.isArray(rules)?rules:[]){if(r?.enabled===false||String(r?.phase||'pre')!==phase)continue;const replacement=String(r?.replacement??'').slice(0,300);if(r.literal){const from=String(r.literal);if(from&&from.length<=120)out=out.split(from).join(replacement);continue;}const pattern=String(r?.pattern||'');if(!safeExternalPattern(pattern))continue;try{const flags=[...new Set(String(r.flags||'giu').replace(/[^gimuys]/g,''))].join('');out=out.replace(new RegExp(pattern,flags.includes('g')?flags:`g${flags}`),replacement);}catch{}}return out;}
function structuralPreNormalize(input,{rules=[]}={}){const p=protect(input);let s=p.text,transforms=[];const mark=(id,before)=>{if(s!==before)transforms.push(id);};let before;
  before=s;s=applyExternalRules(s,rules,'pre');mark('external-pre',before);
  before=s;s=s.replace(/\bvs\.(?=\s|$)|\bvs\b/giu,'versus');mark('versus',before);
  before=s;s=s.replace(/\bEE\.\s*UU\./giu,'Estados Unidos').replace(/\bFF\.\s*AA\./giu,'Fuerzas Armadas').replace(/\bRR\.\s*HH\./giu,'Recursos Humanos').replace(/\bN(?:ro|º|°)\.?\s*(?=\d)/giu,'número ');mark('abbreviations',before);
  before=s;s=s.replace(/\b(20\d{2}|19\d{2})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])\b/g,(m,y,mo,d)=>validDate(y,mo,d)?`${integerWords(BigInt(+d))} de ${MONTHS[+mo-1]} de ${integerWords(BigInt(+y))}`:m);mark('iso-date',before);
  before=s;s=s.replace(/\b(19\d{2}|20\d{2})\/(\d{2})\b/g,(m,y,b)=>{const full=seasonEndYear(y,b);return full==null?m:`${integerWords(BigInt(y))}, ${integerWords(BigInt(full))}`;});mark('season',before);
  before=s;s=s.replace(/\b(versi[oó]n)\s+(\d+)\.(\d+)(?:\.(\d+))?\b/giu,(m,label,a,b,c)=>`${label} ${integerWords(BigInt(a))} punto ${integerWords(BigInt(b))}${c!=null?` punto ${integerWords(BigInt(c))}`:''}`);mark('software-version',before);
  before=s;s=s.replace(/\b([01]?\d|2[0-3]):([0-5]\d)\s*horas?\b/gi,(m,h,min)=>{const hn=+h,mn=+min,hText=hourWords(hn),hourNoun=hn===1?'hora':'horas';return mn===0?`${hText} ${hourNoun}`:`${hText} ${hourNoun} con ${minuteWords(mn)} ${mn===1?'minuto':'minutos'}`;});mark('24h-explicit',before);
  before=s;s=s.replace(/([+-]?\d+(?:[.,]\d+)?)\s*%\s*[-–—]\s*([+-]?\d+(?:[.,]\d+)?)\s*%/g,(m,a,b)=>`${numberWords(a,{dotDecimal:true})} a ${numberWords(b,{dotDecimal:true})} por ciento`);mark('percent-range',before);
  before=s;s=s.replace(/(^|[^\p{L}\p{N}_])([+-]?\d[\d.,]*)\s*%/gu,(m,prefix,n)=>`${prefix}${numberWords(n,{dotDecimal:true})} por ciento`);mark('percentage',before);
  before=s;s=s.replace(/\b([+-]?\d{1,3}(?:\.\d{3})+)\b/g,(m,n)=>numberWords(n));mark('thousands',before);
  before=s;s=s.replace(/\b(?:Mw|MW|M)\s*([+-]?\d+(?:[.,]\d+)?)\b/g,(m,n)=>`magnitud ${numberWords(n,{dotDecimal:true})}`);mark('magnitude',before);
  before=s;s=s.replace(/\bkm\s+([0-9][\d.,]*)\b/gi,(m,n)=>`kilómetro ${numberWords(n)}`);mark('km-prefix',before);
  before=s;s=s.replace(/\b(\d+(?:[.,]\d+)?)\s*[-–—]\s*(\d+(?:[.,]\d+)?)\s*(km|kg|cm|mm|años?|°C)\b/gi,(m,a,b,u)=>{const k=u.toLowerCase(),name={km:'kilómetros',kg:'kilogramos',cm:'centímetros',mm:'milímetros','año':'años','años':'años','°c':'grados Celsius'}[k]||u;return`${numberWords(a,{dotDecimal:true})} a ${numberWords(b,{dotDecimal:true})} ${name}`;});mark('unit-range',before);
  before=s;s=s.replace(/S\/\s*(\d+(?:[.,]\d+)?)\s*[-–—]\s*(?:S\/\s*)?(\d+(?:[.,]\d+)?)/gi,(m,a,b)=>`${numberWords(a,{dotDecimal:true})} a ${numberWords(b,{dotDecimal:true})} soles`);mark('currency-range',before);
  before=s;s=s.replace(/\b([A-ZÁÉÍÓÚÜÑ][\p{L}ÁÉÍÓÚÜÑáéíóúüñ'’.-]+(?:\s+[A-ZÁÉÍÓÚÜÑ][\p{L}ÁÉÍÓÚÜÑáéíóúüñ'’.-]+){0,2})\s+([IVXLCDM]{1,8})\b/gu,(m,name,roman)=>{const last=name.trim().split(/\s+/).at(-1).toLocaleLowerCase('es');if(ROMAN_EXCLUSIONS.has(last))return m;const n=romanToInt(roman);if(!n)return m;return`${name} ${romanNameWords(roman,FEMALE_NAMES.has(last))}`;});mark('roman-name',before);
  before=s;s=s.replace(/\bsiglo\s+([IVXLCDM]{1,8})\b/giu,(m,r)=>{const n=romanToInt(r);return n?`siglo ${integerWords(BigInt(n))}`:m;}).replace(/\b(capítulo|tomo|volumen|parte)\s+([IVXLCDM]{1,8})\b/giu,(m,k,r)=>{const n=romanToInt(r);return n?`${k} ${integerWords(BigInt(n))}`:m;}).replace(/\b([IVXLCDM]{1,8})\s+(Guerra\s+Mundial|República|Conferencia|Congreso)\b/gu,(m,r,k)=>{const n=romanToInt(r);if(!n||n>100)return m;const female=/Guerra|República|Conferencia/.test(k);return`${ordinalWords(n,female)} ${k}`;});mark('roman-context',before);
  before=s;s=s.replace(/\b(\d{1,2})\s*[-–]\s*(\d{1,2})\b/g,(m,a,b,offset,full)=>{const around=full.slice(Math.max(0,offset-90),Math.min(full.length,offset+m.length+90));const teamShape=/[A-ZÁÉÍÓÚÜÑ][\p{L}ÁÉÍÓÚÜÑáéíóúüñ.-]+\s+$/.test(full.slice(Math.max(0,offset-45),offset))&&/^\s+[A-ZÁÉÍÓÚÜÑ][\p{L}ÁÉÍÓÚÜÑáéíóúüñ.-]+/u.test(full.slice(offset+m.length,offset+m.length+45));return SPORTS_HINT.test(around)||teamShape?`${integerWords(BigInt(a))} a ${integerWords(BigInt(b))}`:m;});mark('score',before);
  before=s;s=s.replace(/\b(\d{1,2}):(\d{1,2})\b/g,(m,a,b,offset,full)=>{const around=full.slice(Math.max(0,offset-90),Math.min(full.length,offset+m.length+90));return SPORTS_HINT.test(around)?`${integerWords(BigInt(a))} a ${integerWords(BigInt(b))}`:m;});mark('score-colon',before);
  before=s;s=s.replace(/≤/g,' menor o igual que ').replace(/≥/g,' mayor o igual que ').replace(/±\s*(?=\d)/g,'más o menos ').replace(/≈\s*(?=\d)/g,'aproximadamente ').replace(/<\s*(?=\d)/g,'menos de ').replace(/>\s*(?=\d)/g,'más de ');mark('math-symbols',before);
  before=s;s=applyExternalRules(s,rules,'post');mark('external-post',before);
  s=s.replace(/[ \t]+/g,' ').replace(/\s+([,.;:!?])/g,'$1').trim();return{text:p.restore(s),transforms:[...new Set(transforms)],version:VERSION};
}
function validateRulePack(pack){if(!pack||typeof pack!=='object')return{ok:false,error:'Paquete vacío'};let bytes=0;try{bytes=Buffer.byteLength(JSON.stringify(pack),'utf8');}catch{return{ok:false,error:'Paquete no serializable'};}if(bytes>256*1024)return{ok:false,error:'Paquete demasiado grande'};if(Number(pack.schema)!==SCHEMA)return{ok:false,error:`Schema incompatible: ${pack.schema}`};const rules=Array.isArray(pack.rules)?pack.rules:[],tests=Array.isArray(pack.tests)?pack.tests:[];if(rules.length>220)return{ok:false,error:'Demasiadas reglas'};if(tests.length>250)return{ok:false,error:'Demasiadas pruebas'};for(const r of rules){if(r?.literal&&String(r.literal).length>120)return{ok:false,error:'Literal demasiado largo'};if(r?.replacement&&String(r.replacement).length>300)return{ok:false,error:'Reemplazo demasiado largo'};if(r?.pattern&&!safeExternalPattern(r.pattern))return{ok:false,error:`Patrón no permitido: ${String(r.id||'sin-id').slice(0,60)}`};}for(const t of tests){if(String(t?.input??'').length>2000||String(t?.expected??'').length>3000)return{ok:false,error:'Prueba demasiado larga'};}return{ok:true};}
module.exports={VERSION,SCHEMA,integerWords,numberWords,hourWords,minuteWords,seasonEndYear,romanToInt,structuralPreNormalize,validateRulePack,applyExternalRules,safeExternalPattern};
