'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {spawn,spawnSync}=require('child_process');
const {pathToFileURL}=require('url');

const ENGINES={
  chatterbox:{id:'chatterbox',label:'Chatterbox V3',package:'chatterbox-tts'},
  qwen3tts:{id:'qwen3tts',label:'Qwen3-TTS 0.6B',package:'qwen-tts'}
};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

class TTSLabRuntime{
  constructor({resourcesDir,dataDir}){
    this.resourcesDir=resourcesDir;this.dataDir=dataDir;
    this.python=path.join(resourcesDir,'runtime','python','python.exe');
    this.workerScript=path.join(resourcesDir,'runtime','tts-lab','tts_lab_worker.py');
    this.root=path.join(dataDir,'tts-lab');this.voiceDir=path.join(this.root,'voices');this.audioDir=path.join(dataDir,'audio');this.modelsDir=path.join(this.root,'models');this.cacheDir=path.join(this.root,'voice-cache');this.fineTunedDir=path.join(this.root,'qwen3tts','fine-tuned');
    fs.mkdirSync(this.voiceDir,{recursive:true});fs.mkdirSync(this.audioDir,{recursive:true});fs.mkdirSync(this.modelsDir,{recursive:true});fs.mkdirSync(this.cacheDir,{recursive:true});fs.mkdirSync(this.fineTunedDir,{recursive:true});
    this.workers=new Map();this.installing=new Map();
  }
  engine(id){return ENGINES[String(id||'')]||null;}
  siteDir(id){return path.join(this.root,String(id||''),'site-packages');}
  marker(id){return path.join(this.root,String(id||''),'.installed.json');}
  preparedMarker(id){return path.join(this.root,String(id||''),'.prepared.json');}
  installed(id){return!!this.engine(id)&&fs.existsSync(this.marker(id));}
  prepared(id){return this.installed(id)&&fs.existsSync(this.preparedMarker(id));}
  env(id){const site=this.siteDir(id),existing=process.env.PYTHONPATH||'';return{...process.env,PYTHONUTF8:'1',PYTHONNOUSERSITE:'1',PYTHONPATH:[site,existing].filter(Boolean).join(path.delimiter),HF_HOME:path.join(this.modelsDir,'huggingface'),HUGGINGFACE_HUB_CACHE:path.join(this.modelsDir,'huggingface','hub'),TRANSFORMERS_CACHE:path.join(this.modelsDir,'transformers'),TOKENIZERS_PARALLELISM:'false'};}
  cacheKey(s){return crypto.createHash('sha1').update(String(s||'')).digest('hex').slice(0,16);}
  chatterboxCache(id){return path.join(this.cacheDir,`${id}.chatterbox.conds.pt`);}
  qwenCache(id,transcript=''){return path.join(this.cacheDir,`${id}.qwen.${this.cacheKey(transcript)}.pt`);}
  clearVoiceCaches(id,kind=''){for(const name of fs.readdirSync(this.cacheDir)){if(!name.startsWith(`${id}.`))continue;if(kind&& !name.includes(`.${kind}.`))continue;try{fs.rmSync(path.join(this.cacheDir,name),{force:true});}catch{}}}
  listVoices(){const out=[];for(const name of fs.readdirSync(this.voiceDir)){if(!/\.json$/i.test(name))continue;try{const meta=JSON.parse(fs.readFileSync(path.join(this.voiceDir,name),'utf8'));if(meta?.id&&meta?.path&&fs.existsSync(meta.path)){const transcript=String(meta.transcript||'').trim();out.push({...meta,transcript,chatterboxPrepared:fs.existsSync(this.chatterboxCache(meta.id)),qwenPrepared:!!transcript&&fs.existsSync(this.qwenCache(meta.id,transcript))});}}catch{}}return out.sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));}
  importReference(src){if(!src||!fs.existsSync(src))throw new Error('El audio de referencia ya no existe');const ext=(path.extname(src)||'.wav').toLowerCase();if(!['.wav','.flac'].includes(ext))throw new Error('Usa una referencia WAV o FLAC para esta prueba');const id=`ref_${crypto.randomUUID()}`,base=path.basename(src,ext).replace(/[^\p{L}\p{N} _-]+/gu,' ').trim()||'Voz de referencia',dest=path.join(this.voiceDir,`${id}${ext}`);fs.copyFileSync(src,dest);const meta={id,name:base,path:dest,transcript:'',createdAt:new Date().toISOString(),source:path.basename(src)};fs.writeFileSync(path.join(this.voiceDir,`${id}.json`),JSON.stringify(meta,null,2),'utf8');return meta;}
  updateReference(id,patch={}){const meta=this.voice(id);if(!meta)throw new Error('Voz de referencia no encontrada');const oldTranscript=String(meta.transcript||'').trim(),next={...meta};if(patch.name!==undefined)next.name=String(patch.name||'').trim()||next.name;if(patch.transcript!==undefined)next.transcript=String(patch.transcript||'').trim();fs.writeFileSync(path.join(this.voiceDir,`${id}.json`),JSON.stringify(next,null,2),'utf8');if(String(next.transcript||'').trim()!==oldTranscript)this.clearVoiceCaches(id,'qwen');return this.voice(id);}
  deleteReference(id){const meta=this.voice(id);if(!meta)throw new Error('Voz de referencia no encontrada');try{fs.rmSync(meta.path,{force:true});}catch{}try{fs.rmSync(path.join(this.voiceDir,`${id}.json`),{force:true});}catch{}this.clearVoiceCaches(id);return meta;}
  voice(id){return this.listVoices().find(x=>x.id===id)||null;}
  findModelDir(root){const queue=[root];while(queue.length){const dir=queue.shift();if(fs.existsSync(path.join(dir,'config.json'))&&fs.existsSync(path.join(dir,'model.safetensors')))return dir;let items=[];try{items=fs.readdirSync(dir,{withFileTypes:true});}catch{}for(const x of items)if(x.isDirectory())queue.push(path.join(dir,x.name));}return null;}
  listFineTunedModels(){const out=[];for(const name of fs.readdirSync(this.fineTunedDir)){const dir=path.join(this.fineTunedDir,name),metaPath=path.join(dir,'metadata.json');if(!fs.existsSync(metaPath))continue;try{const meta=JSON.parse(fs.readFileSync(metaPath,'utf8'));if(meta?.id&&fs.existsSync(path.join(dir,'config.json'))&&fs.existsSync(path.join(dir,'model.safetensors')))out.push({...meta,path:dir});}catch{}}return out.sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));}
  fineTunedModel(id){return this.listFineTunedModels().find(x=>x.id===id)||null;}
  deleteFineTunedModel(id){const meta=this.fineTunedModel(id);if(!meta)throw new Error('Modelo Qwen entrenado no encontrado');fs.rmSync(meta.path,{recursive:true,force:true});return meta;}
  importFineTunedZip(src){if(!src||!fs.existsSync(src))throw new Error('El archivo del modelo ya no existe');if(path.extname(src).toLowerCase()!=='.zip')throw new Error('Importa el checkpoint Qwen entrenado como archivo ZIP');const tmp=path.join(this.root,`import-${crypto.randomUUID()}`);fs.mkdirSync(tmp,{recursive:true});try{const py="import sys,zipfile,pathlib\nsrc=sys.argv[1]; dst=pathlib.Path(sys.argv[2]).resolve()\nwith zipfile.ZipFile(src) as z:\n    for m in z.infolist():\n        target=(dst/m.filename).resolve()\n        if target!=dst and dst not in target.parents: raise RuntimeError('ZIP contiene rutas no seguras')\n    z.extractall(dst)";const ex=spawnSync(this.python,['-c',py,src,tmp],{windowsHide:true,encoding:'utf8'});if(ex.status!==0)throw new Error(`No se pudo descomprimir el modelo: ${String(ex.stderr||ex.stdout||'').slice(-1000)}`);const modelDir=this.findModelDir(tmp);if(!modelDir)throw new Error('El ZIP no contiene un checkpoint Qwen válido (config.json + model.safetensors)');const cfg=JSON.parse(fs.readFileSync(path.join(modelDir,'config.json'),'utf8')),spk=cfg?.talker_config?.spk_id||{},speaker=Object.keys(spk)[0]||'';if(!speaker)throw new Error('El checkpoint no declara speaker_name en talker_config.spk_id');const id=`ft_${crypto.randomUUID()}`,name=path.basename(src,'.zip').replace(/[^\p{L}\p{N} _-]+/gu,' ').trim()||speaker,dest=path.join(this.fineTunedDir,id);fs.cpSync(modelDir,dest,{recursive:true});const meta={id,name,speaker,source:path.basename(src),createdAt:new Date().toISOString(),ttsModelType:String(cfg.tts_model_type||'custom_voice')};fs.writeFileSync(path.join(dest,'metadata.json'),JSON.stringify(meta,null,2),'utf8');return{...meta,path:dest};}finally{try{fs.rmSync(tmp,{recursive:true,force:true});}catch{}}}
  async install(id){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(this.installed(id))return{ok:true,already:true,engine:id};if(this.installing.has(id))return this.installing.get(id);const task=(async()=>{if(!fs.existsSync(this.python))throw new Error('Python portable de GEC no está disponible');const site=this.siteDir(id);fs.mkdirSync(site,{recursive:true});const args=['-m','pip','install','--disable-pip-version-check','--no-warn-script-location','--upgrade','--target',site,e.package];await new Promise((resolve,reject)=>{const p=spawn(this.python,args,{windowsHide:true,env:{...process.env,PYTHONUTF8:'1'}});let err='';p.stdout.on('data',d=>{err=(err+d.toString()).slice(-5000);});p.stderr.on('data',d=>{err=(err+d.toString()).slice(-5000);});p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(new Error(`Instalación de ${e.label} falló (${code}): ${err.slice(-1800)}`)));});fs.mkdirSync(path.dirname(this.marker(id)),{recursive:true});fs.writeFileSync(this.marker(id),JSON.stringify({engine:id,package:e.package,installedAt:new Date().toISOString()},null,2),'utf8');return{ok:true,engine:id};})();this.installing.set(id,task);try{return await task;}finally{this.installing.delete(id);}}
  async prepare(id){if(!this.installed(id))await this.install(id);const worker=await this.ensureWorker(id);const result=await this.command(id,{cmd:'prepare'},15*60*1000);fs.writeFileSync(this.preparedMarker(id),JSON.stringify({engine:id,preparedAt:new Date().toISOString(),device:result.device||''},null,2),'utf8');return{ok:true,engine:id,device:result.device||'',prepared:true};}
  async prepareReference(id,referenceVoiceId){const voice=this.voice(referenceVoiceId);if(!voice)throw new Error('Voz de referencia no encontrada');if(id==='qwen3tts'&&!voice.transcript)throw new Error('Añade la transcripción exacta de esta referencia antes de prepararla para Qwen3-TTS');const payload={cmd:'prepare_reference',reference:voice.path,reference_text:voice.transcript||'',cache_path:id==='chatterbox'?this.chatterboxCache(voice.id):this.qwenCache(voice.id,voice.transcript||'')};return this.command(id,payload,12*60*1000);}
  workerState(id){const w=this.workers.get(id);return{running:!!w?.child&&w.ready,modelLoaded:!!w?.modelLoaded,device:w?.device||''};}
  status(selected='kokoro'){
    const engines=[{id:'kokoro',label:'Kokoro',installed:true,prepared:true},...Object.values(ENGINES).map(e=>({id:e.id,label:e.label,installed:this.installed(e.id),prepared:this.prepared(e.id),installing:this.installing.has(e.id),...this.workerState(e.id)}))];
    return{ok:true,selected,engines,voices:this.listVoices(),fineTunedModels:this.listFineTunedModels(),python:fs.existsSync(this.python),workerScript:fs.existsSync(this.workerScript)};
  }
  attach(id,child){const state={child,ready:false,buffer:'',pending:new Map(),seq:0,stderr:'',modelLoaded:false,device:''};this.workers.set(id,state);child.stdout.on('data',d=>{state.buffer+=d.toString();let i;while((i=state.buffer.indexOf('\n'))>=0){const line=state.buffer.slice(0,i).trim();state.buffer=state.buffer.slice(i+1);if(!line.startsWith('LABJSON '))continue;let msg;try{msg=JSON.parse(line.slice(8));}catch{continue;}if(msg.type==='ready'){state.ready=msg.ok===true;continue;}const key=String(msg.id||''),p=state.pending.get(key);if(!p)continue;state.pending.delete(key);clearTimeout(p.timer);if(msg.ok===false)p.reject(new Error(msg.error||'Error del motor TTS'));else{if(msg.prepared){state.modelLoaded=true;state.device=msg.device||state.device;}p.resolve(msg);}}});child.stderr.on('data',d=>{state.stderr=(state.stderr+d.toString()).slice(-3000);});const gone=()=>{if(this.workers.get(id)!==state)return;for(const p of state.pending.values()){clearTimeout(p.timer);p.reject(new Error(`El motor ${id} se cerró: ${state.stderr.slice(-1000)}`));}state.pending.clear();this.workers.delete(id);};child.on('exit',gone);child.on('error',gone);return state;}
  async ensureWorker(id){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(!this.installed(id))throw new Error(`${e.label} no está instalado`);const existing=this.workers.get(id);if(existing?.child&&existing.ready)return existing;const child=spawn(this.python,[this.workerScript,id],{windowsHide:true,env:this.env(id),cwd:this.resourcesDir});const state=this.attach(id,child);const end=Date.now()+30000;while(Date.now()<end){if(state.ready)return state;if(!this.workers.has(id))throw new Error(`No se pudo iniciar ${e.label}: ${state.stderr.slice(-1200)}`);await sleep(100);}this.stop(id);throw new Error(`${e.label} tardó demasiado en iniciar`);}
  async command(id,payload,timeoutMs=240000){const state=await this.ensureWorker(id),reqId=`v2-${++state.seq}`;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{state.pending.delete(reqId);reject(new Error(`El motor de voz excedió ${Math.round(timeoutMs/1000)} s`));},timeoutMs);state.pending.set(reqId,{resolve,reject,timer});try{state.child.stdin.write(JSON.stringify({id:reqId,...payload})+'\n');}catch(e){clearTimeout(timer);state.pending.delete(reqId);reject(e);}});}
  async generate(id,text,{referenceVoiceId='',referencePath='',referenceText='',style='news',params={}}={}){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(!this.installed(id))throw new Error(`${e.label} no está instalado. Instálalo desde Audio y locución.`);const qwenMode=String(params?.voiceMode||'reference'),fine=qwenMode==='finetuned'?this.fineTunedModel(String(params?.fineTunedModelId||'')):null;let voice=referencePath?{id:'benchmark',path:referencePath,transcript:String(referenceText||'')}:this.voice(referenceVoiceId);if(id==='qwen3tts'&&qwenMode==='finetuned'&&!fine)throw new Error('Selecciona un modelo Qwen3-TTS entrenado');if(id==='qwen3tts'&&qwenMode!=='finetuned'&&!voice)throw new Error('Selecciona una voz de referencia para Qwen3-TTS');if(id==='qwen3tts'&&qwenMode!=='finetuned'&&!String(voice.transcript||'').trim())throw new Error('Qwen3-TTS necesita la transcripción exacta del audio de referencia');const out=path.join(this.audioDir,`news-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.wav`),started=Date.now(),cachePath=voice?(id==='chatterbox'?this.chatterboxCache(voice.id):this.qwenCache(voice.id,voice.transcript||'')):'';const r=await this.command(id,{cmd:'generate',text:String(text||''),reference:voice?.path||'',reference_text:voice?.transcript||'',cache_path:cachePath,output:out,style,params,qwen_mode:qwenMode,model_path:fine?.path||'',speaker:fine?.speaker||''},12*60*1000);if(!fs.existsSync(out)||fs.statSync(out).size<1000)throw new Error(`${e.label} no produjo un WAV válido`);const elapsedMs=Number(r.elapsed_ms)||Date.now()-started,durationSec=Number(r.duration_sec)||0,rtf=Number(r.rtf)||(durationSec>0?Number(((elapsedMs/1000)/durationSec).toFixed(3)):0);return{path:out,url:pathToFileURL(out).href,durationSec,voice:fine?.id||voice?.id||'builtin',elapsedMs,synthesisElapsedMs:elapsedMs,workerStartupMs:0,persistent:true,threads:0,executionMode:r.device||'auto',performanceProfile:`lab-${id}`,performanceLabel:e.label,realtimeFactor:rtf,steadyRealtimeFactor:rtf,engine:id,device:r.device||'',qwenMode};}
  async benchmark(id,options={}){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');const text='GEC Automatic News realiza esta prueba para medir el nuevo motor de voz con una locución periodística realista. El sistema compara el tiempo de creación, la estabilidad y el comportamiento mientras la inteligencia artificial local continúa preparando noticias.';const runs=[];for(let i=0;i<2;i++){const audio=await this.generate(id,text,options);runs.push({id:`run-${i+1}`,label:`${e.label} · prueba ${i+1}`,realtimeFactor:audio.realtimeFactor,medianRealtimeFactor:audio.realtimeFactor,worstRealtimeFactor:audio.realtimeFactor,cpuAverage:0,safe:true,durationSec:audio.durationSec});try{fs.rmSync(audio.path,{force:true});}catch{}}const values=runs.map(x=>x.realtimeFactor).sort((a,b)=>a-b),median=values.length===2?(values[0]+values[1])/2:values[0],worst=Math.max(...values);return{ok:true,recommended:'safe_streaming',recommendedLabel:e.label,bestRealtimeFactor:Number(median.toFixed(3)),fastestRealtimeFactor:Number(Math.min(...values).toFixed(3)),worstRealtimeFactor:Number(worst.toFixed(3)),results:runs,engine:id};}
  stop(id=''){const ids=id?[id]:[...this.workers.keys()];for(const key of ids){const state=this.workers.get(key);if(!state)continue;this.workers.delete(key);try{state.child.stdin.write(JSON.stringify({id:`stop-${Date.now()}`,cmd:'stop'})+'\n');}catch{}setTimeout(()=>{try{if(state.child.exitCode==null)state.child.kill();}catch{}},700);}return true;}
  async stopAndWait(id=''){this.stop(id);await sleep(250);return true;}
}
module.exports={TTSLabRuntime,ENGINES};
