'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {spawn,spawnSync}=require('child_process');
const {pathToFileURL}=require('url');

const CUDA_RUNTIME={revision:1,torch:'2.6.0',torchaudio:'2.6.0',indexUrl:'https://download.pytorch.org/whl/cu124'};
const CACHE_REVISION='lab11-r1';
const ENGINES={
  chatterbox:{id:'chatterbox',label:'Chatterbox V3',package:'chatterbox-tts',installRevision:3,packages:['setuptools<81','resemble-perth','chatterbox-tts']},
  qwen3tts:{id:'qwen3tts',label:'Qwen3-TTS 0.6B',package:'qwen-tts',installRevision:2,packages:['qwen-tts']}
};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

class TTSLabRuntime{
  constructor({resourcesDir,dataDir}){
    this.resourcesDir=resourcesDir;this.dataDir=dataDir;
    this.python=path.join(resourcesDir,'runtime','python','python.exe');
    this.workerScript=path.join(resourcesDir,'runtime','tts-lab','tts_lab_worker.py');
    this.root=path.join(dataDir,'tts-lab');this.voiceDir=path.join(this.root,'voices');this.audioDir=path.join(dataDir,'audio');this.modelsDir=path.join(this.root,'models');this.cacheDir=path.join(this.root,'voice-cache');this.fineTunedDir=path.join(this.root,'qwen3tts','fine-tuned');this.cudaRoot=path.join(this.root,'shared-cuda');this.cudaSite=path.join(this.cudaRoot,'site-packages');
    fs.mkdirSync(this.voiceDir,{recursive:true});fs.mkdirSync(this.audioDir,{recursive:true});fs.mkdirSync(this.modelsDir,{recursive:true});fs.mkdirSync(this.cacheDir,{recursive:true});fs.mkdirSync(this.fineTunedDir,{recursive:true});fs.mkdirSync(this.cudaSite,{recursive:true});
    this.workers=new Map();this.installing=new Map();
  }
  engine(id){return ENGINES[String(id||'')]||null;}
  siteDir(id){return path.join(this.root,String(id||''),'site-packages');}
  marker(id){return path.join(this.root,String(id||''),'.installed.json');}
  preparedMarker(id){return path.join(this.root,String(id||''),'.prepared.json');}
  cudaMarker(){return path.join(this.cudaRoot,'.cuda-runtime.json');}
  cudaInstalled(){if(!fs.existsSync(this.cudaMarker()))return false;try{const m=JSON.parse(fs.readFileSync(this.cudaMarker(),'utf8'));return Number(m.revision||0)>=CUDA_RUNTIME.revision&&String(m.torch||'')===CUDA_RUNTIME.torch&&String(m.torchaudio||'')===CUDA_RUNTIME.torchaudio;}catch{return false;}}
  pipEnv(extra={}){return{...process.env,PYTHONUTF8:'1',PYTHONNOUSERSITE:'1',...extra};}
  async runPip(args,label,env={}){await new Promise((resolve,reject)=>{const p=spawn(this.python,['-m','pip','install','--disable-pip-version-check','--no-warn-script-location',...args],{windowsHide:true,env:this.pipEnv(env)});let log='';p.stdout.on('data',d=>{log=(log+d.toString()).slice(-9000);});p.stderr.on('data',d=>{log=(log+d.toString()).slice(-9000);});p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(new Error(`${label} falló (${code}): ${log.slice(-2600)}`)));});}
  async installCudaRuntime(){if(this.cudaInstalled())return{ok:true,already:true};fs.mkdirSync(this.cudaSite,{recursive:true});await this.runPip(['--upgrade','--force-reinstall','--target',this.cudaSite,`torch==${CUDA_RUNTIME.torch}`,`torchaudio==${CUDA_RUNTIME.torchaudio}`,'--index-url',CUDA_RUNTIME.indexUrl],'Instalación de PyTorch CUDA');fs.writeFileSync(this.cudaMarker(),JSON.stringify({revision:CUDA_RUNTIME.revision,torch:CUDA_RUNTIME.torch,torchaudio:CUDA_RUNTIME.torchaudio,indexUrl:CUDA_RUNTIME.indexUrl,installedAt:new Date().toISOString()},null,2),'utf8');return{ok:true};}
  removeTorchShadow(id){const site=this.siteDir(id);let removed=[];let items=[];try{items=fs.readdirSync(site,{withFileTypes:true});}catch{return removed;}const exact=new Set(['torch','torchaudio','functorch','torchgen']);for(const item of items){const name=item.name,low=name.toLowerCase();const hit=exact.has(low)||/^torch-.*\.dist-info$/i.test(name)||/^torchaudio-.*\.dist-info$/i.test(name)||/^functorch-.*\.dist-info$/i.test(name);if(!hit)continue;try{fs.rmSync(path.join(site,name),{recursive:true,force:true});removed.push(name);}catch{}}return removed;}
  installed(id){const e=this.engine(id);if(!e||!fs.existsSync(this.marker(id))||!this.cudaInstalled())return false;try{const m=JSON.parse(fs.readFileSync(this.marker(id),'utf8'));return Number(m.installRevision||1)>=Number(e.installRevision||1)&&Number(m.cudaRuntimeRevision||0)>=CUDA_RUNTIME.revision;}catch{return false;}}
  chatterboxVariant(params={}){return String(params?.variant||'latam')==='multilingual'?'multilingual':'latam';}
  quickFileFingerprint(file){try{const st=fs.statSync(file),h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),chunk=Math.min(1024*1024,st.size),a=Buffer.alloc(chunk),b=Buffer.alloc(chunk);if(chunk){fs.readSync(fd,a,0,chunk,0);fs.readSync(fd,b,0,chunk,Math.max(0,st.size-chunk));}fs.closeSync(fd);h.update(String(st.size));h.update(a);h.update(b);return h.digest('hex').slice(0,24);}catch{return'';}}
  modelFingerprint(dir){try{const cfg=path.join(dir,'config.json'),model=path.join(dir,'model.safetensors');if(!fs.existsSync(cfg)||!fs.existsSync(model))return'';const h=crypto.createHash('sha256');h.update(fs.readFileSync(cfg));h.update(this.quickFileFingerprint(model));return h.digest('hex').slice(0,24);}catch{return'';}}
  qwenSelection(params={}){const mode=String(params?.voiceMode||'reference')==='finetuned'?'finetuned':'reference';if(mode!=='finetuned')return{mode,id:'base',fingerprint:'base',modelPath:'',speaker:'',key:'reference:base'};const id=String(params?.fineTunedModelId||''),fine=this.fineTunedModel(id);if(!fine)return{mode,id,fingerprint:'',modelPath:'',speaker:'',key:`finetuned:${id||'missing'}:missing`,missing:true};const fingerprint=String(fine.fingerprint||this.modelFingerprint(fine.path)||'');return{mode,id:fine.id,fingerprint,modelPath:fine.path,speaker:fine.speaker||'',name:fine.name||fine.id,key:`finetuned:${fine.id}:${fingerprint||'unknown'}`};}
  preparedInfo(id){try{return fs.existsSync(this.preparedMarker(id))?JSON.parse(fs.readFileSync(this.preparedMarker(id),'utf8')):{};}catch{return{};}}
  prepared(id,{params={}}={}){if(!this.installed(id)||!fs.existsSync(this.preparedMarker(id)))return false;try{const m=this.preparedInfo(id),e=this.engine(id);if(Number(m.installRevision||0)!==Number(e?.installRevision||0)||Number(m.cudaRuntimeRevision||0)!==CUDA_RUNTIME.revision||String(m.cacheRevision||'')!==CACHE_REVISION)return false;if(id==='chatterbox')return String(m.variant||'multilingual')===this.chatterboxVariant(params);if(id==='qwen3tts'){const sel=this.qwenSelection(params);return !sel.missing&&String(m.selectionKey||'')===sel.key;}return true;}catch{return false;}}
  env(id){const site=this.siteDir(id),existingPy=process.env.PYTHONPATH||'',existingPath=process.env.PATH||'',torchLib=path.join(this.cudaSite,'torch','lib');return{...process.env,PYTHONUTF8:'1',PYTHONNOUSERSITE:'1',PYTHONPATH:[site,this.cudaSite,existingPy].filter(Boolean).join(path.delimiter),PATH:[torchLib,existingPath].filter(Boolean).join(path.delimiter),HF_HOME:path.join(this.modelsDir,'huggingface'),HUGGINGFACE_HUB_CACHE:path.join(this.modelsDir,'huggingface','hub'),TRANSFORMERS_CACHE:path.join(this.modelsDir,'transformers'),TOKENIZERS_PARALLELISM:'false',GEC_TTS_CUDA_RUNTIME:'1'};}
  cacheKey(s){return crypto.createHash('sha1').update(String(s||'')).digest('hex').slice(0,16);}
  chatterboxCache(id,variant='latam'){return path.join(this.cacheDir,`${id}.chatterbox.${variant==='multilingual'?'multilingual':'latam'}.${CACHE_REVISION}.conds.pt`);}
  qwenCache(id,transcript=''){return path.join(this.cacheDir,`${id}.qwen.${CACHE_REVISION}.${this.cacheKey(transcript)}.pt`);}
  clearVoiceCaches(id,kind=''){for(const name of fs.readdirSync(this.cacheDir)){if(!name.startsWith(`${id}.`))continue;if(kind&& !name.includes(`.${kind}.`))continue;try{fs.rmSync(path.join(this.cacheDir,name),{force:true});}catch{}}}
  listVoices(){const out=[];for(const name of fs.readdirSync(this.voiceDir)){if(!/\.json$/i.test(name))continue;try{const meta=JSON.parse(fs.readFileSync(path.join(this.voiceDir,name),'utf8'));if(meta?.id&&meta?.path&&fs.existsSync(meta.path)){const transcript=String(meta.transcript||'').trim();out.push({...meta,transcript,chatterboxPreparedLatam:fs.existsSync(this.chatterboxCache(meta.id,'latam')),chatterboxPreparedMultilingual:fs.existsSync(this.chatterboxCache(meta.id,'multilingual')),chatterboxPrepared:fs.existsSync(this.chatterboxCache(meta.id,'latam'))||fs.existsSync(this.chatterboxCache(meta.id,'multilingual')),qwenPrepared:!!transcript&&fs.existsSync(this.qwenCache(meta.id,transcript))});}}catch{}}return out.sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));}
  importReference(src){if(!src||!fs.existsSync(src))throw new Error('El audio de referencia ya no existe');const ext=(path.extname(src)||'.wav').toLowerCase();if(!['.wav','.flac'].includes(ext))throw new Error('Usa una referencia WAV o FLAC para esta prueba');const id=`ref_${crypto.randomUUID()}`,base=path.basename(src,ext).replace(/[^\p{L}\p{N} _-]+/gu,' ').trim()||'Voz de referencia',dest=path.join(this.voiceDir,`${id}${ext}`);fs.copyFileSync(src,dest);const meta={id,name:base,path:dest,transcript:'',createdAt:new Date().toISOString(),source:path.basename(src)};fs.writeFileSync(path.join(this.voiceDir,`${id}.json`),JSON.stringify(meta,null,2),'utf8');return meta;}
  updateReference(id,patch={}){const meta=this.voice(id);if(!meta)throw new Error('Voz de referencia no encontrada');const oldTranscript=String(meta.transcript||'').trim(),next={...meta};if(patch.name!==undefined)next.name=String(patch.name||'').trim()||next.name;if(patch.transcript!==undefined)next.transcript=String(patch.transcript||'').trim();fs.writeFileSync(path.join(this.voiceDir,`${id}.json`),JSON.stringify(next,null,2),'utf8');if(String(next.transcript||'').trim()!==oldTranscript)this.clearVoiceCaches(id,'qwen');return this.voice(id);}
  deleteReference(id){const meta=this.voice(id);if(!meta)throw new Error('Voz de referencia no encontrada');try{fs.rmSync(meta.path,{force:true});}catch{}try{fs.rmSync(path.join(this.voiceDir,`${id}.json`),{force:true});}catch{}this.clearVoiceCaches(id);return meta;}
  voice(id){return this.listVoices().find(x=>x.id===id)||null;}
  findModelDir(root){const queue=[root];while(queue.length){const dir=queue.shift();if(fs.existsSync(path.join(dir,'config.json'))&&fs.existsSync(path.join(dir,'model.safetensors')))return dir;let items=[];try{items=fs.readdirSync(dir,{withFileTypes:true});}catch{}for(const x of items)if(x.isDirectory())queue.push(path.join(dir,x.name));}return null;}
  listFineTunedModels(){const out=[];for(const name of fs.readdirSync(this.fineTunedDir)){const dir=path.join(this.fineTunedDir,name),metaPath=path.join(dir,'metadata.json');if(!fs.existsSync(metaPath))continue;try{let meta=JSON.parse(fs.readFileSync(metaPath,'utf8'));if(meta?.id&&fs.existsSync(path.join(dir,'config.json'))&&fs.existsSync(path.join(dir,'model.safetensors'))){const fingerprint=String(meta.fingerprint||this.modelFingerprint(dir)||'');if(fingerprint&&fingerprint!==meta.fingerprint){meta={...meta,fingerprint};try{fs.writeFileSync(metaPath,JSON.stringify(meta,null,2),'utf8');}catch{}}out.push({...meta,fingerprint,path:dir});}}catch{}}return out.sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));}
  fineTunedModel(id){return this.listFineTunedModels().find(x=>x.id===id)||null;}
  deleteFineTunedModel(id){const meta=this.fineTunedModel(id);if(!meta)throw new Error('Modelo Qwen entrenado no encontrado');fs.rmSync(meta.path,{recursive:true,force:true});return meta;}
  importFineTunedZip(src){if(!src||!fs.existsSync(src))throw new Error('El archivo del modelo ya no existe');if(path.extname(src).toLowerCase()!=='.zip')throw new Error('Importa el checkpoint Qwen entrenado como archivo ZIP');const tmp=path.join(this.root,`import-${crypto.randomUUID()}`);fs.mkdirSync(tmp,{recursive:true});try{const py="import sys,zipfile,pathlib\nsrc=sys.argv[1]; dst=pathlib.Path(sys.argv[2]).resolve()\nwith zipfile.ZipFile(src) as z:\n    for m in z.infolist():\n        target=(dst/m.filename).resolve()\n        if target!=dst and dst not in target.parents: raise RuntimeError('ZIP contiene rutas no seguras')\n    z.extractall(dst)";const ex=spawnSync(this.python,['-c',py,src,tmp],{windowsHide:true,encoding:'utf8'});if(ex.status!==0)throw new Error(`No se pudo descomprimir el modelo: ${String(ex.stderr||ex.stdout||'').slice(-1000)}`);const modelDir=this.findModelDir(tmp);if(!modelDir)throw new Error('El ZIP no contiene un checkpoint Qwen válido (config.json + model.safetensors)');const cfg=JSON.parse(fs.readFileSync(path.join(modelDir,'config.json'),'utf8')),weights=path.join(modelDir,'model.safetensors'),weightSize=fs.statSync(weights).size;if(weightSize<1024*1024)throw new Error('model.safetensors parece incompleto o es un puntero de Git LFS');const spk=cfg?.talker_config?.spk_id||{},speaker=Object.keys(spk)[0]||'';if(!speaker)throw new Error('El checkpoint no declara speaker_name en talker_config.spk_id');const modelType=String(cfg.tts_model_type||'custom_voice');if(!/custom|voice/i.test(modelType))throw new Error(`El checkpoint Qwen no parece ser un modelo de voz fine-tuned compatible (tts_model_type=${modelType||'vacío'})`);const id=`ft_${crypto.randomUUID()}`,name=path.basename(src,'.zip').replace(/[^\p{L}\p{N} _-]+/gu,' ').trim()||speaker,dest=path.join(this.fineTunedDir,id);fs.cpSync(modelDir,dest,{recursive:true});const fingerprint=this.modelFingerprint(dest);if(!fingerprint)throw new Error('No se pudo verificar la identidad del checkpoint Qwen entrenado');const meta={id,name,speaker,source:path.basename(src),createdAt:new Date().toISOString(),ttsModelType:modelType,weightSize,fingerprint};fs.writeFileSync(path.join(dest,'metadata.json'),JSON.stringify(meta,null,2),'utf8');return{...meta,path:dest};}finally{try{fs.rmSync(tmp,{recursive:true,force:true});}catch{}}}
  async install(id){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(this.installed(id)&&this.cudaInstalled())return{ok:true,already:true,engine:id};if(this.installing.has(id))return this.installing.get(id);const task=(async()=>{if(!fs.existsSync(this.python))throw new Error('Python portable de GEC no está disponible');await this.installCudaRuntime();const site=this.siteDir(id);fs.mkdirSync(site,{recursive:true});const packages=Array.isArray(e.packages)&&e.packages.length?e.packages:[e.package];const pyPath=[this.cudaSite,process.env.PYTHONPATH||''].filter(Boolean).join(path.delimiter);for(const pkg of packages){await this.runPip(['--upgrade','--target',site,pkg],`Instalación de ${e.label} · ${pkg}`,{PYTHONPATH:pyPath});}const removed=this.removeTorchShadow(id);fs.mkdirSync(path.dirname(this.marker(id)),{recursive:true});fs.writeFileSync(this.marker(id),JSON.stringify({engine:id,package:e.package,packages,installRevision:e.installRevision||1,cudaRuntimeRevision:CUDA_RUNTIME.revision,torch:CUDA_RUNTIME.torch,torchaudio:CUDA_RUNTIME.torchaudio,removedTorchShadow:removed,installedAt:new Date().toISOString()},null,2),'utf8');try{fs.rmSync(this.preparedMarker(id),{force:true});}catch{}this.stop(id);return{ok:true,engine:id,repaired:true,cuda:true};})();this.installing.set(id,task);try{return await task;}finally{this.installing.delete(id);}}
  async validateSelectedQwen(params={}){if(!this.installed('qwen3tts'))await this.install('qwen3tts');const sel=this.qwenSelection(params);if(sel.missing)throw new Error('Selecciona un modelo Qwen3-TTS entrenado válido');await this.ensureWorker('qwen3tts');const result=await this.command('qwen3tts',{cmd:'validate_qwen',model_path:sel.mode==='finetuned'?sel.modelPath:'',speaker:sel.speaker||''},15*60*1000);return{ok:true,selection:sel,repairedAssets:Array.isArray(result.repaired)?result.repaired:[],sharedAssetsOk:result.shared_assets_ok===true};}
  async prepare(id,{params={}}={}){if(!this.installed(id))await this.install(id);await this.ensureWorker(id);const variant=id==='chatterbox'?this.chatterboxVariant(params):'',e=this.engine(id),sel=id==='qwen3tts'?this.qwenSelection(params):null;if(id==='qwen3tts'&&sel?.missing)throw new Error('Selecciona un modelo Qwen3-TTS entrenado válido');let validation=null;if(id==='qwen3tts')validation=await this.validateSelectedQwen(params);const result=await this.command(id,{cmd:'prepare',params,qwen_mode:sel?.mode||'',model_path:sel?.mode==='finetuned'?sel.modelPath:'',speaker:sel?.speaker||''},15*60*1000);const marker={engine:id,variant,selectionKey:sel?.key||'',qwenMode:sel?.mode||'',fineTunedModelId:sel?.mode==='finetuned'?sel.id:'',fineTunedFingerprint:sel?.mode==='finetuned'?sel.fingerprint:'',installRevision:Number(e?.installRevision||0),cudaRuntimeRevision:CUDA_RUNTIME.revision,cacheRevision:CACHE_REVISION,preparedAt:new Date().toISOString(),device:result.device||'',gpuName:result.gpu_name||'',gpuVramMb:Number(result.gpu_vram_mb||0),torchVersion:result.torch_version||'',torchCuda:result.torch_cuda||'',cudaAvailable:result.cuda_available===true,repairedAssets:validation?.repairedAssets||result.repaired_assets||[]};fs.writeFileSync(this.preparedMarker(id),JSON.stringify(marker,null,2),'utf8');return{ok:true,engine:id,variant,selectionKey:marker.selectionKey,qwenMode:marker.qwenMode,fineTunedModelId:marker.fineTunedModelId,fineTunedFingerprint:marker.fineTunedFingerprint,repairedAssets:marker.repairedAssets,device:result.device||'',prepared:true};}
  async prepareReference(id,referenceVoiceId,{params={}}={}){const voice=this.voice(referenceVoiceId);if(!voice)throw new Error('Voz de referencia no encontrada');if(id==='qwen3tts'&&!voice.transcript)throw new Error('Añade la transcripción exacta de esta referencia antes de prepararla para Qwen3-TTS');const variant=id==='chatterbox'?this.chatterboxVariant(params):'';const payload={cmd:'prepare_reference',reference:voice.path,reference_text:voice.transcript||'',cache_path:id==='chatterbox'?this.chatterboxCache(voice.id,variant):this.qwenCache(voice.id,voice.transcript||''),params};return this.command(id,payload,12*60*1000);}
  async warmup(id,{referenceVoiceId='',params={}}={}){if(!id||id==='kokoro')return{ok:true,engine:'kokoro',skipped:true};await this.prepare(id,{params});let referencePrepared=false;const qwenFine=id==='qwen3tts'&&String(params?.voiceMode||'reference')==='finetuned';if(referenceVoiceId&&!qwenFine){await this.prepareReference(id,referenceVoiceId,{params});referencePrepared=true;}return{ok:true,engine:id,referencePrepared,qwenSelection:id==='qwen3tts'?this.qwenSelection(params):null,state:this.workerState(id),cacheRevision:CACHE_REVISION};}
  workerState(id){const w=this.workers.get(id);return{running:!!w?.child&&w.ready,modelLoaded:!!w?.modelLoaded,device:w?.device||'',gpuName:w?.gpuName||'',gpuVramMb:Number(w?.gpuVramMb||0),torchVersion:w?.torchVersion||'',torchCuda:w?.torchCuda||'',cudaAvailable:!!w?.cudaAvailable,variant:w?.variant||''};}
  status(selected='kokoro',{params={}}={}){
    const fineModels=this.listFineTunedModels(),engines=[{id:'kokoro',label:'Kokoro',installed:true,prepared:true},...Object.values(ENGINES).map(e=>{const ep=e.id===selected?params:{},prepared=this.prepared(e.id,{params:ep}),saved=prepared?this.preparedInfo(e.id):{},live=this.workerState(e.id),selection=e.id==='qwen3tts'?this.qwenSelection(ep):null;return{id:e.id,label:e.label,installed:this.installed(e.id),prepared,installing:this.installing.has(e.id),requestedVariant:e.id==='chatterbox'?this.chatterboxVariant(ep):'',selectionKey:selection?.key||'',qwenMode:selection?.mode||'',fineTunedModelId:selection?.mode==='finetuned'?selection.id:'',fineTunedFingerprint:selection?.mode==='finetuned'?selection.fingerprint:'',...live,device:live.device||saved.device||'',gpuName:live.gpuName||saved.gpuName||'',gpuVramMb:Number(live.gpuVramMb||saved.gpuVramMb||0),torchVersion:live.torchVersion||saved.torchVersion||'',torchCuda:live.torchCuda||saved.torchCuda||'',cudaAvailable:live.cudaAvailable||saved.cudaAvailable===true,variant:live.variant||saved.variant||''};})];
    const preparedInfo=this.preparedInfo('qwen3tts');for(const m of fineModels)m.prepared=String(preparedInfo.selectionKey||'')===`finetuned:${m.id}:${m.fingerprint||'unknown'}`&&this.prepared('qwen3tts',{params:{voiceMode:'finetuned',fineTunedModelId:m.id}});
    return{ok:true,selected,engines,voices:this.listVoices(),fineTunedModels:fineModels,python:fs.existsSync(this.python),workerScript:fs.existsSync(this.workerScript),cudaRuntimeInstalled:this.cudaInstalled(),cudaRuntime:{torch:CUDA_RUNTIME.torch,torchaudio:CUDA_RUNTIME.torchaudio,indexUrl:CUDA_RUNTIME.indexUrl}};
  }
  attach(id,child){const state={child,ready:false,buffer:'',pending:new Map(),seq:0,stderr:'',modelLoaded:false,device:'',gpuName:'',gpuVramMb:0,torchVersion:'',torchCuda:'',cudaAvailable:false,variant:''};this.workers.set(id,state);child.stdout.on('data',d=>{state.buffer+=d.toString();let i;while((i=state.buffer.indexOf('\n'))>=0){const line=state.buffer.slice(0,i).trim();state.buffer=state.buffer.slice(i+1);if(!line.startsWith('LABJSON '))continue;let msg;try{msg=JSON.parse(line.slice(8));}catch{continue;}if(msg.type==='ready'){state.ready=msg.ok===true;continue;}const key=String(msg.id||''),p=state.pending.get(key);if(!p)continue;if(msg.type==='progress'){p.progressCount=(p.progressCount||0)+1;p.lastProgress=msg;clearTimeout(p.idleTimer);if(p.inactivityMs>0)p.idleTimer=setTimeout(p.onIdle,p.inactivityMs);continue;}state.pending.delete(key);clearTimeout(p.idleTimer);clearTimeout(p.totalTimer);if(msg.ok===false){const detail=String(msg.trace||'').trim().split('\n').slice(-5).join(' | '),err=new Error(msg.error||'Error del motor TTS');err.code=msg.code||'TTS_ENGINE_ERROR';err.details=detail;p.reject(err);}else{if(msg.prepared){state.modelLoaded=true;state.device=msg.device||state.device;state.gpuName=msg.gpu_name||state.gpuName;state.gpuVramMb=Number(msg.gpu_vram_mb||state.gpuVramMb||0);state.torchVersion=msg.torch_version||state.torchVersion;state.torchCuda=msg.torch_cuda||state.torchCuda;state.cudaAvailable=msg.cuda_available===true;state.variant=msg.variant||state.variant;}msg.progress_count=p.progressCount||0;p.resolve(msg);}}});child.stderr.on('data',d=>{state.stderr=(state.stderr+d.toString()).slice(-3000);});const gone=()=>{if(this.workers.get(id)!==state)return;for(const p of state.pending.values()){clearTimeout(p.idleTimer);clearTimeout(p.totalTimer);const err=new Error(`El motor ${id} se cerró: ${state.stderr.slice(-1000)}`);err.code='TTS_WORKER_EXIT';p.reject(err);}state.pending.clear();this.workers.delete(id);};child.on('exit',gone);child.on('error',gone);return state;}
  async ensureWorker(id){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(!this.installed(id))throw new Error(`${e.label} no está instalado`);const existing=this.workers.get(id);if(existing?.child&&existing.ready)return existing;const child=spawn(this.python,[this.workerScript,id],{windowsHide:true,env:this.env(id),cwd:this.resourcesDir});const state=this.attach(id,child);const end=Date.now()+30000;while(Date.now()<end){if(state.ready)return state;if(!this.workers.has(id))throw new Error(`No se pudo iniciar ${e.label}: ${state.stderr.slice(-1200)}`);await sleep(100);}this.stop(id);throw new Error(`${e.label} tardó demasiado en iniciar`);}
  hardStop(id){const state=this.workers.get(id);if(!state)return false;this.workers.delete(id);for(const p of state.pending.values()){clearTimeout(p.idleTimer);clearTimeout(p.totalTimer);const err=new Error(`El motor ${id} fue reiniciado para recuperar el pipeline`);err.code='TTS_WORKER_ABORTED';try{p.reject(err);}catch{}}state.pending.clear();try{state.child.kill();}catch{}return true;}
  async command(id,payload,timeoutMs=240000,{inactivityMs=0}={}){const state=await this.ensureWorker(id),reqId=`v2-${++state.seq}`;return new Promise((resolve,reject)=>{const fail=(code,message)=>{if(!state.pending.has(reqId))return;state.pending.delete(reqId);const p=holder;clearTimeout(p.idleTimer);clearTimeout(p.totalTimer);this.hardStop(id);const err=new Error(message);err.code=code;err.timeoutMs=code==='TTS_STALL'?inactivityMs:timeoutMs;err.progressCount=p.progressCount||0;err.lastProgress=p.lastProgress||null;reject(err);};const holder={resolve,reject,inactivityMs:Number(inactivityMs)||0,progressCount:0,lastProgress:null,idleTimer:null,totalTimer:null,onIdle:()=>fail('TTS_STALL',`El motor de voz no reportó progreso durante ${Math.round(inactivityMs/1000)} s`)};if(holder.inactivityMs>0)holder.idleTimer=setTimeout(holder.onIdle,holder.inactivityMs);holder.totalTimer=setTimeout(()=>fail('TTS_TOTAL_TIMEOUT',`El motor de voz excedió ${Math.round(timeoutMs/1000)} s en total`),timeoutMs);state.pending.set(reqId,holder);try{state.child.stdin.write(JSON.stringify({id:reqId,...payload})+'\n');}catch(e){clearTimeout(holder.idleTimer);clearTimeout(holder.totalTimer);state.pending.delete(reqId);reject(e);}});}
  async generate(id,text,{referenceVoiceId='',referencePath='',referenceText='',style='news',params={}}={}){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');if(!this.installed(id))throw new Error(`${e.label} no está instalado. Instálalo desde Audio y locución.`);const qwenMode=String(params?.voiceMode||'reference'),fine=qwenMode==='finetuned'?this.fineTunedModel(String(params?.fineTunedModelId||'')):null;let voice=referencePath?{id:'benchmark',path:referencePath,transcript:String(referenceText||'')}:this.voice(referenceVoiceId);const variant=id==='chatterbox'?this.chatterboxVariant(params):'';if(id==='chatterbox'&&variant==='latam'&&!voice)throw new Error('Chatterbox LatAm necesita una voz de referencia para conservar identidad y acento');if(id==='qwen3tts'&&qwenMode==='finetuned'&&!fine)throw new Error('Selecciona un modelo Qwen3-TTS entrenado');if(id==='qwen3tts'&&qwenMode!=='finetuned'&&!voice)throw new Error('Selecciona una voz de referencia para Qwen3-TTS');if(id==='qwen3tts'&&qwenMode!=='finetuned'&&!String(voice.transcript||'').trim())throw new Error('Qwen3-TTS necesita la transcripción exacta del audio de referencia');const out=path.join(this.audioDir,`news-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.wav`),started=Date.now(),cachePath=voice?(id==='chatterbox'?this.chatterboxCache(voice.id,variant):this.qwenCache(voice.id,voice.transcript||'')):'';const rawText=String(text||''),expectedSec=Math.max(12,Math.min(90,rawText.length/13)),totalMs=Math.round(Math.max(95000,Math.min(180000,expectedSec*2100+30000))),inactivityMs=id==='chatterbox'?85000:100000,payload={cmd:'generate',text:rawText,reference:voice?.path||'',reference_text:voice?.transcript||'',cache_path:cachePath,output:out,style,params,qwen_mode:qwenMode,model_path:fine?.path||'',speaker:fine?.speaker||''};const r=await this.command(id,payload,totalMs,{inactivityMs});if(!fs.existsSync(out)||fs.statSync(out).size<1000)throw new Error(`${e.label} no produjo un WAV válido`);const elapsedMs=Number(r.elapsed_ms)||Date.now()-started,durationSec=Number(r.duration_sec)||0,rtf=Number(r.rtf)||(durationSec>0?Number(((elapsedMs/1000)/durationSec).toFixed(3)):0);return{path:out,url:pathToFileURL(out).href,durationSec,voice:fine?.id||voice?.id||'builtin',elapsedMs,synthesisElapsedMs:elapsedMs,workerStartupMs:0,persistent:true,threads:0,executionMode:r.device||'auto',performanceProfile:`lab-${id}`,performanceLabel:e.label,realtimeFactor:rtf,steadyRealtimeFactor:rtf,engine:id,device:r.device||'',gpuName:r.gpu_name||'',gpuVramMb:Number(r.gpu_vram_mb||0),cudaPeakAllocatedMb:Number(r.cuda_peak_allocated_mb||0),cudaPeakReservedMb:Number(r.cuda_peak_reserved_mb||0),torchVersion:r.torch_version||'',torchCuda:r.torch_cuda||'',cudaAvailable:r.cuda_available===true,qwenMode,qwenRuntime:r.qwen_runtime||{},variant:r.variant||variant,speed:Number(r.speed||params?.speed||1),generationAttempts:1,progressCount:Number(r.progress_count||0),watchdog:{inactivityMs,totalMs}};}
  async qwenCapabilities(){if(!this.installed('qwen3tts'))throw new Error('Qwen3-TTS no está instalado');await this.ensureWorker('qwen3tts');return this.command('qwen3tts',{cmd:'capabilities'},30000);}
  qwenPerfCandidates(params={},caps={}){const base={...params,voiceMode:params.voiceMode||'reference',dtypeMode:'bf16',attentionMode:'auto',chunkChars:360,performanceProfile:'baseline'},out=[
    {id:'baseline',label:'Actual · BF16 / Auto · 360',params:base},
    {id:'bf16-sdpa-600',label:'BF16 / SDPA · 600',params:{...base,dtypeMode:'bf16',attentionMode:'sdpa',chunkChars:600,performanceProfile:'bf16-sdpa-600'}},
    {id:'fp16-sdpa-600',label:'FP16 / SDPA · 600',params:{...base,dtypeMode:'fp16',attentionMode:'sdpa',chunkChars:600,performanceProfile:'fp16-sdpa-600'}},
    {id:'bf16-eager-600',label:'BF16 / Eager · 600',params:{...base,dtypeMode:'bf16',attentionMode:'eager',chunkChars:600,performanceProfile:'bf16-eager-600'}},
    {id:'fp16-eager-600',label:'FP16 / Eager · 600',params:{...base,dtypeMode:'fp16',attentionMode:'eager',chunkChars:600,performanceProfile:'fp16-eager-600'}}
  ];if(caps?.flash_attention_2){out.push({id:'bf16-fa2-600',label:'BF16 / Flash Attention 2 · 600',params:{...base,dtypeMode:'bf16',attentionMode:'flash_attention_2',chunkChars:600,performanceProfile:'bf16-fa2-600'}});out.push({id:'fp16-fa2-600',label:'FP16 / Flash Attention 2 · 600',params:{...base,dtypeMode:'fp16',attentionMode:'flash_attention_2',chunkChars:600,performanceProfile:'fp16-fa2-600'}});}return out;}
  async benchmarkQwenPerformance(options={},onProgress=()=>{}){const params={...(options.params||{})},caps=await this.qwenCapabilities(),candidates=this.qwenPerfCandidates(params,caps),warmText='El Comercio verifica el rendimiento de la voz.',testText='El Comercio informó nuevas medidas que serán evaluadas durante las próximas horas. Las autoridades señalaron que ofrecerán más detalles conforme avance la jornada.';const results=[];for(let i=0;i<candidates.length;i++){const cand=candidates[i];onProgress({type:'tts-lab-benchmark',phase:'candidate',index:i+1,total:candidates.length,label:cand.label});try{await this.stopAndWait('qwen3tts');const warm=await this.generate('qwen3tts',warmText,{...options,params:cand.params});try{fs.rmSync(warm.path,{force:true});}catch{}onProgress({type:'tts-lab-benchmark',phase:'measure',index:i+1,total:candidates.length,label:cand.label});const audio=await this.generate('qwen3tts',testText,{...options,params:cand.params});const row={id:cand.id,label:cand.label,params:cand.params,rtf:Number(audio.realtimeFactor||0),elapsedMs:Number(audio.elapsedMs||0),durationSec:Number(audio.durationSec||0),cudaPeakAllocatedMb:Number(audio.cudaPeakAllocatedMb||0),cudaPeakReservedMb:Number(audio.cudaPeakReservedMb||0),safe:Number(audio.realtimeFactor||0)>0};results.push(row);try{fs.rmSync(audio.path,{force:true});}catch{}}catch(e){results.push({id:cand.id,label:cand.label,params:cand.params,rtf:999,error:String(e?.message||e),safe:false});}finally{await this.stopAndWait('qwen3tts').catch(()=>{});}}
    const safe=results.filter(x=>x.safe&&x.rtf>0&&x.rtf<999).sort((a,b)=>a.rtf-b.rtf);if(!safe.length)throw new Error('Ninguna configuración de inferencia Qwen3-TTS pudo generar audio correctamente');
    const bestCore=safe[0],chunkCandidates=[360,600,900].filter(n=>n!==Number(bestCore.params.chunkChars)),chunkResults=[];for(let i=0;i<chunkCandidates.length;i++){const chunkChars=chunkCandidates[i],p={...bestCore.params,chunkChars,performanceProfile:`${bestCore.params.dtypeMode}-${bestCore.params.attentionMode}-${chunkChars}`};onProgress({type:'tts-lab-benchmark',phase:'chunk',index:i+1,total:chunkCandidates.length,label:`${p.dtypeMode.toUpperCase()} / ${p.attentionMode} · ${chunkChars}`});try{await this.stopAndWait('qwen3tts');const warm=await this.generate('qwen3tts',warmText,{...options,params:p});try{fs.rmSync(warm.path,{force:true});}catch{}const audio=await this.generate('qwen3tts',testText,{...options,params:p});chunkResults.push({id:`chunk-${chunkChars}`,label:`Chunk ${chunkChars}`,params:p,rtf:Number(audio.realtimeFactor||0),elapsedMs:Number(audio.elapsedMs||0),durationSec:Number(audio.durationSec||0),cudaPeakAllocatedMb:Number(audio.cudaPeakAllocatedMb||0),cudaPeakReservedMb:Number(audio.cudaPeakReservedMb||0),safe:Number(audio.realtimeFactor||0)>0});try{fs.rmSync(audio.path,{force:true});}catch{}}catch(e){chunkResults.push({id:`chunk-${chunkChars}`,label:`Chunk ${chunkChars}`,params:p,rtf:999,error:String(e?.message||e),safe:false});}finally{await this.stopAndWait('qwen3tts').catch(()=>{});}}
    const all=[...results,...chunkResults],winner=all.filter(x=>x.safe&&x.rtf>0&&x.rtf<999).sort((a,b)=>a.rtf-b.rtf)[0],baseline=results.find(x=>x.id==='baseline'),gain=baseline?.rtf>0?Math.max(0,(baseline.rtf-winner.rtf)/baseline.rtf):0;onProgress({type:'tts-lab-benchmark',phase:'done',label:winner.label,rtf:winner.rtf,gain});return{ok:true,engine:'qwen3tts',capabilities:caps,results,chunkResults,recommendedParams:winner.params,recommendedLabel:winner.label,bestRealtimeFactor:Number(winner.rtf.toFixed(3)),baselineRealtimeFactor:Number((baseline?.rtf||0).toFixed(3)),gainPct:Number((gain*100).toFixed(1)),cacheRevision:CACHE_REVISION};}
  async benchmark(id,options={}){const e=this.engine(id);if(!e)throw new Error('Motor TTS desconocido');const text='GEC Automatic News realiza esta prueba para medir el nuevo motor de voz con una locución periodística realista. El sistema compara el tiempo de creación, la estabilidad y el comportamiento mientras la inteligencia artificial local continúa preparando noticias.';const warm=await this.generate(id,text,options),coldStartRealtimeFactor=Number(warm.realtimeFactor||0),warmupElapsedMs=Number(warm.elapsedMs||0);try{fs.rmSync(warm.path,{force:true});}catch{}const runs=[];for(let i=0;i<3;i++){const audio=await this.generate(id,text,options);runs.push({id:`run-${i+1}`,label:`${e.label} · prueba estable ${i+1}`,realtimeFactor:audio.realtimeFactor,medianRealtimeFactor:audio.realtimeFactor,worstRealtimeFactor:audio.realtimeFactor,cpuAverage:0,safe:true,durationSec:audio.durationSec,cudaPeakAllocatedMb:Number(audio.cudaPeakAllocatedMb||0),cudaPeakReservedMb:Number(audio.cudaPeakReservedMb||0),qwenRuntime:audio.qwenRuntime||{}});try{fs.rmSync(audio.path,{force:true});}catch{}}const values=runs.map(x=>Number(x.realtimeFactor)||0).filter(x=>x>0).sort((a,b)=>a-b),mid=Math.floor(values.length/2),median=values.length?(values.length%2?values[mid]:(values[mid-1]+values[mid])/2):0,worst=values.length?Math.max(...values):0,quality=median<=1.3?'excellent':median<=1.6?'good':median<=1.8?'slow':'insufficient';return{ok:true,recommended:'safe_streaming',recommendedLabel:e.label,bestRealtimeFactor:Number(median.toFixed(3)),stableRealtimeFactor:Number(median.toFixed(3)),coldStartRealtimeFactor:Number(coldStartRealtimeFactor.toFixed(3)),warmupElapsedMs,fastestRealtimeFactor:values.length?Number(Math.min(...values).toFixed(3)):0,worstRealtimeFactor:Number(worst.toFixed(3)),performanceQuality:quality,performanceAcceptable:median<=1.8,results:runs,engine:id,cacheRevision:CACHE_REVISION};}
  stop(id=''){const ids=id?[id]:[...this.workers.keys()];for(const key of ids){const state=this.workers.get(key);if(!state)continue;this.workers.delete(key);try{state.child.stdin.write(JSON.stringify({id:`stop-${Date.now()}`,cmd:'stop'})+'\n');}catch{}setTimeout(()=>{try{if(state.child.exitCode==null)state.child.kill();}catch{}},700);}return true;}
  async stopAndWait(id=''){const ids=id?[id]:[...this.workers.keys()],states=ids.map(key=>this.workers.get(key)).filter(Boolean);this.stop(id);const end=Date.now()+5000;while(Date.now()<end&&states.some(s=>s?.child&&s.child.exitCode==null)){await sleep(100);}for(const s of states){try{if(s?.child&&s.child.exitCode==null)s.child.kill();}catch{}}await sleep(100);return true;}
}
module.exports={TTSLabRuntime,ENGINES,CUDA_RUNTIME,CACHE_REVISION};
