'use strict';
const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const release=read('src/services/release0331.js'),hotfixSrc=read('src/services/release0331Hotfix.js'),renderer=read('src/renderer-0331.js'),out=read('src/output-0331.js'),preload=read('src/preload.js'),boot=read('src/bootstrap-0331.js'),pkg=JSON.parse(read('package.json'));
const hotfix=require(path.join(root,'src','services','release0331Hotfix.js'));

assert(boot.includes("require('./bootstrap-0330')"),'0.3.31 must layer on stable 0.3.30');
assert(boot.includes("autoplay-policy")&&boot.includes('no-user-gesture-required'),'Output audio autoplay policy missing');
assert(boot.includes('release0331Hotfix'),'0.3.31 queue identity hotfix not installed');
assert(release.includes("since<every-1)return normal||null"),'exclusive scheduler must wait instead of emitting consecutive exclusives');
assert(release.includes("this.__ec0331SkippedContent&&this.emissionRunning"),'skipped content must retain post-content handling');
assert(release.includes('await this.playAdAfterCanned'),'skipped content must route to the post-content ad');
assert(release.includes('adLocked=true'),'planned ads must expose a locked identity');
assert(release.includes('scheduleSpecificContent'),'manual exact-content scheduling missing');
assert(release.includes('mediaByPath(this.canned,folder,wanted)'),'manual scheduling must resolve the exact selected media path');
assert(hotfixSrc.includes('syncExclusiveIdentity')&&hotfixSrc.includes('normalizeDisplayRows'),'exclusive identity persistence hotfix missing');
const exclusiveItem={id:'e',sourceType:'rss',status:'LISTA',result:{title:'E',isExclusive:true,accessStatus:'SUBSCRIBER_ONLY'}};assert(hotfix.syncExclusiveIdentity(exclusiveItem)===true&&exclusiveItem.isExclusive===true,'exclusive identity must be persisted on the queue item');
assert(renderer.includes('Programar como próximo'),'manual content UI action missing');
assert(renderer.includes('function renderQueueDirect(snapshot)'),'queue must render directly from the automation snapshot');
assert(renderer.includes("const rows=(snapshot?.queue||[]).filter(Boolean)"),'queue renderer must use snapshot.queue as its source of truth');
assert(!renderer.includes('matchCards(snapshot)'),'legacy DOM-to-row reconciliation must not be used');
assert(!renderer.includes('card.dataset.ecQueueId'),'queue must not infer row identity from previously rendered cards');
assert(renderer.includes("exclusive=!!row.isExclusive")&&renderer.includes("<span class=\"queue-exclusive\">EXCLUSIVO</span>"),'exclusive badge must come directly from row identity');
assert(renderer.includes("planned=!!row.planned")&&renderer.includes("rowTypeLabel(row)")&&renderer.includes("queue-item',planned?'planned'"),'planned content/ad rows must be rendered directly');
assert(renderer.includes('__ec0331QueueAudit'),'queue runtime audit marker missing');
assert(renderer.includes("positions:[...box.querySelectorAll('.queue-index')]") ,'queue sequential-position audit missing');
assert(renderer.includes('Sin video de espera configurado'),'standby optional fallback UI missing');
assert(out.includes("video.loop=true"),'standby video must loop');
assert(out.includes("if(a==='stop')setTimeout(()=>showStandby"),'Output stop must return to standby');
assert(out.includes('waitMusicReady')&&out.includes('musicRetryTimer'),'standby music startup retry missing');
assert(out.includes('__ec0331StandbyMusicPlaying'),'standby music playback verification flag missing');
assert(out.includes('transitionDuration'),'standby must reuse configured transition duration');
assert(preload.includes('output:pickStandbyVideo')&&preload.includes('canned:scheduleSpecific'),'0.3.31 bridge APIs missing');
assert(preload.includes('output-0331.js')&&preload.includes('renderer-0331.js'),'0.3.31 renderer/output assets not injected');
const lab=/^2\.0\.0-lab\./.test(pkg.version);
assert(['0.3.31','0.3.32'].includes(pkg.version)||lab,'0.3.31 regression check must run on 0.3.31, 0.3.32 or V2 Lab derivative');
assert(['src/bootstrap-0331.js','src/bootstrap-0332.js'].includes(pkg.main)||(lab&&pkg.main==='src/bootstrap-v2lab.js'),'0.3.31 regression check must preserve the 0.3.31/0.3.32 base or V2 wrapper');
if(lab){const v2=read('src/bootstrap-v2lab.js');assert(v2.includes("require('./bootstrap-0332')"),'V2 Lab must inherit 0.3.32 before TTS extensions');}
console.log('check-0331: OK · cola directa + numeración estable + exclusivas + contenidos/anuncios + música standby');
