const fs=require('fs');
const path=require('path');
const os=require('os');
const {spawnSync}=require('child_process');

let failed=false;
function assert(ok,message){if(!ok)throw new Error(message);}
function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())walk(p);else if(p.endsWith('.js')){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.status!==0){failed=true;console.error(`Syntax error: ${p}`);console.error(r.stderr);}}}}
walk('src');walk('scripts');if(failed)process.exit(1);

try{
  const {parseFeed,parseHtmlLatest}=require('../src/services/rss');
  const sample=`<?xml version="1.0"?><rss><channel><item><title><![CDATA[Noticia de prueba]]></title><link>https://example.com/nota</link><description>Descripción</description><pubDate>Wed, 19 Aug 2026 10:00:00 GMT</pubDate></item></channel></rss>`;
  const items=parseFeed(sample,{id:'test',name:'Test'});assert(items.length===1&&items[0].link==='https://example.com/nota','RSS parser smoke test failed');
  const webItems=parseHtmlLatest('<main><article><h2><a href="https://elcomercio.pe/politica/noticia-de-prueba-con-titular-largo-noticia/">Noticia de prueba con titular suficientemente largo</a></h2><p>Bajada</p><time datetime="2026-08-21T10:00:00-05:00"></time></article></main>',{id:'latest',name:'Últimas'});
  assert(webItems.length===1&&webItems[0].category==='Politica','Latest-news HTML fallback failed');

  const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ec-news-0312-check-'));
  const videos=path.join(tmp,'videos');fs.mkdirSync(videos);for(const name of ['a.mp4','b.mp4','c.webm'])fs.writeFileSync(path.join(videos,name),'x');
  const {CannedManager}=require('../src/services/canned');const contents=new CannedManager(),ads=new CannedManager();assert(contents.list(videos).count===3,'Contents folder scan failed');assert(ads.list(videos).count===3,'Ads folder scan failed');const preview=contents.peek(videos);assert(preview&&contents.pick(videos).name===preview.name,'Canned peek does not match next pick');assert(new Set([ads.pick(videos).name,ads.pick(videos).name,ads.pick(videos).name]).size===3,'Ads random bag repeated early');

  const docsRoot=path.join(tmp,'docs'),politica=path.join(docsRoot,'POLITICA');fs.mkdirSync(politica,{recursive:true});fs.writeFileSync(path.join(politica,'POLITICA.jpg'),'x');fs.writeFileSync(path.join(politica,'reforma.txt'),'TÍTULO: Reforma electoral\nFECHA: 21/08/2026\nEl Congreso debatió una reforma electoral con información de prueba.','utf8');
  const {DocumentLibrary,canonicalCategory}=require('../src/services/documents');const docLib=new DocumentLibrary(),scan=docLib.scan(docsRoot);assert(scan.count===1,'Document folder scan failed');assert(scan.files[0].categoryFromFolder==='POLÍTICA','Document category folder detection failed');assert(scan.files[0].imageSource==='category','Category fallback image was not detected');assert(canonicalCategory('economia')==='ECONOMÍA','Category canonicalization failed');

  const legacyDir=path.join(tmp,'pron');fs.mkdirSync(legacyDir);fs.writeFileSync(path.join(legacyDir,'pronunciation-cache.json'),JSON.stringify({Reuters:'róiters'}),'utf8');
  const {PronunciationNormalizer,LEARNING_SCHEMA}=require('../src/services/pronunciation');const pron=new PronunciationNormalizer({resourcesDir:tmp,dataDir:legacyDir,getSettings:()=>({tts:{pronunciationMaxSeconds:15,pronunciationClaudeVerify:true}})});const normalized=pron.basic('Apple TV informó un avance de 25% en YouTube. S/900 millones, US$25 millones, 30 °C y 80 km/h.');assert(/ápol te uve/i.test(normalized)&&/25 por ciento/i.test(normalized)&&/yutub/i.test(normalized),'Basic pronunciation rules failed');assert(/900 millones de soles/i.test(normalized)&&/25 millones de dólares/i.test(normalized),'Currency pronunciation failed');const candidates=pron.candidates('Élysée recibió a Donald Trump y Emmanuel Macron.');assert(candidates.some(x=>x.term==='Élysée')&&candidates.some(x=>x.term==='Donald Trump'),'Unicode/multiword pronunciation candidates failed');assert(pron.exportLearning().schemaVersion===LEARNING_SCHEMA,'Learning schema export failed');

  const {AutomationEngine}=require('../src/services/automation');
  const dummySettings={automation:{bufferReady:15,queueMax:30,maxAgeHours:6,avoidRepeats:true,recoveryAutonomyMin:8,criticalAutonomyMin:3},documents:{targetSeconds:60},ai:{primary:'claude'},tts:{voice:'ef_dora',speed:1},visual:{pauseSeconds:0},canned:{enabled:true,interval:10,emergency:true,folder:videos,adsFolder:videos,insertAdAfterContent:true}};
  const engine=new AutomationEngine({rss:{loadAll:async()=>({items:[],errors:[],feedStatus:[]})},fetchArticle:async()=>({}),providers:{generate:async()=>({result:{title:'x',script:'x'},attempts:[],metrics:{}}),generateDocument:async()=>({provider:'claude',model:'haiku',result:{title:'Doc',category:'POLÍTICA',summary:'',script:'Texto'},attempts:[],metrics:{elapsedMs:1}})},kokoro:{generate:async()=>({path:'',url:'',durationSec:60}),cleanupAudio:()=>{}},pronunciation:null,canned:contents,ads,history:{has:()=>false,add:()=>{}},getSettings:()=>dummySettings,getFallbackUrl:()=>'',sendAutomaticOutput:()=>true,isOutputReady:()=>true,controlOutput:()=>{}});
  engine.scheduledNewsTotal=10;assert(engine.scheduledProgress(10).due,'Exact scheduled-content multiple not detected');engine.lastScheduledCannedAt=10;assert(!engine.scheduledProgress(10).due&&engine.scheduledProgress(10).nextIn===10,'Scheduled slot served state failed');engine.queue=[{sourceType:'rss',story:{title:'A'},status:'PROCESANDO',audio:{durationSec:60}},{sourceType:'rss',story:{title:'B'},status:'LISTA',audio:{durationSec:60}}];assert(engine.readyItems()[0].story.title==='B','Ready-item selection failed');assert(engine.bufferHealth(dummySettings).minutes===1,'Autonomy calculation failed');const display=engine.displayQueue(dummySettings);assert(display.some(x=>x.sourceType==='content'&&x.status==='PROGRAMADO'),'Planned content missing from unified queue');assert(display.some(x=>x.sourceType==='ad'),'Planned ad missing from unified queue');

  const preload=fs.readFileSync(path.join('src','preload.js'),'utf8');for(const token of ['contextBridge.exposeInMainWorld','documentPickFolder','documentEnqueue','benchmarkTts','cannedPickAdsFolder','exportPronunciationLearning','resetSessionCounters'])assert(preload.includes(token),`Preload bridge missing ${token}`);assert(!/document\.|window\.addEventListener|require\(['"]\.\//.test(preload),'Preload contains sandbox-incompatible wrapper code');
  const main=fs.readFileSync(path.join('src','main.js'),'utf8');for(const token of ['sandbox:true',"preload:path.join(__dirname,'preload.js')",'DocumentLibrary','documents:enqueue','tts:benchmark','syncDocumentWatch','kokoro?.stop'])assert(main.includes(token),`Main integration missing ${token}`);assert(!main.includes("require('./main-v038.js')")&&!main.includes("require('./main-v0310.js')"),'Consolidated main still chains wrappers');

  const control=fs.readFileSync(path.join('src','control.html'),'utf8');for(const id of ['documentList','pickDocumentFolder','generateSelectedDocs','documentWatch','dateColor','queueColorRss','queueColorGenerated','queueColorContent','queueColorAd','queueColorError','feeds','save','processingDetail'])assert(control.includes(`id="${id}"`),`Control UI missing ${id}`);assert(control.includes('Generador de Notas')&&control.includes('Guardar todos los cambios')&&control.includes('Imagen de respaldo'),'Humanized 0.3.12 UI labels missing');assert(!control.includes('data-tab="editor"'),'Legacy Editor navigation still visible');
  const renderer=fs.readFileSync(path.join('src','renderer.js'),'utf8');for(const token of ['dateColor','QUEUE_COLOR_DEFAULT','documentDuration','ttsProfileHint'])assert(renderer.includes(token),`Renderer missing ${token}`);const rendererUi=fs.readFileSync(path.join('src','renderer-ui.js'),'utf8');for(const token of ['refreshDocuments','renderDocuments','sourceTypeName','Ver detalles técnicos','Mejorando pronunciación','Funcionando mediante fuente alternativa'])assert(rendererUi.includes(token),`Renderer UI missing ${token}`);assert(!rendererUi.includes('Etapa: ${x.stage}'),'Technical raw stage leaked into queue');const rendererActions=fs.readFileSync(path.join('src','renderer-actions.js'),'utf8');for(const token of ['documentEnqueue','benchmarkTts','resetQueueColors','dateColor','checkAllFeeds'])assert(rendererActions.includes(token),`Renderer actions missing ${token}`);
  const css=fs.readFileSync(path.join('src','control.css'),'utf8');for(const token of ['feed-list-scroll','document-list','queue-type','--date-color','settings-save'])assert(css.includes(token),`Control CSS missing ${token}`);
  const outputJs=fs.readFileSync(path.join('src','output.js'),'utf8'),outputCss=fs.readFileSync(path.join('src','output.css'),'utf8');assert(outputJs.includes("setProperty('--date-color'")&&outputCss.includes('color:var(--date-color)'),'Independent date color not wired to Output');

  const settingsSrc=fs.readFileSync(path.join('src','services','settings.js'),'utf8');for(const token of ['queueColors','dateColor','documents:','persistentIdleMinutes','recoveryAutonomyMin'])assert(settingsSrc.includes(token),`Settings missing ${token}`);const providersSrc=fs.readFileSync(path.join('src','services','providers.js'),'utf8');for(const token of ['generateDocument','buildDocumentPrompt','DEFAULT_CLAUDE_MODEL','claude-haiku-4-5-20251001'])assert(providersSrc.includes(token),`Document/Claude integration missing ${token}`);assert(!providersSrc.includes("model=models.find(x=>/haiku")&&!providersSrc.includes("models.find(x=>/sonnet"),'Claude test silently switches model');
  const automationSrc=fs.readFileSync(path.join('src','services','automation.js'),'utf8');for(const token of ['enqueueDocument','displayQueue','emissionHistory','bufferHealth','sourceType:\'generated\'','this.queue.find(x=>x.status===\'LISTA\')'])assert(automationSrc.includes(token),`Automation 0.3.12 feature missing ${token}`);
  const kokoroSrc=fs.readFileSync(path.join('src','services','kokoro.js'),'utf8');for(const token of ['ensureWorker','workerCommand','scheduleIdleStop','benchmark','OMP_WAIT_POLICY'])assert(kokoroSrc.includes(token),`Persistent Kokoro feature missing ${token}`);const ttsPy=fs.readFileSync(path.join('scripts','tts.py'),'utf8');for(const token of ['--worker','ECJSON ','load_engine','cmd==\'stop\''])assert(ttsPy.includes(token),`Kokoro worker protocol missing ${token}`);
  const runtimePs=fs.readFileSync(path.join('scripts','prepare-windows-runtime.ps1'),'utf8');assert(runtimePs.includes("$LlamaRelease = 'b10218'"),'llama.cpp runtime is not pinned');assert(!runtimePs.includes('releases/latest'),'Build downloads latest llama.cpp dynamically');
  const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));assert(pkg.version==='0.3.12',`Unexpected package version ${pkg.version}`);assert(pkg.main==='src/main.js',`Unexpected package main ${pkg.main}`);assert(pkg.dependencies?.mammoth,'DOCX dependency missing');
  const py=spawnSync('python',['-m','py_compile',path.join('scripts','tts.py')],{encoding:'utf8'});if(py.error==null)assert(py.status===0,`Python syntax error in tts.py: ${py.stderr}`);
  fs.rmSync(tmp,{recursive:true,force:true});
  console.log('EC 0.3.12 CHECK OK · sintaxis · RSS y respaldo · Generador TXT/DOCX · categorías e imágenes · Cola unificada · autonomía · colores · fecha independiente · bridge sandbox · Kokoro persistente · Claude Haiku fijo');
}catch(e){console.error(e.stack||e);process.exit(1);}
