'use strict';
const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const release=read('src/services/release0331.js'),hotfixSrc=read('src/services/release0331Hotfix.js'),renderer=read('src/renderer-0331.js'),out=read('src/output-0331.js'),preload=read('src/preload.js'),boot=read('src/bootstrap-0331.js'),pkg=JSON.parse(read('package.json'));
const hotfix=require(path.join(root,'src','services','release0331Hotfix.js'));

assert(boot.includes("require('./bootstrap-0330')"),'0.3.31 must layer on stable 0.3.30');
assert(boot.includes("autoplay-policy")&&boot.includes('no-user-gesture-required'),'Output audio autoplay policy missing');
assert(boot.includes('release0331Hotfix'),'0.3.31 queue identity hotfix not installed');
assert(release.includes("since<every-1)return normal||null"),'exclusive scheduler must wait instead of emitting consecutive exclusives');
assert(release.includes("this.__ec0331SkippedContent&&this.emissionRunning"),'skipped content must retain post-content handling');
assert(release.includes('await this.playAdAfterCanned'),'skipped content must route to the post-content ad');
assert(release.includes('adLocked=true'),'planned ads must expose a locked identity');
assert(release.includes('scheduleSpecificContent'),'manual exact-content scheduling missing');
assert(release.includes('mediaByPath(this.canned,folder,wanted)'),'manual scheduling must resolve the exact selected media path');
assert(hotfixSrc.includes('syncExclusiveIdentity')&&hotfixSrc.includes('normalizeDisplayRows'),'exclusive identity persistence hotfix missing');
const exclusiveItem={id:'e',sourceType:'rss',status:'LISTA',result:{title:'E',isExclusive:true,accessStatus:'SUBSCRIBER_ONLY'}};assert(hotfix.syncExclusiveIdentity(exclusiveItem)===true&&exclusiveItem.isExclusive===true,'exclusive identity must be persisted on the queue item');
assert(renderer.includes('Programar como próximo'),'manual content UI action missing');
assert(renderer.includes('matchCards(snapshot)')&&renderer.includes('card.dataset.ecQueueId'),'queue cards must reconcile by stable identity/title');
assert(!renderer.includes('const row=rows[i]'),'renderer must not associate queue cards with snapshot rows by array index');
assert(renderer.includes("qAll('#queue .queue-exclusive').forEach(x=>x.remove())")&&renderer.includes('row.isExclusive'),'exclusive badge must be rebuilt from current row identity on every refresh');
assert(renderer.includes('Sin video de espera configurado'),'standby optional fallback UI missing');
assert(out.includes("video.loop=true"),'standby video must loop');
assert(out.includes("if(a==='stop')setTimeout(()=>showStandby"),'Output stop must return to standby');
assert(out.includes('waitMusicReady')&&out.includes('musicRetryTimer'),'standby music startup retry missing');
assert(out.includes('__ec0331StandbyMusicPlaying'),'standby music playback verification flag missing');
assert(out.includes('transitionDuration'),'standby must reuse configured transition duration');
assert(preload.includes('output:pickStandbyVideo')&&preload.includes('canned:scheduleSpecific'),'0.3.31 bridge APIs missing');
assert(preload.includes('output-0331.js')&&preload.includes('renderer-0331.js'),'0.3.31 renderer/output assets not injected');
const lab=/^2\.0\.0-lab\./.test(pkg.version);assert(pkg.version==='0.3.31'||lab,'package must be 0.3.31 or V2 TTS Lab derivative');assert.strictEqual(pkg.main,lab?'src/bootstrap-v2lab.js':'src/bootstrap-0331.js','entry point must preserve 0.3.31 base or V2 Lab wrapper');
console.log(`check-0331: OK · baseline 0.3.31 preserved${lab?' inside V2 TTS Lab':''}`);
