'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert');
const {getProfileManager}=require('../src/services/profileManager0329');
const {ProfilePackage0329,readPackage}=require('../src/services/profilePackage0329');
let checks=0;const ok=(v,m)=>{checks++;assert.ok(v,m);},eq=(a,b,m)=>{checks++;assert.deepStrictEqual(a,b,m);};
const defaults={rssFeeds:[{id:'legacy',name:'Legacy',url:'https://example.com/rss',enabled:true}],rssPartialClose:{enabled:true,template:'x'},exclusiveClose:{enabled:true,template:'y'},ai:{primary:'local',backup1:'claude',backup2:'none',claudeKeyEnc:'',geminiKeyEnc:'',claudeModel:'fixed',localResourceMode:'safe_streaming',editorialInstructions:''},tts:{voice:'ef_dora',speed:1,resourceMode:'performance',performanceThreads:8,manualPronunciations:{},pronunciationBlockedTerms:[]},visual:{theme:{yellow:'#F7C600'},queueColors:{rss:'#111111',generated:'#222222',content:'#333333',ad:'#444444',exclusive:'#555555',error:'#666666'},fallbackImage:'',output:{format:'16:9',titleColor:'#fff',musicFile:'',verticalVideoBackground:''}},canned:{enabled:false,folder:'',adsFolder:''},documents:{folder:'',processed:{}},automation:{bufferReady:15}};
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gec0329-'));
try{
  fs.writeFileSync(path.join(root,'settings.json'),JSON.stringify({...defaults,rssFeeds:[{id:'old',name:'No migrar perfil',url:'https://old'}],ai:{...defaults.ai,claudeKeyEnc:'SECRET-ENC'},tts:{...defaults.tts,manualPronunciations:{Reuters:{pronunciation:'róiters',needsReplacement:true}}}},null,2));
  const m=getProfileManager(root),initial=m.effectiveSettings(defaults);ok(!m.status().hasProfiles,'inicio sin perfiles');eq(initial.rssFeeds,[],'la configuración de perfil legacy no se convierte en perfil');eq(initial.ai.claudeKeyEnc,'SECRET-ENC','API cifrada legacy migra a global');ok(initial.tts.manualPronunciations.Reuters,'pronunciación manual migra global');eq(initial.visual.queueColors.exclusive,'#555555','color Exclusivos global preservado');
  const ec=m.create({name:'El Comercio',color:'#F7C600',defaults});ok(ec.active,'primer perfil activo');let s=m.effectiveSettings(defaults);s.rssFeeds=[{id:'ec',name:'EC',url:'https://ec.test'}];s.visual.output.titleColor='#ABCDEF';s.ai.primary='claude';s.tts.voice='ef_dora';m.saveEffective(defaults,s);const ecId=ec.id;
  const ge=m.create({name:'Gestión',color:'#22C55E',defaults});ok(!ge.active&&m.activeId()===ecId,'crear un segundo perfil no cambia el activo en caliente');const geId=ge.id;m.activate(geId);let g=m.effectiveSettings(defaults);eq(g.rssFeeds,[],'perfil nuevo limpio');g.rssFeeds=[{id:'ge',name:'Gestión',url:'https://gestion.test'}];g.visual.output.titleColor='#00FF00';g.ai.primary='local';m.saveEffective(defaults,g);
  m.activate(ecId);s=m.effectiveSettings(defaults);eq(s.rssFeeds[0].id,'ec','RSS EC aislado');eq(s.visual.output.titleColor,'#ABCDEF','diseño EC aislado');eq(s.ai.claudeKeyEnc,'SECRET-ENC','API global visible en EC');m.activate(geId);g=m.effectiveSettings(defaults);eq(g.rssFeeds[0].id,'ge','RSS Gestión aislado');eq(g.visual.queueColors.exclusive,'#555555','color de cola compartido globalmente');
  fs.writeFileSync(m.historyFile(geId),JSON.stringify({emitted:[{url:'x'}],automation:{exclusiveHasEmitted:true}}));fs.writeFileSync(m.cycleFile(geId),JSON.stringify({version:2,sources:{a:{played:['x']}}}));const dup=m.duplicate(geId,{name:'Gestión copia',color:'#3B82F6'});eq(JSON.parse(fs.readFileSync(m.historyFile(dup.id))).emitted,[],'duplicado con historial limpio');eq(Object.keys(JSON.parse(fs.readFileSync(m.cycleFile(dup.id))).sources).length,0,'duplicado con ciclos nuevos');ok(m.readProfileSettings(dup.id).canned.contentSourceId!==m.readProfileSettings(geId).canned.contentSourceId,'source IDs nuevos al duplicar');
  assert.throws(()=>m.delete(geId),/perfil activo/i);checks++;m.activate(ecId);m.delete(dup.id);ok(!m.list().some(x=>x.id===dup.id),'eliminación de perfil inactivo');
  const assetDir=m.assetsDir(ecId);fs.mkdirSync(assetDir,{recursive:true});const music=path.join(assetDir,'background-music.mp3');fs.writeFileSync(music,'audio');s=m.effectiveSettings(defaults);s.visual.output.musicFile=music;m.saveEffective(defaults,s);const one=path.join(root,'ec.gecprofile'),packager=new ProfilePackage0329({manager:m,dataDir:root});packager.exportProfile(ecId,one);const parsed=readPackage(one);eq(parsed.manifest.kind,'profile','paquete individual');ok(!JSON.stringify(parsed).includes('SECRET-ENC'),'API key no se exporta en perfil');ok(String(parsed.profiles[0].settings.visual.output.musicFile).startsWith('@profile/assets/'),'asset usa ruta portable');
  fs.writeFileSync(path.join(root,'pronunciation-learning.json'),JSON.stringify({schemaVersion:2,entries:{Reuters:{pronunciation:'róiters'}}}));const all=path.join(root,'all.gecpack');packager.exportAll(all);const parsedAll=readPackage(all);eq(parsedAll.manifest.kind,'all','paquete completo');ok(!JSON.stringify(parsedAll.globalSettings).includes('SECRET-ENC'),'API key no se exporta en gecpack');ok(parsedAll.resources.some(x=>x.path==='global/pronunciation-learning.json'),'pronunciación global incluida');ok(parsedAll.profiles.some(x=>x.history),'historial incluido en gecpack');ok(parsedAll.profiles.some(x=>x.cycle),'ciclos incluidos en gecpack');
  const root2=fs.mkdtempSync(path.join(os.tmpdir(),'gec0329-import-'));try{const m2=getProfileManager(root2),p2=new ProfilePackage0329({manager:m2,dataDir:root2});const r=p2.importFile(one,'keep');ok(r.ok&&m2.status().hasProfiles,'importación de perfil');const imported=m2.effectiveSettings(defaults);ok(imported.visual.output.musicFile.startsWith(m2.assetsDir(m2.activeId())),'asset reubicado al nuevo equipo');ok(fs.existsSync(imported.visual.output.musicFile),'asset importado existe');eq(imported.rssFeeds[0].id,'ec','settings de perfil importados');}finally{fs.rmSync(root2,{recursive:true,force:true});}
  const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),renderer=read('src/renderer-0329.js'),policy=read('src/services/profilePolicy0329.js'),preload=read('src/preload.js'),css=read('src/control-0329.css'),bootstrap=read('src/bootstrap-0329.js'),pkgSource=read('src/services/profilePackage0329.js');
  for(const token of ['Crear perfil nuevo','Cargar perfiles','Detener y cambiar','Forzar cambio','Reiniciar GEC y cambiar','Administrar perfiles','Exportar todos'])ok(renderer.includes(token),`UX perfiles: ${token}`);for(const token of ['stopForSwitch','resetEngineSession','PROFILE_ACTIVE_DELETE','profiles:exportAll','profiles:import','profile-switch-force'])ok(policy.includes(token),`policy perfiles: ${token}`);ok(preload.includes('renderer-0329.js')&&preload.includes('control-0329.css')&&preload.includes('profileExportAll'),'preload 0329');ok(css.includes('flex-wrap')&&css.includes('max-height')&&css.includes('94vw'),'UX responsive');ok(bootstrap.includes('requestSingleInstanceLock'),'single instance lock');ok(pkgSource.includes('voices-ec-custom.bin')&&pkgSource.includes('requiresRestart'),'importación de voces invalida archive y reinicia');
  console.log(`GEC 0.3.29 checks OK · ${checks} verificaciones`);
}finally{fs.rmSync(root,{recursive:true,force:true});}
