'use strict';
(function installOutput0324(){
  if(typeof applyDesign!=='function'||typeof setStoryContent!=='function'||typeof makeStorySnapshot!=='function'){setTimeout(installOutput0324,30);return;}
  if(window.__ecOutput0324)return;window.__ecOutput0324=true;
  let exclusive=document.getElementById('exclusiveBadge');if(!exclusive){exclusive=document.createElement('div');exclusive.id='exclusiveBadge';exclusive.textContent='EXCLUSIVO';const meta=document.getElementById('metaRow');if(meta)meta.appendChild(exclusive);}
  const loadedFonts=new Set();
  function loadCustomFonts(list){for(const x of list||[]){const family=String(x?.family||''),url=String(x?.url||'');if(!family||!url||loadedFonts.has(`${family}|${url}`))continue;loadedFonts.add(`${family}|${url}`);try{const face=new FontFace(family,`url("${url.replace(/"/g,'%22')}")`);face.load().then(f=>document.fonts.add(f)).catch(()=>loadedFonts.delete(`${family}|${url}`));}catch{loadedFonts.delete(`${family}|${url}`);}}}
  const baseApplyDesign=applyDesign;
  applyDesign=function(next={}){baseApplyDesign(next);loadCustomFonts(design.customFonts);const root=document.documentElement.style,set=(k,v)=>root.setProperty(k,v),font=(v,fallback='Arial')=>`"${String(v||fallback).replace(/"/g,'')}\",sans-serif`;set('--title-font-family',font(design.titleFontFamily||design.fontFamily));set('--summary-font-family',font(design.summaryFontFamily||design.fontFamily));set('--category-font-family',font(design.categoryFontFamily||design.fontFamily));set('--date-font-family',font(design.dateFontFamily||design.fontFamily));set('--exclusive-font-family',font(design.exclusiveFontFamily||design.fontFamily));set('--title-font-size',`${Math.max(20,Math.min(120,Number(design.titleFontSize)||70))}px`);set('--summary-font-size',`${Math.max(12,Math.min(72,Number(design.summaryFontSize)||34))}px`);set('--category-font-size',`${Math.max(10,Math.min(48,Number(design.categoryFontSize)||28))}px`);set('--date-font-size',`${Math.max(10,Math.min(48,Number(design.dateFontSize)||27))}px`);set('--exclusive-font-size',`${Math.max(10,Math.min(48,Number(design.exclusiveFontSize)||24))}px`);set('--title-font-weight',Math.max(100,Math.min(900,Number(design.titleFontWeight)||900));set('--summary-font-weight',Math.max(100,Math.min(900,Number(design.summaryFontWeight)||400));set('--category-font-weight',Math.max(100,Math.min(900,Number(design.categoryFontWeight)||900));set('--date-font-weight',Math.max(100,Math.min(900,Number(design.dateFontWeight)||500));set('--exclusive-font-weight',Math.max(100,Math.min(900,Number(design.exclusiveFontWeight)||800));set('--exclusive-color',design.exclusiveTextColor||'#000000');set('--exclusive-bg',design.exclusiveBgColor||'#F7C600');set('--exclusive-border',design.exclusiveBorderColor||design.exclusiveBgColor||'#F7C600');set('--exclusive-border-width',`${Math.max(0,Math.min(8,Number(design.exclusiveBorderWidth)||0))}px`);set('--exclusive-radius',`${Math.max(0,Math.min(30,Number(design.exclusiveRadius)||5))}px`);exclusive.textContent=String(design.exclusiveText||'EXCLUSIVO').slice(0,32);if(design.exclusiveEnabled===false)exclusive.classList.remove('show');};
  transitionEnabled=function(){return design.transitionType!=='none';};
  const baseSetStory=setStoryContent;
  setStoryContent=async function(p){await baseSetStory(p);const show=!!p?.isExclusive&&design.exclusiveEnabled!==false;exclusive.textContent=String(design.exclusiveText||'EXCLUSIVO').slice(0,32);exclusive.classList.toggle('show',show);exclusive.dataset.publisher=String(p?.publisherName||'');};
  const baseSnapshot=makeStorySnapshot;
  makeStorySnapshot=function(){const snap=baseSnapshot();if(!snap)return snap;const meta=snap.querySelector('.snapshot-meta-row');if(meta&&exclusive.classList.contains('show')){const ex=document.createElement('div');ex.className='snapshot-exclusive show';ex.textContent=exclusive.textContent;meta.appendChild(ex);}return snap;};
  try{applyDesign(design);}catch{}
})();