'use strict';
const {contextBridge,ipcRenderer}=require('electron');
const invoke=(channel,...args)=>ipcRenderer.invoke(channel,...args);
const allowedEvents=new Set(['automation:state','automation:itemError','automation:engineError','local:event','pronunciation:event','tts:gpuEvent','output:story','output:control','output:design','output:state']);
let localDownloadActive=false,ttsStatusCache=null,ttsStatusPromise=null,localStatusCache=null,localStatusAt=0,localStatusPromise=null;
function cachedLocalStatus(){const now=Date.now(),ttl=localDownloadActive?1000:0;if(ttl&&localStatusCache&&now-localStatusAt<ttl)return Promise.resolve(localStatusCache);if(localStatusPromise)return localStatusPromise;const task=invoke('local:status').then(r=>{localStatusCache=r;localStatusAt=Date.now();return r;});localStatusPromise=task;return task.finally(()=>{if(localStatusPromise===task)localStatusPromise=null;});}
function cachedTtsStatus(){if(localDownloadActive&&ttsStatusCache)return Promise.resolve(ttsStatusCache);if(ttsStatusPromise)return ttsStatusPromise;const task=invoke('tts:status').then(r=>{ttsStatusCache=r;return r;});ttsStatusPromise=task;return task.finally(()=>{if(ttsStatusPromise===task)ttsStatusPromise=null;});}
function clearTtsCache(){ttsStatusCache=null;ttsStatusPromise=null;}
function injectAsset(tag,attrs){try{const el=document.createElement(tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);document.head.appendChild(el);}catch{}}
window.addEventListener('DOMContentLoaded',()=>{const page=(location.pathname.split('/').pop()||'').toLowerCase();if(page==='control.html'){injectAsset('link',{rel:'stylesheet',href:'control-0324.css'});injectAsset('script',{src:'renderer-0324.js'});injectAsset('script',{src:'renderer-local-model-fix-0324.js'});injectAsset('script',{src:'renderer-image-hydration-0324.js'});}else if(page==='output.html'){injectAsset('link',{rel:'stylesheet',href:'output-0324.css'});injectAsset('script',{src:'output-0324.js'});}}, {once:true});

contextBridge.exposeInMainWorld('ECAPI',{
  getSettings:()=>invoke('settings:get'),saveSettings:s=>invoke('settings:save',s),
  loadRss:()=>invoke('rss:load'),testRss:f=>invoke('rss:test',f),fetchArticle:u=>invoke('article:fetch',u),testProvider:p=>invoke('providers:test',p),generate:(story,article)=>invoke('providers:generate',story,article),
  localStatus:()=>cachedLocalStatus(),downloadLocalModel:()=>invoke('local:downloadModel'),startLocal:()=>invoke('local:start'),stopLocal:()=>invoke('local:stop'),benchmarkLocalAI:settings=>invoke('local:benchmark',settings),
  pronunciationStatus:()=>invoke('pronunciation:status'),downloadPronunciationModel:()=>invoke('pronunciation:downloadModel'),stopPronunciation:()=>invoke('pronunciation:stop'),testPronunciation:()=>invoke('pronunciation:test'),exportPronunciationLearning:()=>invoke('pronunciation:exportLearning'),importPronunciationLearning:()=>invoke('pronunciation:importLearning'),clearPronunciationLearning:()=>invoke('pronunciation:clearLearning'),
  ttsStatus:()=>cachedTtsStatus(),generateTts:text=>invoke('tts:generate',text),benchmarkTts:()=>invoke('tts:benchmark'),gpuTtsStatus:()=>invoke('tts:gpuStatus'),installGpuTts:()=>invoke('tts:gpuInstall'),benchmarkGpuTts:()=>invoke('tts:gpuBenchmark'),useCpuTts:()=>invoke('tts:gpuUseCpu'),
  voicesList:()=>invoke('voices:list'),importVoice:name=>invoke('voices:import',{name}).finally(clearTtsCache),renameVoice:(id,name)=>invoke('voices:rename',{id,name}).finally(clearTtsCache),deleteVoice:id=>invoke('voices:delete',{id}).finally(clearTtsCache),exportVoice:id=>invoke('voices:export',{id}),
  fontsList:()=>invoke('fonts:list'),refreshFonts:()=>invoke('fonts:refresh'),importFont:()=>invoke('fonts:import'),deleteFont:family=>invoke('fonts:delete',family),
  documentPickFolder:()=>invoke('documents:pickFolder'),documentList:()=>invoke('documents:list'),documentEnqueue:(paths,options={},force=false)=>invoke('documents:enqueue',{paths,options,force}),documentResetProcessed:()=>invoke('documents:resetProcessed'),
  pickFallback:()=>invoke('fallback:pick'),pickVerticalVideoBackground:()=>invoke('output:pickVerticalBackground'),clearVerticalVideoBackground:()=>invoke('output:clearVerticalBackground'),pickMusic:()=>invoke('output:pickMusic'),clearMusic:()=>invoke('output:clearMusic'),
  cannedPickFolder:()=>invoke('canned:pickFolder'),cannedList:()=>invoke('canned:list'),cannedPickAdsFolder:()=>invoke('canned:pickAdsFolder'),cannedListAds:()=>invoke('canned:listAds'),cannedLaunchNow:()=>invoke('canned:launchNow'),
  openOutput:()=>invoke('output:open'),closeOutput:()=>invoke('output:close'),outputStatus:()=>invoke('output:status'),sendManualOutput:p=>invoke('output:manualSend',p),controlOutput:a=>ipcRenderer.send('output:control',a),previewOutputDesign:d=>ipcRenderer.send('output:designPreview',d),outputPlayback:e=>ipcRenderer.send('output:playback',e),
  automationStatus:()=>invoke('automation:status'),processingStart:()=>invoke('automation:processingStart'),processingPause:()=>invoke('automation:processingPause'),processingResume:()=>invoke('automation:processingResume'),processingStop:()=>invoke('automation:processingStop'),emissionStart:()=>invoke('automation:emissionStart'),emissionPause:()=>invoke('automation:emissionPause'),emissionResume:()=>invoke('automation:emissionResume'),emissionStop:()=>invoke('automation:emissionStop'),clearQueue:()=>invoke('automation:clearQueue'),resetSessionCounters:()=>invoke('automation:resetCounters'),resetHistory:()=>invoke('history:reset'),notify:p=>ipcRenderer.send('notify',p),
  on:(channel,cb)=>{if(!allowedEvents.has(channel)||typeof cb!=='function')return()=>{};const listener=(_,payload)=>{if(channel==='local:event'){const type=String(payload?.type||'');if(type==='model-download'||type==='download-progress')localDownloadActive=true;else if(type==='model-downloaded'||type==='model-download-error'){localDownloadActive=false;localStatusCache=null;localStatusAt=0;}}cb(payload);};ipcRenderer.on(channel,listener);return()=>ipcRenderer.removeListener(channel,listener);}
});
