'use strict';
(function installGecV2TtsLab(){
  if(window.__gecV2TtsLabUi)return;
  if(!window.ECAPI||typeof settings==='undefined'||!settings||!document.querySelector('#ec27VoiceSlot')){setTimeout(installGecV2TtsLab,120);return;}
  window.__gecV2TtsLabUi=true;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ENGINES={kokoro:'Kokoro',chatterbox:'Chatterbox V3',qwen3tts:'Qwen3-TTS 0.6B'};
  let labStatus=null,busy=false;

  document.title='GEC Automatic News — V2.0 TTS Lab';
  const brand=q('.brand');if(brand&&!q('#v2LabMark')){const m=document.createElement('div');m.id='v2LabMark';m.innerHTML='<b>V2.0</b><span>TTS LAB</span>';brand.insertAdjacentElement('afterend',m);}

  const voiceSlot=q('#ec27VoiceSlot'),voiceCard=voiceSlot.closest('.ec27-card'),voiceBadge=voiceCard?.querySelector('.section-head .mini-pill');
  const engineBox=document.createElement('div');engineBox.id='v2EngineBox';engineBox.innerHTML=`
    <label>Motor de voz<select id="v2TtsEngine"><option value="kokoro">Kokoro</option><option value="chatterbox">Chatterbox V3</option><option value="qwen3tts">Qwen3-TTS 0.6B</option></select></label>
    <div id="v2EngineStatus" class="v2-engine-status">Comprobando motor…</div>`;
  voiceSlot.insertAdjacentElement('afterbegin',engineBox);

  const external=document.createElement('div');external.id='v2ExternalVoice';external.className='v2-external hidden';external.innerHTML=`
    <div class="v2-two"><label><span id="v2ReferenceLabelText">Voz</span><select id="v2ReferenceVoice"></select></label><label>Estilo de locución<select id="v2VoiceStyle"><option value="news">Noticias / Informativo</option><option value="neutral">Neutral</option><option value="expressive">Más expresivo</option></select></label></div>
    <div class="buttons"><button id="v2InstallEngine">Instalar y preparar motor</button><button id="v2TestVoice" class="dark">Probar voz</button></div>
    <div id="v2EngineAction" class="note"></div><audio id="v2VoicePreview" controls></audio>`;
  voiceSlot.appendChild(external);

  const tech=q('#ec27VoiceTech');if(tech&&!q('#v2EngineAdvanced')){const adv=document.createElement('div');adv.id='v2EngineAdvanced';adv.innerHTML=`<div id="v2ChatterboxAdvanced" class="v2-advanced-engine hidden"><h4>Chatterbox</h4><div class="v2-two"><label>Expresividad<input id="v2ChatterExaggeration" type="number" min="0.1" max="1.2" step="0.05"></label><label>CFG / fidelidad<input id="v2ChatterCfg" type="number" min="0" max="1" step="0.05"></label></div></div><div id="v2QwenAdvanced" class="v2-advanced-engine hidden"><h4>Qwen3-TTS</h4><label>Temperatura<input id="v2QwenTemperature" type="number" min="0.2" max="1.4" step="0.05"></label></div>`;tech.insertAdjacentElement('afterbegin',adv);}

  const customSlot=q('#ec27CustomVoiceSlot'),kokoroCustom=customSlot?.firstElementChild||null,customCard=customSlot?.closest('.ec27-card'),customBadge=customCard?.querySelector('.section-head .mini-pill');
  const refPanel=document.createElement('div');refPanel.id='v2ReferenceManager';refPanel.className='hidden';refPanel.innerHTML=`<p class="note">Añade un clip limpio del locutor. Para esta prueba usa WAV o FLAC sin música, reverberación ni efectos.</p><div class="buttons"><button id="v2ImportReference">+ Añadir voz de referencia</button></div><div id="v2ReferenceList" class="v2-reference-list"><div class="empty">No hay voces de referencia.</div></div>`;customSlot?.appendChild(refPanel);

  function currentEngine(){return String(settings?.tts?.engine||'kokoro');}
  function engineLabel(){return ENGINES[currentEngine()]||currentEngine();}
  function engineRow(){return labStatus?.engines?.find(x=>x.id===currentEngine())||null;}
  function setBusy(on,msg=''){busy=!!on;for(const id of ['v2TtsEngine','v2InstallEngine','v2TestVoice','v2ImportReference']){const el=q('#'+id);if(el)el.disabled=busy;}if(msg&&q('#v2EngineAction'))q('#v2EngineAction').textContent=msg;}
  function optimizationText(){const root=q('#ecOptimizer0321');if(!root)return;const p=root.querySelector('.ec-opt-grid p.note');if(p)p.textContent=`Una sola prueba configura ${engineLabel()}, Qwen local y el reparto de CPU/GPU para esta computadora. GEC valida también Qwen + ${engineLabel()} al mismo tiempo y guarda la combinación recomendada.`;const opt=settings?.optimization0321,badge=q('#ecOptimizeState0321');if(badge&&currentEngine()!=='kokoro'&&(!opt||opt.ttsEngine!==currentEngine())){badge.textContent='SIN OPTIMIZAR';badge.className='mini-pill';}}
  function renderStatus(){const engine=currentEngine(),row=engineRow(),box=q('#v2EngineStatus');if(voiceBadge)voiceBadge.textContent=engine==='kokoro'?'KOKORO':engine==='chatterbox'?'CHATTERBOX':'QWEN3-TTS';if(customBadge)customBadge.textContent=engine==='kokoro'?'IMPORTABLES':'REFERENCIAS';if(!box)return;if(engine==='kokoro'){box.innerHTML='<b>Motor incluido ✓</b><span>Kokoro permanece disponible como referencia rápida y estable.</span>';box.className='v2-engine-status ok';return;}if(!row?.installed){box.innerHTML=`<b>${esc(engineLabel())} no instalado</b><span>Instálalo una sola vez en esta computadora antes de usarlo.</span>`;box.className='v2-engine-status warn';}else if(!row?.prepared){box.innerHTML=`<b>${esc(engineLabel())} instalado</b><span>Falta descargar/preparar el modelo para la primera locución.</span>`;box.className='v2-engine-status warn';}else{box.innerHTML=`<b>${esc(engineLabel())} listo ✓</b><span>${row.device?`Motor preparado en ${esc(row.device.toUpperCase())}. `:''}${settings?.optimization0321?.ttsEngine===engine?'Optimizado para esta computadora ✓':'Pendiente de optimización conjunta con Qwen.'}</span>`;box.className='v2-engine-status ok';}}
  function renderVoices(){const sel=q('#v2ReferenceVoice'),list=q('#v2ReferenceList'),voices=labStatus?.voices||[],engine=currentEngine();const label=q('#v2ReferenceLabelText');if(label)label.textContent=engine==='chatterbox'?'Voz':'Voz de referencia';if(sel){const selected=String(settings?.tts?.referenceVoiceId||'');const first=engine==='chatterbox'?'<option value="">Voz predeterminada de Chatterbox</option>':'<option value="">Selecciona una voz de referencia…</option>';sel.innerHTML=first+voices.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');sel.value=voices.some(v=>v.id===selected)?selected:'';}if(list){if(!voices.length){list.innerHTML='<div class="empty">No hay voces de referencia.</div>';}else list.innerHTML=voices.map(v=>`<div class="v2-reference-row" data-id="${esc(v.id)}"><div><b>${esc(v.name)}</b><span>${esc(v.source||'WAV / FLAC')}</span></div><button class="danger compact" data-delete="${esc(v.id)}">Eliminar</button></div>`).join('');list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteReference(b.dataset.delete));}}
  function render(){const engine=currentEngine(),ext=engine!=='kokoro';q('#v2TtsEngine').value=engine;q('#v2ExternalVoice')?.classList.toggle('hidden',!ext);if(kokoroCustom)kokoroCustom.classList.toggle('hidden',ext);q('#v2ReferenceManager')?.classList.toggle('hidden',!ext);const voiceLabel=q('#voice')?.closest('label'),speedLabel=q('#voiceSpeed')?.closest('label');voiceLabel?.classList.toggle('hidden',ext);speedLabel?.classList.toggle('hidden',ext);q('#v2ChatterboxAdvanced')?.classList.toggle('hidden',engine!=='chatterbox');q('#v2QwenAdvanced')?.classList.toggle('hidden',engine!=='qwen3tts');q('#v2VoiceStyle').value=settings?.tts?.style||'news';q('#v2ChatterExaggeration').value=Number(settings?.tts?.engineParams?.chatterbox?.exaggeration??0.42);q('#v2ChatterCfg').value=Number(settings?.tts?.engineParams?.chatterbox?.cfgWeight??0.35);q('#v2QwenTemperature').value=Number(settings?.tts?.engineParams?.qwen3tts?.temperature??0.78);const install=q('#v2InstallEngine');const row=engineRow();if(install)install.textContent=row?.prepared?'Motor preparado ✓':row?.installed?'Preparar modelo':'Instalar y preparar motor';const note=q('#v2EngineAction');if(note&&!busy&&engine==='chatterbox'&&!settings?.tts?.referenceVoiceId)note.textContent='Puedes usar la voz predeterminada de Chatterbox o añadir una voz de referencia para clonación.';renderStatus();renderVoices();optimizationText();}
  async function refreshLab(){try{labStatus=await window.ECAPI.ttsLabStatus();render();}catch(e){if(q('#v2EngineStatus'))q('#v2EngineStatus').textContent=`No se pudo comprobar el laboratorio TTS: ${e.message||e}`;}}
  async function persistVoiceOptions(){settings.tts=settings.tts||{};settings.tts.referenceVoiceId=q('#v2ReferenceVoice')?.value||'';settings.tts.style=q('#v2VoiceStyle')?.value||'news';settings.tts.engineParams=settings.tts.engineParams||{};settings.tts.engineParams.chatterbox={...(settings.tts.engineParams.chatterbox||{}),exaggeration:Number(q('#v2ChatterExaggeration')?.value||0.42),cfgWeight:Number(q('#v2ChatterCfg')?.value||0.35)};settings.tts.engineParams.qwen3tts={...(settings.tts.engineParams.qwen3tts||{}),temperature:Number(q('#v2QwenTemperature')?.value||0.78)};await window.ECAPI.saveSettings(settings);settings=await window.ECAPI.getSettings();}
  async function selectEngine(engine){setBusy(true,'Cambiando motor de voz…');try{const r=await window.ECAPI.ttsLabSelectEngine(engine);settings=r?.settings||await window.ECAPI.getSettings();labStatus=r?.status||await window.ECAPI.ttsLabStatus();render();if(typeof status==='function')status(`Motor de voz: ${engineLabel()}.`);}catch(e){if(typeof status==='function')status(`Motor TTS: ${e.message||e}`);}finally{setBusy(false);}}
  async function installEngine(){const engine=currentEngine();if(engine==='kokoro')return;setBusy(true,`Instalando ${engineLabel()}… La primera instalación puede tardar varios minutos.`);try{const row=engineRow();if(!row?.installed)await window.ECAPI.ttsLabInstall(engine);q('#v2EngineAction').textContent=`Preparando ${engineLabel()} y descargando su modelo…`;await window.ECAPI.ttsLabPrepare(engine);labStatus=await window.ECAPI.ttsLabStatus();render();if(typeof status==='function')status(`${engineLabel()} instalado y preparado.`);}catch(e){q('#v2EngineAction').textContent=`Instalación detenida: ${e.message||e}`;if(typeof status==='function')status(`TTS Lab: ${e.message||e}`);}finally{setBusy(false);}}
  async function testVoice(){const engine=currentEngine();if(engine==='qwen3tts'&&!q('#v2ReferenceVoice')?.value){q('#v2EngineAction').textContent='Qwen3-TTS necesita una voz de referencia antes de generar audio.';return;}setBusy(true,'Generando una prueba de locución…');try{await persistVoiceOptions();const a=await window.ECAPI.generateTts('El Comercio informó esta mañana nuevas medidas que serán evaluadas durante las próximas horas. Las autoridades señalaron que ofrecerán más detalles conforme avance la jornada.');const audio=q('#v2VoicePreview');audio.src=a.url||a.audioUrl||'';audio.load();await audio.play().catch(()=>{});q('#v2EngineAction').textContent=`Prueba lista · ${engineLabel()} · ${Number(a.durationSec||0).toFixed(1)} s de audio · RTF ${Number(a.steadyRealtimeFactor||a.realtimeFactor||0).toFixed(2)}${a.device?` · ${String(a.device).toUpperCase()}`:''}`;}catch(e){q('#v2EngineAction').textContent=`No se pudo generar la prueba: ${e.message||e}`;}finally{setBusy(false);}}
  async function importReference(){setBusy(true,'Añadiendo voz de referencia…');try{const r=await window.ECAPI.ttsLabImportReference();if(!r?.ok)return;labStatus=await window.ECAPI.ttsLabStatus();settings.tts.referenceVoiceId=r.item?.id||settings.tts.referenceVoiceId;await window.ECAPI.saveSettings(settings);render();}catch(e){if(typeof status==='function')status(`Voz de referencia: ${e.message||e}`);}finally{setBusy(false);}}
  async function deleteReference(id){if(!confirm('¿Eliminar esta voz de referencia?'))return;try{await window.ECAPI.ttsLabDeleteReference(id);if(settings.tts.referenceVoiceId===id){settings.tts.referenceVoiceId='';await window.ECAPI.saveSettings(settings);}labStatus=await window.ECAPI.ttsLabStatus();render();}catch(e){if(typeof status==='function')status(`No se pudo eliminar: ${e.message||e}`);}}

  q('#v2TtsEngine').onchange=e=>selectEngine(e.target.value);
  q('#v2InstallEngine').onclick=installEngine;q('#v2TestVoice').onclick=testVoice;q('#v2ImportReference').onclick=importReference;
  for(const id of ['v2ReferenceVoice','v2VoiceStyle','v2ChatterExaggeration','v2ChatterCfg','v2QwenTemperature'])q('#'+id)?.addEventListener('change',()=>persistVoiceOptions().then(()=>render()).catch(e=>status(e.message||e)));
  const observer=new MutationObserver(()=>optimizationText());const opt=q('#ecOptimizer0321');if(opt)observer.observe(opt,{childList:true,subtree:true,characterData:true});
  refreshLab();setInterval(()=>{if(!document.hidden&&q('#tab-audio')?.classList.contains('show'))refreshLab();},10000);
})();
