'use strict';
(function installEc0328(){
  if(window.__ec0328Installed)return;
  if(!window.__ec0327Installed||!window.ECAPI||typeof settings==='undefined'||!settings){setTimeout(installEc0328,140);return;}
  window.__ec0328Installed=true;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=v=>String(v||'').normalize('NFKC').trim().toLocaleLowerCase('es');
  const fmt=v=>{const n=Math.max(0,Math.round(Number(v)||0)),h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;};
  const setStatus=t=>{if(typeof status==='function')status(t);};

  const emissionCard=q('#emissionStart')?.closest('.card');
  if(emissionCard&&!q('#ec28EmissionPanel')){const h=emissionCard.querySelector('.section-head h3');if(h)h.textContent='Control de emisión';const note=emissionCard.querySelector(':scope > .note');if(note)note.textContent='Controla la salida automática en vivo. GEC conserva la lógica de cola, contenidos y anuncios mientras puedes pausar, continuar u omitir el elemento actual.';const panel=document.createElement('div');panel.id='ec28EmissionPanel';panel.className='ec28-player';panel.innerHTML=`<div class="ec28-player-top"><div><span id="ec28NowType" class="mini-pill">SIN EMISIÓN</span><strong id="ec28NowTitle">Nada al aire</strong></div><div id="ec28Time">0:00 / 0:00</div></div><div class="ec28-progress"><div id="ec28ProgressBar"></div></div><div class="ec28-next"><span>Siguiente</span><b id="ec28NextTitle">Esperando cola</b></div>`;const buttons=q('#emissionStart')?.closest('.buttons');buttons?.insertAdjacentElement('beforebegin',panel);const next=document.createElement('button');next.id='ec28EmissionNext';next.className='dark';next.textContent='Siguiente';next.title='Omite el elemento actual y continúa con el siguiente válido de la cola';q('#emissionResume')?.insertAdjacentElement('afterend',next);next.onclick=async()=>{next.disabled=true;try{const s=await window.ECAPI.emissionNext();renderEmissionControl(s);setStatus('Elemento actual omitido; GEC continúa con la cola.');}catch(e){setStatus(`Emisión: ${e.message||e}`);}finally{setTimeout(()=>{next.disabled=false;},250);}};}
  function renderEmissionControl(s){const e=s?.emission||{},p=e.progress||{},current=String(e.currentTitle||''),kind=String(e.currentKind||'none'),source=String(e.currentSourceType||''),labels={news:source==='generated'?'NOTA GENERADA':'NOTICIA',canned:'CONTENIDO',ad:'ANUNCIO',none:'SIN EMISIÓN'},duration=Math.max(0,Number(p.durationSec)||0),at=Math.max(0,Number(p.currentSec)||0),pct=duration?Math.max(0,Math.min(100,at/duration*100)):0;if(q('#ec28NowType'))q('#ec28NowType').textContent=labels[kind]||kind.toUpperCase();if(q('#ec28NowTitle'))q('#ec28NowTitle').textContent=current||((e.running&&!e.paused)?'Esperando el siguiente elemento':'Nada al aire');if(q('#ec28Time'))q('#ec28Time').textContent=`${fmt(at)} / ${duration?fmt(duration):'--:--'}`;if(q('#ec28ProgressBar'))q('#ec28ProgressBar').style.width=`${pct}%`;if(q('#ec28NextTitle'))q('#ec28NextTitle').textContent=e.next?.title||'Esperando cola';const n=q('#ec28EmissionNext');if(n)n.disabled=!e.running||kind==='none';}
  window.ECAPI.on('automation:state',renderEmissionControl);window.ECAPI.automationStatus().then(renderEmissionControl).catch(()=>{});

  ['#ec27ToggleAddPron','#ec27AddPron','#ec27LearningToolbar','#ec27LearningList'].forEach(s=>q(s)?.classList.add('ec27-hidden'));
  const learnCard=q('#ec27LearningSummary')?.closest('.ec27-card');let learning=[],drafts=new Map(),learningBusy=false;
  if(learnCard&&!q('#ec28LearningManager')){const manager=document.createElement('div');manager.id='ec28LearningManager';manager.innerHTML=`<div class="ec28-learning-add"><button id="ec28ToggleAdd" class="dark compact">+ Añadir pronunciación</button><div id="ec28AddBox" class="ec27-add-box ec27-hidden"><div class="ec27-add-grid"><label>Término<input id="ec28NewTerm" placeholder="Ej. streaming"></label><label>Pronunciación para TTS<input id="ec28NewPron" placeholder="Ej. stríming"></label><div class="buttons"><button id="ec28AddSave">Agregar</button></div></div><label class="ec0323-show-nochange"><input id="ec28NewNoChange" type="checkbox"> No requiere cambio</label></div></div><div class="ec27-learning-tools"><input id="ec28LearningSearch" type="search" placeholder="Buscar término o pronunciación…"><label class="ec0323-show-nochange"><input id="ec28ShowNoChange" type="checkbox"> Mostrar reglas sin cambio</label></div><div id="ec28LearningMessage" class="note"></div><div id="ec28LearningList" class="ec27-learning-list"><div class="empty">Cargando aprendizaje…</div></div>`;const buttons=q('#ec27LearningButtons');if(buttons)buttons.insertAdjacentElement('afterend',manager);else learnCard.appendChild(manager);}
  function ensureManual(){settings.tts=settings.tts||{};if(!settings.tts.manualPronunciations||typeof settings.tts.manualPronunciations!=='object')settings.tts.manualPronunciations={};if(!Array.isArray(settings.tts.pronunciationBlockedTerms))settings.tts.pronunciationBlockedTerms=[];}
  function captureDrafts(){qa('#ec28LearningList .ec28-pron-input').forEach(input=>{const term=input.closest('.ec27-row')?.dataset.term;if(!term)return;const k=key(term),d=drafts.get(k)||{term,original:String(input.dataset.original||'')};d.value=input.value;d.dirty=d.value!==d.original;drafts.set(k,d);});}
  function sourceTag(x){if(x.manual)return['Manual','manual'];const s=String(x.source||'IA').toLowerCase();if(s.includes('claude'))return['Claude','claude'];if(s.includes('qwen'))return['Qwen','qwen'];return[String(x.source||'IA'),''];}
  function filteredLearning(){const search=key(q('#ec28LearningSearch')?.value||''),show=q('#ec28ShowNoChange')?.checked===true;return learning.filter(x=>(!search||key(`${x.term} ${x.pronunciation} ${x.source}`).includes(search))&&(show||x.needsReplacement||x.inconsistentEmptyAdjustment)).slice(0,220);}
  function renderLearning(){const box=q('#ec28LearningList');if(!box)return;captureDrafts();const active=document.activeElement?.classList?.contains('ec28-pron-input')?document.activeElement:null,focusKey=active?key(active.closest('.ec27-row')?.dataset.term):'',selStart=active?.selectionStart,selEnd=active?.selectionEnd,rows=filteredLearning();box.replaceChildren();if(!rows.length){box.innerHTML='<div class="empty">No hay reglas que coincidan.</div>';return;}for(const x of rows){const k=key(x.term),stored=String(x.needsReplacement?x.pronunciation:''),draft=drafts.get(k)||{term:x.term,original:stored,value:stored,dirty:false};if(!draft.dirty){draft.original=stored;draft.value=stored;}drafts.set(k,draft);const [tag,cls]=sourceTag(x),row=document.createElement('div');row.className='ec27-row';row.dataset.term=x.term;row.innerHTML=`<div><div class="ec27-term">${esc(x.term)}</div><div class="ec27-meta">${x.inconsistentEmptyAdjustment?'Regla incompleta · se tratará como sin cambio':x.needsReplacement?'Con ajuste fonético':'Sin cambio'}</div></div><div><input class="ec27-input ec28-pron-input" value="${esc(draft.value)}" data-original="${esc(draft.original)}" placeholder="Escribe la corrección…"><div class="ec27-dirty">${draft.dirty?'Cambio sin guardar':''}</div></div><span class="ec27-tag ${cls}">${esc(tag)}</span><span class="ec27-meta ec27-uses">${Number(x.uses||0)} uso${Number(x.uses||0)===1?'':'s'}</span><div class="ec27-actions"><button class="ec28-save" ${draft.dirty?'':'disabled'}>Guardar corrección</button><button class="ec28-delete dark">Eliminar</button></div>`;const input=row.querySelector('.ec28-pron-input'),save=row.querySelector('.ec28-save'),mark=row.querySelector('.ec27-dirty');input.oninput=()=>{const d=drafts.get(k);d.value=input.value;d.dirty=d.value!==d.original;drafts.set(k,d);mark.textContent=d.dirty?'Cambio sin guardar':'';save.disabled=!d.dirty;};save.onclick=()=>saveDraft(x.term).catch(e=>setStatus(`Pronunciación: ${e.message||e}`));row.querySelector('.ec28-delete').onclick=()=>deleteTerm(x.term).catch(e=>setStatus(`Pronunciación: ${e.message||e}`));box.appendChild(row);}if(focusKey){const next=qa('#ec28LearningList .ec27-row').find(r=>key(r.dataset.term)===focusKey)?.querySelector('.ec28-pron-input');if(next){try{next.focus({preventScroll:true});if(Number.isInteger(selStart))next.setSelectionRange(selStart,selEnd);}catch{}}}}
  async function saveManualSettings(){ensureManual();return window.ECAPI.saveSettings({tts:{manualPronunciations:settings.tts.manualPronunciations,pronunciationBlockedTerms:settings.tts.pronunciationBlockedTerms}});}
  async function saveDraft(term){ensureManual();captureDrafts();const k=key(term),d=drafts.get(k);if(!d)return;for(const name of Object.keys(settings.tts.manualPronunciations))if(key(name)===k&&name!==term)delete settings.tts.manualPronunciations[name];settings.tts.pronunciationBlockedTerms=settings.tts.pronunciationBlockedTerms.filter(x=>key(x)!==k);const value=String(d.value||'').trim();settings.tts.manualPronunciations[term]={pronunciation:value,needsReplacement:!!value};await saveManualSettings();d.original=value;d.value=value;d.dirty=false;drafts.set(k,d);setStatus(`Corrección guardada: ${term}${value?` → ${value}`:' → sin cambio'}.`);await refreshLearning();}
  async function deleteTerm(term){if(!confirm(`¿Eliminar la regla de pronunciación para “${term}”?`))return;ensureManual();captureDrafts();const k=key(term);for(const name of Object.keys(settings.tts.manualPronunciations))if(key(name)===k)delete settings.tts.manualPronunciations[name];if(!settings.tts.pronunciationBlockedTerms.some(x=>key(x)===k))settings.tts.pronunciationBlockedTerms.push(term);await saveManualSettings();drafts.delete(k);await refreshLearning();}
  async function refreshLearning(){if(learningBusy)return;learningBusy=true;try{captureDrafts();const p=await window.ECAPI.pronunciationStatus();learning=Array.isArray(p?.learningList)?p.learningList:[];const repl=learning.filter(x=>x.needsReplacement).length,manual=learning.filter(x=>x.manual).length,neg=learning.filter(x=>!x.needsReplacement).length;if(q('#ec27LearningSummary'))q('#ec27LearningSummary').textContent=`${repl} ajustes · ${manual} manuales · ${neg} verificadas`;if(q('#ec28LearningMessage'))q('#ec28LearningMessage').textContent='';renderLearning();}catch(e){if(q('#ec28LearningMessage'))q('#ec28LearningMessage').textContent=`No se pudo actualizar el contador: ${e.message||e}. Tus cambios sin guardar se conservan.`;}finally{learningBusy=false;}}
  q('#ec28LearningSearch')?.addEventListener('input',renderLearning);q('#ec28ShowNoChange')?.addEventListener('change',renderLearning);q('#ec28ToggleAdd')?.addEventListener('click',()=>q('#ec28AddBox')?.classList.toggle('ec27-hidden'));q('#ec28NewNoChange')?.addEventListener('change',e=>{q('#ec28NewPron').disabled=e.target.checked;});q('#ec28AddSave')?.addEventListener('click',async()=>{const term=String(q('#ec28NewTerm').value||'').trim(),noChange=q('#ec28NewNoChange').checked,pron=String(q('#ec28NewPron').value||'').trim();if(!term)return setStatus('Escribe el término que quieres añadir.');if(!noChange&&!pron)return setStatus('Escribe la pronunciación para TTS o marca “No requiere cambio”.');const existing=learning.find(x=>key(x.term)===key(term));if(existing&&!confirm(`“${term}” ya existe. ¿Actualizar su corrección manual?`))return;const canonical=existing?.term||term,k=key(canonical);drafts.set(k,{term:canonical,original:String(existing?.needsReplacement?existing?.pronunciation||'':''),value:noChange?'':pron,dirty:true});await saveDraft(canonical);q('#ec28NewTerm').value='';q('#ec28NewPron').value='';q('#ec28NewNoChange').checked=false;q('#ec28NewPron').disabled=false;q('#ec28AddBox').classList.add('ec27-hidden');});refreshLearning();setInterval(()=>{if(!document.hidden&&q('#tab-audio')?.classList.contains('show'))refreshLearning();},5000);

  const oldSave=q('#ec27SaveAudio');if(oldSave){const btn=oldSave.cloneNode(true);oldSave.replaceWith(btn);btn.onclick=async()=>{btn.disabled=true;const old=btn.textContent;btn.textContent='Guardando…';try{settings.tts=settings.tts||{};if(q('#voice')?.value)settings.tts.voice=q('#voice').value;settings.tts.speed=Math.max(.7,Math.min(1.4,Number(q('#voiceSpeed')?.value)||1));settings.tts.pronunciationClaudeVerify=q('#pronunciationClaudeVerify')?.checked!==false;settings.tts.pronunciationMaxSeconds=Math.max(5,Math.min(30,Number(q('#pronunciationMaxSeconds')?.value)||15));settings.tts.speechNormalizerEnabled=q('#speechNormalizerEnabled')?.checked!==false;settings.tts.initialAttackProtection=q('#initialAttackProtection')?.checked!==false;settings.tts.initialAttackPaddingMs=Math.max(0,Math.min(200,Number(q('#initialAttackPaddingMs')?.value)||70));if(typeof updateDesignFromControls==='function')updateDesignFromControls(false);const r=await window.ECAPI.saveSettings({tts:{...settings.tts},visual:{output:{...(settings.visual?.output||{})}}});if(!r?.ok)throw new Error('El backend no confirmó el guardado');setStatus('Audio y locución guardados correctamente.');btn.textContent='Guardado ✓';setTimeout(()=>{btn.textContent=old;},1200);}catch(e){btn.textContent=old;setStatus(`Audio y locución: ${e.message||e}`);}finally{btn.disabled=false;}};}

  const BASE=['Arial','Segoe UI','Verdana','Georgia','Impact'],IDS=['title','summary','category','date','exclusive'];let fontRepairBusy=false;const baseVariants=[['regular','Regular'],['medium','Medium'],['semibold','Semibold'],['bold','Bold'],['extrabold','Extra Bold'],['black','Black'],['italic','Italic'],['bolditalic','Bold Italic']];
  async function repairFontControls(){if(fontRepairBusy)return;fontRepairBusy=true;try{const r=await window.ECAPI.fontsList(),custom=Array.isArray(r?.custom)?r.custom:[],families=[...new Set([...BASE,...custom.filter(x=>!x.invalid).map(x=>x.family)])];for(const id of IDS){const fam=q(`#ec25-${id}-family`),variant=q(`#ec25-${id}-variant`);if(!fam||!variant)continue;const familyKey=`${id}FontFamily`,wanted=fam.value||settings.visual?.output?.[familyKey]||'Arial',selected=families.includes(wanted)?wanted:'Arial';fam.replaceChildren(...families.map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;}));fam.value=selected;fam.disabled=false;fam.removeAttribute('disabled');fam.style.pointerEvents='auto';if(settings.visual?.output&&!families.includes(settings.visual.output[familyKey]))settings.visual.output[familyKey]='Arial';const rows=BASE.includes(selected)?baseVariants:custom.filter(x=>x.family===selected&&!x.invalid).map(x=>[String(x.variant||'regular'),String(x.variantLabel||x.variant||'Regular')]);const uniq=[];for(const row of rows.length?rows:[['regular','Regular']])if(!uniq.some(x=>x[0]===row[0]))uniq.push(row);const vw=variant.value||settings.visual?.output?.[`${id}FontVariant`]||'regular',vv=uniq.some(x=>x[0]===vw)?vw:(uniq.find(x=>x[0]==='regular')?.[0]||uniq[0][0]);variant.replaceChildren(...uniq.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o;}));variant.value=vv;variant.disabled=false;variant.removeAttribute('disabled');variant.style.pointerEvents='auto';}if(typeof setDesignControls==='function')setDesignControls(settings.visual.output);}catch(e){setStatus(`Tipografías: ${e.message||e}`);}finally{fontRepairBusy=false;}}
  document.addEventListener('click',e=>{if(e.target?.closest?.('#resetDesign,#ec25ImportFont,.ec25-delete-font,.ec26-delete-font'))setTimeout(repairFontControls,180);},true);const designEditor=q('#ec0325DesignEditor');if(designEditor){const observer=new MutationObserver(ms=>{if(fontRepairBusy)return;if(ms.some(m=>m.type==='attributes'&&m.attributeName==='disabled'&&m.target?.matches?.('.ec25-family,.ec25-variant')))setTimeout(repairFontControls,0);});observer.observe(designEditor,{subtree:true,attributes:true,attributeFilter:['disabled']});}setTimeout(repairFontControls,300);

  const oldInstall=q('#ec27InstallLocal');if(oldInstall){const btn=oldInstall.cloneNode(true);oldInstall.replaceWith(btn);async function localStatus(){const [p,l]=await Promise.all([window.ECAPI.pronunciationStatus(),window.ECAPI.localStatus()]),pron=!!p?.runtime&&!!p?.model,main=!!l?.runtime&&!!l?.model,parts=[`Pronunciación ${pron?'✓':p?.model?'runtime faltante':'pendiente'}`,`IA principal ${main?'✓':l?.model?'runtime faltante':'pendiente'}`];if(q('#ec27InstallState'))q('#ec27InstallState').textContent=parts.join(' · ');if(q('#ec27LocalInstallBadge'))q('#ec27LocalInstallBadge').textContent=pron&&main?'LISTA ✓':'INCOMPLETA';btn.textContent=pron&&main?'Verificar IA local completa':'Instalar IA local completa';return{p,l,pron,main};}btn.onclick=async()=>{btn.disabled=true;try{let st=await localStatus();if(!st.p?.runtime||!st.l?.runtime)throw new Error('Falta el runtime local incluido con GEC. Reinstala el Portable antes de descargar modelos.');if(!st.pron){q('#ec27InstallState').textContent='Paso 1 de 2 · Descargando IA de pronunciación…';await window.ECAPI.downloadPronunciationModel();st=await localStatus();if(!st.pron)throw new Error('La IA de pronunciación no superó la verificación de archivo + runtime.');}if(!st.main){q('#ec27InstallState').textContent='Paso 2 de 2 · Descargando IA principal…';await window.ECAPI.downloadLocalModel();st=await localStatus();if(!st.main)throw new Error('La IA principal no superó la verificación de archivo + runtime.');}const wasRunning=!!st.l.running;if(!wasRunning){q('#ec27InstallState').textContent='Verificando arranque de la IA principal…';await window.ECAPI.startLocal();const live=await window.ECAPI.localStatus();if(!live?.running)throw new Error('El modelo está instalado pero la IA principal no logró arrancar.');await window.ECAPI.stopLocal();}q('#ec27InstallState').textContent='IA local completa verificada ✓ · modelos y runtime disponibles.';setStatus('IA local completa verificada.');}catch(e){q('#ec27InstallState').textContent=`Verificación detenida: ${e.message||e}`;}finally{btn.disabled=false;localStatus().catch(()=>{});}};localStatus().catch(()=>{});}

  async function syncNormalizerState(){try{const p=await window.ECAPI.pronunciationStatus(),n=p?.speechNormalizer||{};if(q('#ec27NormalizerBadge'))q('#ec27NormalizerBadge').textContent=n.enabled===false?`Motor ${n.version||'2.1'} · OFF`:`Motor ${n.version||'2.1'} · ON`;if(q('#speechNormalizerEnabled'))q('#speechNormalizerEnabled').checked=n.enabled!==false;}catch{}}
  q('#speechNormalizerEnabled')?.addEventListener('change',()=>setTimeout(syncNormalizerState,350));syncNormalizerState();

  const rec=q('#ec27RecoveryStatus');if(rec){const h=rec.querySelector('h3');if(h)h.textContent='Próximo contenido / selección';if(!q('#ec28CycleInfo')){const box=document.createElement('div');box.id='ec28CycleInfo';box.className='ec28-cycle';box.innerHTML='<strong>Ciclo de contenidos</strong><span>Esperando biblioteca…</span>';rec.appendChild(box);}}
  function renderCycle(s){const c=s?.canned?.cycle,box=q('#ec28CycleInfo');if(!box)return;if(!c?.ok){box.innerHTML='<strong>Ciclo de contenidos</strong><span>Sin biblioteca disponible.</span>';return;}const recent=(c.recent||[]).slice(0,4);box.innerHTML=`<div><strong>Ciclo aleatorio #${Number(c.cycleNumber)||1}</strong><span>${Number(c.emitted)||0} / ${Number(c.total)||0} emitidos · ${Number(c.remaining)||0} restantes${c.complete?' · ciclo completado':''}</span></div>${recent.length?`<div class="ec28-recent"><span>Últimos:</span> ${recent.map(esc).join(' · ')}</div>`:''}`;}
  window.ECAPI.on('automation:state',renderCycle);window.ECAPI.automationStatus().then(renderCycle).catch(()=>{});
})();
