'use strict';

(function installEc0320Ui(){
  if(!window.__ec0319UiInstalled||typeof refreshAutomation!=='function'||typeof renderQueue!=='function'||typeof refreshRuntimeStatus!=='function'||!window.ECAPI){setTimeout(installEc0320Ui,120);return;}
  if(window.__ec0320UiInstalled)return;window.__ec0320UiInstalled=true;

  const style=document.createElement('style');style.textContent=`
    .local-ai-result{margin-top:10px;line-height:1.55}.local-ai-candidate{padding:7px 0;border-top:1px solid rgba(255,255,255,.08)}.local-ai-candidate:first-child{border-top:0}.pipeline-pills{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.queue-meta.waiting-ai{color:#e9c46a}.queue-meta.ai-active{color:#8bd3ff}.attempt-list{margin-top:7px;display:grid;gap:4px}.attempt-row{font-size:12px;opacity:.9}.benchmark-good{color:#8ed99b}.benchmark-warn{color:#f3c969}
  `;document.head.appendChild(style);

  const ttsBtn=$('#optimizeTts');if(ttsBtn)ttsBtn.textContent='Optimizar motor de voz';

  function ensurePipelineUi(){
    const state=$('#processingState');if(state&&!$('#localPipelineState0320')){const pill=document.createElement('span');pill.id='localPipelineState0320';pill.className='mini-pill';pill.textContent='PIPELINE LOCAL · EN ESPERA';state.insertAdjacentElement('afterend',pill);}
    const detail=$('#processingDetail');if(detail&&!$('#pipelineMetrics0320')){const metrics=document.createElement('p');metrics.id='pipelineMetrics0320';metrics.className='note';metrics.textContent='Rendimiento: esperando muestras reales.';detail.insertAdjacentElement('afterend',metrics);}
  }
  ensurePipelineUi();

  function ensureLocalOptimizer(){
    if($('#localOptimizer0320'))return;const progress=$('#downloadProgress'),anchor=progress||$('#localInfo');if(!anchor)return;const box=document.createElement('div');box.id='localOptimizer0320';box.className='subcard top-gap';box.innerHTML=`<div class="section-head"><h3>Optimización de IA local</h3><span id="localTuneState0320" class="mini-pill">SIN OPTIMIZAR</span></div><p class="note">EC probará distintas cargas de Qwen en GPU/Vulkan y CPU, medirá texto corto/medio/largo y validará las mejores configuraciones trabajando junto con Kokoro. Se realiza una vez por computadora o después de cambiar hardware.</p><div class="buttons"><button id="optimizeLocalAi0320">Optimizar IA local</button></div><div id="localBenchmarkResult0320" class="local-ai-result note">Detén temporalmente Preparación y Emisión antes de ejecutar la prueba.</div>`;anchor.insertAdjacentElement('afterend',box);$('#optimizeLocalAi0320').onclick=runLocalBenchmark;refreshLocalTuneBadge();
  }
  ensureLocalOptimizer();

  function refreshLocalTuneBadge(){const badge=$('#localTuneState0320');if(!badge||!settings?.ai)return;const tuned=settings.ai.localAutoTuned&&settings.ai.localTunedConfig;badge.textContent=tuned?'OPTIMIZADA ✓':'SIN OPTIMIZAR';badge.className=`mini-pill ${tuned?'ok':''}`;}
  function seconds(ms){return`${(Number(ms||0)/1000).toFixed(1)} s`;}
  function benchmarkRows(r){return(r.results||[]).map(x=>{if(x.error)return`<div class="local-ai-candidate"><b>${escapeHtml(x.label||x.id)}</b> · DESCARTADA · ${escapeHtml(x.error)}</div>`;const overlap=x.overlap?.voiceRtf?` · Kokoro RTF ${Number(x.overlap.voiceRtf).toFixed(2)}`:'';return`<div class="local-ai-candidate"><b>${escapeHtml(x.label||x.id)}</b> · mediana ${seconds(x.medianElapsedMs)} · peor ${seconds(x.worstElapsedMs)} · ${Number(x.tokensPerSec||0).toFixed(1)} tok/s · CPU ${Number(x.cpuAverage||0).toFixed(0)}% · GPU ${Number(x.gpuAverage||0).toFixed(0)}%${x.vramMaxMb?` · VRAM ${(Number(x.vramMaxMb)/1024).toFixed(1)} GB`:''}${overlap}</div>`;}).join('');}
  async function runLocalBenchmark(){
    const btn=$('#optimizeLocalAi0320'),box=$('#localBenchmarkResult0320');btn.disabled=true;box.textContent='Preparando prueba de Qwen. EC evaluará varias configuraciones y luego comprobará las mejores junto con Kokoro; puede tardar varios minutos…';status('Optimizando IA local para esta computadora…');
    try{
      await saveSettings({quiet:true});const r=await window.ECAPI.benchmarkLocalAI(settings);if(!r?.ok)throw new Error(r?.error||'No se pudo completar la optimización de IA local');
      settings.ai.localResourceMode='tuned';settings.ai.localAutoTuned=true;settings.ai.localTunedConfig=r.recommendedConfig;settings.ai.lastLocalBenchmark=r.summary;await window.ECAPI.saveSettings(settings);settings=await window.ECAPI.getSettings();refreshLocalTuneBadge();const s=r.summary||{},overlap=s.overlap?.voiceRtf?` · Kokoro simultáneo RTF ${Number(s.overlap.voiceRtf).toFixed(2)}`:'';box.innerHTML=`<div class="benchmark-good"><b>Optimización completada ✓</b></div><div><b>Recomendada:</b> ${escapeHtml(r.recommendedLabel||'Configuración optimizada')} · mediana ${seconds(s.medianElapsedMs)} · peor ${seconds(s.worstElapsedMs)} · ${Number(s.tokensPerSec||0).toFixed(1)} tok/s · CPU ${Number(s.cpuAverage||0).toFixed(0)}% · GPU ${Number(s.gpuAverage||0).toFixed(0)}%${s.vramMaxMb?` · VRAM ${(Number(s.vramMaxMb)/1024).toFixed(1)} GB`:''}${overlap}</div>${benchmarkRows(r)}`;status(`IA local optimizada · ${Number(s.tokensPerSec||0).toFixed(1)} tok/s · mediana ${seconds(s.medianElapsedMs)}.`);await refreshRuntimeStatus();
    }catch(e){box.innerHTML=`<span class="benchmark-warn">No se pudo completar la optimización: ${escapeHtml(humanError(e))}</span>`;status(`IA local: ${humanError(e)}`);}finally{btn.disabled=false;}
  }

  const baseRefreshRuntime=refreshRuntimeStatus;
  refreshRuntimeStatus=async function(){await baseRefreshRuntime();try{const st=await window.ECAPI.localStatus(),info=$('#localInfo');if(info&&st?.model){const p=st.profile||{},recent=st.recent||{},mode=st.resourceMode==='tuned'?`Optimizada ✓ · ${p.gpuLayers||0} capas GPU · ${p.threads||0} hilos · batch ${p.batch||0}`:p.label||'IA local lista';const perf=recent.samples?` · últimas ${recent.samples}: ${(recent.averageElapsedMs/1000).toFixed(1)} s prom. · ${Number(recent.averageTokensPerSec||0).toFixed(1)} tok/s`:'';info.textContent=`IA local lista ✓ · ${mode}${perf}`;}refreshLocalTuneBadge();}catch{}}

  function attemptDescription(a={}){const code=String(a.code||''),map={BAD_JSON:'JSON inválido',EMPTY_RESPONSE:'respuesta vacía',BAD_STATUS:'estado inválido',BAD_QUALITY:'calidad inválida',EMPTY_FIELDS:'campos incompletos',FORMAT_GARBAGE:'formato inválido',SOURCE_CTA:'enlace o CTA no permitido',TOO_SHORT:'texto demasiado corto',UNSUPPORTED_NUMBER:'cifra no respaldada',TOO_LONG:'texto demasiado largo',SOURCE_INSUFFICIENT:'fuente insuficiente',COOLDOWN:'límite temporal de uso'};return map[code]||String(a.message||code||'correcto').replace(/^IA:\s*/i,'').slice(0,150);}
  function providerShort(p){return({local:'Qwen',claude:'Claude',gemini:'Gemini'}[p]||providerName(p)||p||'IA');}
  function metricsTech(x){const m=x.metrics||{},parts=[];if(x.provider)parts.push(providerName(x.provider));if(x.model)parts.push(x.model);if(m.inputChars)parts.push(`entrada ${m.inputChars} caracteres`);if(m.promptTokens)parts.push(`prompt editorial ~${m.promptTokens} tokens`);if(m.localPromptTokens)parts.push(`Qwen prompt ${m.localPromptTokens} tok`);if(m.localPromptTokensPerSec)parts.push(`prompt ${Number(m.localPromptTokensPerSec).toFixed(1)} tok/s`);if(m.localOutputTokens)parts.push(`salida ${m.localOutputTokens} tok`);if(m.localTokensPerSec)parts.push(`generación ${Number(m.localTokensPerSec).toFixed(1)} tok/s`);if(m.localGpuLayers!=null&&m.localGpuLayers)parts.push(`${m.localGpuLayers} capas GPU`);if(m.localThreads)parts.push(`${m.localThreads} hilos IA`);if(m.ttsThreads)parts.push(`${m.ttsThreads} hilos de voz`);if(m.ttsRealtimeFactor)parts.push(`RTF ${Number(m.ttsRealtimeFactor).toFixed(2)}×`);if(m.ttsPersistent)parts.push('Kokoro persistente');return parts.join(' · ');}
  function attemptHtml(x){if(!x.attempts?.length)return'';return`<div class="attempt-list">${x.attempts.map((a,i)=>`<div class="attempt-row">${i+1}. ${escapeHtml(providerShort(a.provider))} · ${a.ok&&a.code!=='SOURCE_INSUFFICIENT'?'OK':escapeHtml(attemptDescription(a))}${a.elapsedMs?` · ${(Number(a.elapsedMs)/1000).toFixed(1)} s`:''}</div>`).join('')}</div>`;}

  renderQueue=function(s){
    const box=$('#queue');if(!box)return;const items=s.queue||[],colors={...QUEUE_COLOR_DEFAULT,...(settings?.visual?.queueColors||{})};if(!items.length){box.innerHTML='<div class="empty">Sin actividad</div>';return;}let activeAiAssigned=false;const localPrimary=settings?.ai?.primary==='local';
    box.innerHTML=items.map((x,i)=>{const type=x.sourceType||'rss',color=x.status==='ERROR'?colors.error:(colors[type]||colors.rss),[badge,badgeClass]=badgeInfo(x.status);let human='';let metaClass='';if(x.reason)human=`Omitida · ${x.reason}`;else if(x.planText)human=x.planText;else if(x.status==='PROCESANDO'&&x.stage==='ai'&&localPrimary){if(!activeAiAssigned){activeAiAssigned=true;human='Generando texto con IA local';metaClass='ai-active';}else{human='En espera de IA local';metaClass='waiting-ai';}}else human=humanTiming(x)||stageName(x.stage,x.status);const tech=metricsTech(x),index=(['rss','generated'].includes(type)&&Number(x.sessionSeq)>0)?Number(x.sessionSeq):i+1,classes=`queue-item${x.planned?' planned':''}${x.history?' history':''}`;return`<div class="${classes}" style="--type-color:${escapeHtml(color)}"><div class="queue-main"><span class="queue-index">${index}.</span><div class="queue-text"><div class="queue-headline"><span class="queue-type">${sourceTypeName(type)}</span><span class="queue-title">${escapeHtml(x.title)}</span></div><div class="queue-meta ${metaClass}">${escapeHtml(human)}</div>${x.error?`<div class="queue-meta" style="color:#ffb3b3">${escapeHtml(x.error)}</div>`:''}${tech||x.attempts?.length?`<details class="technical-details"><summary>Ver detalles técnicos</summary>${tech?`<div>${escapeHtml(tech)}</div>`:''}${attemptHtml(x)}</details>`:''}</div><span class="queue-badge ${badgeClass}">${badge}</span></div></div>`;}).join('');
  };

  const baseRefreshAutomation0320=refreshAutomation;
  refreshAutomation=function(s){baseRefreshAutomation0320(s);ensurePipelineUi();const overlap=s?.processing?.pipelineOverlap,pill=$('#localPipelineState0320');if(pill){if(!s?.processing?.running){pill.textContent='PIPELINE LOCAL · DETENIDO';pill.className='mini-pill';}else if(settings?.ai?.primary!=='local'){pill.textContent='PIPELINE · IA REMOTA';pill.className='mini-pill';}else if(overlap?.active){pill.textContent='PIPELINE LOCAL · SOLAPADO ✓';pill.className='mini-pill ok';}else{pill.textContent='PIPELINE LOCAL · SECUENCIAL';pill.className='mini-pill warn';pill.title=overlap?.reason||'';}}
    const rows=(s?.queue||[]).filter(x=>x?.metrics&&['LISTA','PROCESANDO'].includes(x.status)&&['rss','generated'].includes(x.sourceType||'rss')).slice(-10),metrics=$('#pipelineMetrics0320');if(metrics){if(!rows.length)metrics.textContent='Rendimiento: esperando muestras reales.';else{const avg=k=>{const v=rows.map(x=>Number(x.metrics?.[k]||0)).filter(n=>n>0);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0;},text=avg('elapsedMs')/1000,pron=avg('pronunciationElapsedMs')/1000,voice=avg('ttsElapsedMs')/1000,rtfs=rows.map(x=>Number(x.metrics?.ttsRealtimeFactor||0)).filter(n=>n>0).sort((a,b)=>a-b),rtf=rtfs.length?rtfs[Math.floor(rtfs.length/2)]:0,bottleneck=Math.max(text,pron,voice),name=bottleneck===text?'IA local':bottleneck===voice?'voz':'pronunciación';metrics.textContent=`Rendimiento real · Texto ${text.toFixed(1)} s · Pronunciación ${pron.toFixed(1)} s · Voz ${voice.toFixed(1)} s${rtf?` · RTF mediano ${rtf.toFixed(2)}`:''} · Cuello de botella: ${name}`;}}
  };

  refreshRuntimeStatus().catch(()=>{});
})();