'use strict';
(function installEc0326(){
  if(!window.__ec0325Installed||!window.ECAPI||typeof settings==='undefined'||!settings||typeof readDesignControls!=='function'||typeof setDesignControls!=='function'){setTimeout(installEc0326,120);return;}
  if(window.__ec0326Installed)return;window.__ec0326Installed=true;
  const BASE=['Arial','Segoe UI','Verdana','Georgia','Impact'];
  const IDS=['title','summary','category','date','exclusive'];
  const DEFAULT_VARIANTS=[['regular','Regular',400,'normal'],['medium','Medium',500,'normal'],['semibold','Semibold',600,'normal'],['bold','Bold',700,'normal'],['extrabold','Extra Bold',800,'normal'],['black','Black',900,'normal'],['italic','Italic',400,'italic'],['bolditalic','Bold Italic',700,'italic']];
  const q=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let custom=[],ownedFaces=[],syncing=false,lastFamilySignature='';
  const names=()=>[...new Set([...BASE,...custom.filter(x=>!x.invalid).map(x=>x.family)])];
  function descriptor(url=''){try{const u=new URL(url);const weight=Math.max(100,Math.min(900,Number(u.hash.match(/(?:^|&)ecw=(\d+)/)?.[1])||400)),style=decodeURIComponent(u.hash.match(/(?:^|&)ecs=([^&]+)/)?.[1]||'normal');u.hash='';return{url:u.href,weight:String(weight),style:style==='italic'?'italic':'normal'};}catch{return{url:String(url).split('#')[0],weight:'400',style:'normal'};}}
  async function installFaces(){for(const f of ownedFaces)try{document.fonts.delete(f);}catch{}ownedFaces=[];const families=new Set(custom.map(x=>x.family));for(const f of [...document.fonts]){try{if(families.has(String(f.family||'').replace(/^['"]|['"]$/g,'')))document.fonts.delete(f);}catch{}}
    for(const x of custom){if(x.invalid||!x.family||!x.url)continue;const d=descriptor(x.url);try{const face=new FontFace(x.family,`url("${d.url.replace(/"/g,'%22')}")`,{weight:d.weight,style:d.style});await face.load();document.fonts.add(face);ownedFaces.push(face);}catch{}}
  }
  function familySelect(id){return q(`ec25-${id}-family`);}function variantSelect(id){return q(`ec25-${id}-variant`);}
  function syncFamilies(){const list=names(),sig=list.join('|');for(const id of IDS){const sel=familySelect(id);if(!sel)continue;const key=`${id}FontFamily`,current=sel.value||settings.visual?.output?.[key]||'Arial',existing=[...sel.options].map(o=>o.value);if(existing.join('|')!==sig){sel.replaceChildren(...list.map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;}));}sel.value=list.includes(current)?current:'Arial';sel.disabled=false;}lastFamilySignature=sig;}
  function variantsFor(family){if(BASE.includes(family))return DEFAULT_VARIANTS.map(([variant,label,weight,style])=>({variant,label,weight,style}));const rows=custom.filter(x=>x.family===family&&!x.invalid),seen=new Set(),out=[];for(const x of rows.sort((a,b)=>Number(a.weight)-Number(b.weight))){const k=String(x.variant||'regular');if(seen.has(k))continue;seen.add(k);out.push({variant:k,label:x.variantLabel||k,weight:Number(x.weight)||400,style:x.style||'normal'});}return out.length?out:[{variant:'regular',label:'Regular',weight:400,style:'normal'}];}
  function syncVariant(id,preserve=true){const fam=familySelect(id),sel=variantSelect(id);if(!fam||!sel)return;const key=`${id}FontVariant`,wanted=preserve?(sel.value||settings.visual?.output?.[key]||'regular'):(settings.visual?.output?.[key]||'regular'),rows=variantsFor(fam.value),choice=rows.some(x=>x.variant===wanted)?wanted:(rows.find(x=>x.variant==='regular')?.variant||rows[0].variant);sel.replaceChildren(...rows.map(x=>{const o=document.createElement('option');o.value=x.variant;o.textContent=x.label;o.dataset.weight=String(x.weight);o.dataset.style=x.style;return o;}));sel.value=choice;const chosen=rows.find(x=>x.variant===choice)||rows[0];if(settings.visual?.output){settings.visual.output[key]=choice;settings.visual.output[`${id}FontWeight`]=chosen.weight;settings.visual.output[`${id}FontItalic`]=chosen.style==='italic';}}
  function renderManager(){const box=q('ec25CustomFonts');if(!box)return;const groups=[...new Set(custom.map(x=>x.family))].map(family=>({family,rows:custom.filter(x=>x.family===family)}));const html=groups.length?groups.map(g=>`<div class="font-manager-item"><div class="font-manager-name">${esc(g.family)}<small>${g.rows.filter(x=>!x.invalid).map(x=>esc(x.variantLabel||x.variant)).filter((x,i,a)=>a.indexOf(x)===i).join(' · ')||'Fuente no válida'}</small></div><div class="font-actions"><button class="dark compact ec26-delete-font" data-family="${esc(g.family)}">Eliminar</button></div></div>`).join(''):'<div class="note">No hay tipografías importadas.</div>';if(box.dataset.ec26Html===html)return;box.dataset.ec26Html=html;box.innerHTML=html;box.querySelectorAll('.ec26-delete-font').forEach(b=>b.onclick=async()=>{const family=b.dataset.family;if(!confirm(`¿Eliminar la tipografía “${family}” y sus variantes?`))return;try{await window.ECAPI.deleteFont(family);for(const id of IDS){const key=`${id}FontFamily`;if(settings.visual.output[key]===family)settings.visual.output[key]='Arial';}await refreshFonts(true);setDesignControls(settings.visual.output);window.ECAPI.previewOutputDesign(readDesignControls());}catch(e){if(typeof status==='function')status(`Tipografía: ${e.message||e}`);}});}
  async function refreshFonts(resetVariants=false){if(syncing)return;syncing=true;try{const r=await window.ECAPI.fontsList();custom=Array.isArray(r?.custom)?r.custom:[];await installFaces();syncFamilies();for(const id of IDS)syncVariant(id,!resetVariants);if(settings.visual?.output)settings.visual.output.customFonts=custom.map(x=>({family:x.family,url:x.url,variant:x.variant,weight:x.weight,style:x.style}));renderManager();}catch(e){if(typeof status==='function')status(`Tipografías: ${e.message||e}`);}finally{syncing=false;}}
  for(const id of IDS){familySelect(id)?.addEventListener('change',()=>{syncVariant(id,false);try{if(typeof updateDesignFromControls==='function')updateDesignFromControls(true);}catch{}});variantSelect(id)?.addEventListener('change',()=>{const sel=variantSelect(id),o=sel?.selectedOptions?.[0];if(o&&settings.visual?.output){settings.visual.output[`${id}FontWeight`]=Number(o.dataset.weight)||400;settings.visual.output[`${id}FontItalic`]=o.dataset.style==='italic';}});}
  const observerTarget=familySelect('title');if(observerTarget){let timer=null;new MutationObserver(()=>{if(syncing)return;clearTimeout(timer);timer=setTimeout(()=>refreshFonts(false),80);}).observe(observerTarget,{childList:true});}

  function injectSpeechUi(){if(q('speech0326'))return;const anchor=q('pronunciationMaxSeconds')?.closest('.subcard')||q('pronunciationMaxSeconds')?.closest('.card')||q('pronunciationClaudeVerify')?.closest('.card');if(!anchor)return;const box=document.createElement('div');box.id='speech0326';box.className='subcard top-gap';box.innerHTML=`<div class="section-head"><h3>Locución ES-PE</h3><span class="mini-pill">0.3.26</span></div><label class="switch-row"><span><b>Normalización avanzada de locución</b><small>Convierte cifras, monedas, porcentajes, horas y puntuación solo para Kokoro.</small></span><input id="speechNormalizerEnabled" type="checkbox"><span class="switch-ui"></span></label><label class="switch-row"><span><b>Protección del ataque inicial</b><small>Protege la primera vocal o sílaba al comenzar cada noticia.</small></span><input id="initialAttackProtection" type="checkbox"><span class="switch-ui"></span></label><label>Margen inicial para vocales (ms)<input id="initialAttackPaddingMs" type="number" min="0" max="200" step="10"></label><div class="section-head top-gap"><h3>Diagnóstico de locución</h3><button id="refreshSpeechDiag" class="dark compact" type="button">Actualizar</button></div><pre id="speechDiagnostic0326" style="white-space:pre-wrap;max-height:220px;overflow:auto;font-size:12px">Sin diagnósticos todavía.</pre>`;anchor.insertAdjacentElement('afterend',box);setSpeechControls();q('refreshSpeechDiag').onclick=refreshSpeechDiagnostic;}
  function setSpeechControls(){const t=settings.tts||{};if(q('speechNormalizerEnabled'))q('speechNormalizerEnabled').checked=t.speechNormalizerEnabled!==false;if(q('initialAttackProtection'))q('initialAttackProtection').checked=t.initialAttackProtection!==false;if(q('initialAttackPaddingMs'))q('initialAttackPaddingMs').value=String(Math.max(0,Math.min(200,Number(t.initialAttackPaddingMs)||70)));}
  function readSpeechControls(){settings.tts=settings.tts||{};settings.tts.speechNormalizerEnabled=q('speechNormalizerEnabled')?.checked!==false;settings.tts.initialAttackProtection=q('initialAttackProtection')?.checked!==false;settings.tts.initialAttackPaddingMs=Math.max(0,Math.min(200,Number(q('initialAttackPaddingMs')?.value)||70));settings.tts.speechDiagnostics=true;}
  async function refreshSpeechDiagnostic(){const out=q('speechDiagnostic0326');if(!out)return;try{const s=await window.ECAPI.pronunciationStatus(),d=s?.speechNormalizer?.last;if(!d){out.textContent=`Normalizador ${s?.speechNormalizer?.version||''} · sin notas procesadas todavía.`;return;}out.textContent=`Original:\n${d.original}\n\nDespués de pronunciación:\n${d.afterPronunciation}\n\nTexto para Kokoro:\n${d.normalized}\n\nTransformaciones: ${(d.transforms||[]).join(', ')||'ninguna'}${d.fallbackReason?`\nFallback: ${d.fallbackReason}`:''}`;}catch(e){out.textContent=`No se pudo leer el diagnóstico: ${e.message||e}`;}}
  injectSpeechUi();
  if(typeof saveSettings==='function'){const baseSave=saveSettings;saveSettings=async function(options={}){readSpeechControls();return baseSave(options);};}
  refreshFonts(false);refreshSpeechDiagnostic();setInterval(()=>{if(!document.hidden&&q('speech0326'))refreshSpeechDiagnostic();},5000);
})();
