'use strict';

(function installEc0321Ui(){
  if(!window.__ec0320UiInstalled||typeof renderQueue!=='function'||typeof openStory!=='function'||!window.ECAPI){setTimeout(installEc0321Ui,120);return;}
  if(window.__ec0321UiInstalled)return;window.__ec0321UiInstalled=true;

  const style=document.createElement('style');style.textContent=`
    #ecOptimizer0321{margin:0 0 18px}.ec-opt-grid{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center}.ec-opt-summary{line-height:1.55}.ec-opt-progress{margin-top:10px}.ec-opt-progress b{color:#8ed99b}.ec-opt-tech{margin-top:10px}.ec-opt-tech pre{white-space:pre-wrap;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;opacity:.88}.source-quality-line{margin-top:5px;font-size:12px}.source-quality-line.warn{color:#f3c969}.source-quality-line.ok{color:#8ed99b}
    #newsModal0321{position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:32px}#newsModal0321.hidden{display:none}.news-modal-card{width:min(1120px,94vw);max-height:88vh;overflow:hidden;background:#171717;border:1px solid #373737;border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,.55);display:flex;flex-direction:column}.news-modal-head{display:flex;gap:20px;align-items:flex-start;justify-content:space-between;padding:22px 24px 16px;border-bottom:1px solid #333}.news-modal-head h2{margin:0;font-size:24px;line-height:1.25}.news-modal-body{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.55fr);gap:24px;padding:22px 24px 26px;overflow:auto}.news-modal-text{white-space:pre-wrap;line-height:1.58}.news-modal-image{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;background:#101010}.news-modal-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.source-chip{display:inline-flex;align-items:center;border:1px solid #444;border-radius:999px;padding:5px 9px;font-size:12px}.source-chip.warn{border-color:#8a6c1a;color:#f3c969}.source-chip.ok{border-color:#286a35;color:#8ed99b}@media(max-width:900px){.ec-opt-grid,.news-modal-body{grid-template-columns:1fr}#newsModal0321{padding:12px}}
  `;document.head.appendChild(style);

  function hideLegacyOptimizers(){
    const tts=$('#optimizeTts');if(tts)tts.style.display='none';const ttsResult=$('#ttsBenchmarkResult');if(ttsResult)ttsResult.style.display='none';const local=$('#localOptimizer0320');if(local)local.style.display='none';const gpu=document.querySelector('.gpu-advanced-wrap');if(gpu)gpu.style.display='none';
  }
  hideLegacyOptimizers();setTimeout(hideLegacyOptimizers,500);

  function ensureUnifiedOptimizer(){
    if($('#ecOptimizer0321'))return;const tab=$('#tab-settings');if(!tab)return;const card=document.createElement('div');card.id='ecOptimizer0321';card.className='card';card.innerHTML=`<div class="ec-opt-grid"><div><div class="section-head"><h3>Optimización automática de EC</h3><span id="ecOptimizeState0321" class="mini-pill">SIN OPTIMIZAR</span></div><p class="note">Una sola prueba configura el motor de voz seleccionado, Qwen local y el reparto de CPU/GPU para esta computadora. GEC valida ambos motores y guarda el perfil recomendado.</p></div><div><button id="optimizeEc0321">Optimizar EC para esta computadora</button></div></div><div id="ecOptimizeResult0321" class="ec-opt-summary note">Ejecuta esta prueba una vez por computadora o después de cambiar hardware.</div><details id="ecOptimizeTech0321" class="advanced ec-opt-tech hidden"><summary>Ver diagnóstico técnico</summary><pre id="ecOptimizeTechText0321"></pre></details>`;const h=tab.querySelector('h1');if(h)h.insertAdjacentElement('afterend',card);else tab.prepend(card);$('#optimizeEc0321').onclick=runUnifiedOptimization;refreshOptimizationState().catch(()=>{});
  }
  ensureUnifiedOptimizer();

  function gpuIdentity(g={}){const d=g.gpu||g.device||{};return{gpu:String(d.name||g.gpuName||g.name||''),vram:Number(d.vramMb||d.memoryTotalMb||g.vramMb||g.memoryTotalMb||0),driver:String(d.driver||g.driver||'')};}
  function ttsLabel0321(){const e=String(settings?.tts?.engine||'kokoro');if(e==='chatterbox')return'Chatterbox V3 · LatAm';if(e==='qwen3tts')return'Qwen3-TTS 0.6B';return'Kokoro';}
  async function hardwareFingerprint(){const labPromise=window.ECAPI.ttsLabStatus?window.ECAPI.ttsLabStatus().catch(()=>({})):Promise.resolve({}),[local,gpu,lab]=await Promise.all([window.ECAPI.localStatus().catch(()=>({})),window.ECAPI.gpuTtsStatus().catch(()=>({})),labPromise]),engine=String(settings?.tts?.engine||'kokoro'),row=engine!=='kokoro'?(lab?.engines||[]).find(x=>x.id===engine):null,legacy=gpuIdentity(gpu),id=row?.gpuName?{gpu:String(row.gpuName),vram:Number(row.gpuVramMb||0),driver:String(row.torchCuda?'CUDA '+row.torchCuda:'')}:legacy,logical=Number(local?.profile?.logicalCpus||0);return{key:JSON.stringify({logical,gpu:id.gpu,vram:Math.round(id.vram/256)*256,driver:id.driver}),label:[logical?`${logical} hilos CPU`:'CPU',id.gpu||'GPU no identificada',id.vram?`${(id.vram/1024).toFixed(1)} GB VRAM`:'' ].filter(Boolean).join(' · ')}}
  async function refreshOptimizationState(){
    if(!settings)return;
    const badge=$('#ecOptimizeState0321'),result=$('#ecOptimizeResult0321');if(!badge)return;
    const hw=await hardwareFingerprint(),saved=settings.optimization0321;
    let production=null;try{production=window.ECAPI.optimizationV2Status?await window.ECAPI.optimizationV2Status():null;}catch{}
    const profile=production?.profile||settings?.activeOptimizationV2||null,profileFingerprint=String(profile?.fingerprint||'');
    if(profile&&profile.valid!==false&&production?.compatible!==false&&profileFingerprint&&profileFingerprint===hw.key){
      const slow=Number(profile?.tts?.expectedRtf||saved?.voice?.medianRtf||0)>1.8||saved?.voice?.performanceAcceptable===false;
      badge.textContent=slow?'OPTIMIZADA · VOZ LENTA ⚠':'OPTIMIZADA ✓';badge.className=slow?'mini-pill warn':'mini-pill ok';
      if(result&&!result.dataset.live){
        const layers=Number(profile?.localAi?.config?.gpuLayers||0),pipe=String(profile?.pipeline?.mode||'split'),rtf=Number(profile?.tts?.expectedRtf||0),runtimeRunning=!!production?.runtime?.running,match=production?.profileMatch?.ok;
        result.textContent=`Perfil de producción ${profile.version||'lab.23'} guardado · ${profile.hardwareLabel||hw.label} · pipeline ${pipe}${layers?` · ${layers} capas GPU`:''}${rtf?` · RTF esperado ${rtf.toFixed(2)}`:''}${runtimeRunning?` · perfil activo ${match?'✓':'⚠'}`:' · se aplicará al iniciar producción'}.`;
      }
    }else if(saved?.fingerprint&&saved.fingerprint===hw.key){
      badge.textContent='REOPTIMIZAR PRODUCCIÓN';badge.className='mini-pill warn';
      if(result&&!result.dataset.live)result.textContent='Existe una optimización anterior, pero falta el perfil único de producción lab.23. Ejecuta Optimizar GEC una vez para vincular benchmark y producción.';
    }else if(saved?.fingerprint||profile){
      badge.textContent='REOPTIMIZAR';badge.className='mini-pill warn';
      if(result&&!result.dataset.live)result.textContent='EC detectó un cambio de hardware, runtime, motor o modelo. Ejecuta nuevamente la optimización.';
    }else{badge.textContent='SIN OPTIMIZAR';badge.className='mini-pill';}
  }
  const sec=ms=>`${(Number(ms||0)/1000).toFixed(1)} s`;
  function formatTts(r={}){const stable=Number(r.stableRealtimeFactor||r.bestRealtimeFactor||r.realtimeFactor||0),cold=Number(r.coldStartRealtimeFactor||0),runtime=r.qwenRuntime||{},q=Object.keys(runtime).length?runtime:(r.autotune?.recommendedParams||{}),stream=q?.nonStreamingMode===true?' · no-stream':q?.nonStreamingMode===false?' · compat-stream':'',cache=q?.cacheImplementation&&q.cacheImplementation!=='auto'?` · cache ${q.cacheImplementation}`:'',perf=q?.dtypeMode?` · ${String(q.dtypeMode).toUpperCase()} / ${q.attentionMode||'auto'} · chunk ${Number(q.chunkChars)||360}${stream}${cache}`:'',gain=Number(r.autotune?.gainPct||0)>0?` · mejora ${Number(r.autotune.gainPct).toFixed(1)}%`:'',grade=stable<=1.3?'excelente':stable<=1.6?'bueno':stable<=1.8?'aceptable':'lento ⚠';return`${r.recommendedLabel||'CPU optimizada'} · RTF estable ${stable.toFixed(2)} · ${grade}${cold>0?` · arranque en frío ${cold.toFixed(2)}`:''} · peor estable ${Number(r.worstRealtimeFactor||0).toFixed(2)}${perf}${gain}`;}
  function formatLocal(r={}){const s=r.summary||{},voice=ttsLabel0321(),mode=String(s.coexistenceMode||r.coexistence?.mode||''),modeText=mode==='simultaneous'?'escalonado simultáneo':mode==='gpu-swap'?'GPU SWAP':'GPU coordinada';return`${r.recommendedLabel||'Qwen optimizado'} · ${Number(s.tokensPerSec||0).toFixed(1)} tok/s · mediana ${sec(s.medianElapsedMs)} · peor ${sec(s.worstElapsedMs)}${s.overlap?.voiceRtf?` · ${voice} simultáneo RTF ${Number(s.overlap.voiceRtf).toFixed(2)}`:''}${mode?` · ${modeText}`:''}`;}
  let optimizerStartedAt=0;
  function optimizerElapsed(){return optimizerStartedAt?Math.max(0,Math.round((Date.now()-optimizerStartedAt)/1000)):0;}
  window.ECAPI.on('tts-lab:event',e=>{const box=$('#ecOptimizeResult0321');if(!box?.dataset.live||!e||String(e.type||'')!=='tts-lab-benchmark')return;const elapsed=optimizerElapsed(),phase=String(e.phase||'');if(phase==='candidate')box.innerHTML=`<b>1/3 · Qwen3-TTS LAB.23 · sampling ${Number(e.index)||'?'} / ${Number(e.total)||'?'}.</b> ${escapeHtml(e.label||'Midiendo')} · ${elapsed} s`;else if(phase==='measure')box.innerHTML=`<b>1/3 · LAB.23 · sampling · repetición ${Number(e.repeatIndex)||'?'} / ${Number(e.repeatTotal)||5}.</b> ${escapeHtml(e.label||'Configuración')} · ${elapsed} s`;else if(phase==='batch')box.innerHTML=`<b>1/3 · LAB.23 · batching ${Number(e.index)||'?'} / ${Number(e.total)||'?'}.</b> ${escapeHtml(e.label||'')} · ${elapsed} s`;else if(phase==='batch-run')box.innerHTML=`<b>1/3 · LAB.23 · ${escapeHtml(e.label||'Batch')} · repetición ${Number(e.repeatIndex)||'?'} / ${Number(e.repeatTotal)||2}.</b> ${elapsed} s`;else if(phase==='done')box.innerHTML=`<b>1/3 · Perfil de voz elegido.</b> ${escapeHtml(e.label||'')} · RTF single ${Number(e.rtf||0).toFixed(2)} · mejora sampling ${Number((e.gain||0)*100).toFixed(1)}% · mejora batch ${Number((e.batchGain||0)*100).toFixed(1)}%`;});
  window.ECAPI.on('local:event',e=>{const box=$('#ecOptimizeResult0321');if(!box?.dataset.live||!e||!String(e.type||'').startsWith('local-ai-benchmark'))return;const elapsed=optimizerElapsed(),phase=String(e.phase||'');if(phase==='candidate')box.innerHTML=`<b>2/3 · Qwen local (texto) · configuración ${Number(e.index)||'?'} / ${Number(e.total)||'?'}.</b> ${escapeHtml(e.label||'Midiendo configuración')} · ${elapsed} s transcurridos`;else if(phase==='warmup')box.innerHTML=`<b>2/3 · Qwen local (texto) · ${escapeHtml(e.label||'Configuración')}.</b> Calentamiento · ${elapsed} s`;else if(phase==='case')box.innerHTML=`<b>2/3 · Qwen local (texto) · ${escapeHtml(e.label||'Configuración')} · prueba ${Number(e.index)||'?'} / ${Number(e.total)||3}.</b> ${escapeHtml(e.caseLabel||e.caseId||'Generación')} · ${elapsed} s`;else if(phase==='overlap')box.innerHTML=`<b>2/3 · Validando Qwen local (texto) + ${escapeHtml(ttsLabel0321())} (voz)…</b> ${escapeHtml(e.label||'')} · ${elapsed} s`;});

  async function runUnifiedOptimization(){
    const btn=$('#optimizeEc0321'),box=$('#ecOptimizeResult0321'),tech=$('#ecOptimizeTech0321'),techText=$('#ecOptimizeTechText0321');if(automationState?.processing?.running||automationState?.emission?.running){box.textContent='Detén temporalmente Preparación y Emisión antes de optimizar EC.';return;}btn.disabled=true;box.dataset.live='1';optimizerStartedAt=Date.now();tech.classList.add('hidden');let ttsResult=null,localResult=null,gpuNote='';
    try{
      const localStatus=await window.ECAPI.localStatus(),chain=[settings?.ai?.primary,settings?.ai?.backup1,settings?.ai?.backup2].filter(Boolean),usesLocal=chain.includes('local');if(usesLocal&&!localStatus?.model)throw new Error('La IA local está configurada pero el modelo Qwen aún no está descargado. Descárgalo antes de optimizar EC.');
      if(usesLocal&&window.ECAPI.stopLocal){box.innerHTML='<b>1/3 · Preparando prueba limpia de voz…</b> Liberando Qwen local y la VRAM antes de medir el TTS.';status('Optimizando EC · liberando IA local…');await window.ECAPI.stopLocal();await new Promise(r=>setTimeout(r,700));}
      box.innerHTML=`<b>1/3 · Optimizando motor de voz…</b> GEC está midiendo ${escapeHtml(ttsLabel0321())} con la GPU libre.`;status('Optimizando EC · motor de voz…');await window.ECAPI.saveSettings(settings);settings=await window.ECAPI.getSettings();const selectedTtsEngine=String(settings?.tts?.engine||'kokoro');let qwenPerf=null;if(selectedTtsEngine==='qwen3tts'){box.innerHTML='<b>1/3 · Validando Qwen3-TTS (voz)…</b> Comprobando el modelo seleccionado y reparando componentes compartidos si hace falta.';await window.ECAPI.ttsLabValidateSelected();qwenPerf=await window.ECAPI.ttsLabBenchmarkPerformance();if(!qwenPerf?.ok)throw new Error(qwenPerf?.error||'No se pudo encontrar una configuración de inferencia estable para Qwen3-TTS');settings=await window.ECAPI.getSettings();settings.tts=settings.tts||{};settings.tts.engineParams=settings.tts.engineParams||{};settings.tts.engineParams.qwen3tts={...(settings.tts.engineParams.qwen3tts||{}),...(qwenPerf.recommendedParams||{})};await window.ECAPI.saveSettings(settings);settings=await window.ECAPI.getSettings();await window.ECAPI.ttsLabPrepare('qwen3tts');box.innerHTML=`<b>1/3 · Qwen3-TTS LAB.23 listo.</b> ${escapeHtml(qwenPerf.recommendedLabel||'Perfil elegido')} · RTF single ${Number(qwenPerf.bestRealtimeFactor||0).toFixed(2)} · RTF efectivo batch ${Number(qwenPerf.batchEffectiveRealtimeFactor||qwenPerf.bestRealtimeFactor||0).toFixed(2)} · midiendo estabilidad final…`;}ttsResult=await window.ECAPI.benchmarkTts();if(qwenPerf)ttsResult.autotune=qwenPerf;if(!ttsResult?.ok)throw new Error(ttsResult?.error||'No se pudo optimizar el motor de voz');settings=await window.ECAPI.getSettings();
      if(usesLocal){box.innerHTML=`<b>2/3 · Voz lista.</b> ${escapeHtml(formatTts(ttsResult))}<br>Liberando la GPU de la voz antes de medir Qwen…`;status('Optimizando EC · liberando GPU…');if(String(settings?.tts?.engine||'kokoro')!=='kokoro'&&window.ECAPI.ttsLabStop)await window.ECAPI.ttsLabStop();box.innerHTML=`<b>2/3 · Voz lista.</b> ${escapeHtml(formatTts(ttsResult))}<br>Ahora GEC optimiza Qwen local (texto) y valida Qwen local + ${escapeHtml(ttsLabel0321())} (voz)…`;status('Optimizando EC · IA local…');localResult=await window.ECAPI.benchmarkLocalAI(settings);if(!localResult?.ok)throw new Error(localResult?.error||'No se pudo optimizar la IA local');settings.ai.localResourceMode='tuned';settings.ai.localAutoTuned=true;settings.ai.localTunedConfig=localResult.recommendedConfig;settings.ai.lastLocalBenchmark=localResult.summary;const engine=String(settings?.tts?.engine||'kokoro'),mode=String(localResult?.summary?.coexistenceMode||localResult?.coexistence?.mode||'');if(engine==='kokoro')gpuNote='Kokoro permanece en CPU para reservar GPU/VRAM a Qwen local.';else if(mode==='simultaneous')gpuNote='Modo de pipeline: Escalonado simultáneo · Qwen local (texto) + '+ttsLabel0321()+' (voz).';else if(mode==='gpu-swap')gpuNote='Modo de pipeline: GPU SWAP · Qwen local (texto) y '+ttsLabel0321()+' (voz) liberan y recuperan la GPU por turnos para proteger la VRAM.';else gpuNote='Modo de pipeline: Escalonado · GPU coordinada · Qwen local (texto) y '+ttsLabel0321()+' (voz) se turnan la carga pesada.';}else{gpuNote='IA local no está en la cadena de proveedores; GEC optimizó '+ttsLabel0321()+' sin coordinación con Qwen.';}
      box.innerHTML='<b>3/3 · Guardando perfil de esta computadora…</b>';const hw=await hardwareFingerprint(),summary=`Voz ${formatTts(ttsResult)}${localResult?` · IA local ${formatLocal(localResult)}`:''}`;settings.optimization0321={version:'2.0-lab.25',ttsEngine:String(settings?.tts?.engine||'kokoro'),ttsVariant:String(settings?.tts?.engine||'kokoro')==='chatterbox'?'latam':'',at:new Date().toISOString(),fingerprint:hw.key,hardwareLabel:hw.label,summary,voice:{recommendedLabel:ttsResult.recommendedLabel||'',medianRtf:Number(ttsResult.stableRealtimeFactor||ttsResult.bestRealtimeFactor||0),worstRtf:Number(ttsResult.worstRealtimeFactor||0),performanceQuality:String(ttsResult.performanceQuality||''),performanceAcceptable:ttsResult.performanceAcceptable!==false,qwenRuntime:ttsResult.qwenRuntime||{},autotune:qwenPerf?{baselineRealtimeFactor:Number(qwenPerf.baselineRealtimeFactor||0),bestRealtimeFactor:Number(qwenPerf.bestRealtimeFactor||0),gainPct:Number(qwenPerf.gainPct||0),batchBaselineRealtimeFactor:Number(qwenPerf.batchBaselineRealtimeFactor||0),batchEffectiveRealtimeFactor:Number(qwenPerf.batchEffectiveRealtimeFactor||0),batchGainPct:Number(qwenPerf.batchGainPct||0),recommendedLabel:qwenPerf.recommendedLabel||''}:null},local:localResult?.summary||null};await window.ECAPI.saveSettings(settings);let productionProfile=null;if(window.ECAPI.optimizationV2Commit){productionProfile=await window.ECAPI.optimizationV2Commit({fingerprint:hw.key,hardwareLabel:hw.label,localResult,ttsResult,qwenPerf,pipelineMode:String(localResult?.summary?.coexistenceMode||localResult?.coexistence?.mode||''),validated:true});}settings=await window.ECAPI.getSettings();const slowVoice=ttsResult.performanceAcceptable===false;box.innerHTML=`<div class="${slowVoice?'benchmark-warn':'benchmark-good'}"><b>${slowVoice?'Optimización completada · voz todavía lenta ⚠':'EC optimizado para esta computadora ✓'}</b></div><div><b>Voz:</b> ${escapeHtml(formatTts(ttsResult))}</div>${localResult?`<div><b>IA local:</b> ${escapeHtml(formatLocal(localResult))}</div>`:''}<div><b>Hardware:</b> ${escapeHtml(hw.label)}</div><div>${escapeHtml(gpuNote)}</div>${productionProfile?.profile?`<div><b>Perfil de producción:</b> ${escapeHtml(productionProfile.profile.version||'lab.23')} · ${escapeHtml(productionProfile.profile.pipeline?.mode||'')} · ${Number(productionProfile.profile.localAi?.config?.gpuLayers||0)} capas GPU · consistencia de voz ${escapeHtml(productionProfile.profile.voiceConsistency?.mode||'default')}.</div>`:''}<div class="note">Benchmark y producción quedan vinculados al mismo perfil. Repite la optimización solo si cambias hardware, motor o modelo.</div>`;
      const tRows=(ttsResult.results||[]).map(x=>`${x.label||x.id}: ${x.error?`DESCARTADA · ${x.error}`:`RTF mediana ${Number(x.medianRealtimeFactor||x.realtimeFactor||0).toFixed(2)} · peor ${Number(x.worstRealtimeFactor||0).toFixed(2)} · CPU ${Number(x.cpuAverage||0).toFixed(0)}%`}`),lRows=(localResult?.results||[]).map(x=>`${x.label||x.id}: ${x.error?`DESCARTADA · ${x.error}`:`${Number(x.tokensPerSec||0).toFixed(1)} tok/s · mediana ${sec(x.medianElapsedMs)} · peor ${sec(x.worstElapsedMs)} · CPU ${Number(x.cpuAverage||0).toFixed(0)}% · GPU ${Number(x.gpuAverage||0).toFixed(0)}% · VRAM ${x.vramMaxMb?(Number(x.vramMaxMb)/1024).toFixed(1):'0'} GB`}`);
      const perfRow=x=>{const g=x.gpuTelemetry||{},st=x.stageTimings||{},p=x.params||{},med=Number(x.medianRealtimeFactor||x.rtf||0),p25=Number(x.p25RealtimeFactor||0),p75=Number(x.p75RealtimeFactor||0),worst=Number(x.worstRealtimeFactor||0),n=Number(x.runCount||0),head=Number(x.vramHeadroomMb||0);return`${x.label||x.id}: ${x.error?`DESCARTADA · ${x.error}`:`RTF mediana ${med.toFixed(2)} · p25/p75 ${p25.toFixed(2)}/${p75.toFixed(2)} · peor ${worst.toFixed(2)} · N=${n} · síntesis ${Number(x.medianSynthesisRtf||x.profileSynthesisRtf||0).toFixed(2)} · GPU ${Number(g.gpu_util_avg_pct||0).toFixed(0)}%/${Number(g.gpu_util_max_pct||0).toFixed(0)}% · potencia ${Number(g.power_avg_w||0).toFixed(0)}/${Number(g.power_max_w||0).toFixed(0)} W · VRAM ${g.vram_max_mb?(Number(g.vram_max_mb)/1024).toFixed(1):'0'} GB${head?` · margen ${(head/1024).toFixed(1)} GB`:''} · frames ${Number(st.talker_output_frames||x.talkerStepsMedian||0).toFixed(0)} · predictor ${Number(st.code_predictor_steps||x.codePredictorStepsMedian||0).toFixed(0)} pasos / ${Number(st.code_predictor_calls||0).toFixed(0)} llamadas · ${Number(st.code_predictor_ms_per_step||0).toFixed(2)} ms/paso · hidden ${p.predictorHiddenStates===false?'OFF':'ON'} · subtalker ${p.subtalkerDoSample===false?'greedy':`sample top-k ${Number(p.subtalkerTopK||50)}`} · batch B${Number(p.batchSize||1)} · comparable ${x.comparable===false?'NO':'sí'}`}`;};
      const perfRows=(qwenPerf?.results||[]).map(perfRow),batchRows=(qwenPerf?.batchResults||[]).map(perfRow),diag=qwenPerf?.diagnostic||{},dg=diag.gpuTelemetry||{},ds=diag.stageTimings||{},db=diag.batchStageTimings||{},diagText=qwenPerf?`DIAGNÓSTICO GANADOR LAB.23
Sampling: ${diag.samplingConfirmed?'confirmado ✓':'baseline conservado'} · ganancia ${Number(diag.samplingGainPct||0).toFixed(1)}% · hidden predictor ${diag.predictorHiddenStates===false?'OFF':'ON'} · subtalker ${diag.subtalkerDoSample===false?'greedy':`sampling top-k ${Number(diag.subtalkerTopK||50)}`}
Batching: B${Number(diag.batchSize||1)} · ${diag.batchConfirmed?'confirmado ✓':'B1 conservado'} · ganancia throughput ${Number(diag.batchGainPct||0).toFixed(1)}% · RTF efectivo ${Number(diag.batchEffectiveRtf||0).toFixed(2)}
Clasificación single: ${diag.bottleneck||'—'} · GPU promedio ${Number(diag.gpuUtilAvgPct||0).toFixed(0)}% · potencia promedio ${Number(diag.powerAvgW||0).toFixed(0)} W · autoregresivo ${Number(diag.autoregressiveSharePct||0).toFixed(1)}%
RTF single: e2e ${Number(diag.rtfE2E||0).toFixed(2)} · síntesis ${Number(diag.rtfSynthesis||0).toFixed(2)}
Pasos: frames talker ${Number(diag.talkerFrames||diag.talkerSteps||0).toFixed(0)} · predictor ${Number(diag.codePredictorSteps||0).toFixed(0)} en ${Number(diag.codePredictorCalls||0).toFixed(0)} llamadas · ${Number(diag.codePredictorMsPerStep||0).toFixed(2)} ms/paso · K=${Number(diag.numCodeGroups||16)}
Batch GPU: ${Number(diag.batchGpuUtilAvgPct||0).toFixed(0)}% prom · ${Number(diag.batchGpuUtilMaxPct||0).toFixed(0)}% pico · VRAM ${diag.batchVramPeakMb?(Number(diag.batchVramPeakMb)/1024).toFixed(1):'0'} GB · margen ${diag.batchVramHeadroomMb?(Number(diag.batchVramHeadroomMb)/1024).toFixed(1):'0'} GB
Etapas single: autoregresivo ${sec(ds.autoregressive_ms)} · predictor ${sec(ds.code_predictor_ms)} · decoder ${sec(ds.decode_ms)} · wrapper/CPU ${sec(ds.wrapper_overhead_ms)}
Etapas batch: autoregresivo ${sec(db.autoregressive_ms)} · predictor ${sec(db.code_predictor_ms)} · decoder ${sec(db.decode_ms)}`:'';
      techText.textContent=[`VOZ ESTABLE\n${tRows.join('\n')}`,perfRows.length?`QWEN3-TTS LAB.23 · SAMPLING (N=5)\n${perfRows.join('\n')}`:'',batchRows.length?`QWEN3-TTS LAB.23 · BATCHING (N=2 + perfil)\n${batchRows.join('\n')}`:'',diagText,localResult?`IA LOCAL\n${lRows.join('\n')}`:'',gpuNote].filter(Boolean).join('\n\n');tech.classList.remove('hidden');window.dispatchEvent(new CustomEvent('gec:settings-updated',{detail:{reason:'optimization'}}));await refreshOptimizationState();await refreshRuntimeStatus();status(ttsResult.performanceAcceptable===false?'Optimización completada; Qwen3-TTS sigue por encima del objetivo de velocidad.':'EC optimizado para esta computadora.');
    }catch(e){box.innerHTML=`<span class="benchmark-warn"><b>Optimización incompleta:</b> ${escapeHtml(humanError(e))}</span>`;status(`Optimización EC: ${humanError(e)}`);}finally{try{await window.ECAPI.ttsLabStop?.();}catch{}try{await window.ECAPI.stopLocal?.();}catch{}delete box.dataset.live;optimizerStartedAt=0;btn.disabled=false;}
  }

  function ensureNewsModal(){if($('#newsModal0321'))return $('#newsModal0321');const overlay=document.createElement('div');overlay.id='newsModal0321';overlay.className='hidden';overlay.innerHTML=`<div class="news-modal-card" role="dialog" aria-modal="true"><div class="news-modal-head"><div><h2 id="newsModalTitle0321">Noticia</h2><div id="newsModalMeta0321" class="news-modal-meta"></div></div><button id="newsModalClose0321" class="dark compact">Cerrar</button></div><div class="news-modal-body"><div><div id="newsModalBody0321" class="news-modal-text"></div></div><div><img id="newsModalImage0321" class="news-modal-image" alt=""><div id="newsModalSourceQuality0321" class="source-chip top-gap"></div><div class="buttons top-gap"><a id="newsModalSource0321" class="news-source-link" target="_blank" rel="noreferrer">Abrir fuente original</a></div></div></div></div>`;document.body.appendChild(overlay);const close=()=>overlay.classList.add('hidden');$('#newsModalClose0321').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.classList.contains('hidden'))close();});return overlay;}
  ensureNewsModal();const oldViewer=$('#newsViewer0319');if(oldViewer)oldViewer.classList.add('hidden');
  openStory=async function(s){
    currentStory=s;status('Cargando noticia…');let article=null;try{article=await window.ECAPI.fetchArticle(s.link);}catch{article={title:s.title,description:s.description,body:s.description,image:s.image||'',sourceChars:String(s.description||'').length,extractionMode:'rss',extractionWarning:true,extractionLabel:`Solo RSS · ${String(s.description||'').length} caracteres`};}currentArticle=article;const modal=ensureNewsModal(),body=String(article?.body||article?.description||s.description||'').trim(),chars=Number(article?.sourceChars)||body.length,label=article?.extractionLabel||(chars<300?`Fuente breve · ${chars} caracteres`:`Artículo · ${chars} caracteres`);$('#newsModalTitle0321').textContent=s.title||article?.title||'Noticia';$('#newsModalMeta0321').innerHTML=`<span class="mini-pill">${escapeHtml(s.feedName||'RSS')}</span>${s.category?`<span class="mini-pill">${escapeHtml(s.category)}</span>`:''}${s.pubDate?`<span class="mini-pill">${escapeHtml(formatPubDate(s.pubDate))}</span>`:''}`;$('#newsModalBody0321').textContent=body||'La fuente no devolvió texto adicional.';const img=article?.image||s.image||'',imgEl=$('#newsModalImage0321');imgEl.src=img||'';imgEl.classList.toggle('hidden',!img);const q=$('#newsModalSourceQuality0321');q.textContent=label+(article?.extractionWarning?' ⚠':'');q.className=`source-chip top-gap ${article?.extractionWarning?'warn':'ok'}`;const link=$('#newsModalSource0321');link.href=s.link||'#';link.classList.toggle('hidden',!s.link);modal.classList.remove('hidden');status(article?.extractionWarning?'Noticia cargada · extracción breve detectada.':'Noticia cargada.');
  };

  const baseRenderQueue0321=renderQueue;
  renderQueue=function(s){baseRenderQueue0321(s);const rows=s?.queue||[],nodes=[...document.querySelectorAll('#queue .queue-item')];nodes.forEach((node,i)=>{const x=rows[i],m=x?.metrics||{};if(!x)return;const details=node.querySelector('.technical-details');if(!details)return;if(m.sourceChars&&!details.querySelector('.source-quality-line')){const warn=m.sourceQualityLevel==='critical'||Number(m.sourceChars)<300,line=document.createElement('div');line.className=`source-quality-line ${warn?'warn':'ok'}`;const mode=String(m.sourceExtractionMode||'article');line.textContent=`Fuente usada: ${mode} · ${Number(m.sourceChars)} caracteres${warn?' ⚠ extracción breve; EC limitó la duración y aplicó redacción conservadora':''}`;details.appendChild(line);}if(m.productionProfileId&&!details.querySelector('.production-profile-line')){const line=document.createElement('div'),layersExpected=Number(m.profileExpectedGpuLayers||0),layersActive=Number(m.profileActiveGpuLayers||0),ratio=Number(m.profileTokensPerSecRatio||0),degraded=m.profilePerformanceDegraded===true||m.profileLocalConfigMatch===false||String(m.pipelineModeExpected||'')!==String(m.pipelineModeActive||'');line.className=`source-quality-line production-profile-line ${degraded?'warn':'ok'}`;line.textContent=`Perfil producción: ${m.productionProfileVersion||'lab.23'} · ${m.pipelineModeActive||m.pipelineModeExpected||'—'}${layersExpected?` · GPU layers ${layersActive||'?'} / ${layersExpected}`:''}${ratio?` · rendimiento ${Math.round(ratio*100)}% del benchmark`:''}${m.ttsExpectedChunkChars?` · TTS chunk ${m.ttsExpectedChunkChars}`:''}${degraded?' ⚠':''}`;details.appendChild(line);}if(Array.isArray(m.ttsChunkDiagnostics)&&m.ttsChunkDiagnostics.length&&!details.querySelector('.tts-chunk-line')){const line=document.createElement('div'),chunks=m.ttsChunkDiagnostics;line.className='source-quality-line tts-chunk-line';line.textContent=`Chunks voz: ${chunks.map(c=>`#${c.index} ${c.chars}c / ${(Number(c.audio_sec)||0).toFixed(1)}s / ${Math.round(Number(c.elapsed_ms)||0)}ms`).join(' · ')}`;details.appendChild(line);}});};

  window.ECAPI.on('profile:changed',async()=>{try{settings=await window.ECAPI.getSettings();await refreshOptimizationState();}catch{}});
  refreshOptimizationState().catch(()=>{});
})();
