'use strict';
(function installEc0327(){
  if(window.__ec0327Installed)return;
  if(!window.ECAPI||typeof settings==='undefined'||!settings||!window.__ec0326Installed){setTimeout(installEc0327,120);return;}
  window.__ec0327Installed=true;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=v=>String(v||'').normalize('NFKC').trim().toLocaleLowerCase('es');
  const fmtSec=v=>{const n=Math.max(0,Math.round(Number(v)||0)),m=Math.floor(n/60),s=n%60;return`${m}:${String(s).padStart(2,'0')}`;};
  function activateTab(name){if(typeof tab==='function')return tab(name);qa('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));qa('.tab').forEach(x=>x.classList.toggle('show',x.id===`tab-${name}`));}
  function make(tag,cls='',html=''){const el=document.createElement(tag);if(cls)el.className=cls;if(html)el.innerHTML=html;return el;}
  function move(el,to){if(el&&to&&el.parentElement!==to)to.appendChild(el);return el;}
  function hideHeading(root,text){const h=qa('h3').find(x=>x.closest('#tab-settings')===root&&x.textContent.trim()===text)||qa('#tab-settings h3').find(x=>x.textContent.trim()===text);if(h){h.classList.add('ec27-hidden');if(h.previousElementSibling?.tagName==='HR')h.previousElementSibling.classList.add('ec27-hidden');}}
  function findSettingsCardBy(id){return q(id)?.closest('.card')||null;}

  const settingsNav=q('.nav[data-tab="settings"]');
  let audioNav=q('.nav[data-tab="audio"]');if(!audioNav){audioNav=make('button','nav','Audio y locución');audioNav.dataset.tab='audio';settingsNav?.insertAdjacentElement('beforebegin',audioNav);audioNav.addEventListener('click',()=>activateTab('audio'));}
  let audioTab=q('#tab-audio');if(!audioTab){audioTab=make('section','tab');audioTab.id='tab-audio';audioTab.innerHTML=`<h1>Audio y locución</h1><div class="ec27-grid"><div class="ec27-stack" id="ec27AudioLeft"></div><div class="ec27-stack" id="ec27AudioRight"></div></div><div class="ec27-audio-footer"><button id="ec27SaveAudio" class="ec27-save-audio">Guardar audio y locución</button></div>`;q('#tab-settings')?.insertAdjacentElement('beforebegin',audioTab);}
  const left=q('#ec27AudioLeft'),right=q('#ec27AudioRight');
  const voiceCard=make('div','ec27-card',`<div class="section-head"><h3>Voz y locución</h3><span class="mini-pill">KOKORO</span></div><div id="ec27VoiceSlot"></div><details class="ec27-advanced"><summary>Ver detalles técnicos de voz</summary><div id="ec27VoiceTech"></div></details>`);left.appendChild(voiceCard);
  const customCard=make('div','ec27-card',`<div class="section-head"><h3>Voces personalizadas</h3><span class="mini-pill">IMPORTABLES</span></div><div id="ec27CustomVoiceSlot"><div class="note">Cargando gestor de voces…</div></div>`);left.appendChild(customCard);
  const pronCard=make('div','ec27-card',`<div class="section-head"><h3>Pronunciación</h3><span class="mini-pill">AUTOMÁTICA</span></div><div id="ec27PronSlot"></div>`);right.appendChild(pronCard);
  const learnCard=make('div','ec27-card',`<div class="section-head"><h3>Gestionar aprendizaje</h3><span id="ec27LearningSummary" class="mini-pill">Cargando…</span></div><p class="note">Las correcciones manuales quedan protegidas y la IA no puede sobrescribirlas. Puedes crear, editar, importar, exportar o eliminar pronunciaciones.</p><button id="ec27ToggleAddPron" class="dark compact">+ Añadir pronunciación</button><div id="ec27AddPron" class="ec27-add-box ec27-hidden"><div class="ec27-add-grid"><label>Término<input id="ec27NewTerm" placeholder="Ej. streaming"></label><label>Pronunciación para TTS<input id="ec27NewPron" placeholder="Ej. stríming"></label><div class="buttons"><button id="ec27AddPronSave">Agregar</button></div></div><label class="ec0323-show-nochange"><input id="ec27NewNoChange" type="checkbox"> No requiere cambio</label></div><div id="ec27LearningToolbar" class="ec27-learning-tools"><input id="ec27LearningSearch" type="search" placeholder="Buscar término o pronunciación…"><label class="ec0323-show-nochange"><input id="ec27ShowNoChange" type="checkbox"> Mostrar reglas sin cambio</label></div><div id="ec27LearningButtons" class="buttons"></div><div id="ec27LearningList" class="ec27-learning-list"><div class="empty">Cargando aprendizaje…</div></div>`);right.appendChild(learnCard);
  const normCard=make('div','ec27-card',`<div class="section-head"><h3>Normalizador ES-PE</h3><span id="ec27NormalizerBadge" class="mini-pill">2.0</span></div><div id="ec27SpeechSlot"></div><div class="subcard top-gap"><div class="section-head"><h3>Reglas actualizables</h3><span id="ec27RuleVersion" class="mini-pill">Cargando…</span></div><p class="note">Las reglas pueden actualizarse sin reinstalar GEC. Cada paquete se valida con sus propias pruebas antes de activarse.</p><div class="ec27-normalizer-actions"><button id="ec27CheckRules" class="dark">Buscar actualización</button><button id="ec27UpdateRules" class="dark" disabled>Actualizar reglas</button><button id="ec27ImportRules" class="dark">Importar paquete</button><button id="ec27RestoreRules" class="dark">Restaurar anterior</button></div><div id="ec27RuleInfo" class="note"></div></div><div class="section-head top-gap"><h3>Diagnóstico completo</h3><button id="ec27RefreshDiag" class="dark compact">Actualizar</button></div><pre id="ec27SpeechDiagnostic" class="ec27-diagnostic">Sin diagnósticos todavía.</pre>`);right.appendChild(normCard);

  function relocateAudio(){
    const voiceSlot=q('#ec27VoiceSlot'),tech=q('#ec27VoiceTech'),pronSlot=q('#ec27PronSlot');
    move(q('#ttsInfo'),voiceSlot);move(q('#voice')?.closest('label'),voiceSlot);move(q('#voiceSpeed')?.closest('label'),voiceSlot);move(q('#ec0322VoicePerformance'),tech);move(q('#ttsBenchmarkResult'),tech);move(q('#ttsPerformanceHint'),tech);
    const cv=q('#customVoiceManager');if(cv){q('#ec27CustomVoiceSlot').replaceChildren(cv);}
    const oldDetails=q('#pronunciationProgress')?.closest('details')||q('#pronunciationMaxSeconds')?.closest('details');move(q('#pronunciationInfo'),pronSlot);move(q('#pronunciationClaudeVerify')?.closest('.switch-row'),pronSlot);move(q('#pronunciationMaxSeconds')?.closest('label'),pronSlot);const test=q('#testPronunciation');if(test)move(test,pronSlot);move(q('#pronunciationTestResult'),pronSlot);move(q('#pronunciationTestAudio'),pronSlot);
    const download=q('#downloadPronunciationModel');if(download)download.classList.add('ec27-hidden');
    const oldLearn=q('#pronunciationLearningCount')?.closest('.subcard');if(oldLearn){const buttons=oldLearn.querySelector('.buttons');if(buttons)move(buttons,q('#ec27LearningButtons'));oldLearn.classList.add('ec27-hidden');}
    const oldManager=q('#ec0323LearningManager');if(oldManager)oldManager.classList.add('ec27-hidden');
    const speech=q('#speech0326');if(speech)move(speech,q('#ec27SpeechSlot'));
    hideHeading(q('#tab-settings'),'Voz');hideHeading(q('#tab-settings'),'Pronunciación');if(oldDetails)oldDetails.classList.add('ec27-hidden');
  }
  relocateAudio();const relocateObserver=new MutationObserver(relocateAudio);relocateObserver.observe(q('#tab-settings')||document.body,{childList:true,subtree:true});setTimeout(()=>relocateObserver.disconnect(),12000);

  const musicCard=q('#musicEnabled')?.closest('.card');if(musicCard){musicCard.querySelector('h3')&&(musicCard.querySelector('h3').textContent='Música y mezcla');move(musicCard,left);}
  const emissionCols=q('#tab-emission .cols'),preview=q('#tab-emission .preview-card'),transition=q('#transitionType')?.closest('.card');if(emissionCols&&preview){let wrap=q('#ec27EmissionRight');if(!wrap){wrap=make('div','ec27-emission-right');wrap.id='ec27EmissionRight';emissionCols.appendChild(wrap);}move(preview,wrap);move(transition,wrap);}

  const settingsCols=q('#tab-settings .settings-cols');if(settingsCols){settingsCols.classList.add('ec27-settings-grid');const sourceCard=findSettingsCardBy('#feeds'),aiCard=findSettingsCardBy('#primary');sourceCard?.classList.add('ec27-source-card');if(aiCard){let queueCard=q('#ec27QueueSettings');if(!queueCard){queueCard=make('div','card ec27-queue-card');queueCard.id='ec27QueueSettings';const grid=q('#queueColorRss')?.closest('.color-grid'),heading=qa('#tab-settings h3').find(h=>h.textContent.includes('Colores de la Cola')),note=heading?.nextElementSibling,actions=q('#resetQueueColors')?.closest('.buttons');if(heading)queueCard.appendChild(heading);if(note?.classList.contains('note'))queueCard.appendChild(note);if(grid)queueCard.appendChild(grid);if(actions)queueCard.appendChild(actions);settingsCols.appendChild(queueCard);}}
  }
  const saveNote=q('#tab-settings .settings-save span');if(saveNote)saveNote.textContent='Guarda fuentes, IA, proveedores, colores de cola y configuración técnica.';

  const localInfo=q('#localInfo');if(localInfo&&!q('#ec27LocalInstaller')){const box=make('div','subcard');box.id='ec27LocalInstaller';box.innerHTML=`<div class="section-head"><h3>IA local completa</h3><span id="ec27LocalInstallBadge" class="mini-pill">COMPROBANDO</span></div><p class="note">Instala de forma secuencial la IA de pronunciación y la IA principal. Los componentes ya verificados se omiten.</p><button id="ec27InstallLocal">Instalar IA local completa</button><div id="ec27InstallState" class="note ec27-install-state">Comprobando componentes…</div><details class="ec27-advanced"><summary>Controles avanzados</summary><div id="ec27LocalAdvanced" class="buttons"></div></details>`;localInfo.insertAdjacentElement('afterend',box);const adv=q('#ec27LocalAdvanced');for(const id of ['startLocal','stopLocal'])move(q('#'+id),adv);q('#downloadModel')?.classList.add('ec27-hidden');}
  async function localInstallStatus(){const [p,l]=await Promise.all([window.ECAPI.pronunciationStatus(),window.ECAPI.localStatus()]);const pron=!!p?.model,main=!!l?.model,txt=`Pronunciación ${pron?'✓':'pendiente'} · IA principal ${main?'✓':'pendiente'}`;if(q('#ec27InstallState'))q('#ec27InstallState').textContent=txt;if(q('#ec27LocalInstallBadge'))q('#ec27LocalInstallBadge').textContent=pron&&main?'LISTA ✓':'INCOMPLETA';if(q('#ec27InstallLocal'))q('#ec27InstallLocal').textContent=pron&&main?'IA local completa ✓':'Instalar IA local completa';return{pron,main};}
  q('#ec27InstallLocal')?.addEventListener('click',async e=>{const btn=e.currentTarget;btn.disabled=true;try{let st=await localInstallStatus();if(!st.pron){q('#ec27InstallState').textContent='Paso 1 de 2 · Descargando IA de pronunciación…';await window.ECAPI.downloadPronunciationModel();st=await localInstallStatus();if(!st.pron)throw new Error('La IA de pronunciación no quedó verificada.');}if(!st.main){q('#ec27InstallState').textContent='Paso 2 de 2 · Descargando IA principal…';await window.ECAPI.downloadLocalModel();st=await localInstallStatus();if(!st.main)throw new Error('La IA principal no quedó verificada.');}q('#ec27InstallState').textContent='IA local completa instalada y verificada ✓';if(typeof status==='function')status('IA local completa lista.');}catch(err){q('#ec27InstallState').textContent=`Instalación detenida: ${err.message||err}`;}finally{btn.disabled=false;localInstallStatus().catch(()=>{});}});localInstallStatus().catch(()=>{});

  let learning=[],dirty=new Map(),refreshing=false;
  function ensureManual(){settings.tts=settings.tts||{};if(!settings.tts.manualPronunciations||typeof settings.tts.manualPronunciations!=='object')settings.tts.manualPronunciations={};if(!Array.isArray(settings.tts.pronunciationBlockedTerms))settings.tts.pronunciationBlockedTerms=[];}
  async function persistManual(term,pron,needs){ensureManual();for(const k of Object.keys(settings.tts.manualPronunciations))if(key(k)===key(term)&&k!==term)delete settings.tts.manualPronunciations[k];settings.tts.pronunciationBlockedTerms=settings.tts.pronunciationBlockedTerms.filter(x=>key(x)!==key(term));settings.tts.manualPronunciations[term]={pronunciation:String(pron||'').trim(),needsReplacement:!!needs};await window.ECAPI.saveSettings(settings);dirty.delete(key(term));if(typeof status==='function')status(`Corrección guardada: ${term}${needs?` → ${pron}`:' → sin cambio'}.`);await refreshLearning(true);}
  async function deleteTerm(term){if(!confirm(`¿Eliminar la regla de pronunciación para “${term}”?`))return;ensureManual();for(const k of Object.keys(settings.tts.manualPronunciations))if(key(k)===key(term))delete settings.tts.manualPronunciations[k];if(!settings.tts.pronunciationBlockedTerms.some(x=>key(x)===key(term)))settings.tts.pronunciationBlockedTerms.push(term);await window.ECAPI.saveSettings(settings);dirty.delete(key(term));await refreshLearning(true);}
  function sourceTag(x){if(x.manual)return['Manual','manual'];const s=String(x.source||'IA').toLowerCase();if(s.includes('claude'))return['Claude','claude'];if(s.includes('qwen'))return['Qwen','qwen'];return[String(x.source||'IA'),''];}
  function renderLearning(force=false){const box=q('#ec27LearningList');if(!box)return;const active=document.activeElement?.closest?.('#ec27LearningList .ec27-row');if(!force&&(active||dirty.size))return;const search=key(q('#ec27LearningSearch')?.value||''),show=q('#ec27ShowNoChange')?.checked===true,rows=learning.filter(x=>(!search||key(`${x.term} ${x.pronunciation} ${x.source}`).includes(search))&&(show||x.needsReplacement||x.inconsistentEmptyAdjustment)).slice(0,180);box.replaceChildren();if(!rows.length){box.innerHTML='<div class="empty">No hay reglas que coincidan.</div>';return;}for(const x of rows){const [tag,cls]=sourceTag(x),row=make('div','ec27-row');row.dataset.term=x.term;row.innerHTML=`<div><div class="ec27-term">${esc(x.term)}</div><div class="ec27-meta">${x.inconsistentEmptyAdjustment?'Regla incompleta · se tratará como sin cambio':x.needsReplacement?'Con ajuste fonético':'Sin cambio'}</div></div><div><input class="ec27-input" value="${esc(x.needsReplacement?x.pronunciation:'')}" placeholder="Escribe la corrección…"><div class="ec27-dirty"></div></div><span class="ec27-tag ${cls}">${esc(tag)}</span><span class="ec27-meta ec27-uses">${Number(x.uses||0)} uso${Number(x.uses||0)===1?'':'s'}</span><div class="ec27-actions"><button class="ec27-save" disabled>Guardar corrección</button><button class="ec27-delete dark">Eliminar</button></div>`;const input=row.querySelector('input'),save=row.querySelector('.ec27-save'),mark=row.querySelector('.ec27-dirty'),original=String(x.needsReplacement?x.pronunciation:'');input.addEventListener('input',()=>{const changed=input.value!==original;save.disabled=!changed;mark.textContent=changed?'Cambio sin guardar':'';if(changed)dirty.set(key(x.term),input.value);else dirty.delete(key(x.term));});save.onclick=()=>persistManual(x.term,input.value,!!String(input.value).trim()).catch(e=>status(`Pronunciación: ${e.message||e}`));row.querySelector('.ec27-delete').onclick=()=>deleteTerm(x.term).catch(e=>status(`Pronunciación: ${e.message||e}`));box.appendChild(row);}}
  async function refreshLearning(force=false){if(refreshing)return;refreshing=true;try{const p=await window.ECAPI.pronunciationStatus();learning=Array.isArray(p?.learningList)?p.learningList:[];const repl=learning.filter(x=>x.needsReplacement).length,manual=learning.filter(x=>x.manual).length,neg=learning.filter(x=>!x.needsReplacement).length;q('#ec27LearningSummary').textContent=`${repl} ajustes · ${manual} manuales · ${neg} verificadas`;renderLearning(force);}catch(e){q('#ec27LearningList').innerHTML=`<div class="empty">No se pudo cargar: ${esc(e.message||e)}</div>`;}finally{refreshing=false;}}
  q('#ec27LearningSearch').addEventListener('input',()=>renderLearning(false));q('#ec27ShowNoChange').addEventListener('change',()=>renderLearning(false));q('#ec27ToggleAddPron').onclick=()=>q('#ec27AddPron').classList.toggle('ec27-hidden');q('#ec27NewNoChange').onchange=e=>{q('#ec27NewPron').disabled=e.target.checked;};q('#ec27AddPronSave').onclick=async()=>{const term=String(q('#ec27NewTerm').value||'').trim(),noChange=q('#ec27NewNoChange').checked,pron=String(q('#ec27NewPron').value||'').trim();if(!term)return status('Escribe el término que quieres añadir.');if(!noChange&&!pron)return status('Escribe la pronunciación para TTS o marca “No requiere cambio”.');const existing=learning.find(x=>key(x.term)===key(term));if(existing&&!confirm(`“${term}” ya existe. ¿Actualizar su corrección manual?`))return;await persistManual(existing?.term||term,pron,!noChange);q('#ec27NewTerm').value='';q('#ec27NewPron').value='';q('#ec27NewNoChange').checked=false;q('#ec27NewPron').disabled=false;q('#ec27AddPron').classList.add('ec27-hidden');};refreshLearning(true);setInterval(()=>refreshLearning(false),5000);

  async function refreshNormalizer(){try{const n=await window.ECAPI.normalizerStatus();q('#ec27RuleVersion').textContent=n.rulesVersion||'integrada';q('#ec27NormalizerBadge').textContent=`Motor ${n.engineVersion||'2.0'}`;q('#ec27RuleInfo').textContent=`${n.ruleCount||0} reglas declarativas · ${n.testCount||0} pruebas · ${n.hasPrevious?'rollback disponible':'sin rollback todavía'}.`;q('#ec27RestoreRules').disabled=!n.hasPrevious;}catch(e){q('#ec27RuleInfo').textContent=e.message||e;}await refreshSpeechDiag();}
  async function refreshSpeechDiag(){const out=q('#ec27SpeechDiagnostic');try{const [p,t]=await Promise.all([window.ECAPI.pronunciationStatus(),window.ECAPI.ttsStatus()]),d=p?.speechNormalizer?.last,k=t?.lastInput0327||p?.speechNormalizer?.lastKokoro;if(!d){out.textContent=`Normalizador ${p?.speechNormalizer?.version||''} · sin notas procesadas todavía.`;return;}out.textContent=`ORIGINAL\n${d.original||''}\n\nDESPUÉS DEL APRENDIZAJE\n${d.afterPronunciation||''}\n\nDESPUÉS DEL NORMALIZADOR\n${d.normalized||''}\n\nENVIADO REALMENTE A KOKORO\n${k?.requested||d.sentToKokoro||''}${k?.prosodicGuard?`\n\nEntrada interna con protección de ataque:\n${k.synthesis||''}`:''}\n\nTransformaciones: ${(d.transforms||[]).join(', ')||'ninguna'}\nReglas: ${d.rulesVersion||p?.speechNormalizer?.rulesVersion||''}${d.fallbackReason?`\nFallback: ${d.fallbackReason}`:''}`;}catch(e){out.textContent=`Diagnóstico: ${e.message||e}`;}}
  q('#ec27RefreshDiag').onclick=refreshSpeechDiag;q('#ec27ImportRules').onclick=async()=>{try{const r=await window.ECAPI.normalizerImport();if(!r?.cancelled)status(`Reglas ${r.rulesVersion} importadas y validadas.`);await refreshNormalizer();}catch(e){status(`Normalizador: ${e.message||e}`);}};q('#ec27RestoreRules').onclick=async()=>{if(!confirm('¿Restaurar el paquete anterior del normalizador?'))return;try{const r=await window.ECAPI.normalizerRestore();status(r.ok?`Reglas restauradas: ${r.rulesVersion}`:(r.error||'No hay copia anterior'));await refreshNormalizer();}catch(e){status(`Normalizador: ${e.message||e}`);}};q('#ec27CheckRules').onclick=async()=>{q('#ec27RuleInfo').textContent='Buscando actualización…';const r=await window.ECAPI.normalizerCheckUpdate();if(r.ok&&r.available){q('#ec27UpdateRules').disabled=false;q('#ec27RuleInfo').textContent=`Disponible ${r.remoteVersion} · actual ${r.currentVersion}.`;}else{q('#ec27UpdateRules').disabled=true;q('#ec27RuleInfo').textContent=r.ok?'Las reglas ya están actualizadas.':`No se pudo consultar el canal remoto. Puedes importar un paquete manualmente. ${r.error||''}`;}};q('#ec27UpdateRules').onclick=async()=>{try{q('#ec27UpdateRules').disabled=true;const r=await window.ECAPI.normalizerUpdate();status(r.updated?`Normalizador actualizado a ${r.rulesVersion}.`:'Ya estaba actualizado.');await refreshNormalizer();}catch(e){status(`Normalizador: ${e.message||e}`);}};refreshNormalizer();setInterval(()=>{if(!document.hidden&&q('#tab-audio')?.classList.contains('show'))refreshSpeechDiag();},5000);

  const cannedCard=q('#cannedEnabled')?.closest('.card');if(cannedCard&&!q('#ec27RecoveryStatus')){const box=make('div','subcard ec27-recovery');box.id='ec27RecoveryStatus';box.innerHTML=`<div class="section-head"><h3>Recuperación de autonomía</h3><span id="ec27RecoveryBadge" class="mini-pill">ESPERANDO</span></div><div class="ec27-recovery-grid"><div><b id="ec27Target">--:--</b><span>Objetivo</span></div><div><b id="ec27Current">--:--</b><span>Disponible</span></div><div><b id="ec27Deficit">--:--</b><span>Déficit</span></div></div><div id="ec27Selection" class="ec27-selection"><strong>Selección de contenidos</strong><span>Aleatoria sin repetición para programación normal.</span></div>`;q('#launchCannedNow')?.closest('.buttons')?.insertAdjacentElement('beforebegin',box);}if(q('#launchCannedNow'))q('#launchCannedNow').textContent='Programar contenido ahora';const listHead=q('#cannedList')?.parentElement?.querySelector('.section-head');if(listHead&&!q('#ec27LibraryMode')){const mode=make('div','ec27-library-mode','Selección normal: aleatoria sin repetición · Recuperación: adaptativa por duración.');mode.id='ec27LibraryMode';listHead.insertAdjacentElement('afterend',mode);}
  function updateRecovery(s){const sel=s?.canned?.adaptiveSelection,b=s?.buffer||{},targetMin=Number(sel?.targetMin||settings?.automation?.targetAutonomyMin||15),current=Number(sel?.currentSec??b.autonomySec??(Number(b.autonomyMin)||0)*60),def=Math.max(0,Number(sel?.deficitSec??targetMin*60-current));if(q('#ec27Target'))q('#ec27Target').textContent=fmtSec(targetMin*60);if(q('#ec27Current'))q('#ec27Current').textContent=fmtSec(current);if(q('#ec27Deficit'))q('#ec27Deficit').textContent=fmtSec(def);const badge=q('#ec27RecoveryBadge'),box=q('#ec27Selection');if(!sel?.selected){if(badge)badge.textContent=def>0?'BAJA RESERVA':'ESTABLE';if(box)box.innerHTML='<strong>Selección normal</strong><span>Aleatoria sin repetición hasta completar el ciclo.</span>';return;}const labels={recovery:'Recuperación de autonomía',emergency:'Respaldo por falta de noticias',scheduled:'Programación periódica',manual:'Programación manual'},label=labels[sel.reason]||sel.reason;if(badge)badge.textContent=sel.adaptive?'ADAPTATIVA':'ALEATORIA';if(box)box.innerHTML=`<strong>${esc(sel.selected.name)}</strong><span>${fmtSec(sel.selected.durationSec)} · ${esc(label)}${sel.adaptive?` · solicitado aprox. ${fmtSec(sel.requestedContentSec)}`:' · aleatorio sin repetición'}</span>`;}
  window.ECAPI.on('automation:state',updateRecovery);window.ECAPI.automationStatus().then(updateRecovery).catch(()=>{});

  q('#ec27SaveAudio').onclick=()=>{const master=q('#save');if(master){master.click();setTimeout(()=>status('Audio y locución guardados.'),250);}else window.ECAPI.saveSettings(settings).then(()=>status('Audio y locución guardados.')).catch(e=>status(e.message||e));};
})();
