'use strict';

(function installEc0321Ui(){
  if(!window.__ec0320UiInstalled||typeof renderQueue!=='function'||typeof openStory!=='function'||!window.ECAPI){setTimeout(installEc0321Ui,120);return;}
  if(window.__ec0321UiInstalled)return;window.__ec0321UiInstalled=true;

  const style=document.createElement('style');style.textContent=`
    #ecOptimizer0321{margin:0 0 18px}.ec-opt-grid{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center}.ec-opt-summary{line-height:1.55}.ec-opt-progress{margin-top:10px}.ec-opt-progress b{color:#8ed99b}.ec-opt-tech{margin-top:10px}.ec-opt-tech pre{white-space:pre-wrap;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;opacity:.88}.source-quality-line{margin-top:5px;font-size:12px}.source-quality-line.warn{color:#f3c969}.source-quality-line.ok{color:#8ed99b}
    #newsModal0321{position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:32px}#newsModal0321.hidden{display:none}.news-modal-card{width:min(1120px,94vw);max-height:88vh;overflow:hidden;background:#171717;border:1px solid #373737;border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,.55);display:flex;flex-direction:column}.news-modal-head{display:flex;gap:20px;align-items:flex-start;justify-content:space-between;padding:22px 24px 16px;border-bottom:1px solid #333}.news-modal-head h2{margin:0;font-size:24px;line-height:1.25}.news-modal-body{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.55fr);gap:24px;padding:22px 24px 26px;overflow:auto}.news-modal-text{white-space:pre-wrap;line-height:1.58}.news-modal-image{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;background:#101010}.news-modal-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.source-chip{display:inline-flex;align-items:center;border:1px solid #444;border-radius:999px;padding:5px 9px;font-size:12px}.source-chip.warn{border-color:#8a6c1a;color:#f3c969}.source-chip.ok{border-color:#286a35;color:#8ed99b}@media(max-width:900px){.ec-opt-grid,.news-modal-body{grid-template-columns:1fr}#newsModal0321{padding:12px}}
  `;document.head.appendChild(style);

  function hideLegacyOptimizers(){
    const tts=$('#optimizeTts');if(tts)tts.style.display='none';const ttsResult=$('#ttsBenchmarkResult');if(ttsResult)ttsResult.style.display='none';const local=$('#localOptimizer0320');if(local)local.style.display='none';const gpu=document.querySelector('.gpu-advanced-wrap');if(gpu)gpu.style.display='none';
  }
  hideLegacyOptimizers();setTimeout(hideLegacyOptimizers,500);

  function ensureUnifiedOptimizer(){
    if($('#ecOptimizer0321'))return;const tab=$('#tab-settings');if(!tab)return;const card=document.createElement('div');card.id='ecOptimizer0321';card.className='card';card.innerHTML=`<div class="ec-opt-grid"><div><div class="section-head"><h3>Optimización automática de EC</h3><span id="ecOptimizeState0321" class="mini-pill">SIN OPTIMIZAR</span></div><p class="note">Una sola prueba configura la voz, Qwen local y el reparto de CPU/GPU para esta computadora. EC valida también Qwen + Kokoro al mismo tiempo y guarda el perfil recomendado.</p></div><div><button id="optimizeEc0321">Optimizar EC para esta computadora</button></div></div><div id="ecOptimizeResult0321" class="ec-opt-summary note">Ejecuta esta prueba una vez por computadora o después de cambiar hardware.</div><details id="ecOptimizeTech0321" class="advanced ec-opt-tech hidden"><summary>Ver diagnóstico técnico</summary><pre id="ecOptimizeTechText0321"></pre></details>`;const h=tab.querySelector('h1');if(h)h.insertAdjacentElement('afterend',card);else tab.prepend(card);$('#optimizeEc0321').onclick=runUnifiedOptimization;refreshOptimizationState().catch(()=>{});
  }
  ensureUnifiedOptimizer();

  function gpuIdentity(g={}){const d=g.gpu||g.device||{};return{gpu:String(d.name||g.gpuName||g.name||''),vram:Number(d.vramMb||d.memoryTotalMb||g.vramMb||g.memoryTotalMb||0),driver:String(d.driver||g.driver||'')};}
  async function hardwareFingerprint(){const [local,gpu]=await Promise.all([window.ECAPI.localStatus().catch(()=>({})),window.ECAPI.gpuTtsStatus().catch(()=>({}))]),id=gpuIdentity(gpu),logical=Number(local?.profile?.logicalCpus||0);return{key:JSON.stringify({logical,gpu:id.gpu,vram:Math.round(id.vram/256)*256,driver:id.driver}),label:[logical?`${logical} hilos CPU`:'CPU',id.gpu||'GPU no identificada',id.vram?`${(id.vram/1024).toFixed(1)} GB VRAM`:'' ].filter(Boolean).join(' · ')};}
  async function refreshOptimizationState(){if(!settings)return;const badge=$('#ecOptimizeState0321'),result=$('#ecOptimizeResult0321');if(!badge)return;const hw=await hardwareFingerprint(),saved=settings.optimization0321;if(saved?.fingerprint&&saved.fingerprint===hw.key){badge.textContent='OPTIMIZADA ✓';badge.className='mini-pill ok';if(result&&!result.dataset.live)result.textContent=`Perfil guardado · ${saved.hardwareLabel||hw.label} · ${saved.summary||'EC adaptado a esta computadora'}.`;}else if(saved?.fingerprint){badge.textContent='REOPTIMIZAR';badge.className='mini-pill warn';if(result&&!result.dataset.live)result.textContent='EC detectó un cambio de hardware. Conviene ejecutar nuevamente la optimización.';}else{badge.textContent='SIN OPTIMIZAR';badge.className='mini-pill';}}
  const sec=ms=>`${(Number(ms||0)/1000).toFixed(1)} s`;
  function formatTts(r={}){return`${r.recommendedLabel||'CPU optimizada'} · RTF mediana ${Number(r.bestRealtimeFactor||r.realtimeFactor||0).toFixed(2)} · peor ${Number(r.worstRealtimeFactor||0).toFixed(2)}`;}
  function formatLocal(r={}){const s=r.summary||{};return`${r.recommendedLabel||'Qwen optimizado'} · ${Number(s.tokensPerSec||0).toFixed(1)} tok/s · mediana ${sec(s.medianElapsedMs)} · peor ${sec(s.worstElapsedMs)}${s.overlap?.voiceRtf?` · Kokoro simultáneo RTF ${Number(s.overlap.voiceRtf).toFixed(2)}`:''}`;}
  async function runUnifiedOptimization(){
    const btn=$('#optimizeEc0321'),box=$('#ecOptimizeResult0321'),tech=$('#ecOptimizeTech0321'),techText=$('#ecOptimizeTechText0321');if(automationState?.processing?.running||automationState?.emission?.running){box.textContent='Detén temporalmente Preparación y Emisión antes de optimizar EC.';return;}btn.disabled=true;box.dataset.live='1';tech.classList.add('hidden');let ttsResult=null,localResult=null,gpuNote='';
    try{
      const localStatus=await window.ECAPI.localStatus(),chain=[settings?.ai?.primary,settings?.ai?.backup1,settings?.ai?.backup2].filter(Boolean),usesLocal=chain.includes('local');if(usesLocal&&!localStatus?.model)throw new Error('La IA local está configurada pero el modelo Qwen aún no está descargado. Descárgalo antes de optimizar EC.');
      box.innerHTML='<b>1/3 · Optimizando motor de voz…</b> EC está buscando la configuración más estable de Kokoro.';status('Optimizando EC · motor de voz…');await window.ECAPI.saveSettings(settings);ttsResult=await window.ECAPI.benchmarkTts();if(!ttsResult?.ok)throw new Error(ttsResult?.error||'No se pudo optimizar el motor de voz');settings=await window.ECAPI.getSettings();
      if(usesLocal){box.innerHTML=`<b>2/3 · Voz lista.</b> ${escapeHtml(formatTts(ttsResult))}<br>Ahora EC optimiza Qwen y valida Qwen + Kokoro simultáneamente…`;status('Optimizando EC · IA local…');localResult=await window.ECAPI.benchmarkLocalAI(settings);if(!localResult?.ok)throw new Error(localResult?.error||'No se pudo optimizar la IA local');settings.ai.localResourceMode='tuned';settings.ai.localAutoTuned=true;settings.ai.localTunedConfig=localResult.recommendedConfig;settings.ai.lastLocalBenchmark=localResult.summary;gpuNote='Kokoro permanece en CPU para reservar GPU/VRAM a Qwen.';}else{gpuNote='IA local no está en la cadena de proveedores; EC optimizó Kokoro sin reservar GPU para Qwen.';}
      box.innerHTML='<b>3/3 · Guardando perfil de esta computadora…</b>';const hw=await hardwareFingerprint(),summary=`Voz ${formatTts(ttsResult)}${localResult?` · IA local ${formatLocal(localResult)}`:''}`;settings.optimization0321={version:'0.3.21',at:new Date().toISOString(),fingerprint:hw.key,hardwareLabel:hw.label,summary,voice:{recommendedLabel:ttsResult.recommendedLabel||'',medianRtf:Number(ttsResult.bestRealtimeFactor||0),worstRtf:Number(ttsResult.worstRealtimeFactor||0)},local:localResult?.summary||null};await window.ECAPI.saveSettings(settings);settings=await window.ECAPI.getSettings();box.innerHTML=`<div class="benchmark-good"><b>EC optimizado para esta computadora ✓</b></div><div><b>Voz:</b> ${escapeHtml(formatTts(ttsResult))}</div>${localResult?`<div><b>IA local:</b> ${escapeHtml(formatLocal(localResult))}</div>`:''}<div><b>Hardware:</b> ${escapeHtml(hw.label)}</div><div>${escapeHtml(gpuNote)}</div><div class="note">No necesitas repetir esta prueba salvo que cambies de computadora o hardware.</div>`;
      const tRows=(ttsResult.results||[]).map(x=>`${x.label||x.id}: ${x.error?`DESCARTADA · ${x.error}`:`RTF mediana ${Number(x.medianRealtimeFactor||x.realtimeFactor||0).toFixed(2)} · peor ${Number(x.worstRealtimeFactor||0).toFixed(2)} · CPU ${Number(x.cpuAverage||0).toFixed(0)}%`}`),lRows=(localResult?.results||[]).map(x=>`${x.label||x.id}: ${x.error?`DESCARTADA · ${x.error}`:`${Number(x.tokensPerSec||0).toFixed(1)} tok/s · mediana ${sec(x.medianElapsedMs)} · peor ${sec(x.worstElapsedMs)} · CPU ${Number(x.cpuAverage||0).toFixed(0)}% · GPU ${Number(x.gpuAverage||0).toFixed(0)}% · VRAM ${x.vramMaxMb?(Number(x.vramMaxMb)/1024).toFixed(1):'0'} GB`}`);techText.textContent=[`VOZ\n${tRows.join('\n')}`,localResult?`IA LOCAL\n${lRows.join('\n')}`:'',gpuNote].filter(Boolean).join('\n\n');tech.classList.remove('hidden');await refreshOptimizationState();await refreshRuntimeStatus();status('EC optimizado para esta computadora.');
    }catch(e){box.innerHTML=`<span class="benchmark-warn"><b>Optimización incompleta:</b> ${escapeHtml(humanError(e))}</span>`;status(`Optimización EC: ${humanError(e)}`);}finally{delete box.dataset.live;btn.disabled=false;}
  }

  function ensureNewsModal(){if($('#newsModal0321'))return $('#newsModal0321');const overlay=document.createElement('div');overlay.id='newsModal0321';overlay.className='hidden';overlay.innerHTML=`<div class="news-modal-card" role="dialog" aria-modal="true"><div class="news-modal-head"><div><h2 id="newsModalTitle0321">Noticia</h2><div id="newsModalMeta0321" class="news-modal-meta"></div></div><button id="newsModalClose0321" class="dark compact">Cerrar</button></div><div class="news-modal-body"><div><div id="newsModalBody0321" class="news-modal-text"></div></div><div><img id="newsModalImage0321" class="news-modal-image" alt=""><div id="newsModalSourceQuality0321" class="source-chip top-gap"></div><div class="buttons top-gap"><a id="newsModalSource0321" class="news-source-link" target="_blank" rel="noreferrer">Abrir fuente original</a></div></div></div></div>`;document.body.appendChild(overlay);const close=()=>overlay.classList.add('hidden');$('#newsModalClose0321').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.classList.contains('hidden'))close();});return overlay;}
  ensureNewsModal();const oldViewer=$('#newsViewer0319');if(oldViewer)oldViewer.classList.add('hidden');
  openStory=async function(s){
    currentStory=s;status('Cargando noticia…');let article=null;try{article=await window.ECAPI.fetchArticle(s.link);}catch{article={title:s.title,description:s.description,body:s.description,image:s.image||'',sourceChars:String(s.description||'').length,extractionMode:'rss',extractionWarning:true,extractionLabel:`Solo RSS · ${String(s.description||'').length} caracteres`};}currentArticle=article;const modal=ensureNewsModal(),body=String(article?.body||article?.description||s.description||'').trim(),chars=Number(article?.sourceChars)||body.length,label=article?.extractionLabel||(chars<300?`Fuente breve · ${chars} caracteres`:`Artículo · ${chars} caracteres`);$('#newsModalTitle0321').textContent=s.title||article?.title||'Noticia';$('#newsModalMeta0321').innerHTML=`<span class="mini-pill">${escapeHtml(s.feedName||'RSS')}</span>${s.category?`<span class="mini-pill">${escapeHtml(s.category)}</span>`:''}${s.pubDate?`<span class="mini-pill">${escapeHtml(formatPubDate(s.pubDate))}</span>`:''}`;$('#newsModalBody0321').textContent=body||'La fuente no devolvió texto adicional.';const img=article?.image||s.image||'',imgEl=$('#newsModalImage0321');imgEl.src=img||'';imgEl.classList.toggle('hidden',!img);const q=$('#newsModalSourceQuality0321');q.textContent=label+(article?.extractionWarning?' ⚠':'');q.className=`source-chip top-gap ${article?.extractionWarning?'warn':'ok'}`;const link=$('#newsModalSource0321');link.href=s.link||'#';link.classList.toggle('hidden',!s.link);modal.classList.remove('hidden');status(article?.extractionWarning?'Noticia cargada · extracción breve detectada.':'Noticia cargada.');
  };

  const baseRenderQueue0321=renderQueue;
  renderQueue=function(s){baseRenderQueue0321(s);const rows=s?.queue||[],nodes=[...document.querySelectorAll('#queue .queue-item')];nodes.forEach((node,i)=>{const x=rows[i],m=x?.metrics||{};if(!x||!m.sourceChars)return;const details=node.querySelector('.technical-details');if(!details||details.querySelector('.source-quality-line'))return;const warn=m.sourceQualityLevel==='critical'||Number(m.sourceChars)<300,line=document.createElement('div');line.className=`source-quality-line ${warn?'warn':'ok'}`;const mode=String(m.sourceExtractionMode||'article');line.textContent=`Fuente usada: ${mode} · ${Number(m.sourceChars)} caracteres${warn?' ⚠ extracción breve; EC limitó la duración y aplicó redacción conservadora':''}`;details.appendChild(line);});};

  refreshOptimizationState().catch(()=>{});
})();
