'use strict';
let settings=null,stories=[],currentStory=null,currentArticle=null,currentGenerated=null,currentAudio=null,documentScan={ok:false,files:[]};
let automationState={processing:{running:false,paused:false},emission:{running:false,paused:false,currentTitle:'',currentKind:'none'},counts:{processing:0,ready:0,pending:0,onAir:0,emitted:0,error:0},buffer:{autonomyMin:0,health:'critical'},queue:[]};
let currentOutputState={open:false,source:'none',kind:'none',title:'',format:'16:9',resolution:'1920×1080'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const status=t=>{const el=$('#status');if(el)el.textContent=String(t||'');};
const providerName=p=>({local:'IA local',claude:'Claude Haiku 4.5',gemini:'Gemini',none:'Ninguno'}[p]||p||'');
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const SELF_TEST=new URLSearchParams(location.search).get('selftest')==='1';
const DESIGN_DEFAULT={format:'16:9',fontFamily:'Arial',dateFontFamily:'Arial',titleColor:'#FFFFFF',summaryColor:'#F3F3F3',dateColor:'#F3F3F3',categoryBgColor:'#F7C600',categoryTextColor:'#000000',lowerBgColor:'#000000',lowerOpacity:.88,animation:'auto',motionSpeed:'normal',tiktokSafe:true,showSafeGuides:true,verticalVideoBackground:'',verticalVideoBackgroundUrl:'',musicFile:'',musicUrl:'',musicEnabled:false,musicLoop:true,musicVolume:20,voiceVolume:100,cannedVolume:100,transitionEnabled:true,transitionType:'fade',transitionDuration:.7};
const QUEUE_COLOR_DEFAULT={rss:'#2E7D32',generated:'#2563EB',content:'#D97706',ad:'#7C3AED',error:'#B91C1C'};

function fatalInterface(message){status(`ERROR DE INTERFAZ · ${message}`);document.body.classList.add('bridge-error');$$('button,input,select,textarea').forEach(el=>{if(el.id!=='status')el.disabled=true;});}
if(!window.ECAPI||typeof window.ECAPI.getSettings!=='function')fatalInterface('La conexión interna de EC no está disponible. Reinicia EC o reinstala esta versión.');
function tab(name){$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab').forEach(x=>x.classList.toggle('show',x.id===`tab-${name}`));}
$$('.nav').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function effectiveImage(){return currentStory?.image||currentArticle?.image||settings?.visual?.fallbackImageUrl||'';}
function formatPubDate(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';try{return new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short',year:'numeric'}).format(d).replace(/\./g,'').toUpperCase();}catch{return'';}}
function hexRgba(hex,opacity){const m=String(hex||'#000').replace('#',''),h=m.length===3?m.split('').map(x=>x+x).join(''):m,n=parseInt(h,16);if(Number.isNaN(n))return`rgba(0,0,0,${opacity})`;return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${opacity})`;}
function design(){return{...DESIGN_DEFAULT,...(settings?.visual?.output||{})};}
function previewMotionMode(img,d){let mode=d.animation||'auto';if(mode==='auto'){const w=img?.naturalWidth||16,h=img?.naturalHeight||9,ar=w/Math.max(1,h);mode=ar<1?'vertical':ar>1.9?'horizontal':'zoom';}return mode;}
function applyPreviewMotion(el,d){const image=el?.querySelector('img');if(!image)return;image.classList.remove('preview-motion-zoom','preview-motion-vertical','preview-motion-horizontal','preview-motion-none');const mode=previewMotionMode(image,d);image.classList.add(`preview-motion-${['zoom','vertical','horizontal','none'].includes(mode)?mode:'zoom'}`);const seconds={slow:26,normal:18,fast:11}[d.motionSpeed]||18;el.style.setProperty('--preview-motion-duration',`${seconds}s`);}
function applyPreviewDesign(el,d,showGuide=false){if(!el)return;el.classList.toggle('format-9-16',d.format==='9:16');el.classList.toggle('format-16-9',d.format!=='9:16');el.classList.toggle('show-safe',showGuide&&d.format==='9:16'&&d.tiktokSafe&&d.showSafeGuides);el.style.fontFamily=`${d.fontFamily},sans-serif`;el.style.setProperty('--title-color',d.titleColor);el.style.setProperty('--summary-color',d.summaryColor);el.style.setProperty('--date-color',d.dateColor||d.summaryColor);el.style.setProperty('--cat-bg',d.categoryBgColor);el.style.setProperty('--cat-color',d.categoryTextColor);el.style.setProperty('--lower-bg',hexRgba(d.lowerBgColor,Number(d.lowerOpacity)));el.querySelectorAll('.preview-date').forEach(x=>{x.style.fontFamily=`${d.dateFontFamily||d.fontFamily},sans-serif`;x.style.color=d.dateColor||d.summaryColor;});applyPreviewMotion(el,d);}
function refreshPreview(){if($('#previewTitle'))$('#previewTitle').textContent=$('#title')?.value||'Titular';if($('#previewCat'))$('#previewCat').textContent=($('#category')?.value||'ACTUALIDAD').toUpperCase();if($('#previewSummary'))$('#previewSummary').textContent=$('#summary')?.value||'';if($('#previewDate'))$('#previewDate').textContent=formatPubDate(currentStory?.pubDate||currentArticle?.pubDate||'')||'20 AGO 2026';if($('#designPreviewDate'))$('#designPreviewDate').textContent=formatPubDate(currentStory?.pubDate||'')||'20 AGO 2026';const i=effectiveImage();if(i){if($('#previewImg'))$('#previewImg').src=i;if($('#designPreviewImg'))$('#designPreviewImg').src=i;}const d=design();applyPreviewDesign($('#editorPreview'),d,d.showSafeGuides);applyPreviewDesign($('#designPreview'),d,true);if($('#previewFormat'))$('#previewFormat').textContent=d.format;if($('#designFormatBadge'))$('#designFormatBadge').textContent=d.format;}
function refreshOutputStatus(s=currentOutputState){currentOutputState=s||currentOutputState;const el=$('#outputStatus'),btn=$('#openOutput');if(!el)return;if(!s?.open){el.textContent='OUTPUT · cerrado';el.className='status-pill neutral';if(btn)btn.textContent='Abrir Output';return;}const kind=s.kind==='canned'?' · Contenido':s.kind==='ad'?' · Anuncio':'',source=s.source==='automatic'?`Automático${kind}`:s.source==='manual'?'Manual':'Listo',res=s.resolution||(s.format==='9:16'?'1080×1920':'1920×1080');el.textContent=`OUTPUT · ${res} · ${source}${s.title?` · ${s.title.slice(0,34)}`:''}`;el.className=`status-pill ${s.source==='automatic'?'live':s.source==='manual'?'pause':'ok'}`;if(btn)btn.textContent='Cerrar Output';}
function refreshLocalPolicyUi(){if(!$('#localBackupMode')||!settings)return;const mode=$('#localBackupMode').value||'on_demand',primary=$('#primary')?.value||settings.ai.primary,backups=[$('#backup1')?.value,$('#backup2')?.value],asBackup=primary!=='local'&&backups.includes('local'),asPrimary=primary==='local';$('#localIdleRow')?.classList.toggle('hidden',mode!=='on_demand');const info=$('#localPolicyInfo');if(!info)return;if(asPrimary)info.textContent='La IA local es el servicio principal y se activa automáticamente cuando se necesita.';else if(asBackup&&mode==='always')info.textContent='La IA local permanecerá preparada para responder inmediatamente si falla el servicio principal.';else if(asBackup)info.textContent='La IA local se activa solo si hace falta y se apaga después de un periodo sin uso.';else info.textContent='Esta opción se aplica cuando la IA local está configurada como respaldo.';}
function refreshProviderUi(){if(!settings)return;const chain=[settings.ai.primary,settings.ai.backup1,settings.ai.backup2].filter(x=>x&&x!=='none');if($('#providerSummary'))$('#providerSummary').textContent=`Orden de uso: ${chain.map(providerName).join(' → ')||'sin servicio'}`;if($('#claudeStatus'))$('#claudeStatus').textContent=settings.ai.hasClaudeKey?'API Key guardada ✓ · Claude Haiku 4.5':'API Key: no configurada';if($('#geminiStatus'))$('#geminiStatus').textContent=settings.ai.hasGeminiKey?'API Key guardada ✓':'API Key: no configurada';if($('#claudeKey'))$('#claudeKey').placeholder=settings.ai.hasClaudeKey?'••••••••  API guardada · pega otra para reemplazar':'Pega una clave nueva';if($('#geminiKey'))$('#geminiKey').placeholder=settings.ai.hasGeminiKey?'••••••••  API guardada · pega otra para reemplazar':'Pega una clave nueva';if($('#claudeModel'))$('#claudeModel').value='claude-haiku-4-5-20251001';refreshLocalPolicyUi();}
function normalizeProviders(showMessage=false){if(!settings)return;const p=$('#primary').value;let b1=$('#backup1').value,b2=$('#backup2').value;const changes=[];if(b1===p){b1='none';$('#backup1').value='none';changes.push('El primer respaldo estaba repetido');}if(b2===p||(b2===b1&&b2!=='none')){b2='none';$('#backup2').value='none';changes.push('El segundo respaldo estaba repetido');}settings.ai.primary=p;settings.ai.backup1=b1;settings.ai.backup2=b2;if(showMessage&&changes.length)status(`${changes.join('. ')}. Se corrigió automáticamente.`);refreshProviderUi();}
function updateRangeLabels(){if($('#musicVolumeValue'))$('#musicVolumeValue').textContent=`${$('#musicVolume').value}%`;if($('#voiceVolumeValue'))$('#voiceVolumeValue').textContent=`${$('#voiceVolume').value}%`;if($('#cannedVolumeValue'))$('#cannedVolumeValue').textContent=`${$('#cannedVolume').value}%`;}
function setDesignControls(d){const value=(id,v)=>{if($('#'+id))$('#'+id).value=v;};value('outputFormat',d.format);value('fontFamily',d.fontFamily);value('dateFontFamily',d.dateFontFamily||d.fontFamily||'Arial');value('imageAnimation',d.animation);value('motionSpeed',d.motionSpeed);value('titleColor',d.titleColor);value('summaryColor',d.summaryColor);value('dateColor',d.dateColor||d.summaryColor);value('categoryBgColor',d.categoryBgColor);value('categoryTextColor',d.categoryTextColor);value('lowerBgColor',d.lowerBgColor);value('lowerOpacity',d.lowerOpacity);if($('#tiktokSafe'))$('#tiktokSafe').checked=d.tiktokSafe!==false;if($('#showSafeGuides'))$('#showSafeGuides').checked=d.showSafeGuides!==false;if($('#musicEnabled'))$('#musicEnabled').checked=!!d.musicEnabled;if($('#musicLoop'))$('#musicLoop').checked=d.musicLoop!==false;value('musicVolume',Number(d.musicVolume??20));value('voiceVolume',Number(d.voiceVolume??100));value('cannedVolume',Number(d.cannedVolume??100));if($('#transitionEnabled'))$('#transitionEnabled').checked=d.transitionEnabled!==false;value('transitionType',d.transitionType||'fade');value('transitionDuration',Number(d.transitionDuration||.7));if($('#verticalVideoBackgroundInfo'))$('#verticalVideoBackgroundInfo').textContent=d.verticalVideoBackground||'Sin fondo: se usará negro.';if($('#musicInfo'))$('#musicInfo').textContent=d.musicFile||'Sin música cargada.';updateRangeLabels();refreshDesignVisibility();}
function readDesignControls(){const existing=settings?.visual?.output||DESIGN_DEFAULT;return{format:$('#outputFormat').value,fontFamily:$('#fontFamily').value,dateFontFamily:$('#dateFontFamily').value,titleColor:$('#titleColor').value,summaryColor:$('#summaryColor').value,dateColor:$('#dateColor').value,categoryBgColor:$('#categoryBgColor').value,categoryTextColor:$('#categoryTextColor').value,lowerBgColor:$('#lowerBgColor').value,lowerOpacity:Number($('#lowerOpacity').value||.88),animation:$('#imageAnimation').value,motionSpeed:$('#motionSpeed').value,tiktokSafe:$('#tiktokSafe').checked,showSafeGuides:$('#showSafeGuides').checked,verticalVideoBackground:existing.verticalVideoBackground||'',verticalVideoBackgroundUrl:existing.verticalVideoBackgroundUrl||'',musicFile:existing.musicFile||'',musicUrl:existing.musicUrl||'',musicEnabled:$('#musicEnabled').checked,musicLoop:$('#musicLoop').checked,musicVolume:Number($('#musicVolume').value||0),voiceVolume:Number($('#voiceVolume').value||0),cannedVolume:Number($('#cannedVolume').value||0),transitionEnabled:$('#transitionEnabled').checked,transitionType:$('#transitionType').value||'fade',transitionDuration:Math.max(.2,Math.min(2,Number($('#transitionDuration').value)||.7))};}
function refreshDesignVisibility(){if(!$('#outputFormat'))return;const vertical=$('#outputFormat').value==='9:16';$('#verticalSafeOptions')?.classList.toggle('hidden',!vertical);$('#verticalVideoBackgroundOptions')?.classList.toggle('hidden',!vertical);if($('#designResolution'))$('#designResolution').textContent=vertical?'1080×1920 · 9:16':'1920×1080 · 16:9';}
function updateDesignFromControls(sendLive=true){if(!settings?.visual?.output)return;const d=readDesignControls();settings.visual.output={...settings.visual.output,...d};refreshDesignVisibility();refreshPreview();updateRangeLabels();if(sendLive)window.ECAPI.previewOutputDesign(d);}
function ttsProfileHint(name){return({safe_streaming:'Prioriza estabilidad mientras transmites con OBS.',balanced:'Equilibra velocidad y consumo de la computadora.',performance:'Prioriza generar la voz lo más rápido posible.'}[name]||'');}
function setQueueColorControls(colors={}){const c={...QUEUE_COLOR_DEFAULT,...colors};for(const [id,key] of [['queueColorRss','rss'],['queueColorGenerated','generated'],['queueColorContent','content'],['queueColorAd','ad'],['queueColorError','error']])if($('#'+id))$('#'+id).value=c[key];}
function readQueueColors(){return{rss:$('#queueColorRss')?.value||QUEUE_COLOR_DEFAULT.rss,generated:$('#queueColorGenerated')?.value||QUEUE_COLOR_DEFAULT.generated,content:$('#queueColorContent')?.value||QUEUE_COLOR_DEFAULT.content,ad:$('#queueColorAd')?.value||QUEUE_COLOR_DEFAULT.ad,error:$('#queueColorError')?.value||QUEUE_COLOR_DEFAULT.error};}
async function loadSettings(){
  if(!window.ECAPI)throw new Error('ECAPI no disponible');settings=await window.ECAPI.getSettings();if(!settings?.ai||!settings?.tts||!settings?.visual)throw new Error('Ajustes incompletos');
  settings.visual.output={...DESIGN_DEFAULT,...(settings.visual.output||{})};settings.visual.queueColors={...QUEUE_COLOR_DEFAULT,...(settings.visual.queueColors||{})};settings.canned={enabled:false,folder:'',adsFolder:'',insertAdAfterContent:true,emergency:true,interval:10,...(settings.canned||{})};settings.documents={folder:'',watch:false,targetSeconds:60,categoryMode:'auto',batchDate:'',priority:'normal',...(settings.documents||{})};
  $('#primary').value=settings.ai.primary;$('#backup1').value=settings.ai.backup1;$('#backup2').value=settings.ai.backup2;$('#claudeModel').value='claude-haiku-4-5-20251001';$('#geminiModel').value=settings.ai.geminiModel||'';$('#localBackupMode').value=settings.ai.localBackupMode||'on_demand';$('#localIdleMinutes').value=settings.ai.localIdleMinutes||5;
  $('#voiceSpeed').value=settings.tts.speed||1;$('#ttsPerformanceProfile').value=settings.tts.resourceMode||'safe_streaming';$('#ttsPerformanceHint').textContent=ttsProfileHint($('#ttsPerformanceProfile').value);$('#pronunciationClaudeVerify').checked=settings.tts.pronunciationClaudeVerify!==false;$('#pronunciationMaxSeconds').value=Math.max(5,Math.min(30,Number(settings.tts.pronunciationMaxSeconds)||15));
  $('#bufferReady').value=settings.automation.bufferReady||15;$('#pauseSeconds').value=settings.visual.pauseSeconds||2.5;$('#maxAge').value=settings.automation.maxAgeHours||6;$('#avoidRepeats').checked=settings.automation.avoidRepeats!==false;$('#fallbackInfo').textContent=settings.visual.fallbackImage||'Sin imagen de respaldo';
  $('#cannedEnabled').checked=!!settings.canned.enabled;$('#cannedEmergency').checked=settings.canned.emergency!==false;$('#adsAfterCanned').checked=settings.canned.insertAdAfterContent!==false;const interval=Number(settings.canned.interval)||0;if([0,10,20,30].includes(interval))$('#cannedInterval').value=String(interval);else{$('#cannedInterval').value='custom';$('#cannedCustomInterval').value=interval||15;}
  $('#documentDuration').value=String(settings.documents.targetSeconds||60);if(!['45','60','90'].includes($('#documentDuration').value))$('#documentDuration').value='60';$('#documentCategory').value=settings.documents.categoryMode||'auto';$('#documentBatchDate').value=settings.documents.batchDate||'';$('#documentPriority').value=settings.documents.priority||'normal';$('#documentWatch').checked=!!settings.documents.watch;$('#documentFolderInfo').textContent=settings.documents.folder||'Sin carpeta seleccionada.';
  setDesignControls(settings.visual.output);setQueueColorControls(settings.visual.queueColors);renderFeeds();refreshProviderUi();refreshPreview();refreshCannedIntervalUi();await refreshRuntimeStatus();await refreshPronunciationStatus();await refreshCannedList();await refreshAdsList();await refreshDocuments();try{refreshAutomation(await window.ECAPI.automationStatus());}catch{}try{refreshOutputStatus(await window.ECAPI.outputStatus());}catch{}
}
function loadRendererPart(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error(`No se pudo cargar ${src}`));document.body.appendChild(s);});}
(async()=>{if(!window.ECAPI)return;try{await loadRendererPart('renderer-ui.js');await loadRendererPart('renderer-actions.js');await loadRendererPart('renderer-patches.js');}catch(e){fatalInterface(`No se pudo cargar la interfaz: ${e.message||e}`);}})();
