'use strict';
const humanError=e=>{const m=String(e?.message||e||'');if(m.includes('MODEL_MISSING'))return'Falta descargar la IA local.';if(m.includes('OUTPUT_NOT_OPEN'))return'Abre la ventana de emisión antes de continuar.';if(m.includes('CANNED_FOLDER_MISSING'))return'Selecciona una carpeta de contenidos.';if(m.includes('ENLATADOS_DISABLED'))return'Activa Contenidos primero.';if(m.includes('EMISSION_NOT_RUNNING'))return'Inicia la emisión automática primero.';return m||'Ocurrió un problema.';};
$('#refresh').onclick=loadNews;$('#search').oninput=renderNews;$('#feedFilter').onchange=renderNews;
$('#openOutput').onclick=async()=>{try{if(currentOutputState?.open){const r=await window.ECAPI.closeOutput();if(r.cancelled)return status('Cierre cancelado.');status('Output cerrado.');}else{const r=await window.ECAPI.openOutput();refreshOutputStatus(r.state);status(`Output abierto en ${r.state?.resolution||'su tamaño de emisión'}.`);}}catch(e){status(`Output: ${humanError(e)}`);}};

$('#addFeed').onclick=()=>{const i=settings.rssFeeds.length;settings.rssFeeds.push({id:`rss-${Date.now()}`,name:'Nueva fuente',url:'',enabled:true,priority:50});renderFeeds();const row=$(`.feedrow[data-feed-index="${i}"]`);row?.classList.add('editing');row?.querySelector('.f-url')?.focus();};
$('#pickFallback').onclick=async()=>{try{const r=await window.ECAPI.pickFallback();if(r.ok){settings.visual.fallbackImage=r.path;settings.visual.fallbackImageUrl=r.url;$('#fallbackInfo').textContent=r.path;refreshPreview();status('Imagen de respaldo actualizada.');}}catch(e){status(`Imagen de respaldo: ${humanError(e)}`);}};
$('#save').onclick=()=>saveSettings().catch(e=>status(`Ajustes: ${humanError(e)}`));
['primary','backup1','backup2'].forEach(id=>$('#'+id).onchange=()=>{normalizeProviders(true);refreshLocalPolicyUi();});$('#localBackupMode').onchange=refreshLocalPolicyUi;

$('#testClaude').onclick=async()=>{try{await saveSettings({quiet:true});$('#claudeStatus').textContent='Comprobando conexión…';status('Comprobando Claude Haiku 4.5…');const r=await window.ECAPI.testProvider('claude');settings.ai.hasClaudeKey=!!r.keyStored;refreshProviderUi();$('#claudeStatus').textContent='Conexión correcta ✓ · Claude Haiku 4.5';status('Claude Haiku 4.5 está listo.');}catch(e){$('#claudeStatus').textContent=`No se pudo conectar: ${humanError(e)}`;status(`Claude: ${humanError(e)}`);}};
$('#testGemini').onclick=async()=>{try{await saveSettings({quiet:true});$('#geminiStatus').textContent='Comprobando conexión…';const r=await window.ECAPI.testProvider('gemini');settings.ai.hasGeminiKey=!!r.keyStored;refreshProviderUi();$('#geminiStatus').textContent='Conexión correcta ✓';status('Gemini está listo.');}catch(e){$('#geminiStatus').textContent=`No se pudo conectar: ${humanError(e)}`;status(`Gemini: ${humanError(e)}`);}};
$('#downloadModel').onclick=async()=>{$('#downloadModel').disabled=true;status('Descargando la IA local. Puede tardar varios minutos…');try{await window.ECAPI.downloadLocalModel();status('IA local descargada.');await refreshRuntimeStatus();}catch(e){status(`Descarga: ${humanError(e)}`);await refreshRuntimeStatus();}};
$('#startLocal').onclick=async()=>{status('Preparando IA local…');try{await window.ECAPI.startLocal();status('IA local preparada.');await refreshRuntimeStatus();}catch(e){status(`IA local: ${humanError(e)}`);}};
$('#stopLocal').onclick=async()=>{try{await window.ECAPI.stopLocal();status('IA local detenida.');await refreshRuntimeStatus();}catch(e){status(`IA local: ${humanError(e)}`);}};

$('#downloadPronunciationModel').onclick=async()=>{$('#downloadPronunciationModel').disabled=true;status('Descargando la mejora local de pronunciación…');try{await window.ECAPI.downloadPronunciationModel();status('Mejora de pronunciación descargada.');await refreshPronunciationStatus();}catch(e){status(`Pronunciación: ${humanError(e)}`);await refreshPronunciationStatus();}};
$('#testPronunciation').onclick=async()=>{status('Probando pronunciación y voz…');$('#pronunciationTestResult').textContent='Preparando prueba…';try{await saveSettings({quiet:true});const r=await window.ECAPI.testPronunciation();$('#pronunciationTestResult').textContent=`Texto preparado: ${r.text} · ${r.learningEntries||0} pronunciaciones guardadas`;$('#pronunciationTestAudio').src=r.audioUrl||'';status('Prueba de pronunciación lista.');await refreshPronunciationStatus();}catch(e){$('#pronunciationTestResult').textContent=`No se pudo completar: ${humanError(e)}`;status(`Pronunciación: ${humanError(e)}`);}};
$('#exportPronunciationLearning').onclick=async()=>{try{const r=await window.ECAPI.exportPronunciationLearning();if(r.cancelled)return;$('#pronunciationLearningInfo').textContent=`Copia guardada: ${r.path}`;status('Aprendizaje exportado.');}catch(e){status(`Exportar: ${humanError(e)}`);}};
$('#importPronunciationLearning').onclick=async()=>{try{const r=await window.ECAPI.importPronunciationLearning();if(r.cancelled)return;$('#pronunciationLearningInfo').textContent=`Importación completada · ${r.total||0} pronunciaciones disponibles`;status('Aprendizaje importado.');await refreshPronunciationStatus();}catch(e){status(`Importar: ${humanError(e)}`);}};
$('#clearPronunciationLearning').onclick=async()=>{if(!confirm('¿Borrar todo el aprendizaje automático de pronunciación?'))return;try{await window.ECAPI.clearPronunciationLearning();$('#pronunciationLearningInfo').textContent='Aprendizaje borrado.';status('Aprendizaje de pronunciación borrado.');await refreshPronunciationStatus();}catch(e){status(`Pronunciación: ${humanError(e)}`);}};
$('#pronunciationClaudeVerify').onchange=()=>saveSettings({quiet:true}).then(refreshPronunciationStatus).catch(e=>status(`Pronunciación: ${humanError(e)}`));$('#pronunciationMaxSeconds').onchange=()=>saveSettings({quiet:true}).catch(e=>status(`Pronunciación: ${humanError(e)}`));

$('#ttsPerformanceProfile').onchange=async()=>{$('#ttsPerformanceHint').textContent=ttsProfileHint($('#ttsPerformanceProfile').value);try{await saveSettings({quiet:true});await refreshRuntimeStatus();status(`Uso de recursos: ${$('#ttsPerformanceProfile option:checked').textContent}`);}catch(e){status(`Voz: ${humanError(e)}`);}};
$('#voice').onchange=()=>saveSettings({quiet:true}).then(()=>status(`Voz seleccionada: ${$('#voice option:checked').textContent}`)).catch(e=>status(`Voz: ${humanError(e)}`));$('#voiceSpeed').onchange=()=>saveSettings({quiet:true}).catch(e=>status(`Velocidad de voz: ${humanError(e)}`));
$('#optimizeTts').onclick=async()=>{const btn=$('#optimizeTts');btn.disabled=true;$('#ttsBenchmarkResult').textContent='Probando distintas configuraciones. Esto puede tardar unos minutos…';status('Optimizando la velocidad de voz para esta computadora…');try{await saveSettings({quiet:true});const r=await window.ECAPI.benchmarkTts();if(!r.ok)throw new Error('No se pudo completar la prueba');settings.tts.resourceMode=r.recommended;$('#ttsPerformanceProfile').value=r.recommended;$('#ttsPerformanceHint').textContent=ttsProfileHint(r.recommended);const label=$('#ttsPerformanceProfile option:checked').textContent;$('#ttsBenchmarkResult').textContent=`Optimización completada ✓ · EC recomienda: ${label}`;status(`Voz optimizada: ${label}.`);await refreshRuntimeStatus();}catch(e){$('#ttsBenchmarkResult').textContent=`No se pudo completar la optimización: ${humanError(e)}`;status(`Voz: ${humanError(e)}`);}finally{btn.disabled=false;}};

$('#pickDocumentFolder').onclick=async()=>{try{const r=await window.ECAPI.documentPickFolder();if(!r.ok)return;settings.documents.folder=r.folder;$('#documentFolderInfo').textContent=r.folder;documentScan=r;renderDocuments();$('#documentCount').textContent=`${r.count||0} documentos`;await saveSettings({quiet:true});status(`${r.count||0} documentos encontrados.`);}catch(e){status(`Generador de Notas: ${humanError(e)}`);}};
$('#refreshDocuments').onclick=async()=>{await refreshDocuments();status('Lista de documentos actualizada.');};
function documentOptions(){return{targetSeconds:Number($('#documentDuration').value)||60,categoryMode:$('#documentCategory').value||'auto',batchDate:$('#documentBatchDate').value||'',priority:$('#documentPriority').value||'normal'};}
async function enqueueDocumentPaths(paths){if(!paths.length)return status('Selecciona al menos un documento pendiente.');try{await saveSettings({quiet:true});status(`Agregando ${paths.length} documento${paths.length===1?'':'s'} al Generador…`);const r=await window.ECAPI.documentEnqueue(paths,documentOptions(),false);status(`${r.queued?.length||0} nota${r.queued?.length===1?'':'s'} agregada${r.queued?.length===1?'':'s'} a la cola${r.skipped?.length?` · ${r.skipped.length} ya procesada(s)`:''}${r.errors?.length?` · ${r.errors.length} con problema`:''}.`);refreshAutomation(r.state);await refreshDocuments();}catch(e){status(`Generador de Notas: ${humanError(e)}`);}}
$('#generateSelectedDocs').onclick=()=>{const paths=$$('.document-check:checked').map(x=>documentScan.files[+x.dataset.docI]?.path).filter(Boolean);enqueueDocumentPaths(paths);};
$('#generateAllDocs').onclick=()=>enqueueDocumentPaths((documentScan.files||[]).filter(x=>!x.processed).map(x=>x.path));
$('#documentWatch').onchange=()=>saveSettings({quiet:true}).then(()=>status($('#documentWatch').checked?'La carpeta se revisará automáticamente para detectar documentos nuevos.':'Revisión automática de la carpeta desactivada.')).catch(e=>status(`Generador: ${humanError(e)}`));
['documentDuration','documentCategory','documentBatchDate','documentPriority'].forEach(id=>$('#'+id).onchange=()=>saveSettings({quiet:true}).catch(e=>status(`Generador: ${humanError(e)}`)));
$('#resetDocumentProcessed').onclick=async()=>{if(!confirm('¿Permitir que EC vuelva a procesar los documentos de esta carpeta?'))return;try{await window.ECAPI.documentResetProcessed();await refreshDocuments();status('Los documentos pueden volver a procesarse.');}catch(e){status(`Generador: ${humanError(e)}`);}};
$('#closeManualReview').onclick=()=>{$('#manualReview').classList.add('hidden');currentStory=null;currentArticle=null;currentGenerated=null;currentAudio=null;status('Revisión cerrada.');};

$('#genScript').onclick=async()=>{if(!currentStory)return;await saveSettings({quiet:true});status('Reescribiendo noticia…');try{const r=await window.ECAPI.generate(currentStory,currentArticle||{});currentGenerated=r;$('#title').value=r.result.title||currentStory.title;$('#category').value=r.result.category||'ACTUALIDAD';$('#summary').value=r.result.summary||'';$('#script').value=r.result.script||'';refreshPreview();status(`Noticia preparada con ${providerName(r.provider)}.`);}catch(e){status(`Generación: ${humanError(e)}`);}};
$('#genVoice').onclick=async()=>{const script=$('#script').value.trim();if(!script)return status('Primero genera o escribe el texto para locución.');await saveSettings({quiet:true});status('Mejorando pronunciación y generando voz…');try{const head=$('#title').value.trim(),clean=x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(),spoken=head&&!clean(script.slice(0,Math.max(220,head.length*2))).startsWith(clean(head))?`${head}. ${script}`:script;currentAudio=await window.ECAPI.generateTts(spoken);$('#previewAudio').src=currentAudio.url;status(`Voz lista · audio de ${Math.round(currentAudio.durationSec||0)} segundos.`);}catch(e){status(`Voz: ${humanError(e)}`);}};
$('#sendOutput').onclick=async()=>{try{const r=await window.ECAPI.sendManualOutput({title:$('#title').value,category:$('#category').value,pubDate:currentStory?.pubDate||currentArticle?.pubDate||new Date().toISOString(),summary:$('#summary').value,image:effectiveImage(),fallbackImage:settings.visual.fallbackImageUrl||'',audioUrl:currentAudio?.url||'',audioDurationSec:currentAudio?.durationSec||0});if(r.cancelled)return status('Emisión cancelada.');status('Noticia enviada a Output.');}catch(e){status(`Output: ${humanError(e)}`);}};
$('#title').oninput=refreshPreview;$('#category').oninput=refreshPreview;$('#summary').oninput=refreshPreview;

$('#processStart').onclick=async()=>{await saveSettings({quiet:true});try{refreshAutomation(await window.ECAPI.processingStart());status('Preparación automática iniciada.');}catch(e){status(`Preparación: ${humanError(e)}`);}};$('#processPause').onclick=async()=>{try{refreshAutomation(await window.ECAPI.processingPause());status('Preparación pausada.');}catch(e){status(`Preparación: ${humanError(e)}`);}};$('#processResume').onclick=async()=>{try{refreshAutomation(await window.ECAPI.processingResume());status('Preparación reanudada.');}catch(e){status(`Preparación: ${humanError(e)}`);}};$('#processStop').onclick=async()=>{try{refreshAutomation(await window.ECAPI.processingStop());status('Preparación detenida. Las notas listas se conservan.');}catch(e){status(`Preparación: ${humanError(e)}`);}};
$('#emissionStart').onclick=async()=>{await saveSettings({quiet:true});try{refreshAutomation(await window.ECAPI.emissionStart());status('Emisión automática iniciada.');}catch(e){status(`Emisión: ${humanError(e)}`);}};$('#emissionPause').onclick=async()=>{try{refreshAutomation(await window.ECAPI.emissionPause());status('Emisión pausada.');}catch(e){status(`Emisión: ${humanError(e)}`);}};$('#emissionResume').onclick=async()=>{try{refreshAutomation(await window.ECAPI.emissionResume());status('Emisión reanudada.');}catch(e){status(`Emisión: ${humanError(e)}`);}};$('#emissionStop').onclick=async()=>{try{refreshAutomation(await window.ECAPI.emissionStop());status('Emisión detenida. Las notas listas permanecen en cola.');}catch(e){status(`Emisión: ${humanError(e)}`);}};
$('#clearQueue').onclick=async()=>{if(!confirm('¿Vaciar todos los elementos pendientes de la Cola de emisión?'))return;try{refreshAutomation(await window.ECAPI.clearQueue());status('Pendientes eliminados de la cola.');}catch(e){status(humanError(e));}};$('#resetSessionCounters').onclick=async()=>{try{refreshAutomation(await window.ECAPI.resetSessionCounters());status('Contadores visibles reiniciados.');}catch(e){status(`Contadores: ${humanError(e)}`);}};

$('#pickCannedFolder').onclick=async()=>{try{const r=await window.ECAPI.cannedPickFolder();if(!r.ok)return;settings.canned.folder=r.folder;await refreshCannedList();status(`${r.count||0} contenidos disponibles.`);}catch(e){status(`Contenidos: ${humanError(e)}`);}};$('#refreshCanned').onclick=async()=>{await refreshCannedList();status('Contenidos actualizados.');};$('#cannedInterval').onchange=async()=>{refreshCannedIntervalUi();await saveSettings({quiet:true});};$('#cannedCustomInterval').onchange=()=>saveSettings({quiet:true});$('#cannedEnabled').onchange=()=>saveSettings({quiet:true});$('#cannedEmergency').onchange=()=>saveSettings({quiet:true});
$('#launchCannedNow').onclick=async()=>{try{refreshAutomation(await window.ECAPI.cannedLaunchNow());status('Contenido programado para salir al terminar lo actual.');}catch(e){status(`Contenidos: ${humanError(e)}`);}};
$('#pickAdsFolder').onclick=async()=>{try{const r=await window.ECAPI.cannedPickAdsFolder();if(!r.ok)return;settings.canned.adsFolder=r.folder;settings.canned.insertAdAfterContent=true;$('#adsAfterCanned').checked=true;await refreshAdsList();status(`${r.count||0} anuncios disponibles.`);}catch(e){status(`Anuncios: ${humanError(e)}`);}};$('#refreshAds').onclick=async()=>{await refreshAdsList();status('Anuncios actualizados.');};$('#adsAfterCanned').onchange=async()=>{settings.canned.insertAdAfterContent=$('#adsAfterCanned').checked;try{await saveSettings({quiet:true});await refreshAdsList();}catch(e){status(`Anuncios: ${humanError(e)}`);}};

$('#pickVerticalVideoBackground').onclick=async()=>{try{const r=await window.ECAPI.pickVerticalVideoBackground();if(r.ok){settings.visual.output.verticalVideoBackground=r.path;settings.visual.output.verticalVideoBackgroundUrl=r.url;$('#verticalVideoBackgroundInfo').textContent=r.path;window.ECAPI.previewOutputDesign(design());status('Fondo vertical cargado.');}}catch(e){status(`Fondo vertical: ${humanError(e)}`);}};$('#clearVerticalVideoBackground').onclick=async()=>{try{await window.ECAPI.clearVerticalVideoBackground();settings.visual.output.verticalVideoBackground='';settings.visual.output.verticalVideoBackgroundUrl='';$('#verticalVideoBackgroundInfo').textContent='Sin fondo: se usará negro.';window.ECAPI.previewOutputDesign(design());status('Fondo vertical eliminado.');}catch(e){status(`Fondo vertical: ${humanError(e)}`);}};
$('#pickMusic').onclick=async()=>{try{const r=await window.ECAPI.pickMusic();if(r.ok){settings.visual.output.musicFile=r.path;settings.visual.output.musicUrl=r.url;$('#musicInfo').textContent=r.path;window.ECAPI.previewOutputDesign(design());status('Música cargada.');}}catch(e){status(`Música: ${humanError(e)}`);}};$('#clearMusic').onclick=async()=>{try{await window.ECAPI.clearMusic();settings.visual.output.musicFile='';settings.visual.output.musicUrl='';$('#musicInfo').textContent='Sin música cargada.';window.ECAPI.previewOutputDesign(design());status('Música eliminada.');}catch(e){status(`Música: ${humanError(e)}`);}};
const designIds=['outputFormat','fontFamily','dateFontFamily','imageAnimation','motionSpeed','lowerOpacity','titleColor','summaryColor','dateColor','categoryBgColor','categoryTextColor','lowerBgColor','tiktokSafe','showSafeGuides','musicEnabled','musicLoop','musicVolume','voiceVolume','cannedVolume','transitionEnabled','transitionType','transitionDuration'];designIds.forEach(id=>{const el=$('#'+id);if(!el)return;el.oninput=()=>updateDesignFromControls(true);el.onchange=()=>updateDesignFromControls(true);});
$('#saveDesign').onclick=async()=>{try{updateDesignFromControls(false);await saveSettings({quiet:true});window.ECAPI.previewOutputDesign(design());status('Diseño guardado.');}catch(e){status(`Diseño: ${humanError(e)}`);}};
$('#resetDesign').onclick=async()=>{if(!confirm('¿Restaurar el diseño visual predeterminado?'))return;const keep={verticalVideoBackground:settings.visual.output.verticalVideoBackground||'',verticalVideoBackgroundUrl:settings.visual.output.verticalVideoBackgroundUrl||'',musicFile:settings.visual.output.musicFile||'',musicUrl:settings.visual.output.musicUrl||''};settings.visual.output={...DESIGN_DEFAULT,...keep};setDesignControls(settings.visual.output);updateDesignFromControls(true);status('Diseño restaurado. Pulsa Guardar diseño para conservarlo.');};
['queueColorRss','queueColorGenerated','queueColorContent','queueColorAd','queueColorError'].forEach(id=>$('#'+id).oninput=()=>{settings.visual.queueColors=readQueueColors();renderQueue(automationState);});
$('#resetQueueColors').onclick=()=>{settings.visual.queueColors={...QUEUE_COLOR_DEFAULT};setQueueColorControls(settings.visual.queueColors);renderQueue(automationState);status('Colores predeterminados restaurados. Pulsa Guardar todos los cambios para conservarlos.');};

window.ECAPI.on('automation:state',refreshAutomation);window.ECAPI.on('automation:itemError',e=>{status(`Atención: ${e.title||'Elemento'} · ${humanError(e.error||'')}`);window.ECAPI.notify({title:'EC Automatic News',body:`${e.title||'Elemento'}: ${humanError(e.error||'')}`});});window.ECAPI.on('automation:engineError',e=>status(`Preparación: ${humanError(e.message||e)}`));
window.ECAPI.on('local:event',e=>{if(e?.type==='download-progress'){const pct=Math.max(0,Math.min(100,Number(e.percent)||0));$('#downloadProgress div').style.width=`${pct}%`;status(`Descargando IA local… ${pct.toFixed(0)}%`);}else if(e?.message)status(humanError(e.message));refreshRuntimeStatus().catch(()=>{});});
window.ECAPI.on('pronunciation:event',e=>{if(e?.type==='download-progress'){const pct=Math.max(0,Math.min(100,Number(e.percent)||0));$('#pronunciationProgress div').style.width=`${pct}%`;status(`Descargando mejora de pronunciación… ${pct.toFixed(0)}%`);}refreshPronunciationStatus().catch(()=>{});});window.ECAPI.on('output:state',refreshOutputStatus);

(async()=>{try{await loadSettings();await loadNews();if(!SELF_TEST)setTimeout(()=>checkAllFeeds().catch(()=>{}),700);status('EC listo.');}catch(e){fatalInterface(humanError(e));}})();
