'use strict';

(function installEc0325(){
  if(typeof settings==='undefined'||!settings||typeof renderQueue!=='function'||typeof readDesignControls!=='function'||typeof setDesignControls!=='function'||typeof refreshPreview!=='function'||!window.ECAPI||!window.__ec0324Installed||!window.__ec0324FinalUiInstalled||!window.__ec0324NewsSyncInstalled){setTimeout(installEc0325,100);return;}
  if(window.__ec0325Installed)return;window.__ec0325Installed=true;

  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const BASE_FONTS=['Arial','Segoe UI','Verdana','Georgia','Impact'];
  const ELEMENTS=[
    {id:'title',label:'Titular',family:'titleFontFamily',variant:'titleFontVariant',size:'titleFontSize',upper:'titleUppercase',color:'titleColor',fallbackSize:70},
    {id:'summary',label:'Bajada',family:'summaryFontFamily',variant:'summaryFontVariant',size:'summaryFontSize',upper:'summaryUppercase',color:'summaryColor',fallbackSize:34},
    {id:'category',label:'Categoría',family:'categoryFontFamily',variant:'categoryFontVariant',size:'categoryFontSize',upper:'categoryUppercase',color:'categoryTextColor',fallbackSize:28},
    {id:'date',label:'Fecha',family:'dateFontFamily',variant:'dateFontVariant',size:'dateFontSize',upper:'dateUppercase',color:'dateColor',fallbackSize:27},
    {id:'exclusive',label:'Exclusivo',family:'exclusiveFontFamily',variant:'exclusiveFontVariant',size:'exclusiveFontSize',upper:'exclusiveUppercase',color:'exclusiveTextColor',fallbackSize:24}
  ];
  const VARIANTS=[['regular','Regular',400,'normal'],['medium','Medium',500,'normal'],['semibold','Semibold',600,'normal'],['bold','Bold',700,'normal'],['extrabold','Extra Bold',800,'normal'],['black','Black',900,'normal'],['italic','Italic',400,'italic'],['bolditalic','Bold Italic',700,'italic']];
  const variantInfo=value=>{const v=VARIANTS.find(x=>x[0]===value)||VARIANTS[0];return{weight:v[2],style:v[3]};};
  const rgba=(hex,a)=>{const m=String(hex||'#000').replace('#',''),h=m.length===3?m.split('').map(x=>x+x).join(''):m,n=parseInt(h,16);return Number.isNaN(n)?`rgba(0,0,0,${a})`:`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`;};
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').replace(/\s+/g,' ').trim();
  let fontData={installed:[...BASE_FONTS],custom:[]};

  function hideOldDesignControls(){const hide=el=>{if(el)el.style.display='none';};hide(q('#typography0324'));hide(q('#exclusiveDesign0324'));for(const id of ['fontFamily','dateFontFamily','lowerOpacity'])hide(q('#'+id)?.closest('label'));const colors=q('#titleColor')?.closest('.color-grid');if(colors){hide(colors);const h=colors.previousElementSibling;if(h?.matches('h3,.minor-title'))hide(h);}}
  function familyOptions(selected='Arial'){const names=[...new Set([...BASE_FONTS,...(fontData.custom||[]).map(x=>x.family)])];return names.map(n=>`<option value="${esc(n)}"${n===selected?' selected':''}>${esc(n)}</option>`).join('');}
  function variantOptions(selected='regular'){return VARIANTS.map(([v,l])=>`<option value="${v}"${v===selected?' selected':''}>${l}</option>`).join('');}
  function typographyRows(){return ELEMENTS.map(x=>`<div class="ec25-design-row" data-element="${x.id}"><div class="ec25-row-label">${x.label}</div><select id="ec25-${x.id}-family" class="ec25-family">${familyOptions('Arial')}</select><select id="ec25-${x.id}-variant" class="ec25-variant">${variantOptions('regular')}</select><input id="ec25-${x.id}-size" class="ec25-size" type="number" min="8" max="140" step="1" value="${x.fallbackSize}"><button id="ec25-${x.id}-upper" class="ec25-upper dark" type="button" title="Mostrar en mayúsculas">TT</button><input id="ec25-${x.id}-color" class="ec25-text-color" type="color"></div>`).join('');}
  function bgRow(id,label,withRadius=true){return`<div class="ec25-bg-row" data-bg="${id}"><div class="ec25-row-label">${label}</div><div class="ec25-color-control"><span class="ec25-color-icon">■</span><input id="ec25-${id}-bg" type="color"></div>${withRadius?`<div class="ec25-radius-control" title="Radio de esquinas"><span class="ec25-radius-icon">▢</span><input id="ec25-${id}-radius" type="number" min="0" max="40" step="1"></div>`:'<div class="ec25-radius-spacer"></div>'}<div class="ec25-opacity-control"><span class="ec25-opacity-icon">◐</span><input id="ec25-${id}-opacity-range" type="range" min="0" max="100" step="1"><input id="ec25-${id}-opacity-number" class="ec25-opacity-number" type="number" min="0" max="100" step="1"><span>%</span></div></div>`;}
  function injectDesignEditor(){
    if(q('#ec0325DesignEditor'))return;const anchor=q('#typography0324')||q('#imageAnimation')?.closest('.form-grid');if(!anchor)return;
    const wrap=document.createElement('div');wrap.id='ec0325DesignEditor';wrap.innerHTML=`<div class="subcard ec25-design-block"><div class="section-head"><h3>Tipografías por elemento</h3><span class="mini-pill">COMPACTO</span></div><div class="ec25-design-head"><span>Elemento</span><span>Fuente</span><span>Variante</span><span>Tamaño</span><span>Mayús.</span><span>Color</span></div>${typographyRows()}<div class="ec25-font-actions"><button id="ec25ImportFont" class="dark">Importar TTF / OTF</button><span class="note">5 fuentes base + tipografías importadas manualmente.</span></div><div id="ec25CustomFonts" class="font-manager-list"></div></div><div class="subcard ec25-design-block"><div class="section-head"><h3>Fondos y casillas</h3><span class="mini-pill">COLOR · OPACIDAD</span></div><div class="ec25-bg-head"><span>Elemento</span><span>Color</span><span>Esquinas</span><span>Opacidad</span></div>${bgRow('category','Categoría',true)}${bgRow('exclusive','Exclusivo',true)}${bgRow('lower','Franja inferior',false)}</div>`;
    anchor.insertAdjacentElement('afterend',wrap);hideOldDesignControls();
    for(const el of qa('#ec0325DesignEditor input,#ec0325DesignEditor select')){el.addEventListener('input',()=>applyDesignEditor(true));el.addEventListener('change',()=>applyDesignEditor(true));}
    for(const x of ELEMENTS){q(`#ec25-${x.id}-upper`)?.addEventListener('click',e=>{e.currentTarget.classList.toggle('active');e.currentTarget.setAttribute('aria-pressed',e.currentTarget.classList.contains('active')?'true':'false');applyDesignEditor(true);});}
    for(const id of ['category','exclusive','lower'])bindOpacity(id);
    q('#ec25ImportFont').onclick=async()=>{try{const r=await window.ECAPI.importFont();if(r?.cancelled)return;await loadFonts();applyDesignEditor(true);status(`Fuente importada: ${r?.item?.family||'lista'}.`);}catch(e){status(`Tipografía: ${typeof humanError==='function'?humanError(e):(e.message||e)}`);}};
  }
  function bindOpacity(id){const range=q(`#ec25-${id}-opacity-range`),num=q(`#ec25-${id}-opacity-number`);if(!range||!num)return;const sync=(from,to)=>{let v=Math.max(0,Math.min(100,Number(from.value)||0));from.value=String(v);to.value=String(v);applyDesignEditor(true);};range.addEventListener('input',()=>sync(range,num));num.addEventListener('input',()=>sync(num,range));}
  function installFonts(list){for(const x of list||[]){if(!x?.family||!x?.url)continue;try{const face=new FontFace(x.family,`url("${String(x.url).replace(/"/g,'%22')}")`);face.load().then(f=>document.fonts.add(f)).catch(()=>{});}catch{}}}
  function renderCustomFonts(){const box=q('#ec25CustomFonts');if(!box)return;const custom=fontData.custom||[];box.innerHTML=custom.length?custom.map(x=>`<div class="font-manager-item"><div class="font-manager-name">${esc(x.family)}<small>Tipografía importada en EC</small></div><div class="font-actions"><button class="dark compact ec25-delete-font" data-family="${esc(x.family)}">Eliminar</button></div></div>`).join(''):'<div class="note">No hay tipografías importadas.</div>';qa('.ec25-delete-font').forEach(b=>b.onclick=async()=>{const family=b.dataset.family;if(!confirm(`¿Eliminar la tipografía “${family}”?`))return;try{await window.ECAPI.deleteFont(family);for(const x of ELEMENTS)if(settings.visual.output[x.family]===family)settings.visual.output[x.family]='Arial';await loadFonts();setEditor(settings.visual.output);applyDesignEditor(true);}catch(e){status(`Tipografía: ${typeof humanError==='function'?humanError(e):(e.message||e)}`);}});}
  async function loadFonts(){try{const selected=Object.fromEntries(ELEMENTS.map(x=>[x.id,q(`#ec25-${x.id}-family`)?.value||settings.visual.output[x.family]||'Arial']));const r=await window.ECAPI.fontsList();fontData={installed:[...BASE_FONTS],custom:Array.isArray(r?.custom)?r.custom:[]};installFonts(fontData.custom);for(const x of ELEMENTS){const sel=q(`#ec25-${x.id}-family`);if(!sel)continue;const names=[...new Set([...BASE_FONTS,...fontData.custom.map(f=>f.family)])];sel.innerHTML=familyOptions();sel.value=names.includes(selected[x.id])?selected[x.id]:'Arial';}settings.visual.output.customFonts=fontData.custom.map(x=>({family:x.family,url:x.url}));renderCustomFonts();}catch(e){status(`Tipografías: ${typeof humanError==='function'?humanError(e):(e.message||e)}`);}}
  function setOpacity(id,value){const p=Math.round(Math.max(0,Math.min(1,Number(value)||0))*100);const r=q(`#ec25-${id}-opacity-range`),n=q(`#ec25-${id}-opacity-number`);if(r)r.value=String(p);if(n)n.value=String(p);}
  function setEditor(d={}){for(const x of ELEMENTS){const family=q(`#ec25-${x.id}-family`),variant=q(`#ec25-${x.id}-variant`),size=q(`#ec25-${x.id}-size`),upper=q(`#ec25-${x.id}-upper`),color=q(`#ec25-${x.id}-color`);if(family)family.value=[...family.options].some(o=>o.value===(d[x.family]||'Arial'))?(d[x.family]||'Arial'):'Arial';if(variant)variant.value=d[x.variant]||({title:'black',summary:'regular',category:'black',date:'medium',exclusive:'extrabold'}[x.id]||'regular');if(size)size.value=String(Number(d[x.size])||x.fallbackSize);const on=d[x.upper]??({category:true,date:true,exclusive:true}[x.id]||false);upper?.classList.toggle('active',!!on);upper?.setAttribute('aria-pressed',on?'true':'false');if(color)color.value=d[x.color]||({title:'#FFFFFF',summary:'#F3F3F3',category:'#000000',date:'#F3F3F3',exclusive:'#000000'}[x.id]);}
    if(q('#ec25-category-bg'))q('#ec25-category-bg').value=d.categoryBgColor||'#F7C600';if(q('#ec25-exclusive-bg'))q('#ec25-exclusive-bg').value=d.exclusiveBgColor||'#F7C600';if(q('#ec25-lower-bg'))q('#ec25-lower-bg').value=d.lowerBgColor||'#000000';if(q('#ec25-category-radius'))q('#ec25-category-radius').value=String(Number(d.categoryRadius)||0);if(q('#ec25-exclusive-radius'))q('#ec25-exclusive-radius').value=String(Number(d.exclusiveRadius)||5);setOpacity('category',d.categoryBgOpacity==null?1:d.categoryBgOpacity);setOpacity('exclusive',d.exclusiveBgOpacity==null?1:d.exclusiveBgOpacity);setOpacity('lower',d.lowerOpacity==null?.88:d.lowerOpacity);
  }
  function readEditor(){const out={};for(const x of ELEMENTS){const variant=q(`#ec25-${x.id}-variant`)?.value||'regular',v=variantInfo(variant);out[x.family]=q(`#ec25-${x.id}-family`)?.value||'Arial';out[x.variant]=variant;out[x.size]=Math.max(8,Math.min(140,Number(q(`#ec25-${x.id}-size`)?.value)||x.fallbackSize));out[x.upper]=q(`#ec25-${x.id}-upper`)?.classList.contains('active')||false;out[x.color]=q(`#ec25-${x.id}-color`)?.value||'#FFFFFF';out[`${x.id}FontWeight`]=v.weight;out[`${x.id}FontItalic`]=v.style==='italic';}
    out.fontFamily=out.titleFontFamily;out.categoryBgColor=q('#ec25-category-bg')?.value||'#F7C600';out.exclusiveBgColor=q('#ec25-exclusive-bg')?.value||'#F7C600';out.lowerBgColor=q('#ec25-lower-bg')?.value||'#000000';out.categoryRadius=Math.max(0,Math.min(40,Number(q('#ec25-category-radius')?.value)||0));out.exclusiveRadius=Math.max(0,Math.min(40,Number(q('#ec25-exclusive-radius')?.value)||0));out.categoryBgOpacity=(Number(q('#ec25-category-opacity-number')?.value)||0)/100;out.exclusiveBgOpacity=(Number(q('#ec25-exclusive-opacity-number')?.value)||0)/100;out.lowerOpacity=(Number(q('#ec25-lower-opacity-number')?.value)||0)/100;out.exclusiveEnabled=true;out.exclusiveText='EXCLUSIVO';out.exclusiveBorderWidth=0;out.exclusiveBorderColor=out.exclusiveBgColor;return out;}

  const baseRead=readDesignControls,baseSet=setDesignControls,baseRefresh=refreshPreview;
  readDesignControls=function(){return{...baseRead(),...readEditor()};};
  setDesignControls=function(d){baseSet(d);setEditor(d||{});renderWysiwyg();};
  refreshPreview=function(){const r=baseRefresh();renderWysiwyg();return r;};
  function applyDesignEditor(sendLive=true){if(!settings?.visual?.output)return;const d=readDesignControls();settings.visual.output={...settings.visual.output,...d};renderWysiwyg();if(sendLive)window.ECAPI.previewOutputDesign(d);}

  function ensureWysiwyg(){const frame=q('#designPreview');if(!frame||frame.dataset.ec25==='1')return;frame.dataset.ec25='1';frame.className='ec25-preview-frame';frame.innerHTML=`<div class="ec25-preview-stage"><img id="designPreviewImg" class="ec25-preview-image" alt=""><div class="ec25-preview-shade"></div><div class="ec25-preview-copy"><div class="ec25-preview-meta"><span id="designPreviewCat" class="ec25-preview-cat">ACTUALIDAD</span><span id="designPreviewDate" class="ec25-preview-date">20 AGO 2026</span><span class="preview-exclusive ec25-preview-exclusive">EXCLUSIVO</span></div><div id="designPreviewTitle" class="ec25-preview-title">Titular de ejemplo para visualizar el diseño</div><div id="designPreviewSummary" class="ec25-preview-summary">Esta es una bajada de ejemplo para comprobar tipografía, colores, posición y movimiento.</div></div><div class="ec25-safe-guide"></div></div>`;const ro=new ResizeObserver(()=>renderWysiwyg());ro.observe(frame);}
  function styleText(el,d,prefix,size,mult=1){if(!el)return;const variant=variantInfo(d[`${prefix}FontVariant`]||'regular');el.style.fontFamily=`"${d[`${prefix}FontFamily`]||d.fontFamily||'Arial'}",sans-serif`;el.style.fontSize=`${Math.max(8,Number(d[`${prefix}FontSize`])||size)*mult}px`;el.style.fontWeight=String(Number(d[`${prefix}FontWeight`])||variant.weight);el.style.fontStyle=d[`${prefix}FontItalic`]||variant.style==='italic'?'italic':'normal';el.style.textTransform=d[`${prefix}Uppercase`]?'uppercase':'none';}
  function renderWysiwyg(){ensureWysiwyg();const frame=q('#designPreview'),stage=frame?.querySelector('.ec25-preview-stage');if(!frame||!stage||!settings?.visual?.output)return;const d={...settings.visual.output,...readEditor()},vertical=d.format==='9:16',w=vertical?1080:1920,h=vertical?1920:1080;stage.style.width=`${w}px`;stage.style.height=`${h}px`;const fw=Math.max(1,frame.clientWidth||700),scale=fw/w;frame.style.height=`${Math.round(h*scale)}px`;stage.style.transform=`scale(${scale})`;stage.dataset.format=vertical?'9:16':'16:9';const image=q('#designPreviewImg'),src=(typeof effectiveImage==='function'?effectiveImage():'')||settings.visual?.fallbackImageUrl||'';if(src&&image.src!==src)image.src=src;const shade=stage.querySelector('.ec25-preview-shade');shade.style.background=`linear-gradient(transparent ${vertical?38:42}%,${rgba(d.lowerBgColor||'#000000',d.lowerOpacity==null?.88:Number(d.lowerOpacity))} 100%)`;const copy=stage.querySelector('.ec25-preview-copy');copy.style.left=vertical?'70px':'64px';copy.style.right=vertical&&d.tiktokSafe?'205px':vertical?'70px':'64px';copy.style.bottom=vertical&&d.tiktokSafe?'420px':vertical?'95px':'54px';const cat=q('#designPreviewCat'),date=q('#designPreviewDate'),ex=stage.querySelector('.ec25-preview-exclusive'),title=q('#designPreviewTitle'),summary=q('#designPreviewSummary');cat.style.color=d.categoryTextColor||'#000';cat.style.background=rgba(d.categoryBgColor||'#F7C600',d.categoryBgOpacity==null?1:Number(d.categoryBgOpacity));cat.style.borderRadius=`${Math.max(0,Number(d.categoryRadius)||0)}px`;cat.style.padding=vertical?'10px 14px':'10px 15px';styleText(cat,d,'category',28,vertical?.93:1);date.style.color=d.dateColor||d.summaryColor||'#F3F3F3';styleText(date,d,'date',27,vertical?.89:1);ex.style.color=d.exclusiveTextColor||'#000';ex.style.background=rgba(d.exclusiveBgColor||'#F7C600',d.exclusiveBgOpacity==null?1:Number(d.exclusiveBgOpacity));ex.style.borderRadius=`${Math.max(0,Number(d.exclusiveRadius)||0)}px`;ex.style.padding='9px 13px';styleText(ex,d,'exclusive',24,vertical?.9:1);title.style.color=d.titleColor||'#FFF';styleText(title,d,'title',70,vertical?.83:1);title.style.maxWidth=vertical?'100%':'1580px';summary.style.color=d.summaryColor||'#F3F3F3';styleText(summary,d,'summary',34,vertical?.88:1);summary.style.maxWidth=vertical?'100%':'1500px';const guide=stage.querySelector('.ec25-safe-guide');guide.style.display=vertical&&d.tiktokSafe&&d.showSafeGuides?'block':'none';}

  function sourceTypeName0325(type){return({rss:'NOTICIA',generated:'NOTA GENERADA',content:'CONTENIDO',ad:'ANUNCIO'}[type]||String(type||'ELEMENTO').toUpperCase());}
  function stateBadge(status){const m={PROCESANDO:['PREPARANDO','prep'],LISTA:['LISTA','ok'],'AL AIRE':['AL AIRE','live'],EMITIDA:['EMITIDA','ok'],OMITIDA:['OMITIDA','muted'],ERROR:['ERROR','error'],PROGRAMADO:['PROGRAMADO','neutral'],PENDIENTE:['PENDIENTE','neutral']};return m[status]||[status||'','neutral'];}
  function stageText(x){if(x.reason)return`${x.status==='OMITIDA'?'Omitida':'Error'} · ${x.reason}`;if(x.planText)return x.planText;const m={article:'Validando fuente y contenido',ai:'Generando texto con IA',pronunciation:'Ajustando pronunciación',tts:'Generando voz',ready:'Lista para emitir'};return m[x.stage]||'';}
  function metricsText(x){const m=x.metrics||{},p=[];if(m.elapsedMs)p.push(`Texto ${(Number(m.elapsedMs)/1000).toFixed(1)} s`);if(m.pronunciationElapsedMs)p.push(`Pronunciación ${(Number(m.pronunciationElapsedMs)/1000).toFixed(1)} s`);if(m.ttsElapsedMs)p.push(`Voz ${(Number(m.ttsElapsedMs)/1000).toFixed(1)} s`);if(m.audioDurationSec)p.push(`Audio ${Math.round(Number(m.audioDurationSec))} s`);return p.join(' · ');}
  function queueKey(x,i){return x.id||`history:${x.storyKey||x.storyUrl||x.title||i}:${x.status}:${x.emittedAt||i}`;}
  function renderQueue0325(s){const box=q('#queue');if(!box)return;const items=s?.queue||[],colors={rss:'#2E7D32',generated:'#2563EB',content:'#D97706',ad:'#7C3AED',error:'#B91C1C',exclusive:'#C89B16',...(settings?.visual?.queueColors||{})};if(!items.length){if(box.children.length!==1||!box.querySelector('.empty'))box.innerHTML='<div class="empty">Sin actividad</div>';return;}box.querySelector('.empty')?.remove();const existing=new Map(qa('#queue .queue-item').map(n=>[n.dataset.key,n])),wanted=new Set();items.forEach((x,i)=>{const key=queueKey(x,i);wanted.add(key);let node=existing.get(key);if(!node){node=document.createElement('div');node.className='queue-item ec25-queue-item';node.dataset.key=key;box.appendChild(node);}const exclusive=!!x.isExclusive,[badge,badgeClass]=stateBadge(x.status),type=x.sourceType||'rss',typeColor=colors[type]||colors.rss,leftColor=x.status==='ERROR'?colors.error:exclusive?colors.exclusive:typeColor,source=x.feedName||(type==='generated'?'Generador de Notas':''),section=x.category||'',meta=[source,section].filter(Boolean).join(' · '),human=stageText(x),timing=metricsText(x),sig=JSON.stringify([x.title,x.status,x.stage,x.reason,x.error,x.isExclusive,meta,timing,x.selectionReason,x.selectionScore,x.planText]);if(node.dataset.sig!==sig){node.dataset.sig=sig;node.style.setProperty('--type-color',leftColor);node.innerHTML=`<div class="queue-main"><span class="queue-index">${i+1}.</span><div class="queue-text"><div class="queue-headline"><span class="queue-type" style="--badge-color:${esc(typeColor)}">${esc(sourceTypeName0325(type))}</span>${exclusive?`<span class="queue-exclusive" style="--exclusive-color:${esc(colors.exclusive)}">EXCLUSIVO</span>`:''}<span class="queue-title">${esc(x.title||'')}</span></div>${meta?`<div class="ec25-source-meta">${esc(meta)}</div>`:''}${human?`<div class="queue-meta">${esc(human)}</div>`:''}${timing?`<div class="queue-meta">${esc(timing)}</div>`:''}${x.error&&!x.reason?`<div class="queue-meta ec25-error-text">${esc(x.error)}</div>`:''}<details class="technical-details"><summary>Ver detalles técnicos</summary><div>${esc([x.provider,x.model].filter(Boolean).join(' · ')||'Sin datos de IA')}</div>${x.selectionReason?`<div>Selección: ${esc(x.selectionReason)}${x.selectionScore?` · puntaje ${esc(x.selectionScore)}`:''}</div>`:''}${x.storyUrl?`<div class="ec25-tech-url">${esc(x.storyUrl)}</div>`:''}</details></div><span class="queue-badge ${badgeClass}">${esc(badge)}</span></div>`;}const ref=box.children[i];if(ref!==node)box.insertBefore(node,ref||null);});for(const [key,node] of existing)if(!wanted.has(key))node.remove();}
  renderQueue=renderQueue0325;
  const refreshAutoBase=refreshAutomation;refreshAutomation=function(s){const r=refreshAutoBase(s);renderQueue0325(s);return r;};

  const renderNewsBase=renderNews;renderNews=function(){const r=renderNewsBase();for(const card of qa('#newsList .newsItem')){const meta=card.querySelector('.meta');if(!meta)continue;const paragraphs=[...meta.querySelectorAll(':scope > p')];if(paragraphs.length>=2){const category=(paragraphs[0].textContent.split('·').pop()||'').trim(),desc=paragraphs[1].textContent.trim();if(desc&&norm(desc)===norm(category))paragraphs[1].style.display='none';}}return r;};

  injectDesignEditor();ensureWysiwyg();loadFonts().then(()=>{setEditor(settings.visual.output);renderWysiwyg();});
  setDesignControls(settings.visual.output);refreshPreview();
  window.ECAPI.automationStatus?.().then(s=>renderQueue0325(s)).catch(()=>{});
})();
