'use strict';
(function installProfiles0329(){
  if(window.__ec0329Installed)return;
  if(!window.ECAPI||typeof settings==='undefined'||!settings||typeof status!=='function'){setTimeout(installProfiles0329,140);return;}
  window.__ec0329Installed=true;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let profileState=null,popover=null,busy=false;
  const DEFAULT_EXCLUSIVE='#D4A514';

  function layer(){let x=q('#ec29ModalLayer');if(!x){x=document.createElement('div');x.id='ec29ModalLayer';x.className='ec29-modal-layer';x.style.display='none';document.body.appendChild(x);}return x;}
  function closeModal(){const x=layer();x.style.display='none';x.innerHTML='';}
  function modal({title='',body='',wide=false,buttons=[]}){return new Promise(resolve=>{const x=layer();x.innerHTML=`<div class="ec29-modal${wide?' wide':''}"><h2>${esc(title)}</h2>${body}<div class="ec29-actions"></div></div>`;const actions=x.querySelector('.ec29-actions');for(const b of buttons){const btn=document.createElement('button');btn.textContent=b.label;btn.className=b.className||'';btn.onclick=()=>{closeModal();resolve(b.value);};actions.appendChild(btn);}x.style.display='flex';});}
  function busyOverlay(text='Procesando…'){let x=q('#ec29Busy');if(!x){x=document.createElement('div');x.id='ec29Busy';x.className='ec29-busy';document.body.appendChild(x);}x.textContent=text;x.style.display='flex';busy=true;}
  function clearBusy(){const x=q('#ec29Busy');if(x)x.style.display='none';busy=false;}
  function active(){return profileState?.profiles?.find(p=>p.active)||profileState?.active||null;}
  function paintProfile(){const p=active(),name=p?.name||'Sin perfil',color=p?.color||'#aaa';if(q('#ec29ProfileName')){q('#ec29ProfileName').textContent=name;q('#ec29ProfileName').style.color=color;}if(q('#ec29HeaderProfile')){q('#ec29HeaderProfile').textContent=p?name:'';q('#ec29HeaderProfile').style.color=color;}if(q('#ec29ProfileButton'))q('#ec29ProfileButton').disabled=!profileState?.hasProfiles;}
  function injectDock(){const aside=q('aside');if(!aside||q('#ec29ProfileDock'))return;const dock=document.createElement('div');dock.id='ec29ProfileDock';dock.className='ec29-profile-dock';dock.innerHTML=`<div class="ec29-profile-caption">PERFIL</div><button id="ec29ProfileButton" class="ec29-profile-button" type="button"><span id="ec29ProfileName" class="ec29-profile-name">Sin perfil</span><span class="ec29-profile-arrow">▴</span></button>`;aside.appendChild(dock);q('#ec29ProfileButton').onclick=togglePopover;const header=q('header .header-left')||q('header');if(header&&!q('#ec29HeaderProfile')){const h=document.createElement('span');h.id='ec29HeaderProfile';h.className='ec29-header-profile';header.appendChild(h);}window.addEventListener('resize',()=>{if(popover)positionPopover();});document.addEventListener('click',e=>{if(popover&&!popover.contains(e.target)&&!q('#ec29ProfileButton')?.contains(e.target))hidePopover();});}
  function positionPopover(){if(!popover)return;const b=q('#ec29ProfileButton')?.getBoundingClientRect();if(!b)return;const width=Math.min(320,window.innerWidth-20),left=Math.max(10,Math.min(window.innerWidth-width-10,b.left));popover.style.width=`${width}px`;popover.style.left=`${left}px`;popover.style.bottom=`${Math.max(10,window.innerHeight-b.top+6)}px`;}
  function hidePopover(){popover?.remove();popover=null;}
  function togglePopover(e){e?.stopPropagation();if(popover){hidePopover();return;}popover=document.createElement('div');popover.className='ec29-popover';const profiles=profileState?.profiles||[];popover.innerHTML=`<button class="ec29-add" data-action="add">+ Añadir nuevo perfil</button>${profiles.map(p=>`<button data-profile="${esc(p.id)}"><span style="color:${esc(p.color)};font-weight:850;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(p.name)}</span><span class="ec29-check">${p.active?'✓':''}</span></button>`).join('')}<button class="ec29-manage" data-action="manage">Administrar perfiles</button>`;document.body.appendChild(popover);positionPopover();popover.querySelector('[data-action=add]').onclick=()=>{hidePopover();editProfile(null);};popover.querySelector('[data-action=manage]').onclick=()=>{hidePopover();showAdmin();};popover.querySelectorAll('[data-profile]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.profile;hidePopover();requestSwitch(id);});}

  async function profileForm(initial=null,title='Crear perfil'){const colors=profileState?.colors||['#F7C600','#22C55E','#3B82F6','#A855F7','#F97316','#EC4899','#06B6D4','#EF4444'],name=initial?.name||'',current=initial?.color||colors[0];const x=layer();x.innerHTML=`<div class="ec29-modal"><h2>${esc(title)}</h2><label>Nombre<input id="ec29ProfileInput" type="text" maxlength="80" value="${esc(name)}" placeholder="Ej. El Comercio"></label><div id="ec29Palette" class="ec29-palette">${colors.map(c=>`<button type="button" class="ec29-swatch${c.toUpperCase()===current.toUpperCase()?' active':''}" data-color="${c}" style="background:${c}" aria-label="Seleccionar ${c}"></button>`).join('')}<input id="ec29CustomColor" class="ec29-custom-color" type="color" value="${esc(current)}" aria-label="Color personalizado"></div><div id="ec29ProfilePreview" class="ec29-profile-preview" style="color:${esc(current)}">${esc(name||'NOMBRE DEL PERFIL')}</div><div class="ec29-actions"><button id="ec29Cancel" class="dark">Cancelar</button><button id="ec29Save">${initial?'Guardar cambios':'Crear perfil'}</button></div></div>`;x.style.display='flex';let selected=current;const input=q('#ec29ProfileInput'),preview=q('#ec29ProfilePreview'),custom=q('#ec29CustomColor');const render=()=>{preview.textContent=(input.value.trim()||'NOMBRE DEL PERFIL').toUpperCase();preview.style.color=selected;qa('#ec29Palette .ec29-swatch').forEach(s=>s.classList.toggle('active',s.dataset.color.toUpperCase()===selected.toUpperCase()));};input.oninput=render;qa('#ec29Palette .ec29-swatch').forEach(s=>s.onclick=()=>{selected=s.dataset.color;custom.value=selected;render();});custom.oninput=()=>{selected=custom.value.toUpperCase();render();};return new Promise(resolve=>{q('#ec29Cancel').onclick=()=>{closeModal();resolve(null);};q('#ec29Save').onclick=()=>{const n=input.value.trim();if(!n){input.focus();return;}closeModal();resolve({name:n,color:selected});};input.focus();});}
  async function editProfile(p){const data=await profileForm(p,p?'Editar perfil':'Crear perfil');if(!data)return;busyOverlay(p?'Guardando perfil…':'Creando perfil…');try{if(p)await window.ECAPI.profileUpdate({...data,id:p.id});else await window.ECAPI.profileCreate(data);location.reload();}catch(e){clearBusy();status(`Perfiles: ${e.message||e}`);await modal({title:'No se pudo guardar',body:`<p>${esc(e.message||e)}</p>`,buttons:[{label:'Cerrar',value:true}]});}}
  async function duplicateProfile(p){const data=await profileForm({name:`${p.name} - copia`,color:p.color},'Duplicar perfil');if(!data)return;busyOverlay('Duplicando perfil…');try{await window.ECAPI.profileDuplicate({id:p.id,...data});clearBusy();profileState=await window.ECAPI.profileStatus();paintProfile();showAdmin();}catch(e){clearBusy();status(`Duplicar: ${e.message||e}`);}}
  async function deleteProfile(p){if(p.active){await modal({title:'No puedes eliminar el perfil activo',body:'<p>Cambia primero a otro perfil y vuelve a intentarlo.</p>',buttons:[{label:'Entendido',value:true}]});return;}const ok=await modal({title:'Eliminar perfil',body:`<p>¿Eliminar <b>${esc(p.name)}</b>? La configuración interna del perfil se guardará en un respaldo de seguridad. Las carpetas externas de contenidos, anuncios y documentos no se eliminarán.</p>`,buttons:[{label:'Cancelar',value:false,className:'dark'},{label:'Eliminar',value:true,className:'danger'}]});if(!ok)return;try{await window.ECAPI.profileDelete(p.id);profileState=await window.ECAPI.profileStatus();paintProfile();showAdmin();}catch(e){status(`Eliminar perfil: ${e.message||e}`);}}
  async function showAdmin(){profileState=await window.ECAPI.profileStatus();const x=layer(),rows=(profileState.profiles||[]).map(p=>`<div class="ec29-admin-row" data-id="${esc(p.id)}"><div class="ec29-admin-main"><div class="ec29-admin-title" style="color:${esc(p.color)}">${esc(p.name)}</div><div class="ec29-admin-meta">${p.active?'ACTIVO':'Perfil disponible'}</div></div><div class="ec29-admin-actions">${p.active?'':`<button data-a="activate">Activar</button>`}<button data-a="edit" class="dark">Editar</button><button data-a="duplicate" class="dark">Duplicar</button><button data-a="export" class="dark">Exportar</button><button data-a="delete" class="danger">Eliminar</button></div></div>`).join('');x.innerHTML=`<div class="ec29-modal wide"><h2>Administrar perfiles</h2><div class="ec29-admin-list">${rows||'<div class="empty">No hay perfiles.</div>'}</div><div class="ec29-actions"><button id="ec29LoadProfiles" class="dark">Cargar perfiles</button><button id="ec29ExportAll" class="dark">Exportar todos</button><button id="ec29AddProfile">+ Añadir perfil</button><button id="ec29AdminClose" class="dark">Cerrar</button></div></div>`;x.style.display='flex';q('#ec29AdminClose').onclick=closeModal;q('#ec29AddProfile').onclick=()=>{closeModal();editProfile(null);};q('#ec29LoadProfiles').onclick=()=>importProfiles();q('#ec29ExportAll').onclick=()=>exportAll();qa('.ec29-admin-row').forEach(row=>{const p=profileState.profiles.find(v=>v.id===row.dataset.id);row.querySelector('[data-a=activate]')?.addEventListener('click',()=>{closeModal();requestSwitch(p.id);});row.querySelector('[data-a=edit]').onclick=()=>{closeModal();editProfile(p);};row.querySelector('[data-a=duplicate]').onclick=()=>{closeModal();duplicateProfile(p);};row.querySelector('[data-a=export]').onclick=()=>exportOne(p);row.querySelector('[data-a=delete]').onclick=()=>{closeModal();deleteProfile(p);};});}

  async function requestSwitch(id){const next=profileState?.profiles?.find(p=>p.id===id),cur=active();if(!next||next.active)return;const ok=await modal({title:'Cambiar de perfil',body:`<p>Vas a cambiar de <b style="color:${esc(cur?.color||'#ddd')}">${esc(cur?.name||'perfil actual')}</b> a <b style="color:${esc(next.color)}">${esc(next.name)}</b>.</p><p>GEC detendrá la automatización, emisión, Output, reproducción y todos los procesos de producción de noticias. La cola y las notas preparadas de la sesión actual se descartarán.</p>`,buttons:[{label:'Cancelar',value:false,className:'dark'},{label:'Detener y cambiar',value:true}]});if(!ok)return;await doSwitch(id,false);}
  async function doSwitch(id,force){busyOverlay(force?'Forzando cambio de perfil…':'Deteniendo procesos y cambiando perfil…');try{const r=await window.ECAPI.profileSwitch({id,force});clearBusy();if(r?.ok){location.reload();return;}if(r?.needsForce){const action=await modal({title:'Un proceso todavía no responde',body:`<p>GEC no logró detener completamente: <b>${esc((r.pending||[]).join(', ')||'un proceso activo')}</b>.</p><p>Puedes reintentar o forzar el cambio. Forzar descartará los trabajos pendientes de esta sesión.</p>`,buttons:[{label:'Cancelar',value:'cancel',className:'dark'},{label:'Reintentar',value:'retry',className:'dark'},{label:'Forzar cambio',value:'force'}]});if(action==='retry')return doSwitch(id,false);if(action==='force')return doSwitch(id,true);return;}}catch(e){clearBusy();const action=await modal({title:'No se pudo completar el cambio',body:`<p>${esc(e.message||e)}</p><p>Si necesitas cambiar de perfil de todos modos, GEC puede reiniciarse y abrir directamente el perfil solicitado.</p>`,buttons:[{label:'Cancelar',value:false,className:'dark'},{label:'Reiniciar GEC y cambiar',value:true}]});if(action){busyOverlay('Reiniciando GEC…');await window.ECAPI.profileRestartInto(id);}}}
  async function exportOne(p){try{const r=await window.ECAPI.profileExportOne(p.id);if(!r?.cancelled)status(`Perfil exportado: ${p.name}`);}catch(e){status(`Exportar perfil: ${e.message||e}`);}}
  async function exportAll(){try{const r=await window.ECAPI.profileExportAll();if(!r?.cancelled)status('Copia completa de perfiles exportada.');}catch(e){status(`Exportar perfiles: ${e.message||e}`);}}
  async function importProfiles(){try{busyOverlay('Cargando perfiles…');const r=await window.ECAPI.profileImport();clearBusy();if(r?.cancelled)return;if(r?.requiresRestart){busyOverlay('Aplicando configuración y reiniciando GEC…');return;}location.reload();}catch(e){clearBusy();status(`Cargar perfiles: ${e.message||e}`);await modal({title:'No se pudieron cargar los perfiles',body:`<p>${esc(e.message||e)}</p>`,buttons:[{label:'Cerrar',value:true}]});}}
  async function onboarding(){const x=layer();x.innerHTML=`<div class="ec29-modal ec29-onboarding"><h2>Bienvenido a GEC Automatic News</h2><p>Para comenzar, crea un perfil nuevo o carga perfiles que hayas exportado anteriormente.</p><div class="ec29-actions"><button id="ec29CreateFirst">+ Crear perfil nuevo</button><button id="ec29LoadFirst" class="dark">Cargar perfiles</button></div></div>`;x.style.display='flex';q('#ec29CreateFirst').onclick=()=>{closeModal();editProfile(null);};q('#ec29LoadFirst').onclick=()=>importProfiles();}
  async function checkHealth(){const p=active();if(!p)return;try{const h=await window.ECAPI.profileHealth(p.id),missing=(h.checks||[]).filter(x=>x.status==='missing');if(missing.length)status(`${p.name} · ${missing.length} ruta${missing.length===1?'':'s'} no disponible${missing.length===1?'':'s'} · puedes reubicarla desde su sección.`);}catch{}}

  function installExclusiveQueueColor(){settings.visual=settings.visual||{};settings.visual.queueColors={...(settings.visual.queueColors||{}),exclusive:settings.visual.queueColors?.exclusive||DEFAULT_EXCLUSIVE};const error=q('#queueColorError');if(error&&!q('#queueColorExclusive')){const label=document.createElement('label');label.innerHTML=`Exclusivos<input id="queueColorExclusive" type="color" value="${esc(settings.visual.queueColors.exclusive)}">`;error.closest('label')?.insertAdjacentElement('beforebegin',label);}if(typeof setQueueColorControls==='function'){const base=setQueueColorControls;setQueueColorControls=function(colors={}){base(colors);if(q('#queueColorExclusive'))q('#queueColorExclusive').value=colors.exclusive||DEFAULT_EXCLUSIVE;};setQueueColorControls(settings.visual.queueColors);}if(typeof readQueueColors==='function'){const base=readQueueColors;readQueueColors=function(){return{...base(),exclusive:q('#queueColorExclusive')?.value||DEFAULT_EXCLUSIVE};};}if(typeof renderQueue==='function'){const base=renderQueue;renderQueue=function(s){const r=base(s),items=s?.queue||[],els=qa('#queue .queue-item'),color=settings?.visual?.queueColors?.exclusive||DEFAULT_EXCLUSIVE;els.forEach((el,i)=>{const item=items[i];if(item?.isExclusive&&item.status!=='ERROR')el.style.setProperty('--type-color',color);});return r;};}}

  async function init(){injectDock();installExclusiveQueueColor();profileState=await window.ECAPI.profileStatus();paintProfile();if(!profileState.hasProfiles){await onboarding();return;}setTimeout(checkHealth,500);}
  window.ECAPI.on?.('profile:changed',s=>{profileState=s;paintProfile();});
  init().catch(e=>status(`Perfiles: ${e.message||e}`));
})();
