'use strict';
(function installEc0324(){
  if(typeof renderFeeds!=='function'||typeof refreshRuntimeStatus!=='function'||typeof refreshPronunciationStatus!=='function'||typeof readDesignControls!=='function'||typeof renderQueue!=='function'||!window.__ec0316UiPatchesInstalled){setTimeout(installEc0324,80);return;}
  if(window.__ec0324Installed)return;window.__ec0324Installed=true;

  const $id=id=>document.getElementById(id),fmtDuration=sec=>{const n=Math.max(0,Math.round(Number(sec)||0));if(!n)return'--:--';const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;};

  // -------- Fuentes universales RSS / WEB --------
  humanFeedStatus=function(r){
    if(!r)return{label:'Sin comprobar',cls:'',dot:''};if(r.paused)return{label:'Pausada',cls:'warn',dot:'paused'};if(r.checking)return{label:'Comprobando…',cls:'',dot:''};
    if(!r.ok)return{label:'No pudimos leer esta fuente',cls:'error',dot:'error'};
    const type=String(r.sourceType||(/WEB/i.test(r.mode||'')?'WEB':'RSS')),count=Number(r.count)||0,raw=Number(r.rawCount)||0,parsed=Number(r.parsedCount)||count;
    if(r.partial){const detail=type.includes('RSS')&&raw?`${type} · ${raw} recibido${raw===1?'':'s'} · ${parsed} válido${parsed===1?'':'s'} · fuente parcial`:`${type} · ${count} noticia${count===1?'':'s'} · fuente parcial`;return{label:detail,cls:'warn partial',dot:'partial'};}
    if(type==='RSS'&&raw&&raw!==parsed)return{label:`RSS · ${raw} recibidos · ${parsed} válidos`,cls:'ok',dot:'ok'};
    return{label:`${type} · ${count} noticia${count===1?'':'s'}`,cls:'ok',dot:'ok'};
  };
  function ensureExclusiveCloseControls(){
    const partial=$id('globalPartialClose'),add=$id('addFeed');if(!settings||(!partial&&!add))return;settings.exclusiveClose={enabled:true,template:'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.',...(settings.exclusiveClose||{})};
    let wrap=$id('globalExclusiveClose');if(!wrap){wrap=document.createElement('div');wrap.id='globalExclusiveClose';wrap.className='subcard top-gap exclusive-config';wrap.innerHTML=`<h3>Cierre para contenido exclusivo</h3><p class="note">EC detecta contenido para suscriptores de forma genérica. Si una nota es exclusiva, este cierre reemplaza al cierre de fuente parcial.</p><label class="switch-row"><span><b>Añadir cierre para contenido exclusivo</b><small>Se aplica cuando la detección automática o la configuración manual marca la nota como exclusiva.</small></span><input id="exclusiveSourceCloseEnabled" type="checkbox"><span class="switch-ui"></span></label><label>Texto del cierre<input id="exclusiveSourceCloseTemplate"><small>Usa <b>{medio}</b> para el nombre del medio y <b>{web}</b> para su dominio.</small></label>`;(partial||add).insertAdjacentElement('afterend',wrap);$id('exclusiveSourceCloseEnabled').onchange=e=>settings.exclusiveClose.enabled=e.target.checked;$id('exclusiveSourceCloseTemplate').oninput=e=>settings.exclusiveClose.template=e.target.value;}
    $id('exclusiveSourceCloseEnabled').checked=settings.exclusiveClose.enabled!==false;$id('exclusiveSourceCloseTemplate').value=settings.exclusiveClose.template||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.';
    if(partial){const note=partial.querySelector('.note');if(note)note.textContent='Se aplica a fuentes RSS o WEB cuando la página indica que faltan datos y la IA marca la fuente como parcial.';}
  }
  function enhanceFeedRows(){
    $$('.feedrow').forEach(row=>{const i=Number(row.dataset.feedIndex),f=settings?.rssFeeds?.[i];if(!f)return;const url=row.querySelector('.f-url'),label=url?.closest('label');if(label&&label.firstChild?.nodeType===3)label.firstChild.textContent='URL de fuente (RSS o web)';let opts=row.querySelector('.feed-0324-options');if(!opts){opts=document.createElement('div');opts.className='feed-0324-options';opts.innerHTML=`<label>Tipo de fuente<select class="f-source-mode" data-i="${i}"><option value="auto">Detectar automáticamente</option><option value="rss">Forzar RSS / Atom</option><option value="web">Forzar página WEB</option></select></label><label>Acceso al contenido<select class="f-access-mode" data-i="${i}"><option value="auto">Automático</option><option value="public">Siempre público</option><option value="exclusive">Siempre exclusivo / suscriptores</option></select></label>`;const test=row.querySelector('.f-test')?.closest('.buttons');(test||row.querySelector('.feed-edit'))?.insertAdjacentElement(test?'beforebegin':'beforeend',opts);}const sm=opts.querySelector('.f-source-mode'),am=opts.querySelector('.f-access-mode');sm.value=f.sourceMode||'auto';am.value=f.accessMode||'auto';sm.onchange=e=>{f.sourceMode=e.target.value;delete feedHealth[f.id];testFeedAt(i,true);};am.onchange=e=>{f.accessMode=e.target.value;};});
  }
  const renderFeeds0323=renderFeeds;
  renderFeeds=function(){const box=$id('feeds'),scroll=box?.scrollTop||0,active=document.activeElement,activeInfo=active?.closest?.('.feedrow')?{i:active.dataset?.i,cls:[...active.classList].find(x=>/^f-/.test(x)),start:active.selectionStart,end:active.selectionEnd}:null;renderFeeds0323();ensureExclusiveCloseControls();enhanceFeedRows();if(box)box.scrollTop=scroll;if(activeInfo?.cls){const next=box?.querySelector(`.${activeInfo.cls}[data-i="${activeInfo.i}"]`);if(next&&document.activeElement!==next){try{next.focus({preventScroll:true});if(Number.isInteger(activeInfo.start))next.setSelectionRange(activeInfo.start,activeInfo.end);}catch{}}}};
  ensureExclusiveCloseControls();renderFeeds();

  const validate0323=validateSettingsBeforeSave;
  validateSettingsBeforeSave=function(){validate0323();ensureExclusiveCloseControls();const enabled=$id('exclusiveSourceCloseEnabled')?.checked!==false,template=String($id('exclusiveSourceCloseTemplate')?.value||'').trim();if(enabled&&!template)throw new Error('Escribe el texto del cierre para contenido exclusivo.');if(enabled&&(!/\{medio\}/i.test(template)||!/\{web\}/i.test(template)))throw new Error('El cierre exclusivo debe incluir {medio} y {web}.');settings.exclusiveClose={enabled,template:template||'Este contenido es exclusivo de {medio}. Para leer la nota, visita {web}.'};};

  // -------- Tipografía por elemento y fuentes del equipo --------
  const weightOptions=`<option value="300">Ligera</option><option value="400">Normal</option><option value="500">Media</option><option value="600">Seminegrita</option><option value="700">Negrita</option><option value="800">Extra negrita</option><option value="900">Black</option>`;
  function injectTypography(){if($id('typography0324'))return;const form=$id('fontFamily')?.closest('.form-grid');if(!form)return;const titleLabel=$id('fontFamily').closest('label'),dateLabel=$id('dateFontFamily').closest('label');if(titleLabel?.firstChild?.nodeType===3)titleLabel.firstChild.textContent='Tipografía del titular';if(dateLabel?.firstChild?.nodeType===3)dateLabel.firstChild.textContent='Tipografía de fecha';const wrap=document.createElement('div');wrap.id='typography0324';wrap.className='subcard typography-0324';wrap.innerHTML=`<div class="section-head"><h3>Tipografías por elemento</h3><span class="mini-pill">INDEPENDIENTES</span></div><div class="form-grid two"><label>Bajada<select id="summaryFontFamily"></select></label><label>Categoría<select id="categoryFontFamily"></select></label><label>Exclusivo<select id="exclusiveFontFamily"></select></label><label>Tamaño titular<input id="titleFontSize" type="number" min="20" max="120"></label><label>Peso titular<select id="titleFontWeight">${weightOptions}</select></label><label>Tamaño bajada<input id="summaryFontSize" type="number" min="12" max="72"></label><label>Peso bajada<select id="summaryFontWeight">${weightOptions}</select></label><label>Tamaño categoría<input id="categoryFontSize" type="number" min="10" max="48"></label><label>Peso categoría<select id="categoryFontWeight">${weightOptions}</select></label><label>Tamaño fecha<input id="dateFontSize" type="number" min="10" max="48"></label><label>Peso fecha<select id="dateFontWeight">${weightOptions}</select></label><label>Tamaño exclusivo<input id="exclusiveFontSize" type="number" min="10" max="48"></label><label>Peso exclusivo<select id="exclusiveFontWeight">${weightOptions}</select></label></div><div class="buttons"><button id="refreshFonts0324" class="dark">Actualizar fuentes de Windows</button><button id="importFont0324" class="dark">Importar TTF / OTF</button></div><div id="customFontManager0324" class="font-manager-list"></div><p class="note custom-font-note">EC enumera nombres de fuentes instaladas y solo carga la fuente seleccionada. Las fuentes importadas se guardan fuera del EXE.</p>`;form.insertAdjacentElement('afterend',wrap);
    for(const id of ['summaryFontFamily','categoryFontFamily','exclusiveFontFamily','titleFontSize','titleFontWeight','summaryFontSize','summaryFontWeight','categoryFontSize','categoryFontWeight','dateFontSize','dateFontWeight','exclusiveFontSize','exclusiveFontWeight']){const el=$id(id);el.oninput=()=>updateDesignFromControls(true);el.onchange=()=>updateDesignFromControls(true);}
    $id('refreshFonts0324').onclick=()=>loadFonts0324(true);$id('importFont0324').onclick=async()=>{try{const r=await window.ECAPI.importFont();if(r.cancelled)return;status(`Fuente importada: ${r.item?.family||'lista'}.`);await loadFonts0324(false);}catch(e){status(`Tipografía: ${humanError(e)}`);}};
  }
  function fontSelects(){return['fontFamily','dateFontFamily','summaryFontFamily','categoryFontFamily','exclusiveFontFamily'].map($id).filter(Boolean);}
  let fontData={installed:[],custom:[]};
  function installPreviewFonts(custom){for(const x of custom||[]){if(!x.family||!x.url)continue;try{const face=new FontFace(x.family,`url("${String(x.url).replace(/"/g,'%22')}")`);face.load().then(f=>document.fonts.add(f)).catch(()=>{});}catch{}}}
  function populateFontSelect(sel,selected){if(!sel)return;const names=[...new Set([...(fontData.installed||[]),...(fontData.custom||[]).map(x=>x.family)])];sel.innerHTML=names.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('');if(names.includes(selected))sel.value=selected;else if(names.includes('Arial'))sel.value='Arial';}
  function renderCustomFonts(){const box=$id('customFontManager0324');if(!box)return;box.innerHTML=(fontData.custom||[]).length?(fontData.custom||[]).map(x=>`<div class="font-manager-item"><div class="font-manager-name">${escapeHtml(x.family)}<small>Fuente importada en EC</small></div><div class="font-actions"><button class="dark compact font-delete" data-family="${escapeHtml(x.family)}">Eliminar</button></div></div>`).join(''):'<div class="note">No hay tipografías importadas.</div>';box.querySelectorAll('.font-delete').forEach(b=>b.onclick=async()=>{const family=b.dataset.family;if(!confirm(`¿Eliminar la tipografía “${family}” de EC?`))return;try{await window.ECAPI.deleteFont(family);for(const key of ['fontFamily','titleFontFamily','summaryFontFamily','categoryFontFamily','dateFontFamily','exclusiveFontFamily'])if(settings.visual.output[key]===family)settings.visual.output[key]='Arial';await loadFonts0324(false);setDesignControls(settings.visual.output);updateDesignFromControls(true);status(`Tipografía “${family}” eliminada.`);}catch(e){status(`Tipografía: ${humanError(e)}`);}});}
  async function loadFonts0324(force=false){try{const selected={};for(const s of fontSelects())selected[s.id]=s.value||settings?.visual?.output?.[s.id]||'Arial';fontData=force?await window.ECAPI.refreshFonts():await window.ECAPI.fontsList();installPreviewFonts(fontData.custom);for(const s of fontSelects())populateFontSelect(s,selected[s.id]||'Arial');if(settings?.visual?.output)settings.visual.output.customFonts=(fontData.custom||[]).map(x=>({family:x.family,url:x.url}));renderCustomFonts();if(force)status(`${fontData.installed?.length||0} fuentes de Windows detectadas.`);}catch(e){status(`Tipografías: ${humanError(e)}`);}}
  injectTypography();
  const baseSetDesign=setDesignControls,baseReadDesign=readDesignControls,baseApplyPreviewDesign=applyPreviewDesign,baseApplyPreviewMotion=applyPreviewMotion;
  setDesignControls=function(d){baseSetDesign(d);const v=(id,val)=>{if($id(id))$id(id).value=val;};v('fontFamily',d.titleFontFamily||d.fontFamily||'Arial');v('summaryFontFamily',d.summaryFontFamily||d.fontFamily||'Arial');v('categoryFontFamily',d.categoryFontFamily||d.fontFamily||'Arial');v('dateFontFamily',d.dateFontFamily||d.fontFamily||'Arial');v('exclusiveFontFamily',d.exclusiveFontFamily||d.fontFamily||'Arial');for(const id of ['titleFontSize','summaryFontSize','categoryFontSize','dateFontSize','exclusiveFontSize','titleFontWeight','summaryFontWeight','categoryFontWeight','dateFontWeight','exclusiveFontWeight'])v(id,d[id]);syncExclusiveControls(d);refreshDesignVisibility();};
  readDesignControls=function(){const d=baseReadDesign(),o=settings?.visual?.output||{};return{...d,fontFamily:$id('fontFamily')?.value||'Arial',titleFontFamily:$id('fontFamily')?.value||'Arial',summaryFontFamily:$id('summaryFontFamily')?.value||o.summaryFontFamily||'Arial',categoryFontFamily:$id('categoryFontFamily')?.value||o.categoryFontFamily||'Arial',dateFontFamily:$id('dateFontFamily')?.value||'Arial',exclusiveFontFamily:$id('exclusiveFontFamily')?.value||o.exclusiveFontFamily||'Arial',titleFontSize:Number($id('titleFontSize')?.value)||64,summaryFontSize:Number($id('summaryFontSize')?.value)||30,categoryFontSize:Number($id('categoryFontSize')?.value)||22,dateFontSize:Number($id('dateFontSize')?.value)||18,exclusiveFontSize:Number($id('exclusiveFontSize')?.value)||18,titleFontWeight:Number($id('titleFontWeight')?.value)||800,summaryFontWeight:Number($id('summaryFontWeight')?.value)||400,categoryFontWeight:Number($id('categoryFontWeight')?.value)||900,dateFontWeight:Number($id('dateFontWeight')?.value)||500,exclusiveFontWeight:Number($id('exclusiveFontWeight')?.value)||800,...readExclusiveControls(),transitionEnabled:($id('transitionType')?.value||'fade')!=='none'};};
  const motionSignatures=new WeakMap();applyPreviewMotion=function(el,d){const image=el?.querySelector('img');if(!image)return;const sig=`${previewMotionMode(image,d)}|${d.motionSpeed}|${d.format}|${image.currentSrc||image.src}`;if(motionSignatures.get(el)===sig)return;motionSignatures.set(el,sig);baseApplyPreviewMotion(el,d);};
  applyPreviewDesign=function(el,d,showGuide=false){baseApplyPreviewDesign(el,d,showGuide);if(!el)return;el.style.setProperty('--title-font',`"${d.titleFontFamily||d.fontFamily}",sans-serif`);el.style.setProperty('--summary-font',`"${d.summaryFontFamily||d.fontFamily}",sans-serif`);el.style.setProperty('--category-font',`"${d.categoryFontFamily||d.fontFamily}",sans-serif`);el.style.setProperty('--date-font',`"${d.dateFontFamily||d.fontFamily}",sans-serif`);el.style.setProperty('--exclusive-font',`"${d.exclusiveFontFamily||d.fontFamily}",sans-serif`);el.style.setProperty('--title-size',`${Math.max(20,Number(d.titleFontSize)||64)/1920*100}vw`);el.style.setProperty('--summary-size',`${Math.max(12,Number(d.summaryFontSize)||30)/1920*100}vw`);el.style.setProperty('--title-weight',d.titleFontWeight||800);el.style.setProperty('--summary-weight',d.summaryFontWeight||400);el.style.setProperty('--category-weight',d.categoryFontWeight||900);el.style.setProperty('--date-weight',d.dateFontWeight||500);el.style.setProperty('--exclusive-weight',d.exclusiveFontWeight||800);const ex=el.querySelector('.preview-exclusive');if(ex){const show=el.id==='designPreview'?d.exclusiveEnabled!==false:!!currentArticle?.isExclusive;ex.style.display=show?'inline-block':'none';ex.textContent=d.exclusiveText||'EXCLUSIVO';ex.style.color=d.exclusiveTextColor||'#000';ex.style.background=d.exclusiveBgColor||'#F7C600';ex.style.border=`${Math.max(0,Number(d.exclusiveBorderWidth)||0)}px solid ${d.exclusiveBorderColor||d.exclusiveBgColor||'#F7C600'}`;ex.style.borderRadius=`${Math.max(0,Number(d.exclusiveRadius)||0)}px`;ex.style.fontSize=`${Math.max(10,Number(d.exclusiveFontSize)||18)/1920*100}vw`;}}
  function ensurePreviewBadges(){for(const el of [$id('designPreview'),$id('editorPreview')]){const date=el?.querySelector('.preview-date');if(date&&!el.querySelector('.preview-exclusive')){const x=document.createElement('span');x.className='preview-exclusive';x.textContent='EXCLUSIVO';date.insertAdjacentElement('afterend',x);}}}
  ensurePreviewBadges();loadFonts0324(false).then(()=>setDesignControls(settings.visual.output));

  // -------- Distintivo EXCLUSIVO --------
  function injectExclusiveDesign(){if($id('exclusiveDesign0324'))return;const colors=$id('titleColor')?.closest('.color-grid');if(!colors)return;const box=document.createElement('div');box.id='exclusiveDesign0324';box.className='subcard';box.innerHTML=`<div class="section-head"><h3>Distintivo de contenido exclusivo</h3><span class="mini-pill">OUTPUT</span></div><label class="switch-row"><span><b>Mostrar distintivo</b><small>La muestra aparece en la Vista previa aunque no haya una noticia premium cargada.</small></span><input id="exclusiveEnabled" type="checkbox"><span class="switch-ui"></span></label><div class="form-grid two"><label>Texto<input id="exclusiveText" maxlength="32"></label><label>Posición<select id="exclusivePosition"><option value="meta">Junto a categoría y fecha</option></select></label><label>Color de texto<input id="exclusiveTextColor" type="color"></label><label>Color de fondo<input id="exclusiveBgColor" type="color"></label><label>Color de borde<input id="exclusiveBorderColor" type="color"></label><label>Grosor de borde<input id="exclusiveBorderWidth" type="number" min="0" max="8" step="1"></label><label>Radio de esquinas<input id="exclusiveRadius" type="number" min="0" max="30" step="1"></label></div>`;colors.insertAdjacentElement('afterend',box);for(const id of ['exclusiveEnabled','exclusiveText','exclusivePosition','exclusiveTextColor','exclusiveBgColor','exclusiveBorderColor','exclusiveBorderWidth','exclusiveRadius']){const el=$id(id);el.oninput=()=>updateDesignFromControls(true);el.onchange=()=>updateDesignFromControls(true);}}
  function syncExclusiveControls(d){const set=(id,v,checked=false)=>{const e=$id(id);if(!e)return;if(checked)e.checked=v!==false;else e.value=v;};set('exclusiveEnabled',d.exclusiveEnabled,true);set('exclusiveText',d.exclusiveText||'EXCLUSIVO');set('exclusivePosition',d.exclusivePosition||'meta');set('exclusiveTextColor',d.exclusiveTextColor||'#000000');set('exclusiveBgColor',d.exclusiveBgColor||'#F7C600');set('exclusiveBorderColor',d.exclusiveBorderColor||'#F7C600');set('exclusiveBorderWidth',Number(d.exclusiveBorderWidth)||0);set('exclusiveRadius',Number(d.exclusiveRadius)||5);}
  function readExclusiveControls(){return{exclusiveEnabled:$id('exclusiveEnabled')?.checked!==false,exclusiveText:String($id('exclusiveText')?.value||'EXCLUSIVO').trim().slice(0,32)||'EXCLUSIVO',exclusivePosition:$id('exclusivePosition')?.value||'meta',exclusiveTextColor:$id('exclusiveTextColor')?.value||'#000000',exclusiveBgColor:$id('exclusiveBgColor')?.value||'#F7C600',exclusiveBorderColor:$id('exclusiveBorderColor')?.value||'#F7C600',exclusiveBorderWidth:Math.max(0,Math.min(8,Number($id('exclusiveBorderWidth')?.value)||0)),exclusiveRadius:Math.max(0,Math.min(30,Number($id('exclusiveRadius')?.value)||0))};}
  injectExclusiveDesign();syncExclusiveControls(settings.visual.output);

  // -------- Transición sin switch redundante --------
  const transitionSwitch=$id('transitionEnabled')?.closest('.switch-row');if(transitionSwitch)transitionSwitch.classList.add('hidden-0324');const typeLabel=$id('transitionType')?.closest('label');if(typeLabel?.firstChild?.nodeType===3)typeLabel.firstChild.textContent='Transición entre contenidos';
  const baseRefreshDesignVisibility=refreshDesignVisibility;refreshDesignVisibility=function(){baseRefreshDesignVisibility();const fade=($id('transitionType')?.value||'fade')!=='none',duration=$id('transitionDuration')?.closest('label');if(duration)duration.classList.toggle('hidden',!fade);};$id('transitionType').onchange=()=>{updateDesignFromControls(true);refreshDesignVisibility();};refreshDesignVisibility();

  // -------- Contenidos y anuncios: duración real --------
  refreshCannedList=async function(){const box=$id('cannedList'),count=$id('cannedCount'),info=$id('cannedFolderInfo');if(!box)return;try{const r=await window.ECAPI.cannedList();if(r.folder)settings.canned.folder=r.folder;info.textContent=r.folder?`${r.folder}${r.ok?` · ${r.count||0} videos`:''}`:'Sin carpeta seleccionada.';count.textContent=`${r.count||0} videos`;if(!r.files?.length){box.innerHTML=`<div class="empty">${escapeHtml(r.message||'No hay contenidos compatibles.')}</div>`;return;}box.innerHTML=r.files.map(x=>`<div class="media-item"><div class="media-name">${escapeHtml(x.name)}</div><div class="media-meta">${fmtDuration(x.durationSec)} · ${Number(x.sizeMB||0).toFixed(1)} MB</div></div>`).join('');}catch{box.innerHTML='<div class="empty">No se pudieron leer los contenidos.</div>';count.textContent='0 videos';}};
  refreshAdsList=async function(){const box=$id('adsList'),count=$id('adsCount'),info=$id('adsFolderInfo'),badge=$id('adsState');if(!box)return;try{const r=await window.ECAPI.cannedListAds();if(r.folder)settings.canned.adsFolder=r.folder;const folder=String(r.folder||settings.canned.adsFolder||'');info.textContent=folder?`${folder}${r.ok?` · ${r.count||0} videos`:''}`:'Sin carpeta seleccionada.';count.textContent=`${r.count||0} videos`;const enabled=settings.canned.insertAdAfterContent!==false;badge.textContent=!folder?'SIN CARPETA':enabled?'ACTIVO':'DESACTIVADO';badge.className=`status-pill ${folder&&enabled?'ok':'neutral'}`;if(!r.files?.length){box.innerHTML=`<div class="empty">${escapeHtml(r.message||'No hay anuncios compatibles.')}</div>`;return;}box.innerHTML=r.files.map(x=>`<div class="media-item"><div class="media-name">${escapeHtml(x.name)}</div><div class="media-meta">${fmtDuration(x.durationSec)} · ${Number(x.sizeMB||0).toFixed(1)} MB</div></div>`).join('');}catch{box.innerHTML='<div class="empty">No se pudieron leer los anuncios.</div>';count.textContent='0 videos';badge.textContent='ERROR';badge.className='status-pill error';}};
  refreshCannedList();refreshAdsList();

  // -------- Gestión de voces Kokoro personalizadas --------
  let voiceState={custom:[],voices:[],active:'',fallback:'ef_dora'};
  function injectVoiceManager(){if($id('customVoiceManager'))return;const anchor=$id('ttsBenchmarkResult');if(!anchor)return;const wrap=document.createElement('div');wrap.id='customVoiceManager';wrap.className='subcard top-gap';wrap.innerHTML=`<div class="section-head"><h3>Voces Kokoro personalizadas</h3><span id="customVoiceCount" class="mini-pill">0 voces</span></div><p class="note">Importa archivos .pt exportados por Kokoro Voice Designer. EC los convierte a su formato ONNX y conserva las voces fuera del EXE.</p><label>Voz predeterminada de respaldo<select id="fallbackVoice0324"></select><small>Se usa automáticamente si una voz personalizada se elimina, desaparece o deja de estar disponible.</small></label><div class="buttons"><button id="importVoice0324">+ Importar voz Kokoro (.pt)</button></div><div id="customVoiceList0324" class="voice-manager-list"></div><audio id="customVoiceTestAudio0324" controls></audio>`;anchor.insertAdjacentElement('afterend',wrap);$id('importVoice0324').onclick=async()=>{const name=prompt('Nombre para la voz personalizada (opcional):','');if(name===null)return;try{status('Importando y validando voz Kokoro…');const r=await window.ECAPI.importVoice(name);if(r.cancelled)return status('Importación cancelada.');status(`Voz “${r.item?.name||'personalizada'}” importada.`);await refreshVoiceUi();}catch(e){status(`Voz: ${humanError(e)}`);}};$id('fallbackVoice0324').onchange=async e=>{settings.tts.fallbackVoice=e.target.value||'ef_dora';try{await saveSettings({quiet:true});status(`Voz de respaldo: ${e.target.options[e.target.selectedIndex]?.textContent||e.target.value}.`);}catch(err){status(`Voz: ${humanError(err)}`);}};}
  function rebuildVoiceSelect(){const v=$id('voice'),fallback=$id('fallbackVoice0324');if(!v)return;const customMap=new Map((voiceState.custom||[]).map(x=>[x.id,x])),official=(voiceState.voices||[]).filter(x=>!customMap.has(x)&&/^e[fm]_/.test(x)),custom=(voiceState.voices||[]).filter(x=>customMap.has(x));v.innerHTML='';const og=document.createElement('optgroup');og.label='Predeterminadas';for(const name of official){const o=document.createElement('option');o.value=name;o.textContent=voiceLabel(name);og.appendChild(o);}v.appendChild(og);if(custom.length){const cg=document.createElement('optgroup');cg.label='Personalizadas';for(const id of custom){const x=customMap.get(id),o=document.createElement('option');o.value=id;o.textContent=`🎙 ${x?.name||id}`;cg.appendChild(o);}v.appendChild(cg);}const active=voiceState.active||settings.tts.voice;if([...v.options].some(o=>o.value===active))v.value=active;settings.tts.voice=v.value||official[0]||'ef_dora';if(fallback){fallback.innerHTML=official.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(voiceLabel(n))}</option>`).join('');const desired=voiceState.fallback||settings.tts.fallbackVoice||'ef_dora';fallback.value=official.includes(desired)?desired:(official.includes('ef_dora')?'ef_dora':official[0]||'');settings.tts.fallbackVoice=fallback.value||'ef_dora';}}
  function renderCustomVoices(){const box=$id('customVoiceList0324'),count=$id('customVoiceCount');if(!box)return;const custom=voiceState.custom||[];count.textContent=`${custom.length} voz${custom.length===1?'':'es'}`;box.innerHTML=custom.length?custom.map(x=>`<div class="voice-manager-item"><div class="voice-manager-name">🎙 ${escapeHtml(x.name)}${voiceState.active===x.id?'<span class="voice-active">✓ ACTIVA</span>':''}<small>Kokoro personalizada · ${escapeHtml(x.source||'.pt')}</small></div><div class="voice-actions"><button class="dark compact voice-test" data-id="${x.id}">Probar</button><button class="dark compact voice-rename" data-id="${x.id}">Renombrar</button><button class="dark compact voice-export" data-id="${x.id}">Exportar</button><button class="danger compact voice-delete" data-id="${x.id}">Eliminar</button></div></div>`).join(''):'<div class="note">No hay voces personalizadas.</div>';
    box.querySelectorAll('.voice-test').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,x=custom.find(v=>v.id===id);try{$id('voice').value=id;settings.tts.voice=id;await saveSettings({quiet:true});status(`Generando prueba con “${x?.name||id}”…`);const a=await window.ECAPI.generateTts('Esta es una prueba de la nueva voz de EC Automatic News.');$id('customVoiceTestAudio0324').src=a.url||'';$id('customVoiceTestAudio0324').play().catch(()=>{});voiceState.active=id;renderCustomVoices();status(`Prueba lista · “${x?.name||id}” quedó seleccionada para locutar.`);}catch(e){status(`Voz: ${humanError(e)}`);}});
    box.querySelectorAll('.voice-rename').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,x=custom.find(v=>v.id===id),name=prompt('Nuevo nombre de la voz:',x?.name||'');if(name===null)return;try{await window.ECAPI.renameVoice(id,name);await refreshVoiceUi();status('Voz renombrada.');}catch(e){status(`Voz: ${humanError(e)}`);}});
    box.querySelectorAll('.voice-export').forEach(b=>b.onclick=async()=>{try{const r=await window.ECAPI.exportVoice(b.dataset.id);if(!r.cancelled)status(`Copia de voz guardada: ${r.path}`);}catch(e){status(`Voz: ${humanError(e)}`);}});
    box.querySelectorAll('.voice-delete').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,x=custom.find(v=>v.id===id);if(!confirm(`¿Eliminar la voz personalizada “${x?.name||id}”?\n\nSi está activa, EC cambiará automáticamente a la voz predeterminada de respaldo.`))return;try{const r=await window.ECAPI.deleteVoice(id);settings.tts.voice=r.active||settings.tts.fallbackVoice||'ef_dora';await refreshVoiceUi();status(`Voz “${x?.name||id}” eliminada${r.active?` · voz activa: ${voiceLabel(r.active)}`:''}.`);}catch(e){status(`Voz: ${humanError(e)}`);}});}
  async function refreshVoiceUi(preferred=''){injectVoiceManager();try{voiceState=await window.ECAPI.voicesList();if(preferred&&voiceState.voices?.includes(preferred))voiceState.active=preferred;rebuildVoiceSelect();renderCustomVoices();}catch(e){status(`Voces: ${humanError(e)}`);}}
  injectVoiceManager();
  let localDownloadBusy0324=false,pronDownloadBusy0324=false;
  const refreshRuntime0323=refreshRuntimeStatus;refreshRuntimeStatus=async function(){if(localDownloadBusy0324)return;const intended=settings?.tts?.voice||'';await refreshRuntime0323();if(intended.startsWith('ecv_'))settings.tts.voice=intended;await refreshVoiceUi(intended);};
  const refreshPron0323=refreshPronunciationStatus;refreshPronunciationStatus=async function(){if(pronDownloadBusy0324)return;return refreshPron0323();};
  const localBtn=$id('downloadModel'),pronBtn=$id('downloadPronunciationModel');if(localBtn?.onclick){const base=localBtn.onclick;localBtn.onclick=async function(e){localDownloadBusy0324=true;try{return await base.call(this,e);}finally{localDownloadBusy0324=false;await refreshRuntimeStatus();}};}if(pronBtn?.onclick){const base=pronBtn.onclick;pronBtn.onclick=async function(e){pronDownloadBusy0324=true;try{return await base.call(this,e);}finally{pronDownloadBusy0324=false;await refreshPronunciationStatus();}};}
  refreshVoiceUi();

  // -------- Cola: distintivo exclusivo secundario --------
  const renderQueue0323=renderQueue;renderQueue=function(s){if(window.__ecQueueRenderOwner==='0332')return;renderQueue0323(s);const nodes=[...document.querySelectorAll('#queue .queue-item')],items=s?.queue||[];nodes.forEach((node,i)=>{if(!items[i]?.isExclusive)return;const head=node.querySelector('.queue-headline');if(head&&!head.querySelector('.queue-exclusive')){const b=document.createElement('span');b.className='queue-exclusive';b.textContent='🔒 EXCLUSIVO';head.appendChild(b);}});};

  // -------- Guardado: nuevos ajustes --------
  const save0323=saveSettings;saveSettings=async function(options={}){if($id('fallbackVoice0324'))settings.tts.fallbackVoice=$id('fallbackVoice0324').value||settings.tts.fallbackVoice||'ef_dora';settings.exclusiveClose={enabled:$id('exclusiveSourceCloseEnabled')?.checked!==false,template:String($id('exclusiveSourceCloseTemplate')?.value||settings.exclusiveClose?.template||'').trim()};return save0323(options);};

  setDesignControls(settings.visual.output);refreshPreview();refreshDesignVisibility();
})();